### ISSUE TITLE
Migrate historical ATR category data 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#1000]
An ~imminent~ **upcoming** update to MOVE’s schema will remove the VDS data and Bicycle ATRs (permanent counters) from the legacy schema (loaded into FLOW at some point in time). Set us up in a way so that the disappearance of those datasets from move_staging won’t impact our  usage  of the three datasets

Data for `category_id IN (2,6,7)` (RESCU, PermStn and Bicycle) will be removed from `traffic.cnt_det` and `traffic.countinfo`.

**Comment by gabrielwol** [comment]
In a mild panic yesterday I copied data for category_id 6 into `traffic.cnt_det_6` & `traffic.countinfo_6` (& ditto for _7). They have the same definitions as the base tables. 
- Nate has been made aware and will adjust the volume index which uses category_id = 7.
- I already copied category_id = 2 data over into `vds` schema as part of #965 

Anything else you see to do?
