### ISSUE TITLE
GCC Puller: Add a generic function to import any layers on GCC to one's schema 

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_data-sources#1028]

**Comment by raha1986** [comment]
@chmnata Is it ready for @Hanighomi to use?

**Comment by chmnata** [comment]
nope! Do you need to pull something other than streetlight?

**Comment by raha1986** [comment]
@Hanighomi Do you need to dld another layer too?

**Comment by Hanighomi** [comment]
@chmnata The other layer is `gcc_pavement`, which has already been extracted and imported into BigData as 'vz_analysis.mbk_pavement_asset' with the same method for `mbk_pole`. It might be worthwhile to delete it and rerun the process using the code to maintain consistency.

**Comment by chmnata** [comment]
Can you check and see if the number of records in `vz_analysis.mbk_pavement_asset` is the same as the one on gcc?

**Comment by Hanighomi** [comment]
The diff is 2 records. 
![image](https://github.com/user-attachments/assets/6557c3a6-170a-45b3-a0e1-a74098171cee)
![image](https://github.com/user-attachments/assets/67c534d4-3a0a-47dc-99c7-08b77a1eaa1f)

**Comment by gabrielwol** [comment]
@chmnata may be able to easily tackle this issue at the same time: https://github.com/CityofToronto/bdit_data-sources/issues/561
