### ISSUE TITLE
Short term counting program documentation needs an overhaul

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#1029]
I keep getting totally turned around in [this readme](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/short_term_counting_program) and am having some have real trouble figuring out some pretty basic things. Some top level issues:

* There's really no overview of the program or the different types of counts. The documentation launches straight into the details. There's no way to start at a general level and navigate my way to any specifics I may be looking for.
* The table names are awful. While they probably can't be changed in the near term, they definitely shouldn't be used as section headings without any other contextualization.
* There doesn't seem to be any consideration of who this document is for. For data-ops Airflow users? For people trying to complete data requests? Etc?
* I can't figure out how to answer basic questions like "I want the TMCs within X area"

I'd love to see this revamped in the style of the [docs we have now for Miovision](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/miovision). 

Or does this exist somewhere else and I'm just looking in the wrong place?

**Comment by radumas** [comment]
This documentation has not kept pace with (new) transformations getting transferred over with the replicator, as well as changes to the data with the changing count contract.

The MOVE team have been documenting tables with comments, which are getting replicated over to the `traffic` schema. But this is insufficient as an entry point to getting an overview of the data.

The data pipeline is the partial responsibility of three different teams, and there's going to be a discussion of whose responsibility it is to overhaul this set of documentation pages.

**Comment by mkewins** [comment]
I can take a first stab at this. @peter-lyons and I recently went through all the replicated tables and made sure they're all commented in the database docs. I can transfer that knowledge -- and higher level knowledge -- over to this space.
