### ISSUE TITLE
Update `move_raw_data` to include WiFi for Highway Routes when aggregating to 5-minutes

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#103]
- [x] Currently just filtering Bluetooth for all routes
- [x] Also update all the data in `bluetooth.aggr5_min` to reflect this.

**Comment by radumas** [comment]
Half of Gardiner routes are missing completely from the aggregate table;
```sql
SELECT segs.*
INTO TEMP TABLE missing_gardiner
FROM bluetooth.segments_dir_corrected segs
-- INNER JOIN bluetooth.all_analyses USING (analysis_id)
LEFT JOIN bluetooth.aggr_5min a USING (analysis_id)
WHERE street ='Gardiner' AND a.analysis_id IS NULL;

SELECT report_name, MIN(measured_timestamp), MAX(measured_timestamp) 
FROM bluetooth.observations
INNER JOIN bluetooth.all_analyses USING (analysis_id)
INNER JOIN missing_gardiner USING (analysis_id)
GROUP BY report_name
```

**Comment by radumas** [comment]
This may take a while
```sql
DELETE FROM bluetooth.aggr_5min aggr
USING bluetooth.segments
WHERE segments.analysis_id = aggr.analysis_id AND ( street LIKE 'Gardiner%' OR street LIKE 'Lakeshore%' OR street LIKE 'DVP%');


INSERT INTO bluetooth.aggr_5min (analysis_id, datetime_bin, tt, obs)
	SELECT	rs.analysis_id,
		TIMESTAMP WITHOUT TIME ZONE 'epoch' +
		INTERVAL '1 second' * (floor((extract('epoch' from rs.measured_timestamp)-1) / 300) * 300) as datetime_bin,
		percentile_cont(0.5) WITHIN GROUP (ORDER BY rs.measured_time) AS travel_time,
		COUNT(rs.user_id) AS obs
	FROM bluetooth.observations rs
	INNER JOIN bluetooth.segments USING (analysis_id)
	WHERE rs.outlier_level = 0 AND ( street LIKE 'Gardiner%' OR street LIKE 'Lakeshore%' OR street LIKE 'DVP%')
	GROUP BY rs.analysis_id, (floor((extract('epoch' from rs.measured_timestamp)-1) / 300) * 300)
	ON CONFLICT DO NOTHING;
```

**Comment by radumas** [comment]
https://github.com/CityofToronto/bdit_data-sources/commit/32ec938adbdaab54524a48d54a373f6459e1d692 Updates `move_raw_data` to allow all device types on Gardiner, Lakeshore, and DVP.

However I think the preferred flag would be `WHERE bluetooth.segments.wifi = TRUE`. **But**, we want to modify arterial routes to not include WiFi observations anymore ++ probably reprocess the data. 
Thoughts? @aharpalaniTO @jwrcoleman

**Comment by radumas** [comment]
Following a conversation with Jesse and the analysis performed on speed differences in [this notebook](https://github.com/CityofToronto/bdit_data-sources/blob/master/bluetooth/Examples/class_of_device.ipynb) only devices we are very confident are cars should be used in the arterial (Not Lakeshore, Gardiner, DVP) aggregate data.

- [ ] Update `move_raw_data()`
- [ ] Need to make sure this **does not** affect procedure for loading King Pilot data [see here](https://github.com/CityofToronto/bdit_king_pilot_dashboard/blob/data_pipeline/bluetooth/sql/populate-table-tt_30min.sql)
- [ ] which also means the moving data procedure in the [blip_api.py](https://github.com/CityofToronto/bdit_data-sources/blob/754b5541daff08d2f08e3851f37ea0d7888174d0/bluetooth/api/blip_api.py#L211-L212) script needs to be changed around a little bit.

**Comment by radumas** [comment]
14 minutes to run
```sql
DELETE FROM bluetooth.aggr_5min a
WHERE analysis_id NOT IN (SELECT analysis_id FROM bluetooth.segments WHERE street LIKE 'Gardiner%' OR street LIKE 'Lakeshore%' OR street LIKE 'DVP%') ;
	
	INSERT INTO bluetooth.aggr_5min (analysis_id, datetime_bin, tt, obs)
	SELECT	rs.analysis_id,
		TIMESTAMP WITHOUT TIME ZONE 'epoch' +
		INTERVAL '1 second' * (floor((extract('epoch' from rs.measured_timestamp)-1) / 300) * 300) as datetime_bin,
		percentile_cont(0.5) WITHIN GROUP (ORDER BY rs.measured_time) AS travel_time,
		COUNT(rs.user_id) AS obs
	FROM bluetooth.observations rs
	JOIN bluetooth.class_of_device USING (cod)
	LEFT OUTER JOIN bluetooth.segments USING (analysis_id)
	WHERE rs.outlier_level = 0 AND 
					analysis_id NOT IN (SELECT analysis_id FROM bluetooth.segments WHERE street LIKE 'Gardiner%' OR street LIKE 'Lakeshore%' OR street LIKE 'DVP%')
		AND 		(--Restrict Arterial device types
					device_class = 1 AND class_of_device.device_type = ANY (ARRAY['Hands-free Device', 'WiFi']) )
	GROUP BY rs.analysis_id, datetime_bin
```

**Comment by radumas** [comment]
Apparently I didn't actually update the function being run on the DB on Dec 27th, so I should probably re-run the above for any data on arterials after December 26

**Comment by aharpalaniTO** [comment]
For this piece of code:

`DELETE FROM bluetooth.aggr_5min a
WHERE analysis_id NOT IN (SELECT analysis_id FROM bluetooth.segments WHERE street LIKE 'Gardiner%' OR street LIKE 'Lakeshore%' OR street LIKE 'DVP%') ;`

can we instead (for cleanliness / future sustainability):
a.  modify all the arterial routes that currently have `wifi = t' to 'wifi = f' (namely older routes that have since been retired)
b. modify where clause to routes with `wifi = F` instead of NOT LIKE statements

**Comment by aharpalaniTO** [comment]
Would also recommend changing this: `JOIN bluetooth.class_of_device USING (cod)` to a LEFT OUTER JOIN

OR

setting up an exception that flags any value in  `bluetooth.observations.cod` that isn't in `bluetooth.class_of_device.cod`
