### ISSUE TITLE
Routing on centreline returns wonky results on one way streets

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#1091]
Thanks to @Nate-Wessel for pointing out this example in Queen's Park Crescent.

```sql
SELECT *
FROM gis_core.get_centreline_btwn_intersections(
     13466931, 13463747 -- northbound from adelaide to bloor routes the wrong way around queens park
    --13463747, 13466931 -- southbound from bloor to adelaide goes way off-course
)
```

Giving the wrong direction around the park

![image](https://github.com/user-attachments/assets/842e79fb-0870-4b4b-be09-6b284e79c063)

**Comment by radumas** [comment]
The problem lies in how `gis_core.routing_centreline_directional` is handling the one-way encoding

![image](https://github.com/user-attachments/assets/752655ce-d5d5-4ea7-a0d7-fe1acf39a2b4)

https://github.com/CityofToronto/bdit_data-sources/blob/51be37001abf4a829f53a27c4367263568707233/gis/centreline/sql/create_view_routing_centreline_directional.sql#L12-L31

One way streets can have their flow either with or against the direction of digitization (the from-to intersection nodes match the drawing order, so they must be reversed **only** if drawn against digitization).

**Comment by Nate-Wessel** [comment]
To be clear, @radumas whatever quick fix you applied has fixed this issue for me.

**Comment by radumas** [comment]
Thanks for confirming!

**Comment by gabrielwol** [comment]
Looks good. Also tested a few more intersection pairs and everything checks out.

```sql
SELECT *
FROM gis_core.get_centreline_btwn_intersections(
    --13466931, 13463747 -- northbound from adelaide to bloor - OK
    --13463747, 13466931 -- southbound from bloor to adelaide - OK
    --13464116, 13465557 -- "River / Bayview" ->	"King / Lower River"	
    --13466960, 13463747	-- "King / Bay" -> "Bloor / Avenue"
    13461228, 13467321 -- "Eglinton / Jane" "King / John"
)

--select two random (miovision) intersections
SELECT int_id, intersection_name
FROM miovision_api.intersections
ORDER BY random() LIMIT 2
```
