### ISSUE TITLE
Optimize aggregating 15minute TMC volumes 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#133]
Offshoot of #99. The aggregation of 1-minute volume data to 15-minute TMC volumes is currently the bottleneck of volume aggregation. The original implementation is [here](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/populate-table-volumes_15min_tmc.sql), an [improved version here](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/populate-table-volumes-15min-tmc-optimized.sql) and [implemented as a function which also updates foreign key relationships](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql). We want to improve the function version of this query and test whether the foreign key relationships are workable with a test month of data.

- [x] Set up a test table with June data with the queries to set up the foreign key relationships: for [volumes](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/create-table-volumes.sql) and [volumes_15_min_tmc](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/create-table-volumes.sql)
- [x] Get a baseline time for running [current function](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql) with foreign key relationships **including** deleting the data from `volumes_15_tmc` afterwards.
- [x] Remove [this `DELETE`](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql#L29) operation from the function by adding a [`HAVING`](https://devdocs.io/postgresql~9.6/sql-select#SQL-HAVING) clause that will do the same thing. 
- [x] Combine [these three `UPDATE` statements](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql#L32-L47) into one using a [`CASE WHEN`](https://devdocs.io/postgresql~9.6/functions-conditional#FUNCTIONS-CASE) expression
- [x] Combine [these two `UPDATE` statements](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql#L49-L53) using a CASE WHEN statement.

To wrap up
- [x] Confirm new method of performing second `UPDATE` produces same data.
- [x] Merge [`function-aggregate-volumes_15min_tmc_optimizations.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/7acfca21cbb454da93faf93175c5dc55fe121d38/volumes/miovision/sql/function-aggregate-volumes_15min_tmc_optimizations.sql) into [`function-aggegrate-volumes_15min_tmc.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/7acfca21cbb454da93faf93175c5dc55fe121d38/volumes/miovision/sql/function-aggegrate-volumes_15min_tmc.sql) 
- [x] Make sure schema and function name are correct. @radumas to replace old `miovision` function.
- [x] delete [`populate-table-volumes-15min-tmc-optimized.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/7acfca21cbb454da93faf93175c5dc55fe121d38/volumes/miovision/sql/populate-table-volumes-15min-tmc-optimized.sql) and [`populate-table-volumes_15min_tmc.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/7acfca21cbb454da93faf93175c5dc55fe121d38/volumes/miovision/sql/populate-table-volumes_15min_tmc.sql)

**Comment by rickl4** [comment]
Baseline was 5:14 to populate the table and 1:47:32 to delete everything from the table. The test tables contained only June data with no data before June existing in the volumes, raw_data, and volume_15min_tmc table.

**Comment by radumas** [comment]
So I just ran my own test with the June data and the tables in my schema and got 5:15 minutes for aggregation and 7.5 secs for deletion.

The difference?
```sql
CREATE INDEX volumes_volume_15min_tmc_uid_idx
  ON volumes
  USING btree
  (volume_15min_tmc_uid);
```
The `volume` table in my schema has an index on the column that references `volumes_15min_tmc`. Whereas the table in your schema does not.

The current function does not scale linearly with data size, currently at 36+ minutes run time for aggregating April and May data...

**Comment by radumas** [comment]
I added `RAISE NOTICE` statements throughout the function (see it at the bottom of this comment) and tested on a new month of data with an existing month already in `volumes` and `volumes_15min_tmc`. It would appear the longest part of the query is inserting into the volumes table (I'll update when the query completes):
```SQL
NOTICE:  Thu Jul 26 13:49:27.314952 2018 UTC Function Start. Inserting into bins
NOTICE:  Thu Jul 26 13:49:28.050072 2018 UTC Inserting finished, deleting bins
NOTICE:  Thu Jul 26 13:49:28.050507 2018 UTC Update 1
NOTICE:  Thu Jul 26 13:49:28.050894 2018 UTC Update 2
NOTICE:  Thu Jul 26 13:49:28.982394 2018 UTC Update 3
NOTICE:  Thu Jul 26 13:49:28.982861 2018 UTC Update 4
NOTICE:  Thu Jul 26 13:49:28.983123 2018 UTC Update 5
NOTICE:  Thu Jul 26 13:49:28.983371 2018 UTC Inserting into volumes_15min_tmc and Updating volumes
```

```sql
CREATE OR REPLACE FUNCTION aggregate_15_min_tmc()
  RETURNS integer AS
$BODY$
BEGIN
	RAISE NOTICE '% Function Start. Inserting into bins', timeofday();
	DROP TABLE IF EXISTS bins;
	CREATE TEMPORARY TABLE bins (
		intersection_uid integer,
		datetime_bin timestamp without time zone,
		avail_minutes integer,
		total_volume bigint,
		start_time timestamp without time zone,
		end_time timestamp without time zone,
		interpolated boolean);
	
	INSERT INTO bins
	SELECT 	intersection_uid, 
		TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) AS datetime_bin,
		COUNT(DISTINCT A.datetime_bin) AS avail_minutes,
		SUM(A.volume) AS total_volume,
		MIN(A.datetime_bin) AS start_time,
		MAX(A.datetime_bin) AS end_time,
		NULL as interpolated
	FROM volumes A
	WHERE volume_15min_tmc_uid IS NULL
	GROUP BY intersection_uid, TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900);
	RAISE NOTICE '% Inserting finished, deleting bins', timeofday();
	-- REMOVE ALL 15-minute bins where 5 or less of the 1-minute bins are populated with volume
	DELETE FROM bins WHERE avail_minutes <= 5;

	RAISE NOTICE '% Update 1', timeofday();
	-- IF # of populated 1-minute bins exceeds difference between start and end time, assume no interpolation needed
	UPDATE bins SET interpolated = FALSE WHERE (EXTRACT(minutes FROM end_time - start_time)+1) > avail_minutes AND avail_minutes < 15;
	RAISE NOTICE '% Update 2', timeofday();
	-- IF one of two 1-minute time bins BEFORE and AFTER 15-minute bin are populated, assume no interpolation needed
	UPDATE bins A 
	SET interpolated = FALSE
	FROM (SELECT intersection_uid, datetime_bin, SUM(volume) AS total_volume FROM volumes WHERE volume_15min_tmc_uid IS NULL GROUP BY intersection_uid, datetime_bin) B
	INNER JOIN (SELECT intersection_uid, datetime_bin, SUM(volume) AS total_volume FROM volumes WHERE volume_15min_tmc_uid IS NULL GROUP BY intersection_uid, datetime_bin) C ON B.intersection_uid = C.intersection_uid
	WHERE 	A.interpolated IS NULL 
		AND A.avail_minutes < 15 
		AND A.intersection_uid = B.intersection_uid 
		AND A.intersection_uid = C.intersection_uid 
		AND (B.datetime_bin >= (A.datetime_bin + INTERVAL '15 minutes') AND B.datetime_bin <= (A.datetime_bin + INTERVAL '16 minutes')) 
		AND (C.datetime_bin <= (A.datetime_bin - INTERVAL '1 minute') AND C.datetime_bin >= A.datetime_bin - (INTERVAL '2 minutes'));
	RAISE NOTICE '% Update 3', timeofday();
	-- ASSUME for all other 15-minute bins with missing data, interpolation needed due to missing video
	UPDATE bins SET interpolated = TRUE WHERE interpolated IS NULL AND avail_minutes < 15;
	RAISE NOTICE '% Update 4', timeofday();
	-- FOR 15-minute bins with interpolation needed, IF missing data at end of 15-minute period, SET end_time = end_time - 1 minute to account for potential partial count
	UPDATE bins SET end_time = end_time - INTERVAL '1 minute' WHERE interpolated = TRUE AND datetime_bin = start_time;
	RAISE NOTICE '% Update 5', timeofday();
	-- FOR 15-minute bins with interpolation needed, IF missing data at start of 15-minute period, SET start_time = start_time + 1 minute to account for potential partial count
	UPDATE bins SET start_time = start_time + INTERVAL '1 minute' WHERE interpolated = TRUE AND datetime_bin + INTERVAL '14 minutes' = end_time;
	RAISE NOTICE '% Inserting into volumes_15min_tmc and Updating volumes', timeofday();
	-- INSERT INTO volumes_15min_tmc, with interpolated volumes
	WITH aggregate_insert AS(
	INSERT INTO volumes_15min_tmc(intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume)
	SELECT 	A.intersection_uid,
		TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) AS datetime_bin,
		A.classification_uid,
		A.leg,
		A.movement_uid,
		CASE WHEN B.interpolated = TRUE THEN SUM(A.volume)*15.0/((EXTRACT(minutes FROM B.end_time - B.start_time)+1)*1.0) ELSE SUM(A.volume) END AS volume
	FROM volumes A
	INNER JOIN bins B USING (intersection_uid)
	WHERE B.start_time <= A.datetime_bin AND B.end_time >= A.datetime_bin 
	GROUP BY A.intersection_uid, TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900), A.classification_uid, A.leg, A.movement_uid, B.interpolated, (EXTRACT(minutes FROM B.end_time - B.start_time)+1)
	RETURNING volume_15min_tmc_uid, datetime_bin, classification_uid, leg, movement_uid
	)
	UPDATE volumes a
	SET volume_15min_tmc_uid = b.volume_15min_tmc_uid
	FROM aggregate_insert b
	WHERE a.datetime_bin >= b.datetime_bin AND a.datetime_bin < b.datetime_bin + INTERVAL '15 minutes'
	AND a.classification_uid  = b.classification_uid 
	AND a.leg = b.leg
	AND a.movement_uid = b.movement_uid;
	RAISE NOTICE '% Done', timeofday();
    RETURN 1;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by rickl4** [comment]
Ok, now the delete time is less than 10 seconds.

1. Replacing the Delete statement with a having statement: 1:44:09 to populate and 5.5 Seconds to delete.
2. Adding the datetime_bin index: 5:21 to populate and 6.7 Seconds to delete.
3. Doing both 1 and 2 at the same time: 5:50 to populate and 5.6 Seconds to delete

**Comment by radumas** [comment]
After adding the `datetime_bin` index, then this `UPDATE` query hangs
```sql
-- IF one of two 1-minute time bins BEFORE and AFTER 15-minute bin are populated, assume no interpolation needed
	UPDATE bins A 
	SET interpolated = FALSE
	FROM (SELECT intersection_uid, datetime_bin, SUM(volume) AS total_volume FROM volumes WHERE volume_15min_tmc_uid IS NULL GROUP BY intersection_uid, datetime_bin) B
	INNER JOIN (SELECT intersection_uid, datetime_bin, SUM(volume) AS total_volume FROM volumes WHERE volume_15min_tmc_uid IS NULL GROUP BY intersection_uid, datetime_bin) C ON B.intersection_uid = C.intersection_uid
	WHERE 	A.interpolated IS NULL 
		AND A.avail_minutes < 15 
		AND A.intersection_uid = B.intersection_uid 
		AND A.intersection_uid = C.intersection_uid 
		AND (B.datetime_bin >= (A.datetime_bin + INTERVAL '15 minutes') AND B.datetime_bin <= (A.datetime_bin + INTERVAL '16 minutes')) 
		AND (C.datetime_bin <= (A.datetime_bin - INTERVAL '1 minute') AND C.datetime_bin >= A.datetime_bin - (INTERVAL '2 minutes'));
```

**Comment by rickl4** [comment]
When converting the 1st and 3rd update statements to case when statement, the run time was 5:32. Subsituting the 2nd update statements for the following query gives a run time of 5:20

```SQL
UPDATE bins A 
SET interpolated = FALSE
FROM (SELECT DISTINCT intersection_uid, datetime_bin FROM rliu.volumes) B 
WHERE 	A.interpolated IS NULL 
	AND A.avail_minutes < 15 
	AND A.intersection_uid = B.intersection_uid 
	AND (B.datetime_bin BETWEEN (A.datetime_bin + INTERVAL '15 minutes') AND  (A.datetime_bin + INTERVAL '16 minutes')
OR B.datetime_bin BETWEEN(A.datetime_bin - INTERVAL '1 minute') AND (A.datetime_bin - (INTERVAL '2 minutes')));

```

I believe it may be an equivalent query but I'm not sure.

**Comment by rickl4** [comment]
June data: 654627 rows
May and June data: 1159923

June only: 5:21
May and June: 20:47
June with pre-existing May data in volumes, raw_data, and volumes_15min_tmc: 11:17

So not only it doesn't scale with data, pre-existing data also prolongs the run times. The `WHERE volume_15min_tmc_uid IS NULL` clause seems to be working though.

**Comment by radumas** [comment]
11 minutes is better than 1 hour 10 minutes!

Can you test with the `RAISE` statements ☝️ to see whether it's the second `UPDATE` that gets longer in the third test case, or if it's the final `INSERT`? (Try with April data with May and June already processed).

**Comment by rickl4** [comment]
All the tests I did so far were with pre-exisitng May data and new June data.

Dropping all indexes at the start and adding them back on at the end: 9:39 (improvement of about 100 seconds)
Creating a multi-column index for leg, classification, and movement columns: 9:36
Adding `WHERE a.volume_15min_tmc_uid IS NULL` clause to where the query was updating the `volume_15min_tmc_uid`: 5:31

About 5 minutes of the 5:31 was spent updating the volume_15min_tmc_uid.

**Comment by rickl4** [comment]
Adding `WHERE a.intersection_uid = b.intersection_uid` to the `SET volume_15min_tmc_uid = b.volume_15min_tmc_uid` reduces the run time significantly.

June data: 21 seconds to insert, 52 seconds total
May and June: 1:03 to insert, 2:36 total
April, May and June: 6:39 to insert and 16:11 total

**Comment by radumas** [comment]
Updated task list to wrap up.
