### ISSUE TITLE
Bug in miovision.aggregate_15min(), not all TMC rows updated with volume_15min_uid

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#137]
## Tasks

- [x] Develop crossover table for ATR & TMC Miovision volumes
- [x] Document the aggregation process from TMC to ATR in the README and [in the function](https://github.com/CityofToronto/bdit_data-sources/blob/c0ada3d94fe0cc1e330287e5021f7fe9213dd4fb/volumes/miovision/sql/function-aggregate-volumes_15min.sql)

## Background
Testing `DELETE` Triggers on #136 I noticed that a row in `volumes_15min` did not get deleted. 

Looking at this in aggregate, ~50% of TMC rows do not get linked to ATR rows:
```sql
SELECT  COUNT(1) , COUNT(a.volume_15min_tmc_uid) FROM miovision.volumes_15min b
LEFT OUTER JOIN miovision.volumes_15min_tmc a ON b.volume_15min_uid = a.volume_15min_uid
``` 
Produces

|Number of 15min volumes|Number of 15min volumes linked to TMC|
|--------:|----------:|
6070554|2385789

For my testing in April in the `rdumas` schema:

|Number of 15min volumes|Number of 15min volumes linked to TMC|
|--------:|----------:|
783716|316604

The linking in the `miovision` schema was done using only an `UPDATE` query, without actually redoing the aggregation, whereas the April data above was aggregated using [`miovision.aggregate_15_min()`](https://github.com/CityofToronto/bdit_data-sources/blob/c0ada3d94fe0cc1e330287e5021f7fe9213dd4fb/volumes/miovision/sql/function-aggregate-volumes_15min.sql#L33-L38)

I don't think the issue is with the `COALESCE`, since ATR rows with non-zero volume are also not getting linked, e.g.:

```sql
SELECT  b.* FROM rdumas.volumes_15min b
LEFT OUTER JOIN rdumas.volumes_15min_tmc a ON b.volume_15min_uid = a.volume_15min_uid
WHERE a.volume_15min_tmc_uid IS NULL AND b.volume > 0 
LIMIT 10
```
volume_15min_uid| intersection_uid| datetime_bin| classification_uid| leg| dir| volume
|-------------------:|-----------------:|----------------|------------------|----|-----|--------:|
910309|5|"2018-04-13 15:15:00"|4|"S"|"NB"|"4"
1283207|21|"2018-04-10 18:30:00"|3|"W"|"EB"|"9"
961437|7|"2018-04-12 13:30:00"|4|"S"|"NB"|"3"
1400743|25|"2018-04-12 16:15:00"|2|"W"|"EB"|"4"
1190142|17|"2018-04-12 21:00:00"|4|"S"|"SB"|"4"
1298887|22|"2018-04-07 14:30:00"|3|"W"|"EB"|"4"
824980|2|"2018-04-11 18:45:00"|2|"S"|"SB"|"2"
1382838|25|"2018-04-07 20:15:00"|4|"S"|"SB"|"2"
1319158|22|"2018-04-12 21:00:00"|3|"S"|"SB"|"2"
1225589|19|"2018-04-09 13:15:00"|4|"S"|"NB"|"3"

**Comment by rickl4** [comment]
So after talking to Aakash, my understanding is that there is a one to many relationship between `volumes_15min_tmc` and `volumes_15min`. In `volumes_15min_tmc`, theres 12 possible movements whereas in `volumes_15min` theres 16 possible movements. `volumes_15min` also populates all movements for all classes meaning that 2,633,919 rows of data with a volume of 0 is added to `volume_15min`. 

The table size of the two tables is also significantly different, which explains why each entry in `volumes_15min_tmc` has a `volume_15min_uid`

|Table|Row number|
|------|------|
|`volume_15min`|6,070,554|
|`volumes_15min_tmc`|2,997,045|

Which matches this query:

```SQL
SELECT  COUNT(1) , COUNT(a.volume_15min_tmc_uid) FROM miovision.volumes_15min b
LEFT OUTER JOIN miovision.volumes_15min_tmc a ON b.volume_15min_uid = a.volume_15min_uid
```

|Table|Row number|
|------|------|
|`volume_15min`|6,070,554|
|`volumes_15min_tmc`|2,997,045|

However, there still is an issue. Each `volume_15min` bin has up to 3 `volume_15min_tmc` bin assigned to it and each `volume_15min_tmc` bin corresponds to up to 3 `volume_15min` bin. This isn't being reflected in the foreign key which only assigns 1 `volume_15min_uid` to each bin. 

This query shows that a `volume_15min` bin can have multiple component `volume_15min_tmc` bin and a `volume_15min_tmc` bin can be in multiple `volume_15min` bin.

```SQL
	SELECT 	A.intersection_uid, 
		A.datetime_bin, 
		A.classification_uid,
		A.leg, 
		A.dir, 
		A.volume,
		array_agg(B.volume_15min_tmc_uid) as uids

	FROM miovision.volumes_15min A
	LEFT JOIN miovision.volumes_15min_tmc B USING (intersection_uid, classification_uid, datetime_bin)
	WHERE datetime_bin>'2018-06-01'
	GROUP BY A.intersection_uid, A.datetime_bin, A.classification_uid, A.leg, dir, a.volume
	ORDER BY A.datetime_bin, A.intersection_uid, A.classification_uid
```

**Comment by rickl4** [comment]
Not sure if the above query is 100% correct logic wise, but it shows the gist of the problem.

**Comment by rickl4** [comment]
These two queries populate potential crossover tables for the `volume_15min_tmc_uid`, `volume_uid`, and `volume_15min_uid`.

```SQL
--volume_uid and volume_15min_tmc_uid
SELECT c.volume_uid,  a.volume_15min_tmc_uid 
FROM rliu.volumes_15min_tmc A
FULL OUTER JOIN rliu.volumes C
ON c.datetime_bin >= a.datetime_bin AND c.datetime_bin < a.datetime_bin + INTERVAL '15 minutes'
AND a.intersection_uid=c.intersection_uid
AND a.leg=c.leg
AND a.movement_uid=c.movement_uid
AND a.classification_uid=c.classification_uid
```

```SQL
--volume_15min_tmc_uid and volume_15min_uid
SELECT a.volume_15min_uid, c.volume_15min_tmc_uid 
FROM rliu.volumes_15min A
LEFT JOIN miovision.movement_map B on B.leg_new = A.leg AND B.dir = A.dir
FULL OUTER JOIN rliu.volumes_15min_tmc C
ON a.datetime_bin=c.datetime_bin
AND a.intersection_uid=c.intersection_uid
AND b.leg_old=c.leg
AND b.movement_uid=c.movement_uid
AND a.classification_uid=c.classification_uid
```

These tables should be able to grab every combination in the many to many relationship between `volume_15min_tmc_uid`, and `volume_15min_uid`. Currently, it the corresponding id to `NULL` if there is no match. 

The easiest way to implelment this for new data is to use a trigger function after insert. 

When I tried to delete from the crossover tables, it only deletes from the crossover table, and doesn't cascade the delete.

**Comment by radumas** [comment]
@rickl4 re your last point
>When I tried to delete from the crossover tables, it only deletes from the crossover table, and doesn't cascade the delete.
The `FOREIGN KEY ... ON DELETE CASCADE` is one-directional: if the row that column is referencing (the primary key of either table) gets deleted, then the crossover table row will be deleted.
What I ended up implementing for the 1 -> 15-min crossover was having the crossover table have `FOREIGN KEY` references and then also a delete trigger. So when the `volumes` rows get deleted, then the corresponding crossover rows get deleted, which triggers deleting the 15-min rows.

**Comment by rickl4** [comment]
I made a new query [`function-populate-volumes_15min-crossover.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-populate-volumes_15min-crossover.sql). It implements the query I wrote above, and checks for valid movements with the process in #144 . 

In `volumes_15min` and `volumes_15min_tmc`, a new column `processed` is created to replace the `volume_15min_tmc_uid` column in both tables. This column is `TRUE` if that entry has been processed, and `NULL` if it hasn't. I can potentially add an option `FALSE` for data thats been processed but not included in `volumes_15min`. 

After the data has been inserted to `volumes_15min`, it populates the crossover table [`create-table-crossover-atr-tmc.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/create-table-crossover-atr-tmc.sql) and sets `processed` in both tables to `TRUE`.

**Comment by radumas** [comment]
Two more questions:

3. If invalid movements are prevented at aggregation to 15-min TMC, is the checking of valid movements still necessary at this stage?
4. Are [these two](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-populate-volumes_15min-crossover.sql#L29-L30) self-joins still necessary if zeroes are being filled in at the 15-min TMC stage?

**Comment by rickl4** [comment]
1&2. I don't think there would never be a situation where that situation may happen, and the bin needed to be set false. 
3. The query still needs to run an inner join with the valid movements, otherwise it will start filling in 0s for the invalid movements.
4. Zeroes would still need to be filled in for trucks.

**Comment by radumas** [comment]
Correct me if I'm missing something here, but it sounds like the `processed` column in the ATR is `NULL` when data is inserted, and then updated to be `TRUE`. Does it have a purpose?

If we are only filling in aggregate zeroes for classifications 1,2,6,7 and this happens at the 15-min aggregation stage, do we need to be filling in zeroes when aggregating to ATRs again?

**Comment by rickl4** [comment]
Its there so the function only runs on new entries/entries with a `NULL` value in the processed column. This replaces the `WHERE volume_15min_tmc_uid IS NULL` clause that used to be there.

We don't need to fill these zeroes again. I can add a where clause on the `LEFT JOIN` to only fill zeroes for the other classifications.

**Comment by rickl4** [comment]
I don't seem to have any further issues with `processed` not updating which probably mean there was an error calling the function or the changes to the query was not properly cascaded to the API. I added another returning clause just to be safe.

```SQL
CREATE OR REPLACE FUNCTION miovision_api_test.aggregate_15_min(
    start_date date,
    end_date date)
  RETURNS integer AS
$BODY$
BEGIN
    WITH transformed AS (
        SELECT     A.intersection_uid,
            A.datetime_bin,
            A.classification_uid,
            B.leg_new as leg,
            B.dir,
            SUM(A.volume) AS volume,
            array_agg(volume_15min_tmc_uid) as uids

        FROM miovision_api_test.volumes_15min_tmc A
        INNER JOIN miovision.movement_map B -- TMC to ATR crossover table.
        ON B.leg_old = A.leg AND B.movement_uid = A.movement_uid 
        WHERE A.processed IS NULL
        --AND datetime_bin BETWEEN start_date and end_date
        GROUP BY A.intersection_uid, A.datetime_bin, A.classification_uid, B.leg_new, B.dir
    ),
    insert_atr AS (
    INSERT INTO miovision_api_test.volumes_15min(intersection_uid, datetime_bin, classification_uid, leg, dir, volume)
    SELECT intersection_uid, datetime_bin, classification_uid, leg, dir, volume
    FROM transformed
    RETURNING volume_15min_uid, intersection_uid, datetime_bin, classification_uid, leg, dir)
    
    --Updates crossover table with new IDs
    , insert_crossover AS(
    INSERT INTO miovision_api_test.atr_tmc_uid (volume_15min_tmc_uid, volume_15min_uid)
    SELECT volume_15min_tmc_uid, volume_15min_uid
    FROM insert_atr A
    INNER JOIN (SELECT intersection_uid, datetime_bin, classification_uid, leg, dir, unnest(uids) as volume_15min_tmc_uid FROM transformed) B
        ON A.datetime_bin=B.datetime_bin
        AND A.intersection_uid=B.intersection_uid
        AND A.leg=B.leg
        AND A.classification_uid=B.classification_uid
    ORDER BY volume_15min_uid
	RETURNING volume_15min_tmc_uid
    )
    --Sets processed column to TRUE
    UPDATE miovision_api_test.volumes_15min_tmc a
    SET processed = TRUE
    FROM insert_crossover b 
    WHERE a.volume_15min_tmc_uid=b.volume_15min_tmc_uid;
    
    RETURN NULL;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE SECURITY DEFINER
  COST 100;
```
