### ISSUE TITLE
Include 0s in 15min TMC table

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#138]
Following the logic for including 0s in the ATR table, 0s should also be included in the TMC table for easier averaging.
- [x] Check how this affects aggregated views
- [x] Create a table of legal movements for each intersection
- [x] Create a crossover table to link 0-volume 15-min TMC rows from `volumes` to enable #136
- [x] Modify [aggregation function](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql) to create 0 records and populate the crossover table.

**Comment by radumas** [comment]
@aharpalaniTO if not all classifications do the same number of distinct movements in our 9 months of data.... should we fill in 0s for the other movements they've never done?

**Comment by radumas** [comment]
Per discussion, will only 0-fill classifications 1, 2, 6 and 7 (cars, bikes, and pedestrians).

**Comment by radumas** [comment]
Testing on April:

|Table                                                  | Count|
|----------------------------------------|-------:|
Before `rdumas.volumes_15min_tmc`|389,356
After `rdumas.volumes_15min_tmc`| 663,729
DISTINCT volume_15min_tmc_uid in `miovision.volumes` | 398,361
DISTINCT volume_15min_tmc_uid in `rdumas.volumes` |300,757

Total function took 11 mins to run.

**Comment by radumas** [comment]
I made a mistake in the previous testing: the array_agg(volume_15min_tmc_uid) was only for a subset of the  classifications. Rerunning tests:
```sql
WITH original AS (SELECT intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume
			   FROM miovision.volumes_15min_tmc
				INNER JOIN sample_volumes_tmc_actual sample USING (intersection_uid, datetime_bin)
			   )
SELECT intersection_uid, datetime_bin, classification_uid, leg, movement_uid
FROM sample_volumes_15min_tmc
WHERE volume > 0
EXCEPT 
SELECT intersection_uid, datetime_bin, classification_uid, leg, movement_uid
FROM original
ORDER BY intersection_uid, datetime_bin, classification_uid, leg, movement_uid
--0
--The reverse is also 0, so we haven't created any extra non-zero rows.
  SELECT COUNT(1)						 
	FROM sample_volume_15min_tmc_zeros;
 -- 2331
SELECT COUNT(1)						 
	FROM sample_volumes_15min_tmc;
 -- 4872
Approximately half this sample data produced is 0s, but the sample was explicitly chosen for having candidates for 0 filling.
```

**Comment by radumas** [comment]
Current function takes 98 minutes to run for April data...
Not ideal. 
If I change the FOREIGN KEY on the 0s table constraints to the below, getting rid of `ON UPDATE RESTRICT`, runtime goes down to 20 minutes, a bit over double what it was before for April.
```sql
ALTER TABLE rdumas.volumes_tmc_zeroes ADD FOREIGN KEY (volume_15min_tmc_uid)
        REFERENCES rdumas.volumes_15min_tmc (volume_15min_tmc_uid) MATCH SIMPLE
        ON DELETE CASCADE;
ALTER TABLE rdumas.volumes_tmc_zeroes ADD FOREIGN KEY (volume_uid)
        REFERENCES rdumas.volumes (volume_uid) MATCH SIMPLE
        ON DELETE CASCADE;
```

**Comment by radumas** [comment]
May: 5 min 16 secs.
June: 6 min 2 secs.
Delete June:  28.7 secs 

Non-zero April and May data exactly the same.

**Comment by radumas** [comment]
April: 11 mins
All 0 volumes appear in the 
Delete `raw_data` April: 3 min 52 s
No data left in `volumes`, `volumes_15min_tmc`, and `volumes_tmc_zeroes` :+1:

**Comment by rickl4** [comment]
I ran this entire process in conjunction with [`function-populate-volumes_15min-crossover.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/miovision_zero_pad_tmc/volumes/miovision/sql/function-populate-volumes_15min-crossover.sql) for July. There wasn't issues with run time,, but the query still had to create 0-volume bins.

|Classification|Number of 0-volume bins|
|------|-----|
|Buses|61362
|Lights|480
|Single-Unit Trucks|57322
|Articulated Trucks|77920
|Bicycle|11280

The 0-volume bins were spread out across multiple days and only at Adelaide/Bathurst, and Front/Bathurst.

**Comment by radumas** [comment]
so going forward, and this should be documented, we are only going to be creating 0-volume bins for classifications 1,2,6 and 7, see https://github.com/CityofToronto/bdit_data-sources/issues/138#issuecomment-413316409

The `intersection_movements` table was create 7 days ago, so could there be some new movement that wasn't present prior to July data?

Can you provide more information on Lights, are you sure this is a valid leg/movement that needs to be filled in?

What is missing for the bikes?

**Comment by rickl4** [comment]
I looked into it further, and all of those zeros were created with the [`function-aggregate-volumes_15min_tmc.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/miovision_zero_pad_tmc/volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql), so the previous comment I made isn't actually a problem.

But I discovered another issue. `intersection_movements` has invalid movements at 3 legged intersections, because miovision has been giving us data with those invalid movements. For example, there are 60 entries with WB thru movements at Adelaide/Bathurst for Lights in `miovision.volumes`. [`aggregate_15_min()` also does this when creating ATR data](https://github.com/CityofToronto/bdit_data-sources/issues/144).
