### ISSUE TITLE
Make deleting raw data a function

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#146]
In order to make sure deletion is cleaner, make deleting raw data a function with startdate and end_date inclusive. Possible checks: preventing deleting beyond a month...?

**Comment by rickl4** [comment]
Would something like this be acceptable?

```SQL
CREATE OR REPLACE FUNCTION rliu.delete_raw_data(
    start_date timestamp without time zone,
    end_date timestamp without time zone)
  RETURNS integer AS
$BODY$
BEGIN	
	IF end_date::date - start_date::date <30 THEN

		DELETE FROM rliu.raw_data
		WHERE datetime_bin BETWEEN start_date AND end_date;
		RETURN 1;
	ELSE 
		RAISE EXCEPTION 'Attempting to delete more than a month of data';
		RETURN 0;
	END IF;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by radumas** [comment]
I think having `start_date` and `end_date` be dates would ensure deletion is from midnight to midnight.

**Comment by rickl4** [comment]
I uploaded a revised version [here](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-delete_raw_data.sql). It took 12 seconds to delete 1 day of data from all tables in the `miovision_api` schema.

**Comment by radumas** [comment]
I guess this should now delete from `volumes` instead.
