### ISSUE TITLE
Change raw_data to a view/not actually store data

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#147]
It's possible to set up views/tables so they look like the raw data we receive, but the `INSERT TRIGGER`s on them mean that only the processed data which gets inserted into our ideal format (in this case `volumes` exists in the end. `DO INSTEAD`. This would solve the challenge of inserting data from the API vs. the `.csv` dumps. 

I'm not sure if pgAdmin will let one import data into a `VIEW`, so maybe just using `DO INSTEAD` will be ideal.

**Comment by rickl4** [comment]
I tried a trigger function on `rliu.raw_data_view` 

```SQL
CREATE TRIGGER populate_raw_data_view
  INSTEAD OF INSERT
  ON raw_data_view
  FOR EACH ROW
  EXECUTE PROCEDURE populate_raw_data_view();
```

Postgres 9 has functionality to insert into a view, but pgAdmin doesn't. When I used the query tool with this:

```SQL
INSERT INTO rliu.raw_data_view VALUES
``` 

it worked, but its probably not what we want if pgAdmin doesn't have functionality to insert into a view. I also ran into another issue. To create the view, I joined `miovision.classifications`, `miovision.intersections` and `miovision.movements` onto `volumes`. But there are still columns that can't be replicated by the joins like `exit_name`, `study_id`, etc. which creates errors when directly inserting the csv file into the view.

For `DO INSTEAD` would it be something like this:

```SQL 
CREATE OR REPLACE RULE populate_raw_data_view AS
  ON INSERT TO raw_data_view
  DO INSTEAD
	INSERT INTO rliu.volumes (intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume)
	SELECT B.intersection_uid, (NEW.datetime_bin AT TIME ZONE 'America/Toronto') AS datetime_bin, C.classification_uid, NEW.entry_dir_name as leg, D.movement_uid, NEW.volume
	FROM miovision.intersections B 
	INNER JOIN miovision.movements D ON (D.movement = NEW.movement)
	INNER JOIN miovision.classifications C ON C.classification = NEW.classification AND C.location_only = D.location_only
	WHERE regexp_replace(NEW.study_name,'Yong\M','Yonge') = B.intersection_name;
```

**Comment by radumas** [comment]
For the missing columns you can do something like
```sql
CREATE OR REPLACE VIEW rliu.raw_data_view AS
 SELECT NULL::bigint   study_id ,
    NULL::TEXT study_name text,
    lat numeric,
    lng numeric,
    datetime_bin ,
    classification ,
    entry_dir_name ,
    entry_name ,
    NULL::TEXT exit_dir_name,
    NULL::TEXT exit_name ,
    movement text,
    volume integer
)
```

**Comment by rickl4** [comment]
Postgres does not allow using a instead trigger on a table. I've also tried using a rule on the `raw_data` table, but it no matter the syntax, it always inserts the data to `raw_data`. 

One alternative is to import to the view directly. pgAdmin doesn't allow this, but its possible using alternative methods such as Python

```python
import psycopg2

cur = conn.cursor()
with open('miovision_data.csv', 'r') as csv_dump:
    cur.copy_from(csv_dump, rliu.raw_data_view', sep=',')
    
conn.commit()
```

in combination with an `INSTEAD OF INSERT` trigger.

Another option is to alter the existing `insert_volumes` trigger so it `RETURNS NULL`. Since the trigger is before the insert, after it populates `volumes` there won't be any data to insert into `raw_data`. This was an accidental discovery when I first was looking developing a trigger for `volumes`.

```SQL
CREATE OR REPLACE FUNCTION miovision.insert_volumes()
  RETURNS trigger AS
$BODY$

BEGIN

	INSERT INTO miovision.volumes (intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume)
	SELECT B.intersection_uid, (NEW.datetime_bin AT TIME ZONE 'America/Toronto') AS datetime_bin, C.classification_uid, NEW.entry_dir_name as leg, D.movement_uid, NEW.volume
	FROM miovision.intersections B 
	INNER JOIN miovision.movements D ON (D.movement = NEW.movement)
	INNER JOIN miovision.classifications C ON C.classification = NEW.classification AND C.location_only = D.location_only
	WHERE regexp_replace(NEW.study_name,'Yong\M','Yonge') = B.intersection_name;
	RETURN NULL;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

I think the second is the easier/simpler solution.

**Comment by radumas** [comment]
Going forward the pgAdmin issue is moot since pulling from API will be done via Python.

The second solution is quite elegant
