### ISSUE TITLE
Integrate checking validity of movements into API pipeline

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#148]
#144 checks if movements provided in the flat files are valid. Integrate this into the API pipeline #101

**Comment by rickl4** [comment]
The API now calls the [`find_invalid_movements()`](https://github.com/CityofToronto/bdit_data-sources/blob/automate_miovision_aggregation/volumes/miovision/sql/function-find_invalid_movements.sql#L15-L65) function, and logs the `conn.notices`. No exception is raised if the number of invalid movements is above 1000.

However, if I pull multiple days of data, this can happen:

```
 ['NOTICE:  Number of invalid movements less than 1000\n', 'NOTICE:  Mon Sep 10 19:44:53.454348 2018 UTC Function Start\n', 'NOTICE:  table "bins" does not exist, skipping\n', 'NOTICE:  Mon Sep 10 19:44:54.194426 2018 UTC Insert Finished\n', 'NOTICE:  Mon Sep 10 19:44:54.693112 2018 UTC 2nd update\n', 'NOTICE:  Mon Sep 10 19:44:54.700265 2018 UTC Adjusting Interpolated Bins\n', 'NOTICE:  Mon Sep 10 19:44:54.700313 2018 UTC Rest of interpolated conditional\n', 'NOTICE:  Number of invalid movements less than 1000\n']
```

So if I was pulling 1 month of data, day 1 will log 1 notice, but day 30 will log 30 notices, 29 of them being repeated from previous days.
Is there a way to only capture the most recent notice in psycopg2 and properly format the notice?

**Comment by radumas** [comment]
Nice work!
`conn.notices` returns an array right? Can you filter the array of `NOTICES` to only include `NOTICE:  Number of invalid movements less than 1000\n`. I guess you also want to make sure you're connecting the notice to the right date when logging.
[From the documentation](http://initd.org/psycopg/docs/connection.html#connection.notices) it sounds like we can write to `conn.notices`, so at the start/end of each cycle could do something like `conn.notices = None`

**Comment by radumas** [comment]
Integration into the API looks good.
Gonna reiterate this
>I think it would be easier to maintain (and extend) a check against movements which are explicitly allowed in intersection_movements rather than enumerating all possible wrong movements.
