### ISSUE TITLE
Log date added/filename during data imports to PostgreSQL

### ISSUE THREAD

**Issue by rickl4** [CityofToronto/bdit_data-sources#149]
To traceback the source of problematic data, a log of the date added to the database or the filename the data is from should be available

**Comment by rickl4** [comment]
I created a table in the `miovision_api_test` schema while testing the views named [`api_log`](https://github.com/CityofToronto/bdit_data-sources/blob/miovision_api/volumes/miovision/sql/create-table-api_log.sql). [This function](https://github.com/CityofToronto/bdit_data-sources/blob/miovision_api/volumes/miovision/sql/function-api_log.sql), when called, will insert the date, intersection and date pulled to the table to create a history of when data was pulled. I didn't subdivide it to classifications since all classifications were pulled at the same time, while intersections can potentially be pulled separately.

For the CSV dumps, I think logging the filenames will be hard to implement automatically, without using python. Date added is simpler and retains the original purpose since the data is organized by date added on the K drive. 

Altering the volumes table/trigger to include a date added column
```SQL
	INSERT INTO miovision_api.volumes (intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume, date_added)
	SELECT B.intersection_uid, (NEW.datetime_bin AT TIME ZONE 'America/Toronto') AS datetime_bin, C.classification_uid, NEW.entry_dir_name as leg, D.movement_uid, NEW.volume, cuurent_timestamp::date
	FROM miovision.intersections B 
	INNER JOIN miovision.movements D ON (D.movement = NEW.movement)
	INNER JOIN miovision_api.classifications C ON C.classification = NEW.classification AND C.location_only = D.location_only
	WHERE regexp_replace(NEW.study_name,'Yong\M','Yonge') = B.intersection_name
	RETURNING volume_uid INTO NEW.volume_uid;
	RETURN NEW;
```

Then we can create a view displaying the relevant info for the log. The advantages of a view over a table with a primary key is that updating data and the log will be faster.

```SQL
CREATE OR REPLACE VIEW miovision_log
SELECT 
intersection_uid, 
min(datetime_bin::date) AS min_date, 
max(datetime_bin::date) AS max date, 
min(volume_uid) AS min_volume_uid,
max(volume_uid) AS max_volume_uid,
date_added
FROM miovision.volumes
GROUP BY intersection_uid, date_added
ORDER BY intersection_uid, date_added
```

These tables/views are very similar to the `report_dates` table that already exists.

**Comment by rickl4** [comment]
Decided to turn the API logging into a separate function that inserts the data to `miovision_api.api_log`. The data is not detailed right now, but since we're not pulling specific intersections/dates/classes, its not that big of an issue.

```
CREATE OR REPLACE FUNCTION miovision_api.api_log(
    start_date date,
    end_date date)
  RETURNS integer AS
$BODY$
BEGIN


INSERT INTO miovision_api.api_log (intersection_uid, start_date, end_date, date_added)
SELECT intersection_uid,  MIN(datetime_bin::date), MAX(datetime_bin::date), current_timestamp::date from miovision_api.volumes
WHERE datetime_bin BETWEEN start_date AND end_date
GROUP BY intersection_uid
ORDER BY current_timestamp::date, intersection_uid;

	RETURN NULL;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by radumas** [comment]
I think this is done.
