### ISSUE TITLE
Define extreme value

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#162]
Develop logic for identifying extreme values in a traffic volumes dataset

**Comment by chelsrosic** [comment]
Look at the IQR method 
https://machinelearningmastery.com/how-to-use-statistics-to-identify-outliers-in-data/

so for each intersection + leg + movement combination
figure out the IQR = 75th percentile - 25th percentile
and flag anything that is either:
-  LESS THAN (25th percentile - IRQ*k)
- MORE THAN (75th percentile + IQR*k)
and play around with different values of k
start with 1.5

**Comment by chelsrosic** [comment]
I implemented the above workflow. I played with the k value,  trying to make the percentage of outliers in the dataset decrease from 7.63

| k value  | % of outliers | 
| ------------- |:-------------:|
| 1.5     | 7.63  |
| 2 |  6.04 |
|2.5  |  5.6  |
| 3 | 4.95 |

The code I used was: 
```sql 
sql_volumes = '''
SELECT px, location, class_type, leg, movement, datetime_bin, volume_15min 
FROM crosic.volumes_tmc_bikes
'''

sql_locations = '''
SELECT DISTINCT ON (px, leg, movement) px, leg, movement
FROM crosic.volumes_tmc_bikes
'''

locations = pandasql.read_sql(sql_locations, con)
volumes = pandasql.read_sql(sql_volumes, con)

final_df = pd.DataFrame(columns=[ 'px', 'location', 'class_type', 'leg', 'movement', 'datetime_bin', 'volume_15min' ])
outliers = pd.DataFrame(columns=[ 'px', 'location', 'class_type', 'leg', 'movement', 'datetime_bin', 'volume_15min' ])

for row in locations.itertuples():
    subset = volumes.loc[ (volumes['px'] == row.px) & (volumes['leg'] == row.leg) & (volumes['movement'] == row.movement)]

    p25, p75 = np.percentile(subset['volume_15min'], 25), np.percentile(subset['volume_15min'], 75)
    iqr = p75 - p25

    # calculate outlier cut off 
    # if volume value is not between lower and upper than it will be considered an outlier
    cut_off = iqr*1.5
    lower, upper = int(p25 - cut_off), int(p75 + cut_off)
    # we cannot have a negative traffic volume
    if lower < 0: 
        lower = 0
    
    # identify outliers
    frames = [outliers, subset.loc[(subset['volume_15min'] < lower) | (subset['volume_15min'] > upper)]  ]
    outliers = pd.concat(frames)
    
    
    # all records that are not outliers
    frames = [final_df, subset.loc[(subset['volume_15min'] >= lower) & (subset['volume_15min'] <= upper)]  ]
    final_df = pd.concat(frames)
  
```

**Comment by aharpalaniTO** [comment]
Can you further investigate whether these outliers are true outliers? Or is it just a case of high variance intersections? For example, if you're looking at King and Spadina cycling volumes, presumably the 15 minute volumes vary significantly between month and time of day. You might need to introduce some additional dimensions into your analysis (e.g. month, time-of-day, etc.)

**Comment by chelsrosic** [comment]
For issue #156 , there were no extreme values identified. The analysis conducted to back this conclusion used the interquartile range (IQR) of the volumes. Outliers were calculated for each unique px number, leg, and movement. Most of the outlier volumes had a volume of 2-4, which is definitely not an "extreme value" given the overall histogram plot for all 15 minute volume counts:
![image](https://user-images.githubusercontent.com/32607196/46431074-d450ae80-c718-11e8-9289-c7e8524b4706.png)


The highest values were value was 203, but even the higher values were not considered to be extreme given that there is a gradual decrease in volumes to get to this value:
![image1](https://user-images.githubusercontent.com/32607196/46430661-ba629c00-c717-11e8-8157-8f77a0238ae8.png)


The process was also modified to conduct IQR outlier classification on each unique px number, leg,  movement, month, and hour. The trends did not change. 

After, the process was completed by changing the percentlies in the IQR method from 25 and 75 to 0 and 75, 10 and 90, 5 and 90, and 5 and 95. All of these results showed similar trends, where most of the values identified as outliers were between the values of 2 and 4 (not extreme values). Therefore, the conclusion that there are no "extreme values" in this dataset was reached.
