### ISSUE TITLE
King Street Pilot - Miovision Volumes (Open Data)

### ISSUE THREAD

**Issue by rickl4** [CityofToronto/bdit_data-sources#163]
There are 2143 entries used for King street pilot reporting in 10 periods (Baseline, December, January etc.). This number only includes the AM/PM Peak Periods.

636 entries on `open_data.ksp_miovision_summary` do not match the spreadsheets used for Miovision reporting. 206 of these entries are because they are not in `open_data.ksp_miovision_summary` at all. 

Breakdown of number of discrepancies by month and classification:

| Period   | Cyclists | Pedestrians | Vehicles |
|----------|----------|-------------|----------|
| Baseline | 16       | 36          | 18       |
| Dec-17   | 17       | 36          | 18       |
| Jan-18   | 12       | 29          | 17       |
| Feb-18   | 14       | 34          | 17       |
| Mar-18   | 14       | 32          | 17       |
| Apr-18   | 14       | 36          | 18       |
| May-18   | 16       | 32          | 19       |
| Jun-18   | 12       | 31          | 15       |
| Jul-18   | 14       | 28          | 16       |
| Aug-18   | 15       | 28          | 15       |

Breakdown of number of discrepancies by intersection and classification:

| Intersection                                   | Cyclists | Pedestrians | Vehicles |
|------------------------------------------------|----------|-------------|----------|
| Adelaide St E / Jarvis St / St. James Park Trl | 11       | 30          | 18       |
| Bathurst St / Adelaide St W                    | 17       | 30          | 18       |
| Bathurst St / Front St W                       | 0        | 0           | 1        |
| Bathurst St / Richmond St W                    | 20       | 40          | 20       |
| Bay St / Adelaide St W                         | 15       | 36          | 18       |
| Bay St / King St W                             | 2        | 6           | 2        |
| Bay St / Queen St W                            | 2        | 2           | 2        |
| Bay St / Richmond St W                         | 17       | 35          | 19       |
| Bay St / Wellington St W                       | 6        | 40          | 18       |
| Richmond St E / Jarvis St                      | 18       | 34          | 18       |
| Spadina Ave / Adelaide St W                    | 18       | 33          | 18       |
| Spadina Ave / Richmond St W                    | 17       | 36          | 18       |

Total number of entries by month:

| Period   | Total |
|----------|-------|
| Baseline | 215   |
| Dec-17   | 214   |
| Jan-18   | 212   |
| Feb-18   | 213   |
| Mar-18   | 214   |
| Apr-18   | 214   |
| May-18   | 215   |
| Jun-18   | 215   |
| Jul-18   | 216   |
| Aug-18   | 215   |

Total number of entries by intersections (only including intersections that have discrepancies):

| Intersection                                   | Total |
|------------------------------------------------|-------|
| Adelaide St E / Jarvis St / St. James Park Trl | 80    |
| Bathurst St / Adelaide St W                    | 80    |
| Bathurst St / Front St W                       | 109   |
| Bathurst St / Richmond St W                    | 80    |
| Bay St / Adelaide St W                         | 80    |
| Bay St / King St W                             | 120   |
| Bay St / Queen St W                            | 120   |
| Bay St / Richmond St W                         | 80    |
| Bay St / Wellington St W                       | 80    |
| Richmond St E / Jarvis St                      | 80    |
| Spadina Ave / Adelaide St W                    | 80    |
| Spadina Ave / Richmond St W                    | 80    |

Bathurst/King, Bathurst/Quenn, Bay/Front, Jarvis/Front, King/Jarvis, Queen/Jarvis, Spadina/Front, Spadina/King don't have any discrepancies. 

A large portion of discrepancies is because certain intersections in `open_data.ksp_miovision_summary` are missing months of data. These intersections don't have any data for any classification for the following months:

| Intersection                                   | Missing Periods        |
|------------------------------------------------|------------------------|
| Adelaide St E / Jarvis St / St. James Park Trl | Feb, Apr               |
| Bathurst St / Adelaide St W                    | Dec                    |
| Bathurst St / Richmond St W                    | All                    |
| Bay St / Adelaide St W                         | Baseline/Dec           |
| Bay St / Richmond St W                         | Baseline/Dec           |
| Bay St / Wellington St W                       | Feb                    |
| Richmond St E / Jarvis St                      | Dec, Jan,Feb, Mar, Apr |
| Spadina Ave / Adelaide St W                    | Feb, Apr               |
| Spadina Ave / Richmond St W                    | Baseline, Dec, Mar     |

Of the intersections where the discrepancies are due to a mismatch of numbers, the error is generally higher for cycling volumes (above 10%) and lower for pedestrians/vehicles (under 10%). The average difference is generally under 100 but above 50 counts:

Absolute average difference between open data and miovision reporting by month:

| Period   | Cyclists | Pedestrians | Vehicles |
|----------|----------|-------------|----------|
| Baseline | 100.0    | 60.5        | 135.8    |
| Dec-17   | 44.3     | 78.1        | 120.0    |
| Jan-18   | 21.3     | 50.0        | 56.9     |
| Feb-18   | 23.3     | 65.6        | 91.1     |
| Mar-18   | 30.0     | 36.5        | 66.4     |
| Apr-18   | 105.0    | 101.5       | 64.0     |
| May-18   | 43.6     | 71.8        | 37.6     |
| Jun-18   | 57.0     | 51.9        | 46.2     |
| Jul-18   | 93.3     | 60.8        | 34.3     |
| Aug-18   | 94.6     | 90.8        | 64.6     |

Absolute average difference between open data and miovision reporting by intersection:

| Intersection                                   | Cyclists | Pedestrians | Vehicles |
|------------------------------------------------|----------|-------------|----------|
| Adelaide St E / Jarvis St / St. James Park Trl | 23.3     | 26.5        | 50.6     |
| Bathurst St / Adelaide St W                    | 95.3     | 18.1        | 84.4     |
| Bathurst St / Front St W                       |          |             | 20.0     |
| Bathurst St / Richmond St W                    |          |             |          |
| Bay St / Adelaide St W                         | 50.9     | 112.5       | 90.0     |
| Bay St / King St W                             | 10.0     | 121.7       | 10.0     |
| Bay St / Queen St W                            | 10.0     | 295.0       | 35.0     |
| Bay St / Richmond St W                         | 47.3     | 65.2        | 80.6     |
| Bay St / Wellington St W                       | 12.5     | 101.7       | 74.4     |
| Richmond St E / Jarvis St                      | 52.2     | 18.6        | 41.3     |
| Spadina Ave / Adelaide St W                    | 113.6    | 69.6        | 75.7     |
| Spadina Ave / Richmond St W                    | 69.1     | 49.6        | 35.0     |

Percent error between open data and miovision reporting by month:

| Period   | Cyclists | Pedestrians | Vehicles |
|----------|----------|-------------|----------|
| Baseline | 22.6     | 9.3         | 5.9      |
| Dec-17   | 16.2     | 6.3         | 4.0      |
| Jan-18   | 18.8     | 4.7         | 2.1      |
| Feb-18   | 18.6     | 6.7         | 3.7      |
| Mar-18   | 13.6     | 4.4         | 2.4      |
| Apr-18   | 34.5     | 8.0         | 2.1      |
| May-18   | 10.1     | 4.5         | 1.9      |
| Jun-18   | 9.9      | 3.4         | 2.1      |
| Jul-18   | 10.0     | 5.3         | 1.3      |
| Aug-18   | 18.5     | 6.3         | 2.5      |

Percent error between open data and miovision reporting by intersection:

| Intersection                                   | Cyclists | Pedestrians | Vehicles |
|------------------------------------------------|----------|-------------|----------|
| Adelaide St E / Jarvis St / St. James Park Trl | 10.6     | 3.9         | 1.7      |
| Bathurst St / Adelaide St W                    | 21.2     | 10.3        | 4.6      |
| Bathurst St / Front St W                       |          |             | 1.2      |
| Bathurst St / Richmond St W                    |          |             |          |
| Bay St / Adelaide St W                         | 12.2     | 5.8         | 2.9      |
| Bay St / King St W                             | 7.4      | 4.0         | 3.6      |
| Bay St / Queen St W                            | 11.3     | 7.1         | 2.7      |
| Bay St / Richmond St W                         | 15.0     | 5.0         | 2.6      |
| Bay St / Wellington St W                       | 31.3     | 5.2         | 2.8      |
| Richmond St E / Jarvis St                      | 10.8     | 4.6         | 1.3      |
| Spadina Ave / Adelaide St W                    | 19.3     | 6.6         | 3.0      |
| Spadina Ave / Richmond St W                    | 15.5     | 4.5         | 1.4      |

Note that the difference can be positive or negative. The values in the four tables above are based off the magnitude of the difference.

**Comment by radumas** [comment]
So this view was last updated April 24th. 

Per our discussion of this issue, paths for debugging:

- [  ] Check dependency views to see if any are outdated.
- [  ] See if the code could be optimized
- [  ] Could there be missing ATR data in the `miovision` schema?
- [  ] Check the reporting legs for one-way streets.

I clearly copied the query from.... something. But I can't seem to find that in the repository :man_shrugging: . One immediate red-flag for this issue [is the `WHERE` clause in the view](https://github.com/CityofToronto/bdit_data-sources/blob/ff8d4cde51fdd63a4d6e593f0675681c63ad7e03/volumes/miovision/sql/open_data_views.sql#L123). It limits the intersections to the 4 screen lines: Bathurst, Spadina, Bay, and Jarvis (which doesn't explain this discrepancy) and then also limits the legs for each intersection:
```sql
AND (c.street_cross = 'Bathurst'::text AND (a.leg = ANY (ARRAY['E'::text, 'S'::text, 'N'::text])) OR
         c.street_cross = 'Jarvis'::text AND (a.leg = ANY (ARRAY['W'::text, 'S'::text, 'N'::text])) OR 
        (c.street_cross <> ALL (ARRAY['Bathurst'::text, 'Jarvis'::text])) 
               AND (a.dir = 'EB'::text AND (a.leg = ANY (ARRAY['W'::text, 'N'::text, 'S'::text])) 
                  OR a.dir = 'WB'::text AND (a.leg = ANY (ARRAY['E'::text, 'N'::text, 'S'::text])))) 
                        AND NOT ((a.class_type = ANY (ARRAY['Vehicles'::text, 'Cyclists'::text])) 
                                 AND (a.dir = 'EB'::text AND (c.street_main = ANY (ARRAY['Wellington'::text, 'Richmond'::text])) 
                                OR a.dir = 'WB'::text AND c.street_main = 'Adelaide'::text))
```

**Comment by rickl4** [comment]
I think the problem is in `valid_bins`, `int_avg`, and `volumes_15` sections of the `open_data.ksp_miovision_summary` query.

 If I only compared this section
```SQL
SELECT daily.period_type AS aggregation_period,
    intersections.int_id,
    centreline_intersection.intersec5 AS intersection_name,
    traffic_signals.px,
        CASE
            WHEN daily.class_type = 'Buses'::text THEN 'Buses and streetcars'::text
            ELSE daily.class_type
        END AS classification,
    daily.dir,
    daily.period_name,
    round(avg(daily.total_volume), '-1'::integer)::integer AS average_volume
   FROM daily
     JOIN miovision.intersections USING (intersection_uid)
     JOIN gis.centreline_intersection USING (int_id)
     JOIN gis.traffic_signals ON traffic_signals.node_id = intersections.int_id
  GROUP BY daily.period_type, intersections.int_id, daily.class_type, centreline_intersection.intersec5, traffic_signals.px, daily.dir, daily.period_name;
```
 section and replaced `FROM daily` with `FROM miovision.report_daily` I got 17 differences. Those differences were at Bay/King in June, Adelaide/Bathurst in July/Aug and Adelaide/Spadina in July/Aug. Adelaide/Bathurst and Adelaide/Spadina were flagged in QC checks during those months. If I compared 

```SQL
daily AS (
         SELECT a.intersection_uid,
            c.intersection_name,
            c.street_main,
            c.street_cross,
            a.class_type,
            a.dir,
            a.period_type,
            a.datetime_bin::date AS dt,
            b.period_name ||
                CASE
                    WHEN b.period_id = 7 THEN ''::text
                    ELSE (((' ('::text || to_char(lower(b.period_range)::interval, 'HH24:MM'::text)) || '-'::text) || to_char(upper(b.period_range)::interval, 'HH24:MM'::text)) || ')'::text
                END AS period_name,
            sum(a.volume) AS total_volume
           FROM volumes_15 a
             CROSS JOIN miovision.periods b
             JOIN miovision.intersections c USING (intersection_uid)
             JOIN intersection_days d ON d.intersection_uid = a.intersection_uid AND a.datetime_bin::date = d.dt
          WHERE a.datetime_bin::time without time zone <@ b.period_range AND b.report_flag AND (a.dir = ANY (ARRAY['EB'::text, 'WB'::text])) AND (b.period_id <> 7 OR d.num_daily_observations > (23 * 4)) AND (c.street_cross = ANY (ARRAY['Bathurst'::text, 'Spadina'::text, 'Bay'::text, 'Jarvis'::text])) AND (c.street_cross = 'Bathurst'::text AND (a.leg = ANY (ARRAY['E'::text, 'S'::text, 'N'::text])) OR c.street_cross = 'Jarvis'::text AND (a.leg = ANY (ARRAY['W'::text, 'S'::text, 'N'::text])) OR (c.street_cross <> ALL (ARRAY['Bathurst'::text, 'Jarvis'::text])) AND (a.dir = 'EB'::text AND (a.leg = ANY (ARRAY['W'::text, 'N'::text, 'S'::text])) OR a.dir = 'WB'::text AND (a.leg = ANY (ARRAY['E'::text, 'N'::text, 'S'::text])))) AND NOT ((a.class_type = ANY (ARRAY['Vehicles'::text, 'Cyclists'::text])) AND (a.dir = 'EB'::text AND (c.street_main = ANY (ARRAY['Wellington'::text, 'Richmond'::text])) OR a.dir = 'WB'::text AND c.street_main = 'Adelaide'::text))
          GROUP BY a.intersection_uid, c.intersection_name, c.street_main, c.street_cross, a.period_type, a.class_type, a.dir, (a.datetime_bin::date), b.period_name, b.period_range, b.period_id
        )
 SELECT daily.period_type AS aggregation_period,
    intersections.int_id,
    centreline_intersection.intersec5 AS intersection_name,
    traffic_signals.px,
        CASE
            WHEN daily.class_type = 'Buses'::text THEN 'Buses and streetcars'::text
            ELSE daily.class_type
        END AS classification,
    daily.dir,
    daily.period_name,
    round(avg(daily.total_volume), '-1'::integer)::integer AS average_volume
   FROM daily
     JOIN miovision.intersections USING (intersection_uid)
     JOIN gis.centreline_intersection USING (int_id)
     JOIN gis.traffic_signals ON traffic_signals.node_id = intersections.int_id
  GROUP BY daily.period_type, intersections.int_id, daily.class_type, centreline_intersection.intersec5, traffic_signals.px, daily.dir, daily.period_name;
``` 
and replaced `FROM volumes_15` with `FROM miovision.report_volumes_15min` , then there are 27 differences. This includes the intersections above and Bay/King in May and Bay/Queen in May.  This means at least 610 of the differences are caused by the section mimicking `report_volumes_15min` 

On another note, how necessary is it to redo the processing for `volumes_15min_by_class` and `report_volumes_15min` rather than selecting stuff from `report_daily`?

**Comment by radumas** [comment]
So my memory has been jogged a bit. The reason the open data view is a rejigging of the reporting pipeline starting at `report_volumes_15min` through to `volumes_15min_by_class`, `report_daily`, and `report_summary` is that we wanted to include more time periods in the Open Data summaries, and so `valid_bins` is different because it does the `CROSS JOIN` on the full 24hrs of 15-min bins.

**Comment by rickl4** [comment]
Of the remaining 29 entries with differences, 15 had differences less than 10. This could be due to the new processing method. 

| Intersection                | Month  | Period  | Direction | Class       | Reporting Volumes | Open Data Volumes | Difference |
|-----------------------------|--------|---------|-----------|-------------|-------------------|-------------------|------------|
| Bathurst St / Adelaide St W | Jul-18 | AM Peak | EB        | Cyclists    | 1170              | 1190              | 20         |
| Bathurst St / Adelaide St W | Jul-18 | AM Peak | EB        | Pedestrians | 240               | 200               | 40         |
| Bathurst St / Richmond St W | Dec-17 | AM Peak | WB        | Vehicles    | 950               | 940               | 10         |
| Bathurst St / Richmond St W | Feb-18 | PM Peak | WB        | Vehicles    | 1720              | 1710              | 10         |
| Bathurst St / Richmond St W | Jan-18 | AM Peak | WB        | Vehicles    | 950               | 940               | 10         |
| Bathurst St / Richmond St W | Jul-18 | AM Peak | WB        | Vehicles    | 950               | 940               | 10         |
| Bathurst St / Richmond St W | Jul-18 | PM Peak | WB        | Vehicles    | 1930              | 1920              | 10         |
| Bathurst St / Richmond St W | Jun-18 | PM Peak | WB        | Vehicles    | 1630              | 1620              | 10         |
| Bay St / King St W          | Jun-18 | PM Peak | WB        | Cyclists    | 130               | 140               | 10         |
| Bay St / King St W          | Jun-18 | AM Peak | EB        | Pedestrians | 2790              | 2770              | 20         |
| Bay St / King St W          | Jun-18 | AM Peak | WB        | Pedestrians | 2900              | 2860              | 40         |
| Bay St / King St W          | Jun-18 | PM Peak | EB        | Pedestrians | 4080              | 3920              | 160        |
| Bay St / King St W          | Jun-18 | PM Peak | WB        | Pedestrians | 4100              | 3900              | 200        |
| Bay St / King St W          | Jun-18 | AM Peak | EB        | Vehicles    | 420               | 430               | 10         |
| Bay St / King St W          | May-18 | AM Peak | EB        | Cyclists    | 140               | 150               | 10         |
| Bay St / King St W          | May-18 | AM Peak | EB        | Pedestrians | 2300              | 2410              | 110        |
| Bay St / King St W          | May-18 | AM Peak | WB        | Pedestrians | 2400              | 2600              | 200        |
| Bay St / King St W          | May-18 | AM Peak | WB        | Vehicles    | 210               | 200               | 10         |
| Bay St / Queen St W         | May-18 | PM Peak | EB        | Cyclists    | 70                | 80                | 10         |
| Bay St / Queen St W         | May-18 | PM Peak | WB        | Cyclists    | 120               | 110               | 10         |
| Bay St / Queen St W         | May-18 | PM Peak | WB        | Pedestrians | 3980              | 3680              | 300        |
| Bay St / Queen St W         | May-18 | PM Peak | EB        | Pedestrians | 4350              | 4060              | 290        |
| Bay St / Queen St W         | May-18 | PM Peak | WB        | Vehicles    | 1120              | 1080              | 40         |
| Bay St / Queen St W         | May-18 | PM Peak | EB        | Vehicles    | 1680              | 1650              | 30         |
| Spadina Ave / Adelaide St W | Jul-18 | PM Peak | EB        | Cyclists    | 480               | 490               | 10         |
| Spadina Ave / Adelaide St W | Jul-18 | AM Peak | EB        | Cyclists    | 1420              | 1540              | 120        |
| Spadina Ave / Adelaide St W | Jul-18 | AM Peak | WB        | Pedestrians | 800               | 780               | 20         |
| Spadina Ave / Adelaide St W | Jul-18 | AM Peak | EB        | Pedestrians | 990               | 980               | 10         |
| Spadina Ave / Queen St W    | Mar-18 | AM Peak | EB        | Cyclists    | 50                | 40                | 10         |

**Comment by rickl4** [comment]
I checked the 14 entries with a difference more than 10. 

| Intersection                | Month  | Period  | Direction | Class       | Reporting Volumes | Open Data Volumes | Difference |
|-----------------------------|--------|---------|-----------|-------------|-------------------|-------------------|------------|
| Bathurst St / Adelaide St W | Jul-18 | AM Peak | EB        | Cyclists    | 1170              | 1190              | 20         |
| Bathurst St / Adelaide St W | Jul-18 | AM Peak | EB        | Pedestrians | 240               | 200               | 40         |
| Spadina Ave / Adelaide St W | Jul-18 | AM Peak | EB        | Cyclists    | 1420              | 1540              | 120        |
| Spadina Ave / Adelaide St W | Jul-18 | AM Peak | WB        | Pedestrians | 800               | 780               | 20         |

This intersection was flagged in the QC check, and the `open_data` volume matched the reporting spreadsheet `K:\tra\GM Office\Big Data Group\Work\King St Pilot\Reporting\Volumes\2018-07\King Street Transit Pilot Traffic Volumes - July 2018 Summary - 2018-08-16.xlsx`. But that file only contains the rounded/formatted values and doesn't have the base data  like in `K:\tra\GM Office\Big Data Group\Work\King St Pilot\Reporting\Volumes\2018-07\Count Data Draft - July 2018.xlsx`, which was used for the comparison/open data checks. This means that the `open_data` view will match what we reported for the King Pilot, but for future months, we'll have to re-copy the July data to the reporting spreadsheet with the updated changes. 

| Intersection                | Month  | Period  | Direction | Class       | Reporting Volumes | Open Data Volumes | Difference |
|-----------------------------|--------|---------|-----------|-------------|-------------------|-------------------|------------|
| Bay St / King St W          | May-18 | AM Peak | EB        | Pedestrians | 2300              | 2410              | 110        |
| Bay St / King St W          | May-18 | AM Peak | WB        | Pedestrians | 2400              | 2600              | 200        |
| Bay St / Queen St W         | May-18 | PM Peak | WB        | Pedestrians | 3980              | 3680              | 300        |
| Bay St / Queen St W         | May-18 | PM Peak | EB        | Pedestrians | 4350              | 4060              | 290        |
| Bay St / Queen St W         | May-18 | PM Peak | WB        | Vehicles    | 1120              | 1080              | 40         |
| Bay St / Queen St W         | May-18 | PM Peak | EB        | Vehicles    | 1680              | 1650              | 30         |

For these entries, the difference is because the hard coded exceptions (https://bditto.slack.com/archives/C2KPPG3DW/p1537985580000100) were not implemented/partially implemented in `miovision_new.ksp_miovision_summary` or `open_data.ksp_miovision_summary`.

| Intersection                | Month  | Period  | Direction | Class       | Reporting Volumes | Open Data Volumes | Difference |
|-----------------------------|--------|---------|-----------|-------------|-------------------|-------------------|------------|
| Bay St / King St W          | Jun-18 | AM Peak | EB        | Pedestrians | 2790              | 2770              | 20         |
| Bay St / King St W          | Jun-18 | AM Peak | WB        | Pedestrians | 2900              | 2860              | 40         |
| Bay St / King St W          | Jun-18 | PM Peak | EB        | Pedestrians | 4080              | 3920              | 160        |
| Bay St / King St W          | Jun-18 | PM Peak | WB        | Pedestrians | 4100              | 3900              | 200        |

When re-checking the data from `miovision.report_summary` and `miovision_new.report_summary` those volumes matched the open data volumes, but not the reporting spreadsheet. Something probably happened to the tables since we reported the June volumes that caused the volumes to change.

**Comment by radumas** [comment]
Great work tracking down the different causes of these differences in data.

A thing to add to this check of that view:
-[ ] does the view still generate 14-hour and 24-hour volumes for the months where we only have peak periods?

**Comment by rickl4** [comment]
Yeah, the open data view still generates 14 and 24 hour counts for all months, even if we don't have data.

**Comment by aharpalaniTO** [comment]
Figured out the difference. No idea how this happened though.

```
SELECT	class_type,
	period_name,	
	dir,
	round(AVG(total_volume),-1) vol_5day,
	round(AVG(CASE WHEN dt = '2018-06-22' THEN NULL ELSE total_volume END),-1) vol_4day 
FROM 	miovision.report_daily 
WHERE 	intersection_uid = 17 AND
	period_type = 'Jun 2018' AND
	period_name LIKE ('%Peak Period%')
GROUP BY class_type, period_name, dir
```
|Class|Period|Direction|5-day Volume|4-day Volume|
|----|-----|-----|-----|----|
|Cyclists|AM Peak Period|EB|170|170|
|Cyclists|AM Peak Period|WB|140|140|
|Cyclists|PM Peak Period|EB|240|240|
|Cyclists|PM Peak Period|WB|140|130|
|Pedestrians|AM Peak Period|EB|2770|2790|
|Pedestrians|AM Peak Period|WB|2860|2900|
|Pedestrians|PM Peak Period|EB|3920|4080|
|Pedestrians|PM Peak Period|WB|3900|4100|
|Vehicles|AM Peak Period|EB|430|420|
|Vehicles|AM Peak Period|WB|230|230|
|Vehicles|PM Peak Period|EB|560|560|
|Vehicles|PM Peak Period|WB|440|440|

**Comment by rickl4** [comment]
Summary of the 29 discrepancies

| Number of Records | Explanation                                                                                                                                                                                                                                  | Months/Intersections Affected                          |
|-------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------|
| 6                 |  A correction was made in the July reporting spreadsheet, but wasn't corrected in the August reporting spreadsheet.                                                                                                                          | July Volumes at Bathurst/Adelaide and Spadina/Adelaide |
| 10                | Gaps in the data on May 28, May 29, May 31 meant that certain periods were not reported on the dashboard                                                                                                                                     | May Volumes at Bay/King and Bay/Queen                  |
| 6                 | New process now filters out invalid movements.                                                                                                                                                                                               | Bathurst/Richmond Volumes                              |
| 1                 | New process to interpolate and gap fill values                                                                                                                                                                                               | March Volumes at Spadina/Queen                         |
| 6                 | Original volumes for King/Bay and Wellington/Bay was not correct because a June 22 data for Wellington/Bay was misplaced as King/Bay. The Wellington/Bay volume was corrected while the King/Bay volume on the dashboard was left unchanged. | June Volumes at Bay/King                               |

**Comment by rickl4** [comment]
After adding the check for entries in `miovision.exceptions` and creating a new table rliu.ksp_miovision_summary_new` with the new check, there are now 9 entries with differences (not including the baseline), all of them relating to either invalid movements or the new interpolation/gap filling process.

**Comment by rickl4** [comment]
After un-rounding the values we're left 24 differences between the reporting spreadsheets and the open data view. 



| Intersection                | Month  | Period                       | Class    | Difference |
|-----------------------------|--------|------------------------------|----------|------------|
| Bathurst St / Adelaide St W | Jan-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Adelaide St W | May-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Adelaide St W | May-18 | PM Peak Period (16:00-19:00) | Vehicles | 4          |
| Bathurst St / Adelaide St W | Jun-18 | PM Peak Period (16:00-19:00) | Vehicles | 1          |
| Bathurst St / Adelaide St W | Jul-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Adelaide St W | Jul-18 | PM Peak Period (16:00-19:00) | Vehicles | 2          |
| Bathurst St / King St W     | Jan-18 | PM Peak Period (16:00-19:00) | Cyclists | 1          |
| Bathurst St / Richmond St W | Dec-17 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | Dec-17 | PM Peak Period (16:00-19:00) | Vehicles | 5          |
| Bathurst St / Richmond St W | Jan-18 | PM Peak Period (16:00-19:00) | Vehicles | 2          |
| Bathurst St / Richmond St W | Feb-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | Feb-18 | PM Peak Period (16:00-19:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | Mar-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | Mar-18 | PM Peak Period (16:00-19:00) | Vehicles | 2          |
| Bathurst St / Richmond St W | Apr-18 | AM Peak Period (07:00-10:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | Apr-18 | PM Peak Period (16:00-19:00) | Vehicles | 2          |
| Bathurst St / Richmond St W | May-18 | PM Peak Period (16:00-19:00) | Vehicles | 1          |
| Bathurst St / Richmond St W | May-18 | AM Peak Period (07:00-10:00) | Vehicles | 3          |
| Bathurst St / Richmond St W | Jun-18 | AM Peak Period (07:00-10:00) | Vehicles | 5          |
| Bathurst St / Richmond St W | Jun-18 | PM Peak Period (16:00-19:00) | Vehicles | 6          |
| Bathurst St / Richmond St W | Jul-18 | AM Peak Period (07:00-10:00) | Vehicles | 3          |
| Bathurst St / Richmond St W | Jul-18 | PM Peak Period (16:00-19:00) | Vehicles | 11         |
| Spadina Ave / Adelaide St W | Jul-18 | PM Peak Period (16:00-19:00) | Vehicles | 1          |
| Spadina Ave / Front St W    | Jul-18 | PM Peak Period (16:00-19:00) | Vehicles | 1          |

The final summary of discrepancies

Number of Records|Reason|Intersection/Months affected
|-----|-----|-----|
21|Old query did not filter out invalid movements on one way streets|Bathurst/Richmond and Bathurst Adelaide December to July
3|Likely due to new interpolation and gap filling method|Spadina Front, Spadina/Adelaide, and Bathurst/King

**Comment by radumas** [comment]
Great work Rick!
