### ISSUE TITLE
King Street Pilot - Bluetooth Travel Times Summary (Open Data)

### ISSUE THREAD

**Issue by rickl4** [CityofToronto/bdit_data-sources#164]

**Comment by rickl4** [comment]
The vast majority of the mismatches in the average monthly travel times were in February and March

| Month   | Number of Mismatches |
|---------|----------------------|
| Dec '17 | 2                    |
| Feb '18 | 33                   |
| Jan '18 | 3                    |
| Mar '18 | 20                   |
| Nov '17 | 2                    |

In the cases that weren't in February/March, it was Adelaide AM and PM during Nov, Dec, Jan and University NB AM in Jan. 

| Number of Mismatches | Street     |
|----------------------|------------|
| 3                    | Jarvis     |
| 7                    | Yonge      |
| 7                    | Front      |
| 10                   | Adelaide   |
| 4                    | Queen      |
| 3                    | Wellington |
| 6                    | Dundas     |
| 4                    | Spadina    |
| 8                    | Bathurst   |
| 8                    | University |

In addition, the baseline travel times also did not match for some streets. I noticed that the baselines times got changed around April.

| Month   | Street   | Direction  | Period                |
|---------|----------|------------|-----------------------|
| Dec '17 | Adelaide | Eastbound  | PM Peak (16:00-19:00) |
| Dec '17 | Adelaide | Eastbound  | AM Peak (07:00-10:00) |
| Feb '18 | Adelaide | Eastbound  | AM Peak (07:00-10:00) |
| Feb '18 | Adelaide | Eastbound  | PM Peak (16:00-19:00) |
| Feb '18 | Front    | Westbound  | PM Peak (16:00-19:00) |
| Feb '18 | Spadina  | Southbound | PM Peak (16:00-19:00) |
| Jan '18 | Adelaide | Eastbound  | PM Peak (16:00-19:00) |
| Jan '18 | Adelaide | Eastbound  | AM Peak (07:00-10:00) |
| Jan '18 | Front    | Westbound  | PM Peak (16:00-19:00) |
| Jan '18 | Spadina  | Southbound | PM Peak (16:00-19:00) |
| Mar '18 | Adelaide | Eastbound  | PM Peak (16:00-19:00) |
| Mar '18 | Adelaide | Eastbound  | AM Peak (07:00-10:00) |
| Mar '18 | Front    | Westbound  | PM Peak (16:00-19:00) |
| Mar '18 | Spadina  | Southbound | PM Peak (16:00-19:00) |
| Nov '17 | Adelaide | Eastbound  | PM Peak (16:00-19:00) |
| Nov '17 | Adelaide | Eastbound  | AM Peak (07:00-10:00) |

**Comment by rickl4** [comment]
For the differences between the baseline travel times, Front and Spadina are off by 0.1 and probably caused by rounding. 

For Adelaide, the entries in `open_data.ksp_agg_travel_time` have the `from_intersection` and `to_intersection` set to Spadina instead of Bathurst for those months, and 10.2 instead of 7.9 (AM) and 14.7 instead of 17.5 (PM) as the baseline travel times.

**Comment by rickl4** [comment]
Number of mismatches and the reasons for the mismatches

|Number of mismatches|Explanation|
|-----|-----|
53|Travel times issues in February and March 
7| Truncation/Rounding in python script to grab travel times making the times off by 0.1 minute
10| Reader down at Adelaide/Bathurst

**Comment by radumas** [comment]
Hurray for an exhaustive listing of the errors.

**Comment by radumas** [comment]
@aharpalaniTO this validation task can be closed?

**Comment by rickl4** [comment]
I made a view `rliu.ksp_agg_travel_time` that does not include the missing data for Adelaide during November and fixed the from intersection to read `Spadina`. I looked at other months as well, but the data we reported did not match travel times either with or without the missing segment (Bathurst - Spadina)

**Comment by rickl4** [comment]
More detail about Adelaide travel times, I compared the data in the reporting spreadsheet to both the travel times from Bathurst to Jarvis and Spadina to Jarvis. I created the view `rliu.ksp_agg_travel_time_adelaide` which is the same as the open data view, except without the segment from Bathurst to Spadina, and `open_dat.ksp_agg_travel_time` which has travel times from Bathurst to Jarvis, and compared it to `rliu.bluetooth_summary_view` which contains the reported travel times.
AM Peak Comparison

| Month   | Reporting | Bathurst to Jarvis | Spadina to Jarvis |
|---------|-----------|--------------------|-------------------|
| Nov '17 | 8         | 10.2               | 8                 |
| Dec '17 | 8.1       | 9.9                | 7.6               |
| Jan '18 | 8.1       | 10.4               | 5.6               |
| Feb '18 | 8.3       | 10.6               | 8.5               |
| Mar '18 | 7.4       | 9.4                | 7.4               |

PM Peak Comparison

| Month   | Reporting | Bathurst to Jarvis | Spadina to Jarvis |
|---------|-----------|--------------------|-------------------|
| Nov '17 | 16.7      | 19.4               | 16.7              |
| Dec '17 | 16.5      | 18.5               | 15.2              |
| Jan '18 | 15        | 17                 | 8.1               |
| Feb '18 | 15.2      | 17.6               | 15.7              |
| Mar '18 | 12.4      | 14.3               | 12.5              |

**Comment by rickl4** [comment]
To deal with missing bluetooth segments, I created an exceptions table similar to the miovision data. Specifically, there is already a corridor in `bt_corridors` for Adelaide that goes from Spadina to Jarvis. So if the date falls into the range specified by the exceptions table, it will instead choose the Spadina to Jarvis corridor instead of the Bathurst corridor.

```SQL
CREATE TABLE king_pilot.bt_corridors_exceptions
(
  corridor_id_old integer,
  corridor_id_new integer,
  excluded_datetime daterange
)
WITH (
  OIDS=FALSE
);
```

Currently, this is the only entry in the exceptions table.

| corridor_id_old | corridor_id_new | excluded_datetime        |
|-----------------|-----------------|--------------------------|
| 6               | 7               | [2017-11-01, 2017-12-01) |

Any other corridors that need to be added to the exceptions table will require adding a new entry in `bt_corridors` and associated table, in addition to the exceptions table

I re-created the view rliu.ksp_agg_travel_time that sets Adelaide to Spadina to Jarvis during November by checking the exceptions table. As soon as we know what to do with the other dates for Adelaide, I'll potentially add those too.

```SQL 
CREATE MATERIALIZED VIEW rliu.ksp_miovision_summary AS 
 WITH valid_bins AS (
         SELECT a_1.intersection_uid,
            a_1.class_type_id,
            a_1.dt + b_1.b AS datetime_bin,
            a_1.period_type
           FROM miovision_new.report_dates_view a_1
             CROSS JOIN ( SELECT generate_series('2017-01-01 00:00:00'::timestamp without time zone, '2017-01-01 23:45:00'::timestamp without time zone, '00:15:00'::interval)::time without time zone AS generate_series) b_1(b)
             LEFT JOIN miovision_new.exceptions c ON a_1.intersection_uid = c.intersection_uid AND a_1.class_type_id = c.class_type_id AND (a_1.dt + b_1.b) <@ c.excluded_datetime
          WHERE c.exceptions_uid IS NULL
        ), int_avg AS (
         SELECT volumes_15min_by_class.intersection_uid,
            volumes_15min_by_class.class_type_id,
            volumes_15min_by_class.dir,
            volumes_15min_by_class.leg,
            volumes_15min_by_class.period_type,
            volumes_15min_by_class.datetime_bin::time without time zone AS time_bin,
            avg(volumes_15min_by_class.total_volume) AS avg_volume
           FROM miovision_new.volumes_15min_by_class
          GROUP BY volumes_15min_by_class.intersection_uid, volumes_15min_by_class.class_type_id, volumes_15min_by_class.period_type, volumes_15min_by_class.dir, volumes_15min_by_class.leg, (volumes_15min_by_class.datetime_bin::time without time zone)
        ), volumes_15 AS (
         SELECT a.intersection_uid,
            a.period_type,
            a.datetime_bin,
            a.class_type_id,
            b.dir,
            b.leg,
            COALESCE(c.total_volume, b.avg_volume) AS volume
           FROM valid_bins a
             JOIN int_avg b USING (intersection_uid, class_type_id, period_type)
             LEFT JOIN miovision_new.volumes_15min_by_class c USING (datetime_bin, intersection_uid, class_type_id, dir, leg, period_type)
          WHERE b.time_bin = a.datetime_bin::time without time zone
        ), intersection_days AS (
         SELECT volumes_15.intersection_uid,
            volumes_15.datetime_bin::date AS dt,
            count(DISTINCT volumes_15.datetime_bin) AS num_daily_observations
           FROM volumes_15
          GROUP BY volumes_15.intersection_uid, (volumes_15.datetime_bin::date)
        ), daily AS (
         SELECT a.intersection_uid,
            c.intersection_name,
            c.street_main,
            c.street_cross,
            class_types.class_type,
            a.dir,
            a.period_type,
            a.datetime_bin::date AS dt,
            b.period_name ||
                CASE
                    WHEN b.period_id = 7 THEN ''::text
                    ELSE (((' ('::text || to_char(lower(b.period_range)::interval, 'HH24:MM'::text)) || '-'::text) || to_char(upper(b.period_range)::interval, 'HH24:MM'::text)) || ')'::text
                END AS period_name,
            sum(a.volume) AS total_volume
           FROM volumes_15 a
             CROSS JOIN miovision_new.periods b
             JOIN miovision_new.intersections c USING (intersection_uid)
             JOIN intersection_days d ON d.intersection_uid = a.intersection_uid AND a.datetime_bin::date = d.dt
             JOIN miovision_new.class_types USING (class_type_id)
          WHERE a.datetime_bin::time without time zone <@ b.period_range AND b.report_flag AND (a.dir = ANY (ARRAY['EB'::text, 'WB'::text])) AND
                CASE
                    WHEN b.period_id = 8 THEN d.num_daily_observations > (23 * 4)
                    WHEN b.period_id = 4 THEN d.num_daily_observations > (13 * 4)
                    ELSE true
                END AND (c.street_cross = ANY (ARRAY['Bathurst'::text, 'Spadina'::text, 'Bay'::text, 'Jarvis'::text])) AND (c.street_cross = 'Bathurst'::text AND (a.leg = ANY (ARRAY['E'::text, 'S'::text, 'N'::text])) OR c.street_cross = 'Jarvis'::text AND (a.leg = ANY (ARRAY['W'::text, 'S'::text, 'N'::text])) OR (c.street_cross <> ALL (ARRAY['Bathurst'::text, 'Jarvis'::text])) AND (a.dir = 'EB'::text AND (a.leg = ANY (ARRAY['W'::text, 'N'::text, 'S'::text])) OR a.dir = 'WB'::text AND (a.leg = ANY (ARRAY['E'::text, 'N'::text, 'S'::text])))) AND NOT ((class_types.class_type = ANY (ARRAY['Vehicles'::text, 'Cyclists'::text])) AND (a.dir = 'EB'::text AND (c.street_main = ANY (ARRAY['Wellington'::text, 'Richmond'::text])) OR a.dir = 'WB'::text AND c.street_main = 'Adelaide'::text))
          GROUP BY a.intersection_uid, c.intersection_name, c.street_main, c.street_cross, a.period_type, class_types.class_type, a.dir, (a.datetime_bin::date), b.period_name, b.period_range, b.period_id
        )
 SELECT daily.period_type AS aggregation_period,
    intersections.int_id,
    centreline_intersection.intersec5 AS intersection_name,
    intersections.px,
        CASE
            WHEN daily.class_type = 'Buses'::text THEN 'Buses and streetcars'::text
            ELSE daily.class_type
        END AS classification,
    daily.dir,
    daily.period_name,
    round(avg(daily.total_volume), '-1'::integer)::integer AS volume
   FROM daily
     JOIN miovision_new.intersections USING (intersection_uid)
     JOIN gis.centreline_intersection USING (int_id)
  GROUP BY daily.period_type, intersections.int_id, daily.class_type, centreline_intersection.intersec5, intersections.px, daily.dir, daily.period_name 
  WITH DATA;
```

**Comment by radumas** [comment]
My thoughts based on https://github.com/CityofToronto/bdit_data-sources/issues/164#issuecomment-426300942:

1. March and November seem fine. February is within half a minute slower, which is odd because Dec, and Jan are under.
2. Biggest difference is January, where it seems likely there are missing data for segments to have the avg travel time be so low. This could be a good place to start to figure out why December is off as well. Not sure why Feb is the way it is

**Comment by rickl4** [comment]
>AM Peak Comparison
>
>| Month   | Reporting Spreadsheet | Bathurst to Jarvis | Spadina to Jarvis |
>|---------|-----------|--------------------|-------------------|
>| Nov '17 | 8         | 10.2               | 8                 |
>| Dec '17 | 8.1       | 9.8                | 7.8               |
>| Jan '18 | 8.1       | 10.1               | 7.8              |
>| Feb '18 | 8.3       | 10.6               | 8.5               |
>| Mar '18 | 7.4       | 9.4                | 7.4               |
>
>PM Peak Comparison
>
>| Month   |Reporting Spreadsheet | Bathurst to Jarvis | Spadina to Jarvis |
>|---------|-----------|--------------------|-------------------|
>| Nov '17 | 16.7      | 19.4               | 16.7              |
>| Dec '17 | 16.5      | 18.5               | 16.1           |
>| Jan '18 | 15        | 17                 |14.6           |
>| Feb '18 | 15.2      | 17.6               | 15.7              |
>| Mar '18 | 12.4      | 14.3               | 12.5              |

I made a mistake in the query when grabbing the data from the open data view. I updated the comment to reflect the new times. 

The January outlier is completely eliminated, however the times are still up to half a minute off. My thinking is that the Bathurst to Spadina reader was down from Nov to March. At some point, we must have repulled the data to have data on that segment. For Feb the difference could easily be caused by the real time data problem for the other streets.

For Dec/Jan, these months have more low traffic days than others due to the holidays. We might have excluded more days than just the statutory holidays, which would explain the higher travel times. There doesn't seem to be a clear record if this is the case since there isn't evidence in the dashboard of reduced data collection dates (it says Dec 1-31, and Jan 1-31).

**Comment by radumas** [comment]
Great sleuthing Rick!
There doesn't appear to be any missing data in February.
```sql
SELECT datetime_bin::DATE dt, SUM( CASE analysis_id WHEN 1453959 THEN 1 ELSE 0 END) AS "Count: Bathurst-Spadina",
SUM( CASE analysis_id WHEN 1453973 THEN 1 ELSE 0 END) AS "Count: Spadina-University",
SUM( CASE analysis_id WHEN 1453998 THEN 1 ELSE 0 END) AS "Count: University-Yonge",
SUM( CASE analysis_id WHEN 1454031 THEN 1 ELSE 0 END) AS "Count: Yonge-Jarvis",
SUM( CASE analysis_id WHEN 1454050 THEN 1 ELSE 0 END) AS "Count: Jarvis-Parliament"
	FROM bluetooth.aggr_5min
	WHERE datetime_bin >= '2018-01-01'
	GROUP BY dt
	ORDER BY dt
```
Count: Bathurst-Spadina|Count: Spadina-University|Count: University-Yonge|Count: Yonge-Jarvis|Count: Jarvis-Parliament
|-------------------------|-----------------------------|----------------------------|----------------------|--------------------------|
'2018-02-01'|'212'|'208'|'248'|'253'|'248'
'2018-02-02'|'217'|'209'|'241'|'246'|'243'
'2018-02-03'|'199'|'213'|'251'|'239'|'228'
'2018-02-04'|'198'|'198'|'237'|'230'|'223'
'2018-02-05'|'193'|'195'|'227'|'224'|'220'
'2018-02-06'|'190'|'196'|'244'|'235'|'237'
'2018-02-07'|'190'|'204'|'254'|'246'|'244'
'2018-02-08'|'206'|'208'|'249'|'252'|'243'
'2018-02-09'|'212'|'210'|'245'|'242'|'240'
'2018-02-10'|'192'|'198'|'241'|'243'|'240'
'2018-02-11'|'184'|'172'|'220'|'215'|'203'
'2018-02-12'|'187'|'166'|'198'|'230'|'228'
'2018-02-13'|'194'|'157'|'185'|'220'|'230'
'2018-02-14'|'204'|'182'|'205'|'231'|'248'
'2018-02-15'|'205'|'197'|'246'|'243'|'243'
'2018-02-16'|'215'|'219'|'244'|'254'|'243'
'2018-02-17'|'204'|'213'|'249'|'242'|'234'
'2018-02-18'|'201'|'187'|'233'|'228'|'226'
'2018-02-19'|'176'|'177'|'221'|'217'|'202'
'2018-02-20'|'184'|'195'|'238'|'235'|'231'
'2018-02-21'|'191'|'210'|'245'|'244'|'240'
'2018-02-22'|'206'|'202'|'250'|'247'|'236'
'2018-02-23'|'214'|'223'|'256'|'246'|'240'
'2018-02-24'|'216'|'211'|'258'|'247'|'244'
'2018-02-25'|'188'|'191'|'238'|'235'|'232'
'2018-02-26'|'202'|'209'|'241'|'238'|'230'
'2018-02-27'|'201'|'202'|'242'|'248'|'239'
'2018-02-28'|'195'|'201'|'235'|'236'|'237'

**Comment by rickl4** [comment]
There was a problem in the original query I wrote where no Adelaide Data was showing up during the exception range. This problem is because of this statement `HAVING count(u.*) = z.segments` that checks to make sure all of the segments are present. However, Bathurst to Spadina _was not actually missing from Nov-Mar_ so there were more segments than required which caused the query to filter out those dates.

I made a simple change to the view by changing the clause to `HAVING count(u.*) >= z.segments` .

```SQL
CREATE MATERIALIZED VIEW ksp_agg_travel_time AS 
 WITH valid_corridors AS (
         SELECT x.dt,
            x.day_type,
            x.category,
            x.period_name,
            x.period_id,
            x.tt,
                CASE
                    WHEN t.excluded_datetime IS NULL THEN y.corridor_id
                    ELSE t.corridor_id_new
                END AS corridor_id
           FROM ( SELECT a.bt_id,
                    b.dt,
                    b.day_type,
                    b.category,
                    c.period_id,
                    c.period_name,
                    avg(a.tt) AS tt
                   FROM king_pilot.tt_30min a
                     JOIN king_pilot.date_lookup b USING (dt)
                     JOIN king_pilot.periods c USING (day_type)
                  WHERE a.time_bin <@ c.period_range
                  GROUP BY a.bt_id, b.dt, b.day_type, b.category, c.period_id, c.period_name
                  ORDER BY a.bt_id, b.dt, b.day_type, b.category, c.period_id) x
             JOIN king_pilot.bt_corridor_segments y USING (bt_id)
             LEFT JOIN king_pilot.bt_corridors_exceptions t ON t.corridor_id_old = y.corridor_id AND x.dt <@ t.excluded_datetime
          WHERE y.corridor_id <> ALL (ARRAY[7, 8, 9])
          ORDER BY x.period_id, x.day_type, x.dt
        ), pilot AS (
         SELECT z.street_name AS street,
            z.direction,
            z.from_intersection,
            z.to_intersection,
            z.corridor_id,
            u.dt,
            u.day_type,
            u.category,
            u.period_name AS period,
            sum(u.tt) / 60.0 AS tt
           FROM valid_corridors u
             JOIN king_pilot.bt_corridors z USING (corridor_id)
          GROUP BY z.corridor_id, z.street_name, z.direction, u.dt, u.day_type, u.category, u.period_name, u.period_id, z.segments, z.from_intersection, z.to_intersection
         HAVING count(u.*) >= z.segments
          ORDER BY z.corridor_id, z.direction, u.period_id, u.day_type, u.dt
        ), baseline AS (
         SELECT z.street_name AS street,
            z.direction,
            z.from_intersection,
            z.to_intersection,
            x.day_type,
            z.corridor_id,
            x.period_name AS period,
            ((('('::text || to_char(lower(x.period_range)::interval, 'HH24:MM'::text)) || '-'::text) || to_char(upper(x.period_range)::interval, 'HH24:MM'::text)) || ')'::text AS period_range,
            sum(x.tt) / 60.0 AS tt
           FROM ( SELECT a.bt_id,
                    a.day_type,
                    b.period_name,
                    b.period_range,
                    avg(a.tt) AS tt
                   FROM king_pilot.baselines a
                     JOIN king_pilot.periods b USING (day_type)
                     JOIN king_pilot.bt_segments c USING (bt_id)
                  WHERE a.time_bin <@ b.period_range
                  GROUP BY a.bt_id, a.day_type, b.period_name, b.period_range) x
             JOIN king_pilot.bt_corridor_segments y USING (bt_id)
             JOIN king_pilot.bt_corridors z USING (corridor_id)
          WHERE z.corridor_id <> ALL (ARRAY[8, 9])
          GROUP BY z.corridor_id, z.corridor_name, x.day_type, x.period_name, x.period_range, z.segments, z.street_name, z.direction, z.from_intersection, z.to_intersection
         HAVING count(x.*) = z.segments
          ORDER BY z.corridor_id, x.day_type, x.period_range
        )
 SELECT to_char(date_trunc('month'::text, pilot.dt::timestamp with time zone), 'Mon ''YY'::text) AS month,
    pilot.street,
    pilot.direction,
    baseline.from_intersection,
    baseline.to_intersection,
    pilot.day_type,
    (pilot.period || ' '::text) || baseline.period_range AS time_period,
    round(baseline.tt, 1) AS baseline_travel_time,
    round(avg(pilot.tt), 1) AS average_travel_time
   FROM pilot
     JOIN baseline USING (corridor_id, direction, day_type, period)
  WHERE pilot.category = 'Pilot'::text AND pilot.dt < date_trunc('month'::text, 'now'::text::date::timestamp with time zone)
  GROUP BY (to_char(date_trunc('month'::text, pilot.dt::timestamp with time zone), 'Mon ''YY'::text)), (date_trunc('month'::text, pilot.dt::timestamp with time zone)), pilot.street, baseline.from_intersection, baseline.to_intersection, pilot.direction, pilot.day_type, ((pilot.period || ' '::text) || baseline.period_range), baseline.tt
  ORDER BY (date_trunc('month'::text, pilot.dt::timestamp with time zone))
WITH DATA;
```

**Comment by radumas** [comment]
Hey! This is published! Yay!
