### ISSUE TITLE
Fill out TMC From-To Lookup table

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#17]
- [ ] automate following #16 by identifying nearest perpendicular TMC to start-end.
- [ ] validate manually

**Comment by radumas** [comment]
633 segments longer than 200m are missing from the lookup table.

**Comment by radumas** [comment]
Not relevant anymore

**Comment by jovenc** [comment]
Was referencing to issue #17 for CityofToronto/bdit_vz_programs
