### ISSUE TITLE
Investigate how the Watch Your Speed Sign API works

### ISSUE THREAD

**Issue by rickl4** [CityofToronto/bdit_data-sources#170]
Each watch your speed sign provides information about the speed and volume of vehicles. We are trying to find out the capabilities of the API and eventually build another data pipeline with information from the API.

**Comment by rickl4** [comment]
I've been getting an error whenever I tried requesting statistics. I'm using `/signs/statistics/location/1845/period/5/speed_units/0` as the url. This response has a `200` status code, but there are some errors.

 Upon further investigation, if I request `json` from the API, the output seems to be in HTML??? (I'm not completely sure) instead of `json` and creates a `JSONDecodeError`. The following is the exact unparsed output (formatted for readability)

```
b'<!DOCTYPE html>\n<html lang="en">
\n<head>
\n    <meta charset="utf-8">
\n    <title>ZF Skeleton Engine</title>
\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">
\n<meta http-equiv="X-UA-Compatible" content="IE=edge">
\n    <!-- Le styles -->
\n    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
\n<link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
\n<link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
\n<link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
\n    <!-- Scripts -->
\n    <script type="text/javascript" src="/js/jquery-3.1.0.min.js"></script>
\n<script type="text/javascript" src="/js/bootstrap.min.js"></script></head>
\n<body>
\n<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
\n    <div class="container">
\n        <div class="navbar-header">
\n            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
>\n                <span class="icon-bar"></span>
\n                <span class="icon-bar"></span>
\n                <span class="icon-bar"></span>
\n            </button>
\n            <a class="navbar-brand" href="/home">
\n                <img src="/img/zf-logo-mark.svg" height="28"
\n                     alt="Zend Framework 3.0.3-dev"/>&nbsp;Skeleton Application
\n            </a>\n        </div>\n        <div class="collapse navbar-collapse">
\n            <ul class="nav navbar-nav">\n                <li class="active"><a href="/home">Home</a></li>\n            </ul>\n        </div>\n    </div>\n</nav>\n<div class="container">
\n    <h1>An error occurred</h1>\n<h2>An error occurred during execution; please try again later.</h2>\n\n            <hr/>\n\n        <h2>Additional information:</h2>
\n        <h3>Doctrine\\ORM\\NonUniqueResultException</h3>\n        <dl>\n            <dt>File:</dt>
\n            <dd>\n                <pre>/var/wd3-rest/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:774</pre>\n            </dd>\n            <dt>Message:</dt>\n            <dd>
\n                <pre></pre>\n            </dd>\n            <dt>Stack trace:</dt>\n            <dd>
\n                <pre>#0 /var/wd3-rest/module/Signs/src/Repositories/RRecSchedule.php(49): Doctrine\\ORM\\AbstractQuery-&gt;getOneOrNullResult(2)\n#1 /var/wd3-rest/module/Signs/src/Controller/StatisticsController.php(173): Signs\\Repositories\\RRecSchedule-&gt;getRecScheduleByParam(828)
\n#2 /var/wd3-rest/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(379): Signs\\Controller\\StatisticsController-&gt;get(&#039;1845&#039;)
\n#3 /var/wd3-rest/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\Mvc\\Controller\\AbstractRestfulController-&gt;onDispatch(Object(Zend\\Mvc\\MvcEvent))
\n#4 /var/wd3-rest/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\\EventManager\\EventManager-&gt;triggerListeners(Object(Zend\\Mvc\\MvcEvent), Object(Closure))
\n#5 /var/wd3-rest/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\\EventManager\\EventManager-&gt;triggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))
\n#6 /var/wd3-rest/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(313): Zend\\Mvc\\Controller\\AbstractController-&gt;dispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response)
)\n#7 /var/wd3-rest/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\\Mvc\\Controller\\AbstractRestfulController-&gt;dispatch(Object(Zend\\Http\\PhpEnvironment\\Request), Object(Zend\\Http\\PhpEnvironment\\Response))
\n#8 /var/wd3-rest/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\\Mvc\\DispatchListener-&gt;onDispatch(Object(Zend\\Mvc\\MvcEvent))
\n#9 /var/wd3-rest/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\\EventManager\\EventManager-&gt;triggerListeners(Object(Zend\\Mvc\\MvcEvent), Object(Closure))
\n#10 /var/wd3-rest/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\\EventManager\\EventManager-&gt;triggerEventUntil(Object(Closure), Object(Zend\\Mvc\\MvcEvent))
\n#11 /var/wd3-rest/public/index.php(40): Zend\\Mvc\\Application-&gt;run()
\n#12 {main}</pre>\n            </dd>\n        </dl>\n\n                <hr>\n    <footer>
\n        <p>&copy; 2005 - 2018 by Zend Technologies Ltd. All rights reserved.</p>
\n    </footer>\n</div>\n</body>\n</html>\n'
```

The same output occurs when I tried requesting XML (I get a `ParseError: mismatched tag: line 15, column 69`). 

It seems like it is directly capturing the online javascript dashboard instead of the actual data. I don't see any data resembling the documentation in the output. Moreover, it actually says theres an error in one of the lines of the html output. For reference, an example output is something like this:

```json
{
"LocInfo": {
"Location": {
"name": "SC NB Second Road West",
"address": "42 Second Road West ",
"state": "Ontario",
"country": "Canada",
"zip": "L8J3Z6",
"geocode": "(43.180489890169355,-79.79455947875944)"
},
"Statistics": {
"max_speed": 35,
"min_speed": 5,
"avg_speed": 25,
"avg_speed85": 30,
"speed_limit": 25,
"count": 111
},
"Parametrs": {
"minutes": 30,
"speed_type": "mph"
},
"raw_records": {
"record": [
{
"-datetime": "2017-06-14 13:10:00",
"counter": [
{
"speed": 17,
"count": 1
},
{
"error_code": 204,
"error_message": "Error: The location ID is not
provided"
}
{
"error_code": 404,
"error_message": "Error: The location ID not valid."
}
{
"error_code": 404,
"error_message": "Error: Incorrect minutes value
provided. Minimum value is 5 minutes"
}
{
"error_code": 404,
"error_message": "Error: Incorrect unit provided.
Need to be 0 or 1"
}
{
"error_code": 404,
"error_message": "Error: The location ID not found"
}
{
"speed": 24,
"count": 1
},
{
"speed": 24,
"count": 1
},
{
"speed": 27,
"count": 3
},
{
"speed": 32,
"count": 2
},
{
"speed": 35,
"count": 2
}
]
},
{
"-datetime": "2017-06-14 13:15:00",
"counter": [
{
"-speed": "22",
"#text": "2"
},
{
"-speed": "23",
"#text": "1"
},
{
"-speed": "25",
"#text": "2"
},
{
"-speed": "25",
"#text": "3"
},
{
"-speed": "27",
"#text": "1"
},
{
"-speed": "28",
"#text": "2"
},
{
"-speed": "29",
"#text": "1"
},
{
"-speed": "30",
"#text": "1"
}
]
},
{
"-datetime": "2017-06-14 13:30:00",
"counter": [
{
"-speed": "18",
"#text": "1"
},
{
"-speed": "24",
"#text": "1"
},
{
"-speed": "24",
"#text": "2"
},
{
"-speed": "27",
"#text": "2"
},
{
"-speed": "28",
"#text": "1"
},
{
"-speed": "31",
"#text": "1"
},
{
"-speed": "34",
"#text": "1"
},
{
"-speed": "35",
"#text": "1"
}
]
}
],
"#text": "
...
"
}
}
}
```

**Comment by rickl4** [comment]
An email from the vendor suggested we did not request a location that was operational. I requested all locations and then fed them all to the API to see which ones had data (theres no other way to check). So while there are 331 watch your speed signs, only 34 of them are giving data.



| Location Id | Address                        |
|-------------|--------------------------------|
| 1745        | 433 Eastern Avenue             |
| 5350        | 484 Bedford Park Avenue        |
| 1967        | 1577 Bloor Street West         |
| 2203        | 1480 Bloor Street West         |
| 7639        | 218 Brock Avenue               |
| 7638        | 7 Bunty Lane                   |
| 7562        | 45 Palomino Crescent           |
| 7648        | 196 Burrows Hall Boulevard     |
| 7635        | 138 Canongate Trail            |
| 7636        | 121 Canongate Trail            |
| 7649        | 91 Springbrook Drive           |
| 1968        | 2269 Dundas Street West        |
| 1844        | 2447 Dundas Street West        |
| 7637        | 25 Gade Drive                  |
| 7651        | 65 McKee Avenue                |
| 7650        | 105 McKee Avenue               |
| 7634        | 2789 Victoria Park Avenue      |
| 7633        | Renforth Drive                 |
| 7654        | 27 Roanoke Road                |
| 7653        | 58 West Beaver Creek Road      |
| 7652        | 762 Scarborough Golf Club Road |
| 2456        | 255 Spadina Avenue             |
| 2455        | 370 Spadina Avenue             |
| 7557        | 175 Mount Olive Drive          |
| 7606        | 145 Brock Avenue               |
| 7607        | 103 Gilmour Avenue             |
| 7608        | 574 Roehampton Avenue          |
| 7558        | 197 Connaught Avenue           |
| 7609        | 127 Pineway Boulevard          |
| 7559        | 36 Haslemere Road              |
| 7614        | 804 Logan Avenue               |
| 7560        | 100 Corporate Drive            |
| 7561        | 86 Brimwood Boulevard          |

Also, it would appear that you can only request the last x minutes of data and theres no way to pull data from a specific datetime. The data is aggregated into roughly 5 minute bins, and returns the count of cars at a particular speed (rounded to 1km/h) in those minutes. I say roughly because not all readers report the same bin size at the same time. Some readers may report at 4:01, 4:04, 4:12, while another reports strictly at 4:00, 4:05, 4:10, while another reports at 4:02, 4:05, 4:11, 4:16.

**Comment by rickl4** [comment]
Its not clear the maximum amount of data I can request. I've successfully requested 10,080 minutes (7 days) of data, but I've frequently run into `504` errors whenever I try requesting large amounts of data. I don't know what the threshold/limit of the amount of data I can request.

**Comment by rickl4** [comment]
Mateen pointed out that the mobile WYS signs don't have their addresses updated regularly. This task is also in the parking lot, so one thing we should investigate is whether lat/long corresponds to the address. If not, then we can use lat/long to update the address automatically.

**Comment by rickl4** [comment]
I've parsed the data into this which I think might be most logically way to do it:

| location_id | datetime_bin        | speed | count |
|-------------|---------------------|-------|-------|
| 7562        | 10-18-2018 15:04:00 | 29    | 1     |
| 7562        | 10-18-2018 15:04:00 | 27    | 1     |
| 7562        | 10-18-2018 15:04:00 | 26    | 2     |
| 7562        | 10-18-2018 15:04:00 | 18    | 1     |
| 7562        | 10-18-2018 15:04:00 | 17    | 1     |
| 7562        | 10-18-2018 15:04:00 | 11    | 1     |
| 7562        | 10-18-2018 15:04:00 | 5     | 3     |
| 7562        | 10-18-2018 15:11:00 | 33    | 1     |
| 7562        | 10-18-2018 15:11:00 | 30    | 1     |
| 7562        | 10-18-2018 15:11:00 | 29    | 1     |
| 7562        | 10-18-2018 15:11:00 | 17    | 2     |
| 7562        | 10-18-2018 15:11:00 | 16    | 1     |
| 7562        | 10-18-2018 15:11:00 | 12    | 1     |
| 7562        | 10-18-2018 15:11:00 | 8     | 2     |
| 7562        | 10-18-2018 15:11:00 | 5     | 3     |
| 7562        | 10-18-2018 15:17:00 | 19    | 1     |
| 7562        | 10-18-2018 15:17:00 | 18    | 1     |
| 7562        | 10-18-2018 15:17:00 | 17    | 1     |
| 7562        | 10-18-2018 15:17:00 | 16    | 1     |
| 7562        | 10-18-2018 15:17:00 | 15    | 1     |
| 7562        | 10-18-2018 15:17:00 | 13    | 1     |
| 7562        | 10-18-2018 15:17:00 | 9     | 2     |
| 7562        | 10-18-2018 15:17:00 | 6     | 1     |
| 7562        | 10-18-2018 15:17:00 | 5     | 3     |
| 7562        | 10-18-2018 15:19:00 | 16    | 1     |
| 7562        | 10-18-2018 15:19:00 | 15    | 1     |
| 7562        | 10-18-2018 15:19:00 | 5     | 2     |
| 7562        | 10-18-2018 15:26:00 | 35    | 1     |
| 7562        | 10-18-2018 15:26:00 | 34    | 1     |
| 7562        | 10-18-2018 15:26:00 | 28    | 1     |
| 7562        | 10-18-2018 15:26:00 | 26    | 2     |
| 7562        | 10-18-2018 15:26:00 | 25    | 1     |
| 7562        | 10-18-2018 15:26:00 | 24    | 1     |
| 7562        | 10-18-2018 15:26:00 | 16    | 1     |
| 7562        | 10-18-2018 15:26:00 | 14    | 1     |
| 7562        | 10-18-2018 15:26:00 | 13    | 2     |
| 7562        | 10-18-2018 15:26:00 | 10    | 1     |
| 7562        | 10-18-2018 15:26:00 | 8     | 1     |
| 7562        | 10-18-2018 15:26:00 | 6     | 1     |
| 7562        | 10-18-2018 15:26:00 | 5     | 2     |
| 7562        | 10-18-2018 15:29:00 | 6     | 1     |
| 7562        | 10-18-2018 15:29:00 | 5     | 1     |
| 7562        | 10-18-2018 15:35:00 | 70    | 1     |
| 7562        | 10-18-2018 15:35:00 | 29    | 2     |
| 7562        | 10-18-2018 15:35:00 | 23    | 1     |
| 7562        | 10-18-2018 15:35:00 | 19    | 1     |
| 7562        | 10-18-2018 15:35:00 | 14    | 1     |
| 7562        | 10-18-2018 15:35:00 | 11    | 1     |
| 7562        | 10-18-2018 15:35:00 | 8     | 1     |
| 7562        | 10-18-2018 15:35:00 | 5     | 4     |
| 7562        | 10-18-2018 15:39:00 | 32    | 1     |
| 7562        | 10-18-2018 15:39:00 | 31    | 1     |

**Comment by rickl4** [comment]
I requested the locations of the signs again today, and 13 additional signs have started reporting.

Mobile WYS

| location_id | output                     |
|-------------|----------------------------|
| 7603        | 54 Haliburton Avenue       |
| 7604        | 109 Winston Park Boulevard |
| 7605        | 98 Goswell Road            |
| 7611        | 211 Bessborough Drive      |
| 7612        | 23 Indigo Street           |
| 7615        | 32 Falmouth Avenue         |
| 7616        | 243 Birkdale Road          |
| 7617        | 93 Wishing Well Drive      |
| 7618        | 177 Galloway Road          |

Permanent 

| location_id | output               |
|-------------|----------------------|
| 7657        | 1376 Bathurst Street |
| 7658        | 730 Renforth Drive   |
| 7658        | 730 Renforth Drive   |
| 7660        | 55 Lafferty Street   |
| 7662        | 95 Richland Crescent |

I think the best way at the moment to request data is to request ~1700 minutes each night at 1AM.

**Comment by rickl4** [comment]
The most recent update to the API now inserts data to the database. I'm also planning to grab the most recent 1443 minutes every day at 1:01AM. The script does not have proper error handling or email notifications, but I figured we have to grab the data if theres no way to request a specific datetime. The script rounds each datetime to the nearest 5 minutes.

The [`populate-table-counts-15min.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/populate-table-counts-15min.sql) query is a rudimentary attempt to aggregate the data to 15 minute bins. It first aggregates the data to 5km/h bins and then to 15 minute bins.

**Comment by rickl4** [comment]
[`populate-table-volumes-15min.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/populate-table-volumes-15min.sql) is a query that only shows the volumes passing by the sign in a 15 minute bin. It also creates 0-volume bins if the sign does not record any volume.

**Comment by rickl4** [comment]
4 more WYS have started reporting data today.

| Location ID | Name             | Address               |
|-------------|------------------|-----------------------|
| 7613        | Ward 29 - Sign 2 | 0                     |
| 7700        | ward 34 - Sign 2 | 69 Sloane Avenue      |
| 7701        | Ward 20 - Sign 2 | 734 Palmerston Avenue |
| 7702        | Ward 18 - Sign 2 | 80 Armstrong Avenue   |
| 7704        | Ward 14 - Sign 2 | 21 Annette Street     |

As well, I've added directions, where available, to the `location` table. However, all of the mobile WYS don't have locations. This is because I'm grabbing the locations from the sign name, and while for the permanent ones it contains the location, direction and serial number (like `Spadina Ave NB   17021348`), the mobile ones are just named by the ward (like `Ward 23 - Sign 2`).

**Comment by rickl4** [comment]
Wrote up this script to get the list of all signs reporting data.

```python
import json
from requests import Session
import configparser
import pprint



def get_signs():
    headers={'Content-Type':'application/json','x-api-key':api_key}
    #params = {'endTime': end_iteration_time, 'startTime' : start_time}
    response=session.get(url+signs_endpoint,
                         headers=headers, proxies=session.proxies)
    if response.status_code==200:
        signs=json.loads(response.content)
        return signs


def get_statistics(location):
    headers={'Content-Type':'application/json','x-api-key':api_key}
    response=session.get(url+statistics_endpoint+str(location)+end, 
                         headers=headers, proxies=session.proxies)
    if response.status_code==200:
        statistics=str(response.content)
        return statistics
    else:
        return response.status_code



session = Session()
session.proxies = {'https': 'https://137.15.73.132:8080'}
url='https://api.streetsoncloud.com/sv2'
signs_endpoint = '/signs'
statistics_endpoint='/signs/statistics/location/'
end='/period/5/speed_units/0'
CONFIG = configparser.ConfigParser()
CONFIG.read('config.cfg')
key=CONFIG['API']
api_key=key['key']
signs=get_signs()
table=[]
for item in signs:
    location=item['location_id']
    statistics=str(get_statistics(location))
    if statistics[4:11] == 'LocInfo':
        temp=[location]
        table.append(temp)
pp = pprint.PrettyPrinter(indent=4)
pp.pprint(table)
```

I'll work on trying to extract the direction, name and address and list the direction in the data. `wys.locations` would probably have to include all 331 signs so that is a new sign starts reporting data, we can easily grab the direction for the `raw_data` table. 

Still don't know how we can deal with mobile WYS signs changing locations. There is a way on streetsoncloud to find the actual sign coordinates, but we can't request that through the API.

**Comment by rickl4** [comment]
WRT to the parking lot item Automated Location Change, there's no call to do it for the API. Doing it on streetsoncloud is relatively simple but also tedious.

**Comment by rickl4** [comment]
In the near future, the vendor will introduce a yellow status flag to the map view on streetsoncloud portal which will indicate if the Mobile WYS Sign is in the wrong location. It still is up to the user to click the button to shift the location and the user may even have to enter the new address/name. This is not much of an improvement over the current state of things.

**Comment by radumas** [comment]
Can you add some comments to [the speed counts function](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/sql/function-aggregate_speed_counts_15min.sql)? 
Took me a moment to figure out what's going on.
