### ISSUE TITLE
Automate Bluetooth OpenData Extraction

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#180]
- [x] Determine schedule with Henry for updating travel time data. Determine process for updating shapefile extract for segments.
- [x] Update OpenData views to reference appropriate segments tables.
- [ ] Confirm extraction schedule by the OpenData team

**Comment by radumas** [comment]
Update OpenData views to reference appropriate segments tables.

**Comment by radumas** [comment]
Update TODO to include confirm extraction automation.

**Comment by gabrielwol** [comment]
Significant changes to Bluetooth network, requires a rethink.
