### ISSUE TITLE
Re-draw Bluetooth Highway Segments

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#183]
We're not entirely sure how these segments were drawn, but they didn't come from the centreline layer. Create a table like `{analysis_id, centreline_id}` for the DVP, Gardiner, and Lakeshore Bluetooth routes and then we'll merge those lines together and replace the geometries in `bluetooth.segments`

**Comment by radumas** [comment]
`natalie.bt_highway_ref` is the reference table with `{analysis_id, geo_id, bt_direction, centreline_geom}`

`natalie.bt_highway_geom` contains merged lines

**Comment by radumas** [comment]
So what is outstanding is to split the centrelines where there are detectors on the highways so that the merged `bluetooth.segments` will be from detector to detector.

detectors can be found at `cnangini.detectors`

**Comment by chmnata** [comment]
I need some clarifications on which detector to use:
1) DVP (analysis_id: 116812)
![image](https://user-images.githubusercontent.com/46324452/60194639-bb88ab80-9807-11e9-8991-13cb32cff623.png)
This bluetooth segment from `bluetooth.segments` spans through detector 1, 2 ,and 3. Should I still cut that segment into two with detector 2?
This one too
![image](https://user-images.githubusercontent.com/46324452/60197245-0e189680-980d-11e9-8217-0776f82088a5.png)
and this one
![image](https://user-images.githubusercontent.com/46324452/60197315-24beed80-980d-11e9-8332-d2c8111119dc.png)


2) Gardiner (analysis_id: 378651)

![image](https://user-images.githubusercontent.com/46324452/60195629-664d9980-9809-11e9-845a-8db532a26bff.png)

Confusing detector placement when comparing with `bluetooth.segments`. Should segment 1 end at detector B ?

3) Gardiner (analysis_id : 1388022)

![image](https://user-images.githubusercontent.com/46324452/60196017-3ce13d80-980a-11e9-977c-e790d4978531.png)
There aren't any detectors near the start point/end point of this segment.

**Comment by aharpalaniTO** [comment]
| Analysis ID | Segment | Action |
| ------------ | --------- | -------- |
| 116812 | DVP - Don Mills to Wynford | Keep as single segment from detector at Don Mills to detector at Wynford |
| 116828 | DVP - Lawrence to York Mills | Keep as single segment from detector at Lawrence to detector at York Mills |
| 116804 | DVP - Bayview to Don Mills | Keep as single segment from detector at Bayview to detector at Don Mills |
| 378651 | Gardiner - Grand to Roncesvalles | This looks fine - the reader in `detectors` appears to have the wrong latitude/longitude. There is a reader at Gardiner / Roncesvalles. |
| 1388022 | Gardiner - Roncesvalles to Dufferin | The start point actually has a detector but isn't reflected in the `detectors` table. The end point likely needs to be moved to terminate at where the Dufferin detector is actually located. This may also affect the start point of the segment for `analysis_id = "analysis_id"
130557` |

@KatiRG can you fix the latitude for the reader at Roncesvalles and Gardiner? I believe the latitude is erroneously negative.

**Comment by KatiRG** [comment]
@aharpalaniTO  Roncesvalles and Gardiner latitude fixed

**Comment by chmnata** [comment]
Found another weird bluetooth segments (analysis_id = analysis_id = 1391870) that was not getting matched with sharedstreets. Will fix with the self intersecting trick. 
![image](https://user-images.githubusercontent.com/46324452/60902103-17f2be80-a23d-11e9-89f7-9285e4ddaf8d.png)

**Comment by chmnata** [comment]
> Found another weird bluetooth segments (analysis_id = analysis_id = 1391870) that was not getting matched with sharedstreets. Will fix with the self intersecting trick.
> ![image](https://user-images.githubusercontent.com/46324452/60902103-17f2be80-a23d-11e9-89f7-9285e4ddaf8d.png)

Apparently this was the one I fixed before, but I didn't made change the geom in `natalie.bluetooth_fixthat2` :P.  The change has now been made, @aharpalaniTO can you update `bluetooth.segment` with `natalie.bluetooth_fixthat2` (analysis_id =1391870) ?
