### ISSUE TITLE
Fix Segments Geocoding

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#193]
Some of the segments are drawn weird.

Fix that.

**Comment by chmnata** [comment]
new table with fixed geometry in `natalie.bluetooth_fixthat`
changes made:
- add missing adelaide geom
- st_dump unnecessary continuous streets and fix those geometries
- st_reverse weird segment for linestrings
- st_dump, reverse, then union weird multi-linestrings

**Comment by chmnata** [comment]
newest table with merged fork york segments in `natalie.bluetooth_fixthat2`

**Comment by radumas** [comment]
Confirmed that `natalie.bluetooth_fixthat2` is the exact same as `bluetooth.segments`
