### ISSUE TITLE
Create new cycling tables to house one-hour permanent data

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#197]
This is a temporary fix until we resolve putting this into FLOW. Create two tables:

`cycling.count_perm_station`
**station_id** - unique identifier for station
**centreline_id**
**dir_id** - +1 for NB or EB, -1 for SB or WB
**dir** - NB, EB, WB, or SB
**location** - textual description of location

`cycling.count_perm_data`
**station_id**
**datetime_start** - timestamp indicating start of count bin
**datetime_end** - timestamp indicating end of count bin
**volume**

You can mimic the existing `count_data` and `count_info` tables.

**Comment by chmnata** [comment]
Created `cycling.count_perm_data` and `cycling.count_perm_station`. Also added hourly 2014 data for Sherbourne & Wellesley.
