### ISSUE TITLE
Automate update of Big Data RDS from Red Light Camera backend

### ISSUE THREAD

**Issue by KatiRG** [CityofToronto/bdit_data-sources#223]
Query to replicate the relevant signal asset info from Red Light Camera database into our database. Should be stored in a permanent schema (via some Airflow process).

**Comment by KatiRG** [comment]
@aharpalaniTO Do you have the query used to make the RLC table?

**Comment by KatiRG** [comment]
@aharpalaniTO I have this process working and dumping to test table `vz_safety_programs_staging.rlc_test`. Can you check this table and let me know when I can write to the real `rlc` table?

**Comment by aharpalaniTO** [comment]
The result sets are identical. Query below returns 0 rows.

```
(TABLE vz_safety_programs_staging.rlc_test EXCEPT TABLE vz_safety_programs_staging.rlc)
UNION ALL
(TABLE vz_safety_programs_staging.rlc_test EXCEPT TABLE vz_safety_programs_staging.rlc)
```

Is the code for the process ingesting data from the RLC feed to the RDS on Github?

**Comment by KatiRG** [comment]
branch `airflow`, `dag` directory that calls tasks in `assets` directory
