### ISSUE TITLE
Build script to pull safety zone data from Google Sheets into RDS

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#224]
Objective
Write and automate a script to ingest data from a Google Sheet maintained by the Vision Zero team using the Google Sheet API

Tasks

- [x] Test pulling data from Google Sheets API using fake data
- [x] Pull data from Safety Zone worksheet provided by Vision Zero team (sent via email)
- [x] Transfer data to Big Data RDS
- [x] Build automated job to pull and transfer this data daily (using Airflow? Or some other method)

**Comment by radumas** [comment]
@jovenc can you make sure when writing up documentation to include a section in the main README of this repository to link to the `vision_zero` folder?

**Comment by jovenc** [comment]
Added a README.md file in the vision_zero folder and updated the main README.md to include `Vision Zero - Google Sheets API` section. Everything is done on branch `vz_api`.
