### ISSUE TITLE
Miovision API Puller bug fix

### ISSUE THREAD

**Issue by jovenc** [CityofToronto/bdit_data-sources#233]
In `miovision_api_bugfix` branch, the script fixed can be found at `volumes/miovision/api/intersection_tmc.py`

## Issues solved/changes made so far:

- #220 resolved, no more duplicated 15min data
- Changed start_date to start_time where necessary to avoid confusion
- Edited `pull_date` function to pull the desired intersection and for clarity
- Edited `process_data` function
- Separated `refresh_views` into a new function
- Created/moved around the `try...except:` block for better clarity
- Parameterized query

## Remaining issues:

- [x] #222 still exists but the error only pops out a step before the script is done aka after all the pulling, inserting and processing data is done. Not sure what is wrong. The script works fine before today.

```
(api) jchew@ip-10-160-2-198:~/miovision_api/volumes/miovision/api$ pipenv run python intersection_tmc.py run-api --intersection 5
04 Nov 2019 11:02:45            DEBUG    Start
04 Nov 2019 11:02:45            DEBUG    Connected to DB
04 Nov 2019 11:02:45            INFO    Pulling from 2019-11-03 00:00:00-04:00 to 2019-11-04 00:00:00-05:00
04 Nov 2019 11:02:45            DEBUG    [(5, 'f4cfdbdc-afea-4a8a-adc4-bb64a3e8e4af', 'Front / Bathurst', Decimal('43.640752'), Decimal('-79.401359'), 'Front', 'Bathurst', 13468126, 297, '0101000020E610000023BDA8DDAFD953C05D6C5A2904D24540', None, None, None, True)]
04 Nov 2019 11:02:45            INFO    Front / Bathurst     2019-11-03 00:00:00-04:00
04 Nov 2019 11:02:51            INFO    Completed data pulling for 2019-11-03 00:00:00-04:00
04 Nov 2019 11:03:03            INFO    Inserted into volumes and updated log
04 Nov 2019 11:03:13            INFO    NOTICE:  Invalid movements more than 1000, QC check raw data

04 Nov 2019 11:03:34            INFO    Aggregated to 15 minute bins
04 Nov 2019 11:03:34            INFO    Completed data processing for 2019-11-03 00:00:00-04:00
04 Nov 2019 11:04:05            INFO    missing_dates_query done
04 Nov 2019 11:04:05            INFO    report_dates done
04 Nov 2019 11:04:05            INFO    Front / Bathurst     2019-11-04 00:00:00-04:00
04 Nov 2019 11:04:05            CRITICAL    Traceback (most recent call last):
  File "intersection_tmc.py", line 95, in run_api
    pull_data(conn, start_time, end_time, intersection, path, pull, key)
  File "intersection_tmc.py", line 314, in pull_data
    table=get_intersection_tmc(table, start_time, end_iteration_time, intersection_id1, intersection_uid, key)
  File "intersection_tmc.py", line 174, in get_intersection_tmc
    error=json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

- [x] Find out why `NOTICE:  Invalid movements more than 1000, QC check raw data` happens
- [x] miovision_api.volumes table consists of duplicated data as a unique id for each row is formed every time the script is run. Suggest to delete all volumes after 2019-09-01 and re-run script once the script is fixed. Or apply unique constraint?
- [x] Figure out what the deal with refreshing materialized views is. That line of script does not complete even after running continuously for 30min and the process freezes my pgAdmin GUI too

**Comment by jovenc** [comment]
![image](https://user-images.githubusercontent.com/54872846/68869697-979b0900-06c7-11ea-818f-fe5207fa83f2.png)

Tried again today and there is no longer the `TypeError: the JSON object must be str, not 'bytes'` issue. I also noticed that the `Invalid movements more than 1000, QC check raw data` issue happens on most intersections but not all of them.

However, I noticed that there is this `TypeError: not all arguments converted during string formatting` when I'm trying to run the script specifically on intersection with double digits as shown below.
![image](https://user-images.githubusercontent.com/54872846/68872301-cf0bb480-06cb-11ea-90bf-90bbfa276b18.png)

**Comment by radumas** [comment]
> I also noticed that the Invalid movements more than 1000, QC check raw data issue happens on most intersections but not all of them. JSON error not found as sound below.

I'm beginning to wonder if there may be an error in how invalid movements are either hard-coded, or only a sample of them were encoded/used. I will investigate further right meow.

>However, I noticed that there is this TypeError: not all arguments converted during string formatting when I'm trying to run the script specifically on intersection with double digits as shown below. Intersection 1 to intersection 9 work well but not intersection 10 and after.

A few things here:
1. parameters to `cur.execute(sql, (arg1,))` should be passed as a tuple or an array
2. strings are arrays in Python, so it's treating 2 character strings as two independent parameters and then getting confused by receiving more variables than there are `%s` placeholders in the query
3. `intersection_id` doesn't actually need to be converted to a string here. The actual column in the database is an `int`, so it can be treated as such.

**Comment by jovenc** [comment]
MAJOR discovery: Running the following query
```
SELECT a.intersection_uid, a.leg, a.classification_uid, a.movement_uid, sum(volume) AS sum FROM miovision_api.volumes a 
LEFT JOIN miovision_api.intersection_movements b 
USING (intersection_uid,leg, classification_uid, movement_uid)
WHERE datetime_bin BETWEEN '2019-10-14 00:00:00' AND '2019-10-15 00:00:00'
AND b.intersection_uid IS NULL
GROUP BY a.intersection_uid, a.leg, a.classification_uid, a.movement_uid
```

to find out what are the invalid movements in a day, I found that more than 99% of the results are where the classification_uid = 8 (which is work van based on [this](https://github.com/CityofToronto/bdit_data-sources/tree/miovision_api_bugfix/volumes/miovision/api#classifications) ).

A little check on `miovision_api.intersection_movements` and voila! There are valid intersection movements for classification_uid 1 to 7 whereas in the volumes table, items are classified from classification_uid of 1 to 6 and 8. There is nth for classification_uid = 8 in `miovision_api.intersection_movements` whereas there is nth for classification_uid = 7 in `miovision_api.volumes`.

I can try fixing it by changing the classification_uid of 8 to 7 in the `intersection_tmc.py` script but I am not too sure if this might affect some other things.

**Comment by radumas** [comment]
Good catch! This came about because the `miovision_api.intersection_movements` table is an exact duplicated of `miovision_new.intersection_movements` despite `miovision_new` and `miovision_api` having different classifications. The csv dump data had "Bicycle" (in crosswalk) as classification 7, which is not present in the API data, which has "WorkVan" as classification 8.

The solution was to assume "WorkVan"s behave the same as "Light" vehicles and duplicate those valid `intersection_movements`

```sql
INSERT INTO miovision_api.intersection_movements(intersection_uid, classification_uid, leg, movement_uid)
SELECT intersection_uid, 8, leg, movement_uid
  FROM miovision_api.intersection_movements
  WHERE classification_uid =1
```

**Comment by jovenc** [comment]
Another issues to look into:

- [ ] For `miovision_api.volumes_15min` &  `miovision_api.volumes_15min_tmc` start_time of the day is 00:00:00 whereas end_time of the day is 23:00:00 instead of 23:45:00. Should be processing from 23:00 previous day to 23:00 current day for quality assurance. There was a bug where 23:00 was getting processed twice.

- [ ]  There are more volume and row count for ATR `miovision_api.volumes_15min` compared to TMC `miovision_api.volumes_15min_tmc` which does not make sense. There should be less ATR counts compared to TMC.

**Comment by radumas** [comment]
>-`Classification_uid` here needs to be changed to 1,2,6,8 too given that that was fixed for another table.

So the reason those are there were because those were the classifications that we wanted to have 0 volumes in their 15-min bins if we were averaging volumes and those were the 3 (4) categories we were most interested in that weren't sparse. If the volume of WorkVans is more like Light Vehicle it should be included, but if it's more like the Truck categories we shouldn't include. 

- [ ] Can you run a quick check on `sum(volume)` for the categories?

**Comment by jovenc** [comment]
For 2 days worth of data in `miovision_api.volumes`, this is what I found:

|classification_uid|classification|count(volume_uid)|sum(volume)|
|------------------|--------------|-----|------|
|1|Light|361695|1299064|
|2|Bicycle|15427|16720|
|3|Bus|53844|64136|
|4|SingleUnitTruck|29876|33610|
|5|ArticulatedTruck|1330|1388|
|6|Pedestrian|297160|1133729|
|8|WorkVan|25608|28520|

 (total count = 784,940 rows & total volume = 2,577,167)

**Comment by radumas** [comment]
Thanks! I think we should not fill in 0s for `WorkVan`s then.

**Comment by jovenc** [comment]
Referring to this https://github.com/CityofToronto/bdit_data-sources/issues/233#issuecomment-555115410,
The following table shows the difference of TMC and ATR table for 3 days worth of data resepectively
**TMC Table**

|classification_uid|total_count|sum_volume|
|------------------|-----------|----------|
1	|"69432"|	"1992698"
2	|"15046"|	"28480"
3	|"32132"|	"97112"
4	|"22668"|	"51697"
5	|"1862"	|"2112"
6	|"53432"	|"1789391"
8	|"19554"	|"43573"

**ATR Table**

|classification_uid|total_count|sum_volume|
|------------------|-----------|----------|
1|	"57974"|	"3985397"
2|	"22540"|	"56961"
3|	"44955"|	"194224"
4|	"32705"|	"103394"
5|	"3602"	|"4224"
6|	"53432"	|"1789391"
8|	"29035"	|"87147"

Volume for ATR table is about double of that in TMC table.
Number of rows for ATR table should generally be less than that of TMC table if there are sufficient data such as for classification_uid=1 (light vehicles aka cars).
Will explain further in README.md .

**Comment by jovenc** [comment]
After fixing #238 , I did another count of rows and sum of volume for 3 days worth of data for the 3 important tables. The results seem pretty promising.

|table|count(volume_uid) respectively|sum(volume)|
|-----|-----------------------------|-----------|
|volumes|1,205,357|4,030,592|
|volumes_15min_tmc|402,808|4,005,066|
|volumes_15min|327,737|6,220,741|

Guess we are good to go! (ignoring refreshing materialized view issue for now)
