### ISSUE TITLE
Download data for new routes and identify gaps

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#235]
Try downloading data going back to May 1, 2019 for routes tagged with "DT2" prefix. 

Produce summary for routes with either a "DT" or "DT2" prefix indicating start and end dates (to identify which routes need to be processed, and which ones might be down currently).

**Comment by aharpalaniTO** [comment]
Just a note that the script for pulling data is located here: 

https://github.com/CityofToronto/bdit_data-sources/tree/master/bluetooth/api

FYI - this can be done in the background (and might take a while).

**Comment by chmnata** [comment]
Pulling the following analysis_id from 20190501 to 20191118
```
select analysis_id from bluetooth.all_analyses where route_name like '%DT2%'
```
