### ISSUE TITLE
What are the gaps in WYS data?

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#240]
What dates or range of dates do not have data in the `wys.counts_15min` table?

**Comment by Parvanehemati** [comment]
I push data from wys.counts_15min to phemati.counts_15min from 2019-11-13 23:59:00 to 2019-11-26 07:59:00
Gap in wys.counts_15min is from 2019-08-30 23:44:00 to 2019-11-13 23:59:00 
please let me know what is the next step

**Comment by radumas** [comment]
When does the data start?

**Comment by Parvanehemati** [comment]
The start date is 2019-07-31 23:59:00
