### ISSUE TITLE
Identify duplicate records in WYS data

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#241]
There are lots of duuuuuuuuuuuuuuuuuupes, in the 15min aggregate tables at least.

**Comment by radumas** [comment]
An example duplicate in the 15-minute aggregated table

`(api_id, datetime_bin, speed_id)=(9784, 2019-11-23 14:59:00, 9)`

I would be curious to know if this affects `wys.raw_data` and `wys.speed_counts` and for which dates. Then we can come up with a strategy for dealing with them

**Comment by Parvanehemati** [comment]
Based on same value for (api_id, datetime_bin , speed_id) fields on table: counts_15min
 there are 11 records duplicated
![Dublicat_records](https://user-images.githubusercontent.com/57957351/69821919-f043c900-11d2-11ea-829d-85ecd9ee3c7c.png)

**Comment by radumas** [comment]
Thanks. 

I think looking at duplicates in the aggregate data tables is superseded by changes we want to make to how to aggregate the data #243 #242. When we create a new aggregate table we will apply a `UNIQUE CONSTRAINT` to it from the beginning.

Can you do a check on the most recent 1-3 million records of raw data to see if duplicates are being generated there?

**Comment by Parvanehemati** [comment]
I raw_data table every record is repeated 3 times
![rep1](https://user-images.githubusercontent.com/57957351/70156694-5a9cb380-1682-11ea-88eb-400eef0ea747.png)

**Comment by Parvanehemati** [comment]
In the speed_counts table number of replicated records are different 3,6,9 or 12 times
![rep2](https://user-images.githubusercontent.com/57957351/70159482-faf4d700-1686-11ea-9c2f-8461068ff8c9.png)

**Comment by radumas** [comment]
Interesting finding! It seems like the number of duplicates is related to the `speed_id`.

Although... I think that might actually be ok. I wasn't thinking about this, but the `speed_counts` table is just converting the integer speed values into ranges of speed, so there will be multiple observations that had different speeds in `raw_data` that now have the same `speed_id`.

Do you know if the duplicates in `raw_data` just occur for November 3rd? Or other dates in November?

btw you could save an intermediate sample (on sample) of duplicate records by doing

```sql
SELECT datetime_bin, api_id, speed, count as spd_cnt, COUNT(1) as num_dups
FROM raw_data
WHERE --some filter on the range of values
GROUP BY datetime_bin, api_id, speed, spd_cnt
HAVING COUNT(1) > 1 --Only keep duplicates
```

**Comment by Parvanehemati** [comment]
I used this query thanks, no I didn't know about COUNT(1) 
Yes, there are duplicate for other days
![rep3](https://user-images.githubusercontent.com/57957351/70270252-fe18c180-1771-11ea-8333-a252d7346d74.png)

**Comment by radumas** [comment]
I moved the three data tables to `wys.TABLENAME_old` and then recreated `raw_data` and `counts_15min` with `UNIQUE` constraints. We'll see if the data script works ok over the weekend. If it doesn't will have to look deeper into what's causing duplicates.

**Comment by radumas** [comment]
Ah ha! The issue I was hoping to trigger (or not actually).
```
09 Dec 2019 11:15:18            ERROR    duplicate key value violates unique constraint "raw_data_api_id_datetime_bin_speed_key"
DETAIL:  Key (api_id, datetime_bin, speed)=(2059, 2019-12-08 00:04:00, 46) already exists.
Traceback (most recent call last):
  File "wys_api.py", line 243, in api_main
    execute_values(cur, 'INSERT INTO wys.raw_data (api_id, datetime_bin, speed, count) VALUES %s', table)
  File "/home/rliu/.local/share/virtualenvs/api-VhaNlK7A/lib/python3.5/site-packages/psycopg2/extras.py", line 1277, in execute_values
    cur.execute(b''.join(parts))
psycopg2.IntegrityError: duplicate key value violates unique constraint "raw_data_api_id_datetime_bin_speed_key"
DETAIL:  Key (api_id, datetime_bin, speed)=(2059, 2019-12-08 00:04:00, 46) already exists.
```

So a run of the API script on an empty raw data table shows that there are duplicate values produced by the script. We should report this to the vendor.

I'm going to relax the `UNIQUE CONSTRAINT` on raw_data for today and see if the constraint gets triggered for aggregating data.

**Comment by radumas** [comment]
Interesting, there is also a duplicate issue with the 15-minute aggregation function
```
09 Dec 2019 14:18:57            CRITICAL    Traceback (most recent call last):
  File "wys_api.py", line 256, in api_main
    cur.execute(counts_15min)
psycopg2.IntegrityError: duplicate key value violates unique constraint "counts_15min_api_id_datetime_bin_speed_id_key"
DETAIL:  Key (api_id, datetime_bin, speed_id)=(1743, 2019-12-07 23:59:00, 5) already exists.
CONTEXT:  SQL statement "WITH speed_bins AS (
        SELECT api_id, datetime_bin, speed_id, sum(count) AS count
        FROM wys.speed_counts B
        WHERE   counts_15min IS NULL
        GROUP BY api_id, datetime_bin, speed_id

        ), insert_data AS(

        --Joins aggregated speed bin data to the valid bins and inserts to counts_15min

        INSERT INTO wys.counts_15min (api_id, datetime_bin, speed_id, count)
        SELECT  B.api_id,
                B.datetime_bin,
                A.speed_id,
                sum(A.count) AS count
        FROM bins B
        INNER JOIN speed_bins A
                                                        ON A.api_id=B.api_id
                                                        WHERE A.datetime_bin >= B.start_time
                                                        AND A.datetime_bin < B.end_time
        GROUP BY B.api_id, B.datetime_bin, A.speed_id
        ORDER BY B.api_id, B.datetime_bin, A.speed_id
        RETURNING counts_15min, api_id, datetime_bin, speed_id)

        --Sets IDs to speed_counts

        UPDATE wys.speed_counts A
        SET counts_15min=B.counts_15min
        FROM insert_data B
        WHERE A.counts_15min IS NULL
        AND A.api_id=B.api_id
        AND A.datetime_bin >= B.datetime_bin AND A.datetime_bin < B.datetime_bin + INTERVAL '15 minutes'
        AND A.speed_id=B.speed_id"
PL/pgSQL function wys.aggregate_speed_counts_15min() line 37 at SQL statement


09 Dec 2019 14:18:57            CRITICAL    Traceback (most recent call last):
  File "wys_api.py", line 277, in api_main
    cur.execute(str(string))
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by radumas** [comment]
So all this might be void because it turns out the script was set to run every hour in `cron`.

**Comment by radumas** [comment]
:eyes: 

```sql
SELECT datetime_bin::DATE dt, "count" AS "Number of Observations",  cnt AS number_of_dupes, COUNT(1)

FROM (SELECT api_id, datetime_bin, speed, count, COUNT(1) AS cnt
  FROM wys.raw_data
  GROUP BY api_id, datetime_bin, speed, count) dupes
GROUP BY dt,"Number of Observations", cnt
ORDER BY dt,"Number of Observations", cnt
```

'dt'|'Number of Observations'|'number_of_dupes'|'count'
'2019-12-08'|1|3|793728
'2019-12-08'|1|6|72
'2019-12-08'|2|3|195678
'2019-12-08'|2|6|16
'2019-12-08'|3|3|58248
'2019-12-08'|3|6|1
'2019-12-08'|4|3|17204
'2019-12-08'|4|6|2
'2019-12-08'|5|3|5237
'2019-12-08'|6|3|1502
'2019-12-08'|7|3|401
'2019-12-08'|8|3|138
'2019-12-08'|9|3|41
'2019-12-08'|10|3|13
'2019-12-08'|11|3|7
'2019-12-08'|12|3|2
'2019-12-08'|13|3|4
'2019-12-08'|15|3|1
'2019-12-09'|1|3|768075
'2019-12-09'|1|6|95
'2019-12-09'|1|9|5
'2019-12-09'|2|3|198540
'2019-12-09'|2|6|27
'2019-12-09'|3|3|60862
'2019-12-09'|3|6|8
'2019-12-09'|4|3|19079
'2019-12-09'|5|3|5870
'2019-12-09'|5|6|1
'2019-12-09'|6|3|1847
'2019-12-09'|6|6|1
'2019-12-09'|7|3|645
'2019-12-09'|8|3|207
'2019-12-09'|9|3|90
'2019-12-09'|10|3|49
'2019-12-09'|11|3|14
'2019-12-09'|12|3|8
'2019-12-09'|13|3|1
'2019-12-09'|14|3|3
'2019-12-09'|16|3|2
'2019-12-09'|17|3|1

**Comment by radumas** [comment]
Fixing the `for attempt in range(3)` bug got rid of most of the duplicates

'dt'|'Number of Observations'|'number_of_dupes'|'count'
|--|----------------------------:|--------------------:|-------:|
'2019-12-10'|1|2|77
'2019-12-10'|2|2|26
'2019-12-10'|3|2|4
'2019-12-10'|4|2|3
'2019-12-10'|5|2|2

**Comment by radumas** [comment]
Vendor has confirmed the remaining duplicates are duplicate data. So keeping the `UNIQUE CONSTRAINT`

**Comment by radumas** [comment]
To deal with existing duplicated raw data in the database ran the below query.

```sql
SELECT DISTINCT api_id, datetime_bin, speed, count
INTO wys.raw_data_old_distinct
  FROM wys.raw_data_old;
``` 

Which produced 123397051 rows in 01:03:3656 hours. Need to re-aggregate these eventually
