### ISSUE TITLE
Only aggregate data for stationary WYS Signs

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#242]
Modify the [wys.aggregate_speed_counts_15min()](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/sql/function-aggregate_speed_counts_15min.sql) to only include data from stationary signs (ones that do not move). The name pattern that those signs has is "address + serial number".

**Comment by Parvanehemati** [comment]
WITH bin_grouping AS (

		SELECT DISTINCT	api_id, 

			TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) - INTERVAL '1 minute' AS datetime_bin,
			TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) - INTERVAL '1 minute' AS start_time,
			TIMESTAMP WITHOUT TIME ZONE 'epoch' + INTERVAL '1 second' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) + INTERVAL '14 minute' AS end_time
		FROM 	phemati.speed_counts A inner join locations on A.api_id=locations.api_id
		WHERE	counts_15min IS NULL and (Length(SUBSTRING(locations.sign_name, '([0-9]{1,8})'))='8')
		GROUP BY api_id, datetime_bin
	)
----------------------------------------------------------------------------------
I just changed this CTE in Function: aggregate_speed_counts_15min()  no execute it

**Comment by Parvanehemati** [comment]
I checked in counts_15min table in 29348 records there are 8127 records without serial number
Do I modify function : aggregate_speed_counts_15min() in my schema or I can modify it on wys.

**Comment by radumas** [comment]
This is a neat way of filtering signs that have a serial number!
`(Length(SUBSTRING(locations.sign_name, '([0-9]{1,8})'))='8')`

Am I correct that this is checking if there's a sequence of digits that is exactly 8 digits long? Are you sure all the serial numbers are exactly 8 digits long?

I would recommend implementing your modifications for this one and #243 in your schema. Create a new aggregate table and apply a `UNIQUE` constraint to it and then test the function on a sample of `raw_data`

**Comment by Parvanehemati** [comment]
The where clues change to  (Length(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})'))>'3')
all of the stations with specific code will be comes in the result list
