### ISSUE TITLE
Change WYS aggregation to be coarser

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#243]
We don't need data at a 5-km/hr speed resolution and a 15-min resolution, update the [`aggregate_speed_counts()`](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/sql/function-aggregate_speed_counts_15min.sql) function to be more coarse.

- [x] Change to hourly bin resolution
- [x] Change the `wys.speed_bins` to be 10 km/hr bins 
- [x] Include `min`, `max`, `avg`, and COUNT
- [x] After #242 is fixed as well, test pulling 1 month of data and see if it's <1 million rows.

**Comment by Parvanehemati** [comment]
changed the row in the speed_bins table to 10 km

**Comment by Parvanehemati** [comment]
Query to find average speed in table :counts_15min
select api_id, datetime_bin,sum(speed_id*count)/sum(count) as Avg_speed  from  counts_15min group by api_id,datetime_bin

**Comment by Parvanehemati** [comment]
Maximum, Minimum ,and count in table :+1: counts_15min
select api_id,datetime_bin,min(speed_id),max(speed_id),sum(count) from counts_15min group by api_id,datetime_bin

**Comment by Parvanehemati** [comment]
to calculate percentage value for a speed in a limit time for a special api_id I create a function 

CREATE OR REPLACE FUNCTION get_percentage_speed(api integer , stime timestamp )
  RETURNS double precision AS
$BODY$
DECLARE  rec record;
DECLARE  sumcou integer ;
Declare res double precision;
BEGIN   
   select sum(count) as sumcou from counts_15min where  api_id=api and datetime_bin=stime;	

   FOR rec IN  select speed_id from counts_15min where  api_id=api and datetime_bin=stime

   LOOP
	select (100/sumcou)*count into res from counts_15min where api_id=api and datetime_bin=stime and speed_id=rec.speed_id;
	rec.NEXT ;
--rec.speed_id;    
        IF res>=0 THEN
	 set per_sp= res;
           --RETURN res;              
      END IF;
  
   END LOOP;
  RETURN res;  
END
$BODY$ 
 LANGUAGE plpgsql STABLE;

**Comment by Parvanehemati** [comment]
This is query calculate percentage of speeds were saved in table counts_15min in a limit time :

select sum(count) num, speed_id , round((100*sum(count):: decimal /(select sum(count) from counts_15min where  datetime_bin>='2019-12-17 00:00:00'  and datetime_bin<='2019-12-17 23:59:59' 
)),2) ::text || '% '  as speed_percentage  from counts_15min where  datetime_bin>='2019-12-17 00:00:00'  and datetime_bin<='2019-12-17 23:59:59' group by speed_id order by speed_id

**Comment by radumas** [comment]
Regarding calculating hourly resolution.

Data from the WYS signs comes in in 5-min bins that are all 1-minute off from clock-face (1:04, 1:09, etc). We strongly suspect this implies that the timestamp actually represents _the end_ of the time bin: `1:04` actually means `[1:00 - 1:05)`. The way the data is aggregated in the [`aggregate_speed_counts`](https://github.com/CityofToronto/bdit_data-sources/blob/wys_api/wys/api/sql/function-aggregate_speed_counts_15min.sql#L25-L27) function should take this into account by doing a simple truncation

**Comment by Parvanehemati** [comment]
In function aggregate_speed_counts_15min() , every 15 min, datetime_bin extract by
TIMESTAMP WITHOUT TIME ZONE 'epoch' - INTERVAL '1  minute' * (floor((extract('epoch' from A.datetime_bin)) / 900) * 900) - INTERVAL '1 minute' AS datetime_bin
if  -INTERVAL '1  minute' changes to  -INTERVAL '5  minute' the extract time will be corecct
-----
if I am wrong please let me know because I search all functions and trigger functions I couldn't find any thing else

**Comment by radumas** [comment]
Yeah that's the right fix, except we want the `datetime_bin` to be hourly bins, so that could just become [`date_trunc('hour', datetime_bin)`](https://devdocs.io/postgresql~9.6/functions-datetime#date_trunc)

**Comment by Parvanehemati** [comment]
Okey based on this change the function can execute every hour instead 15 min

**Comment by Parvanehemati** [comment]
The changed function is on my schema

**Comment by Parvanehemati** [comment]
Created FUNCTION aggregate_speed_counts_one_hour() to save  sum of the counts for same speed in one hour based on api_id

**Comment by Parvanehemati** [comment]
Changed the name of primary key in table counts_15min because in PostgreSQL if the name of a table and primary key of that table is same sometimes in insert time appears error
and also I changed foreign key of table speed_counts

**Comment by radumas** [comment]
Changing back to 5 kph bins. I have huge regrets.
