### ISSUE TITLE
Validate Sign Locations

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#245]
We get locations of the signs from the API which are stored in `wys.locations`. We want to validate the locations of the stationary signs by comparing to a dataset that has been independently generated for the [Vision Zero Toronto Map](https://www.toronto.ca/services-payments/streets-parking-transportation/road-safety/vision-zero/safety-measures-and-mapping/) 

![image](https://user-images.githubusercontent.com/10623872/70545436-8fee4900-1b3b-11ea-94f3-de652f71cd83.png)

These can be point in `vz_safety_programs.points_wyss`

- [x] You will need to generate a [`GEOMETRY` type column](http://postgis.net/docs/manual-2.3/reference.html#Geometry_Constructors) from the `wys.locations` table (this should also ultimately be automated as a `TRIGGER` on that table). 
- [x] Compare the distance between the signs in the `locations` table with the sign in `vz_safety_programs.points_wyss` because we can't relate the two together by a key, you will need to do a nearest neighbour query (see the PostGIS exercises in Notion). Flag any sign that is further than 5-10m 
- [x] If there are multiple rows for an `api_id`, what changes over time? 
- [ ] Validate the address of the `wys.locations`. Does the address of the sign match up with the location of the geometry?

**Comment by Parvanehemati** [comment]
Add a field  to locations table : 'shape' geometry
Set shape field with query : ST_MakePoint(float x, float y)
change SRID to 98012 of this field with : select  UpdateGeometrySRID('locations', 'shape', 98012);

**Comment by Parvanehemati** [comment]
Add two fields to locations table : 
1- 'distance' double precision  : save distance between this location and nearest location in wys_location
2- 'loc_id' character varying : save a key two make relation between two tables location and wys_location
create function 'update_locations' to find the nearest location and update table locations
CREATE OR REPLACE FUNCTION update_locations(shape_in geometry,api integer,add text)
  RETURNS boolean  AS
$BODY$
Declare diffs double precision;
BEGIN
	with Measure AS(
		select shape,ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)) as diff from wyss_locations
		where (select ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)))<0.01
		order by diff limit 1
	)	
	
	update locations set 
	  shape = Measure.shape, loc_id=cast(api as text)||substring(add,0,3) , distance=Measure.diff  from Measure
          where locations.address=add;
     
        Return true;
END; $BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

**Comment by Parvanehemati** [comment]
query to use the function and update location table is:
select update_locations(shape , api_id, address) from locations

**Comment by radumas** [comment]
Before you re-ran the `update_locations` function with `ST_Transform`, did you delete the contents of those columns?

**Comment by Parvanehemati** [comment]
yes every time before ran this function I deleted this column's value but the delete comment is not in the function

**Comment by radumas** [comment]
I don't think we need an accuracy of 1 cm  (0.01m) when comparing these positions.

```sql
where (select ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)))<0.01
```

I would remove that `WHERE` clause so we can analyze outliers and the closest location they are matched to

**Comment by Parvanehemati** [comment]
okey

**Comment by Parvanehemati** [comment]
In the Table locations add four columns :
- loc_id (save key to relation between table locations and wyss_locations)
-distance 
- shape geometry value of the location 
_shape_wyss geometry value of close location from wys_locations table
-------Function to find closest location from wyss_locations
CREATE OR REPLACE FUNCTION update_locations(
    shape_in geometry,
    api integer,
    add text)
  RETURNS boolean AS
$BODY$
BEGIN
	with Measure AS(
		select wyss_locations.shape,ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)) as diff from wyss_locations
		where ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012))=(select min(ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)))from wyss_locations)
		order by diff limit 1
	)	
	update locations set 
	  shape_wyss = ST_Transform(Measure.shape,98012), 
	  loc_id=cast(api as text)||substring(add,0,3) ,
	  distance=Measure.diff  from Measure
          where locations.address=add;   
        Return true;
END; $BODY$
----Run this Function with query
select update_locations(shape,api_id,address) from locations

**Comment by radumas** [comment]
There are 9 stationary sign locations where a same `address` has different `loc` details

```sql
SELECT address

FROM wys.locations
WHERE Length(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})'))>'3'
GROUP BY address
HAVING COUNT(DISTINCT loc) > 1
```

So performing the `UPDATE` using only `address` as the key will lead to undesirable outcomes. Because the finding of the closest location is performed based on the `shape_in` geometry, that could used in the `UPDATE` statement as well.

Also the below `WHERE` clause in the `Measure` sub-query is unnecessary
```sql
		where ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012))=(select min(ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)))from wyss_locations)
```

`Measure` can be re-written as 

```sql
select wyss_locations.shape,
ST_Distance(ST_Transform(wyss_locations.shape,98012), ST_Transform(shape_in,98012)) as diff 
from wyss_locations
order by diff 
limit 1
```

I'm also a little bit confused by `loc_id`. It seems to be derived from elements that are already in the `locations` table, the api_id and the address, so I don't understand how that links to the `wyss_locations` table.

**Comment by Parvanehemati** [comment]
I consider Loc_id  just as a primary key in this table it's unique because it created from two field and I can set this field in wys_locations as foreign key
if do you mind it's not usable I can remove it

**Comment by radumas** [comment]
It's a good idea.

Unfortunately it's not unique
```sql
SELECT loc_id
  FROM phemati.locations
  GROUP BY loc_id
  HAVING COUNT(*) > 1;
```

**Comment by Parvanehemati** [comment]
Ohh it wasn't good idea

**Comment by Parvanehemati** [comment]
The last changed of update_locations function is placed on my schema

**Comment by radumas** [comment]
It looks like the `phemati.locations.shape` column was created with the X and the Y reversed, see the below image and note that the shape of Toronto appears rotated 90 degrees. Also please recreate all geometries using `SRID: 2952` and redo the geographic matching process accordingly.

![image](https://user-images.githubusercontent.com/10623872/72104325-31aeb480-32f9-11ea-83d4-c8cf4cc07b83.png)

**Comment by Parvanehemati** [comment]
Okey  I did

**Comment by Parvanehemati** [comment]
I changed function update_locations and table locations

**Comment by Parvanehemati** [comment]
I add an id field to the safety_location table to create connection between two tables, so after edit the function I found about 200 of locations aren't in Toronto, they are in GTA.
Red dots are safety locations
Blue dots are API locations
Number shows relation between location
![locations](https://user-images.githubusercontent.com/57957351/72383720-073e6c00-36ea-11ea-9d83-c1d3a947f8c3.png)

**Comment by Parvanehemati** [comment]
Create another function to locate nearest distance for every safety location in the api locations
FUNCTION nearest_api_locations(geometry,integer)

**Comment by Parvanehemati** [comment]
change function nearest_api_locations to search locations with type='Permanent' and execute update safety_locations query again

**Comment by radumas** [comment]
Seems like most of the duplicate stationary signs in the `wys.locations` table are for silly things like minor changes rather than big stuff. We could probably edit/delete some historic entries in the `locations` table. 

I created a materialized view to de-duplicate where the serial number changes but otherwise the name of the sign stays the same.

`wys.stationary_signs`

**Comment by radumas** [comment]
@jovenc you were gonna transform this into a VIEW correct?

**Comment by radumas** [comment]
I think this is the query

```sql
WITH distinctish_signs AS(
	SELECT DISTINCT ON (api_id,  regexp_replace(sign_name, '([0-9]{5,8})','')) 
	api_id, address, regexp_replace(sign_name, '([0-9]{5,8})','') AS sign_name, dir, start_date, st_setsrid(st_makepoint(split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text, 2)::float, 
						split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text, 1)::float), 4326) AS geom
	FROM wys.locations
	WHERE length("substring"(reverse(locations.sign_name), '([0-9]{1,8})'::text)) > 3
	ORDER BY api_id, regexp_replace(sign_name, '([0-9]{5,8})',''))

SELECT distinctish_signs.*
FROM distinctish_signs
INNER JOIN (SELECT api_id FROM distinctish_signs GROUP BY api_id HAVING COUNT(1)>1) dupes USING (api_id)
```

**Comment by jovenc** [comment]
duplicates of  `api_id` with different `sign_name` (serial number not included) are 4648, 7904, 8212, 8214, 9677, 9678, 9717, 9719, 9774, 10290, 10461, 10765, 10766, 13784, 13798, 22721, 22722.

**Comment by jovenc** [comment]
For `api_id` = 4648, the `sign_name` was written as 'Janet St SB' instead of 'Jane St SB'.
![image](https://user-images.githubusercontent.com/54872846/74563782-8c13e400-4f3b-11ea-9ac2-dfd4366851f4.png)


![api_id=4648](https://user-images.githubusercontent.com/54872846/74563661-4525ee80-4f3b-11ea-98ce-d8a9dfb87813.PNG)

**Comment by jovenc** [comment]
For `api_id` = 7904, the `sign_name` was written as 'Saint Marks Ave WB' instead of 'Saint Marks Rd WB'.
![image](https://user-images.githubusercontent.com/54872846/74563967-ead95d80-4f3b-11ea-8fcc-c85f273e6590.png)
![api_id=7904](https://user-images.githubusercontent.com/54872846/74563976-f036a800-4f3b-11ea-9e2e-0bcc15a2d859.PNG)

**Comment by jovenc** [comment]
For `api_id` = 8212, the `sign_name` were different although having the same serial number. The `sign_name` should be 'Gladstone Ave SB' given the location. The `loc` is slightly different too. One just has more decimal points than the other as shown below.
![image](https://user-images.githubusercontent.com/54872846/74564102-3a1f8e00-4f3c-11ea-893f-6c3ab8d44be8.png)
![image](https://user-images.githubusercontent.com/54872846/74564207-85d23780-4f3c-11ea-83ff-2731434fa8e4.png)

**Comment by jovenc** [comment]
For `api_id` = 8214, the `sign_name` should be 'Dufferin St NB' instead of 'Gladstone Ave'
![image](https://user-images.githubusercontent.com/54872846/74564393-fed18f00-4f3c-11ea-8e1a-361c05223a9d.png)
![image](https://user-images.githubusercontent.com/54872846/74564470-2294d500-4f3d-11ea-8313-dfbff7dcd134.png)

**Comment by jovenc** [comment]
For `api_id` = 9677, `sign_name` should be 'Faywood Blvd NB' as 'Sheppard Ave NB' does not exist. There is also a slight change in `loc` where the longitude has an additional decimal point as shown below. 

![image](https://user-images.githubusercontent.com/54872846/74565022-460c4f80-4f3e-11ea-9fba-48f2af258531.png)
![image](https://user-images.githubusercontent.com/54872846/74565063-5a504c80-4f3e-11ea-9bb8-77259e182944.png)

**Comment by jovenc** [comment]
For `api_id` = 9677, `sign_name` should be 'Faywood Blvd SB' because 'Sheppard Ave **SB**' does not exist. 
![image](https://user-images.githubusercontent.com/54872846/74565192-af8c5e00-4f3e-11ea-8220-9dc1e61ab44d.png)
![image](https://user-images.githubusercontent.com/54872846/74565212-bdda7a00-4f3e-11ea-9ed7-076246f06aab.png)

**Comment by jovenc** [comment]
For `api_id` = 9717, the `sign_name` should be 'Ardwick Blvd SB' instead of 'Blue Haven Cres NB'.
![image](https://user-images.githubusercontent.com/54872846/74565480-4b1dce80-4f3f-11ea-8368-92f62bf9ddbb.png)
![image](https://user-images.githubusercontent.com/54872846/74565515-57099080-4f3f-11ea-8ae6-940e53bdd4c7.png)

**Comment by jovenc** [comment]
For `api_id` = 9719, is the `dir` WB or EB? The API map on _streetsoncloud.com_ shows that EB is the latest one.
![image](https://user-images.githubusercontent.com/54872846/74566530-a94bb100-4f41-11ea-8fe4-1e140beb8df4.png)
![image](https://user-images.githubusercontent.com/54872846/74566602-dac47c80-4f41-11ea-9e37-de526204c6a3.png)

**Comment by jovenc** [comment]
For `api_id` = 9774, `sign_name` **and** `dir` changed. From the API map, the actual device location is about 100m away from the current shown location. 
![image](https://user-images.githubusercontent.com/54872846/74567102-0431d800-4f43-11ea-820b-d92462c4a25c.png)
![image](https://user-images.githubusercontent.com/54872846/74567163-24fa2d80-4f43-11ea-8bdd-aa6ccfdf3d29.png)

**Comment by jovenc** [comment]
For `api_id` = 10290, the `sign_name` is slightly different. The one from a latter date is the right one as shown below.
![image](https://user-images.githubusercontent.com/54872846/74568795-cdf65780-4f46-11ea-8c37-a297395959d4.png)
![image](https://user-images.githubusercontent.com/54872846/74568832-ee261680-4f46-11ea-9445-785cf57d26a3.png)

**Comment by jovenc** [comment]
For `api_id` = 10461, is the `dir` = WB or EB?
![image](https://user-images.githubusercontent.com/54872846/74568980-5248da80-4f47-11ea-9255-063976d195bf.png)
![image](https://user-images.githubusercontent.com/54872846/74569004-5e349c80-4f47-11ea-910e-0cf46ed7464d.png)

**Comment by jovenc** [comment]
For `api_id` = 10765, is the `dir` = WB or EB?
![image](https://user-images.githubusercontent.com/54872846/74569123-a0f67480-4f47-11ea-851d-b9b598299306.png)
![image](https://user-images.githubusercontent.com/54872846/74569191-d0a57c80-4f47-11ea-99a3-7d280f0fe92d.png)

**Comment by jovenc** [comment]
For `api_id` = 10766, is the `dir` = WB or EB? The `loc` is also slightly different like they are located right next to each other.
![image](https://user-images.githubusercontent.com/54872846/74569358-3a258b00-4f48-11ea-874e-387f841d52b2.png)
![image](https://user-images.githubusercontent.com/54872846/74569381-49a4d400-4f48-11ea-90db-ddae67e4d738.png)

**Comment by jovenc** [comment]
For `api_id` = 13784, is the `dir` EB or WB? BUT it's already out of commission though, does it still matter? Last communicated `2019-12-11 23:06:04`
![image](https://user-images.githubusercontent.com/54872846/74569483-82dd4400-4f48-11ea-848d-f4b6efbd3278.png)
![image](https://user-images.githubusercontent.com/54872846/74569896-79a0a700-4f49-11ea-88ac-eb94f31422e6.png)

**Comment by jovenc** [comment]
For `api_id` = 13798, is the `dir` EB or WB?
![image](https://user-images.githubusercontent.com/54872846/74570739-e4061700-4f4a-11ea-807e-d66c6e24dc86.png)
![image](https://user-images.githubusercontent.com/54872846/74570870-0c8e1100-4f4b-11ea-9844-69a65338f6f0.png)

**Comment by jovenc** [comment]
For `api_id` = 22721, seems like something weird is going on here. I couldn't find the serial number 'C19174058'. The latest one is right regardless.
![image](https://user-images.githubusercontent.com/54872846/74571453-d56c2f80-4f4b-11ea-9778-860b4cb71de5.png)
![image](https://user-images.githubusercontent.com/54872846/74571540-fcc2fc80-4f4b-11ea-81b2-403145331c0b.png)

**Comment by jovenc** [comment]
For `api_id` = 22722, not sure as to why there's an additional 'C' in the `sign_name`. There's also a change in serial number. I found second row in the API map but not the first row.
![image](https://user-images.githubusercontent.com/54872846/74572279-db164500-4f4c-11ea-9568-192fed04d5a6.png)

![image](https://user-images.githubusercontent.com/54872846/74572260-d3ef3700-4f4c-11ea-8ae5-4ee5c5fea96a.png)

**Comment by jovenc** [comment]
> I think this is the query
> 
> ```sql
> WITH distinctish_signs AS(
> 	SELECT DISTINCT ON (api_id,  TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')))
> 	api_id, address, TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')) AS sign_name, dir, start_date, st_setsrid(st_makepoint(split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text, 2)::float, 
> 						split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text, 1)::float), 4326) AS geom
> 	FROM wys.locations
> 	WHERE length(substring(reverse(locations.sign_name), '([0-9]{1,8})'::text)) > 3
> 	ORDER BY api_id, TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')), start_date DESC)
> 
> SELECT distinctish_signs.*
> FROM distinctish_signs
> INNER JOIN (SELECT api_id FROM distinctish_signs GROUP BY api_id HAVING COUNT(1)>1) dupes USING (api_id)
> ```

In addition to the above, added the distance difference between the first and second location/geom of the same `api_id` .
```
WITH 
distinctish_signs AS (
	 SELECT DISTINCT ON (api_id, TRIM(regexp_replace(sign_name, '([0-9]{5,8})',''))) locations.api_id,
		address,
		TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')) AS sign_name,
		REVERSE(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})')) AS serial_number, 
		dir,
		start_date,
		st_setsrid(st_makepoint(split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text , 2)::float, 
								split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text , 1)::float), 4326) AS geom
	   FROM wys.locations
	  WHERE length(substring(reverse(sign_name), '([0-9]{1,8})')) > 3
	  ORDER BY api_id, TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')), start_date
	),
distance AS (
SELECT *, 
	ST_Distance(ST_Transform(geom, 2952), ST_Transform(lag(geom) OVER (PARTITION BY api_id ORDER BY start_date), 2952)) AS dist_diff
FROM distinctish_signs
ORDER BY api_id, start_date
)
	
SELECT distance.api_id,
	row_number() OVER (ORDER BY distance.api_id, distance.start_date) AS sign_id,
	distance.address,
	distance.sign_name,
	distance.serial_number,
	distance.dir,
	distance.start_date,
	lead(distance.start_date) OVER w AS next_start,
	lag(distance.start_date) OVER w AS prev_start,
	distance.dist_diff,
	distance.geom
FROM distance
--WHERE dist_diff IS NOT NULL
WINDOW w AS (PARTITION BY distance.api_id ORDER BY distance.start_date)
ORDER BY api_id, start_date
```

**Comment by radumas** [comment]
> Duplicates of `api_id` with different `sign_name` (serial number not included) are 4648, 7904, 8212, 8214, 9677, 9678, 9717, 9719, 9774, 10290, 10461, 10765, 10766, 13784, 13798, 22721, 22722.
> 
> For BDIT to correct:
> 
>     * [x]  7904
> 
>     * [x]  8214
> 
>     * [x]  9678
> 
>     * [x]  9717
> 
>     * [x]  10290
> 
>     * [x]  22721
> 
>     * [x]  22722
> 
> 
> To ask Jacqui:
> 
>     * [x]  4648 (typo in sign name)
> 
>     * [x]  8212 (address & loc different)
> 
>     * [x]  9677 (sign name & loc different)
> 
>     * [x]  9719 (dir issue)
> 
>     * [x]  9774 (sign name and actual device location 100m away)
> 
>     * [x]  10461 (dir issue)
> 
>     * [x]  10765 (dir issue)
> 
>     * [x]  10766 (dir issue & loc different)
> 
>     * [x]  13784 (dir issue)
> 
>     * [x]  13798 (dir issue)

Fixed with the below sql

```sql
-- UPDATE wys.locations
-- -- 	SET api_id=?, address=?, sign_name=?, dir=?, start_date=?, loc=?
-- 	SET sign_name = 'Jane St SB 1710808' 
-- 	WHERE sign_name = 'Janet St SB 1710808' 
	
-- UPDATE wys.locations
-- -- 	SET api_id=?, address=?, sign_name=?, dir=?, start_date=?, loc=?
-- 	SET sign_name = 'St Marks Rd WB 18092403'
-- 	WHERE sign_name = 'St Marks Ave WB 18092403'
	
-- UPDATE wys.locations
-- SET address = '8 Saint Mark''s Road'
-- WHERE address = '8 Saint Mark&amp;#39;s Road'

-- UPDATE wys.locations
-- SET sign_name = 'Dufferin St NB 18082335', dir='NB'
-- WHERE sign_name = 'Gladstone Ave SB 18082335'

-- UPDATE wys.locations
-- SET sign_name = 'Faywood Blvd SB 18112701'
-- WHERE sign_name = 'Sheppard Ave SB 18112701'

-- UPDATE wys.locations
-- SET sign_name = 'Ardwick Blvd SB 18102438', dir = 'SB'
-- WHERE sign_name = 'Blue Haven Cres NB 18102438'

-- UPDATE wys.locations
-- SET sign_name = 'Brimley Rd S NB 18112670'
-- WHERE sign_name = 'Brimley Rd NB 18112670'

-- DELETE FROM wys.locations 
-- WHERE address = '26 River Bend Road' AND sign_name = 'Currie Ave WB C19174058'

-- UPDATE wys.locations
-- SET sign_name = 'Currie Ave WB 19174058'
-- WHERE sign_name = 'Currie Ave WB C19174058'

-- UPDATE wys.locations
-- SET sign_name = 'Avenue Rd NB 19104013'
-- WHERE sign_name = 'Avenue Rd NB C 19104013'

-- UPDATE wys.locations
-- SET sign_name = 'Gladstone Ave SB 18102457'
-- WHERE sign_name = 'Dufferin St SB 18102457'

-- UPDATE wys.locations
-- SET sign_name = 'Faywood Blvd NB 18112674'
-- WHERE sign_name = 'Sheppard Ave NB 18112674'

-- UPDATE wys.locations
-- SET sign_name = 'Saskatoon Dr EB 18092421', dir ='EB'
-- WHERE sign_name = 'Saskatoon Dr WB 18092421'

-- UPDATE wys.locations
-- SET sign_name = 'Seneca Hill Dr EB18112627', dir ='EB'
-- WHERE sign_name = 'Don Mills Rd NB 18112627'

-- UPDATE wys.locations
-- SET sign_name = 'Seneca Hill Dr EB18112627', dir ='EB'
-- WHERE sign_name = 'Don Mills Rd NB 18112627'

-- UPDATE wys.locations
-- SET sign_name = 'Seneca Hill Dr EB 18112627', address = '312 Seneca Hill Drive'
-- WHERE sign_name = 'Seneca Hill Dr EB18112627'

-- UPDATE wys.locations
-- SET sign_name = 'Pleasant Ave EB 18122782', dir ='EB'
-- WHERE sign_name = 'Pleasant Ave WB 18122782'

-- UPDATE wys.locations
-- SET sign_name = 'Freshmeadow Dr WB 18112688', dir ='WB'
-- WHERE sign_name = 'Freshmeadow Dr EB 18112688'

-- UPDATE wys.locations
-- SET sign_name = 'Freshmeadow Dr EB 18112700', dir ='EB'
-- WHERE sign_name = 'Freshmeadow Dr WB 18112700'

-- UPDATE wys.locations
-- SET sign_name = 'Grandravine Ave EB 19080030', dir ='EB'
-- WHERE sign_name = 'Grandravine Ave WB 19080030'

UPDATE wys.locations
SET sign_name = 'Grandravine Ave WB 19070468', dir ='WB'
WHERE sign_name = 'Grandravine Ave EB 19070468'
```

**Comment by radumas** [comment]
I don't think we need to include a distance filter in the stationary view. I ran the below and all but one of the distances over 100m are signs coming online when they were positioned up North and then being located according to their GPS position. 

```sql
WITH 
distinctish_signs AS (
	 SELECT api_id, --DISTINCT ON (api_id, TRIM(regexp_replace(sign_name, '([0-9]{5,8})',''))) locations.
		address,
		TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')) AS sign_name,
		REVERSE(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})')) AS serial_number, 
		dir,
		start_date,
		st_setsrid(st_makepoint(split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text , 2)::float, 
								split_part(regexp_replace(loc, '[()]', '', 'g'), ','::text , 1)::float), 4326) AS geom,
	   CASE WHEN length(substring(reverse(sign_name), '([0-9]{1,8})')) > 3 THEN 'Permanent sign' END as sign_type
	   FROM wys.locations
-- 	  WHERE length(substring(reverse(sign_name), '([0-9]{1,8})')) > 3
	  ORDER BY api_id, TRIM(regexp_replace(sign_name, '([0-9]{5,8})','')), start_date 
	),
distance AS (
SELECT *, 
	ST_Distance(ST_Transform(geom, 2952), ST_Transform(lag(geom) OVER w, 2952)) AS dist_diff,
	lead(start_date) OVER w AS next_start,
	lag(start_date) OVER w AS prev_start
FROM distinctish_signs
	WINDOW w AS (PARTITION BY api_id ORDER BY start_date)
ORDER BY api_id, start_date
)
	
SELECT distance.api_id,
	row_number() OVER (ORDER BY distance.api_id, distance.start_date) AS sign_id,
	distance.address,
	distance.sign_name,
	distance.serial_number,
	distance.dir,
	distance.start_date,
	next_start,
	prev_start,
	sign_type, 
	distance.dist_diff,
	distance.geom
FROM distance
WHERE next_start IS NOT NULL OR prev_start IS NOT NULL
ORDER BY api_id, start_date
```
