### ISSUE TITLE
Add functionality to send a slack message if there are non-critical errors

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#249]
Per [this SO post](https://stackoverflow.com/questions/59092268/how-to-get-the-exit-code-for-a-failed-bashoperator) it's possible to get the return value from a BashOperator. The return value should modify what message Slack sends. There are a few non-critical errors the script will log that won't kill the program. These should bubble to some final `sys.exit()` call which would trigger a Slack message to notify that the data pipeline encountered a weird issue.

**Comment by radumas** [comment]
Kind of wondering if I should make these unusual errors fail it instead.

**Comment by Nate-Wessel** [comment]
If there what?

**Comment by radumas** [comment]
are non-critical errors

**Comment by radumas** [comment]
Wow I was really allergic to writing "errors" when I wrote the issue title and description. Updated.

**Comment by radumas** [comment]
This has been dealt with in the splitting the BashOperator into python tasks
