### ISSUE TITLE
Calculate avg, median, 85th percentile speed for each stationary sign

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#252]
Splitting this off from #243. As a first step to validating the data we're getting from these signs, we want to compare the speeds they're reporting at a high-level. Based on month of data, calculate the following aggregate statistics for each stationary sign and store in a table:

- [x] average speed
- [x] median (50th percentile) speed
- [x] 85th percentile speed

[Here is the documentation for the percentile function](https://devdocs.io/postgresql~9.6/functions-aggregate#percentile_cont32within32group32). There's some subtlety in using percentile functions on aggregate data, but you could do a [cumulative sum of the count](https://stackoverflow.com/questions/22841206/calculating-cumulative-sum-in-postgresql) ordered by speed bins and identify which speed bin crosses the 50% and the 85% thresholds of counts for that sign.

**Comment by Parvanehemati** [comment]
Query to find speed average for all locations in a limit time :
select distinct address, locations.api_id, date_trunc('day', datetime_bin), round(avg(speed_id) over (PARTITION BY counts_15min.api_id , date_trunc('day', datetime_bin) 
order by counts_15min.api_id),2) speed_Ave from counts_15min inner join  locations on counts_15min.api_id=locations.api_id
where datetime_bin>='2019-12-17 00:00:00' and   datetime_bin<'2019-12-18 00:00:00'

**Comment by Parvanehemati** [comment]
To get average from counts_15min, with consider the absolute cumulative frequency and without consider :
select distinct address, locations.api_id, date_trunc('day', datetime_bin), 
round(avg(speed_id) over (PARTITION BY counts_15min.api_id , date_trunc('day', datetime_bin) order by counts_15min.api_id),2) speed_Ave,
round(round(sum(speed_id*count) over (PARTITION BY counts_15min.api_id , date_trunc('day', datetime_bin) order by counts_15min.api_id),2) /
round(sum(count) over (PARTITION BY counts_15min.api_id , date_trunc('day', datetime_bin) order by counts_15min.api_id),2),2) speed_Ave_abs
from counts_15min inner join  locations on counts_15min.api_id=locations.api_id
where datetime_bin>='2019-12-17 00:00:00' and   datetime_bin<'2019-12-18 00:00:00'

**Comment by Parvanehemati** [comment]
To get what is the speed_id for 75% or 50%, I used a formula I describe it in the function speed_percentage(api integer,
    perc integer,
    stime1 timestamp with time zone,
    stime2 timestamp with time zone)   perc is variable for 50% it has to be 50 
70% it has to be 70 and ....
query to use the function:
select api_id,speed_percentage(api_id, 50, '2019-12-17 00:00:00',  '2019-12-17 01:00:00') from locations  limit 10
