### ISSUE TITLE
Create lookup table for WYS signs

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#255]
Create a lookup table to identify whether a sign is permanent, mobile, or dummy. This can be done (as per Mateen) using the sign_name.

Use regular expressions to do this, documentation here: https://www.postgresql.org/docs/9.3/functions-matching.html

Permanent signs: street name   direction   sign number
Mobile signs: ward number - two-character alphanumeric
Dummy: two-character alphanumeric

Task: Create and populate table `signs` with following table definition:

`api_id` - unique identifier based on `wys.locations`
`sign_name` - based on `sign_name` on `wys.locations`. Should be unique - verify that it is.
`type` - "mobile", "permanent", OR "dummy"
`last_known_location` based on latest `start_date` in `wys_locations` for that `api_id`

**Comment by Parvanehemati** [comment]
Created table signs, These queries are for adding values from table locations to signs table
--------------------------------------------- Permanent locations-------------------------------
with select_perm AS( select ROW_NUMBER() over (partition by api_id order by start_date desc ) rr,api_id,start_date,sign_name   from locations  where (Length(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})'))>'3')  order by api_id--,start_date desc
)
INSERT INTO signs(api_id, sign_name,type,last_known_location)
select api_id,sign_name,'Permanent', start_date from select_perm where rr=1

--------------------------------------------- Mobile locations--------------------------------
with select_mob AS(
 select ROW_NUMBER() over (partition by api_id order by start_date desc ) rr,api_id,start_date,sign_name   from locations  where  (sign_name ~ 'Ward') order by api_id
)

INSERT INTO signs(api_id, sign_name,type,last_known_location)
select api_id,sign_name,'Mobile', start_date from select_mob where rr=1

---------------------------------------- Dummy locations------------------------------------
with select_dummy AS(
 select ROW_NUMBER() over (partition by api_id order by start_date desc ) rr,api_id,start_date,sign_name   from locations  where  ((sign_name ~ E'(A)\\d{1}') or (sign_name ~ E'(F)\\d{1}')) order by api_id
)

select rr, start_date,api_id,sign_name  from select_dummy where rr=1
INSERT INTO signs(api_id, sign_name,type,last_known_location)
select api_id,sign_name,'Dummy', start_date from select_dummy where rr=1 and api_id not in(select s1.api_id from locations as s1 inner join locations as s2 on s1.api_id=s2.api_id
 where  ((s1.sign_name ~ E'(A)\\d{1}') or (s1.sign_name ~ E'(F)\\d{1}')) and
(Length(SUBSTRING(reverse(s2.sign_name), '([0-9]{1,8})'))>'3') and s1.api_id=s2.api_id )

--------------------------------------------------------------------------------------------------------
---Query to find common api_id  locations between Permanent and Mobile locations-------------
----------------------------------------------------------------------------------------------
select  s1.api_id,s1.sign_name ,s2.api_id,s2.sign_name   from locations as s1 inner join locations as s2 on s1.api_id=s2.api_id
 where  ((s1.sign_name ~ E'(A)\\d{1}') or (s1.sign_name ~ E'(F)\\d{1}')) and
(Length(SUBSTRING(reverse(s2.sign_name), '([0-9]{1,8})'))>'3') and s1.api_id=s2.api_id  order by s1.api_id

**Comment by aharpalaniTO** [comment]
@Parvanehemati a couple of quick changes/asks:
1. Modify last_know_location to be the actual geometry as opposed to the date
2. Match to nearest location based on `wyss_locations` (using your previous work on this) in a seperate query, plot on map

**Comment by Parvanehemati** [comment]
Added two columns to signs table
shape_api  (value comes from locations table)
shape_wys (value comes from safety_locations table)
