### ISSUE TITLE
Link Mobile WYS Location data to the wys.locations api_id

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#260]
In the `wys.locations` table, mobile signs are identified by the following pattern in the `sign_name` column `Ward [WARD NUMBER] - S [SIGN NUMBER]`. These numbers should correspond with the ward number and the sign number from the spreadsheets. Attempt to join them using this composite string so that we can link one `api_id` to every mobile sign installation, which we will need in order to attach location information on mobile signs to the speed data.

**Comment by radumas** [comment]
For cases where the `api_id` changes over time for a given `sign_name`, once the speed data is aggregated, we can create ranges for when each row in the `locations` table was active.

**Comment by jovenc** [comment]
`sign_name` of 'Ward 3 - S5' has changing api_id of '7605' to '23784'
`sign_name` of 'Ward 5 - S8' has changing api_id of '8335' to '24854'

**Comment by jovenc** [comment]
See `wys.mobile_api_id` to link mobile WYS signs to their `api_id`.

**NOTE:** Mobile WYS data for ward 5, 8, 14, 15 and 20 is not available yet while the duplicates issue is being resolved

**Comment by radumas** [comment]
@jovenc you were gonna transform this into a VIEW correct?

**Comment by jovenc** [comment]
`wys.mobile_api_id` is already a view 😃
