### ISSUE TITLE
WYS Open Data Format

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#261]
## Mobile Signs

Mobile signs move every 3 weeks. Since we don't have a geometry associated with them, I don't think it makes sense to have a separate location table for them 

### Mobile Sign Summary

Field Name | Description | Notes
|-----------|-------------|-------|
ward_no| integer | Ward number|
location| text | Street where the sign was installed |
from_street| text | Intersection from which vehicles would travel past this sign  |
to_street| text | Intersection to which vehicles would travel past this sign |
direction| text | Cardinal direction of travel (e.g. NB = North Bound) |
installation_date| date | Date the sign was installed|
removal_date| date | Date the sign was removed |
min_speed | integer | Speed at which the sign begins to display a speed
speed_limit | integer | Device setting for the speed limit
flash_speed | integer | Device setting for speed at which digits flash
strobe_speed | integer | Device setting for speed at which strobes start
schedule | text | Times of week when the sign is on. (e.g.: Weekdays from 9 AM - 9PM)
pct_5 | integer | _5th percentile speed observed at this location while the sign was installed
pct_10 | integer | 10th percentile speed observed at this location while the sign was installed
pct_15 | integer | 15th percentile speed observed at this location while the sign was installed
pct_20 | integer | 20th percentile speed observed at this location while the sign was installed
pct_25 | integer | 25th percentile speed observed at this location while the sign was installed
pct_30 | integer | 30th percentile speed observed at this location while the sign was installed
pct_35 | integer | 35th percentile speed observed at this location while the sign was installed
pct_40 | integer | 40th percentile speed observed at this location while the sign was installed
pct_45 | integer | 45th percentile speed observed at this location while the sign was installed
pct_50 | integer | 50th percentile speed observed at this location while the sign was installed
pct_55 | integer | 55th percentile speed observed at this location while the sign was installed
pct_60 | integer | 60th percentile speed observed at this location while the sign was installed
pct_65 | integer | 65th percentile speed observed at this location while the sign was installed
pct_70 | integer | 70th percentile speed observed at this location while the sign was installed
pct_75 | integer | 75th percentile speed observed at this location while the sign was installed
pct_80 | integer | 80th percentile speed observed at this location while the sign was installed
pct_85 | integer | 85th percentile speed observed at this location while the sign was installed
pct_90 | integer | 90th percentile speed observed at this location while the sign was installed
pct_95 | integer | 95th percentile speed observed at this location while the sign was installed
count | integer | total number of vehicles observed while sign was installed

### Mobile Sign Disaggregate

Field Name | Description | Notes
|-----------|-------------|-------|
ward_no| integer | Ward number|
location| text | Street where the sign was installed |
from_street| text | Intersection from which vehicles would travel past this sign  |
to_street| text | Intersection to which vehicles would travel past this sign |
direction| text | Cardinal direction of travel (e.g. NB = North Bound) |
datetime_bin | timestamp | Hour during which these observations were made |
speed_bin | integer range | Range of speeds observed (e.g. [10,20) represents speeds from 10km/hr up to and not including 20 km/hr) |
volume | integer | Number of vehicles observed in that hour and speed bin |

**Comment by radumas** [comment]
## Stationary Signs

Stationary signs don't move. We have geometry data for them. 

### Sign Locations

If task 3 of #245 reveals that locations of stationary `api_id` change over time... we should consider changing the id to be unique per stationary sign installation/location 

Field Name | Description | Notes
|-----------|-------------|-------|
api_id | integer | unique identifier for the sign's location  |
address | text | Address of the sign |
dir | text |Cardinal direction of travel (e.g. NB = North Bound) |
start_date | date | Date sign started reporting data|
end_date | date | Date sign stopped reporting data|
speed_limit | integer | Speed limit at the device's location
speed_limit_device | integer | Device setting for the speed limit
tolerated_speed| integer | Device setting for speed 
flash_speed | integer | Device setting for speed at which digits flash
strobe_speed | integer | Device setting for speed at which strobes start
geom | geometry | location of the sign |

### Stationary Watch Your Speed Summary 

- Same as mobile signs?
- Should there just be one "big"  summary file?

### Stationary WYS Detailed

With current 1hr bins and 10km/hr bins, monthly extracts of permanent data only would be ~1.3M rows, not quite openable in Excel. Should we break them out by ward instead?

Field Name | Description | Notes
|-----------|-------------|-------|
ward_no| integer | Ward number|
location| text | Street where the sign was installed |
from_street| text | Intersection from which vehicles would travel past this sign  |
to_street| text | Intersection to which vehicles would travel past this sign |
direction| text | Cardinal direction of travel (e.g. NB = North Bound) |
datetime_bin | timestamp | Hour during which these observations were made |
speed_bin | integer range | Range of speeds observed (e.g. [10,20) represents speeds from 10km/hr up to and not including 20 km/hr) |
volume | integer | Number of vehicles observed in that hour and speed bin |

**Comment by jovenc** [comment]
`wys.sign_schedules_clean` is where you can get the sign_type, schedule, min_speed, speed_limit, flash_speed and strobe_speed based on `schedule_name`

**Comment by radumas** [comment]
## Mobile Summary

```sql
CREATE MATERIALIZED VIEW open_data.wys_mobile_summary as

SELECT ward_no, location, from_street, to_street, direction, installation_date, removal_date, 
percentile_cont(0.05) WITHIN GROUP (ORDER BY speed) pct_5,
percentile_cont(0.10) WITHIN GROUP (ORDER BY speed) pct_10,
percentile_cont(0.15) WITHIN GROUP (ORDER BY speed) pct_15,
percentile_cont(0.20) WITHIN GROUP (ORDER BY speed) pct_20,
percentile_cont(0.25) WITHIN GROUP (ORDER BY speed) pct_25,
percentile_cont(0.30) WITHIN GROUP (ORDER BY speed) pct_30,
percentile_cont(0.35) WITHIN GROUP (ORDER BY speed) pct_35,
percentile_cont(0.40) WITHIN GROUP (ORDER BY speed) pct_40,
percentile_cont(0.45) WITHIN GROUP (ORDER BY speed) pct_45,
percentile_cont(0.50) WITHIN GROUP (ORDER BY speed) pct_50,
percentile_cont(0.55) WITHIN GROUP (ORDER BY speed) pct_55,
percentile_cont(0.60) WITHIN GROUP (ORDER BY speed) pct_60,
percentile_cont(0.65) WITHIN GROUP (ORDER BY speed) pct_65,
percentile_cont(0.70) WITHIN GROUP (ORDER BY speed) pct_70,
percentile_cont(0.75) WITHIN GROUP (ORDER BY speed) pct_75,
percentile_cont(0.80) WITHIN GROUP (ORDER BY speed) pct_80,
percentile_cont(0.85) WITHIN GROUP (ORDER BY speed) pct_85,
percentile_cont(0.90) WITHIN GROUP (ORDER BY speed) pct_90,
percentile_cont(0.95) WITHIN GROUP (ORDER BY speed) pct_95,
COUNT(1) as count
	FROM wys.mobile_api_id loc
	INNER JOIN wys.raw_data raw ON loc.api_id = raw.api_id AND datetime_bin >= installation_date and datetime_bin < removal_date
	GROUP BY ward_no, location, from_street, to_street, direction, installation_date, removal_date
```

## Mobile Detailed

```sql
CREATE VIEW open_data.wys_mobile_detailed_2019 AS
SELECT  ward_no, location, from_street, to_street, direction, datetime_bin, speed_bins::TEXT, volume
FROM wys.mobile_api_id loc
INNER JOIN wys.speed_counts_agg agg  ON loc.api_id = agg.api_id AND datetime_bin >= installation_date and datetime_bin < removal_date
INNER JOIN wys.speed_bins USING (speed_id)
```

**Comment by radumas** [comment]
I need to think about this one for longer. Dealing with the "stationary" locations is a bit more complex.

```sql

DO $do$
DECLARE
	startdate DATE;
	yyyymm TEXT;
	basetablename TEXT := 'wys_stationary_detailed_';
	tablename TEXT;
BEGIN

	for yyyy IN 2019..2020 LOOP
		FOR mm IN 01..12 LOOP
			startdate:= to_date(yyyy||'-'||mm||'-01', 'YYYY-MM-DD');
			IF mm < 10 THEN
				yyyymm:= yyyy||'0'||mm;
			ELSE
				yyyymm:= yyyy||''||mm;
			END IF;
			tablename:= basetablename||yyyymm;
			EXECUTE format($$CREATE VIEW open_data.%I AS
						   direction, datetime_bin, speed_bin::TEXT, volume
				FROM wys.locations loc
				INNER JOIN wys.speed_counts_agg agg  ON loc.api_id = agg.api_id AND (Length(SUBSTRING(reverse(locations.sign_name), '([0-9]{1,8})'))>'3')
						   							 AND datetime_bin >= installation_date and datetime_bin < removal_date
				INNER JOIN wys.speed_bins USING (speed_id)
				WHERE datetime_bin >= '2019-01-01' AND datetime_bin < '2019-01-01'::DATE + INTERVAL '1 year'

```

**Comment by radumas** [comment]
This has 76 fewer rows than `wys.stationary_signs`, worth having a look....

```sql
CREATE MATERIALIZED VIEW open_data.wys_stationary_locations AS

SELECT sign_id, address, sign_name, dir, schedule, 
    min_speed, 
    speed_limit, 
    flash_speed, 
    strobe_speed, 
	CASE WHEN prev_start IS NOT NULL THEN start_date ELSE MIN(datetime_bin) END AS start_date,
	LEAST(next_start, MAX(datetime_bin)) AS end_date,
	geom
	FROM wys.stationary_signs
	JOIN wys.sign_schedules_list USING (api_id)
     JOIN wys.sign_schedules_clean USING (schedule_name)
	 JOIN wys.speed_counts_agg USING (api_id) 
	 GROUP BY sign_id, address, sign_name, dir, schedule, 
    min_speed, 
    speed_limit, prev_start,next_start, start_date,
    flash_speed, 
    strobe_speed, geom
```

**Comment by radumas** [comment]
I need to update the `open_data.wys_stationary_locations` so that the sign end dates can be NULL if the sign is still in operation and the start date is `2019-01-01` until we get info on previous years locations.

**Comment by jovenc** [comment]
The 76 fewer rows in `open_data.wys_stationary_locations` which are 
```
SELECT X.* 
FROM wys.stationary_signs X
LEFT JOIN open_data.wys_stationary_locations Y
USING (sign_id)
WHERE Y.sign_id IS NULL
```
76 `api_id` **NOT** included in open_data are
(375,1745,1845,2350,3774,3783,4038,4671,4677,5294,
 8529,9780,10245,10288, 10289,10292,10293,10301,10302,10437,
 10438,10440,10441,10457,10458,10459,10460,10461,10461,10462,
 10467,10468,10470,10473,10495,10496,10497,10503,10508,10509,
 10517,10518,10527,10528,10529,10531,10532,10534,10537,10539,
 10540,10552,10553,10554,10557,10558,10765,10765,10766,10766,
 10768,11569,11570,11571,11572,11573,11574,13095,22776,23322,
 23323,23326,23339,23548,24999,26319)

Of those 76 `api_id`, 
- 56 of them has speed data from `wys.speed_counts_agg` which are 
(10288,10289,10292,10293,10301,10302,10437,10438,10440,10441,
 10457,10459,10460,10461,10462,10467,10468,10470,10473,10495,
 10496,10497,10503,10508,10509,10517,10518,10527,10528,10529,
 10531,10532,10534,10537,10539,10540,10552,10553,10554,10557,
 10558,10765,10766,10768,11569,11570,11571,11572,11573,11574,
 13095,23322,23323,23326,23339,23548)
- whereas 3 of them has repeated rows which are
(10461,10765,10766)
- and 17 of them without speed data which are
(375,1745,1845,2350,3774,3783,4038,4671,4677,5294,
8529,9780,10245,10458,22776,24999,26319).

Of the 17 without speed data, 
- 13 was found in `wys.sign_schedules_list` which are (375,1745,1845,2350,3774,3783,4038,4671,4677,5294,
8529,9780,10245)
- whereas 4 are not on the list and has no speed data which are
(10458,22776,24999,26319)
