### ISSUE TITLE
Update and Validate Speed Limit Layer using new bylaw info

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#265]
Revisit Chelsea's process and run speed limit layer update

**Comment by jovenc** [comment]
More information [here](https://www.notion.so/bditto/2020-02-18-Speed-Limit-Layer-Update-Process-b1029cea06f34052ad411b71303aac8d) on Notion.

**Comment by jovenc** [comment]
Putting steps taken / queries used to find out the 
- new bylaws
- 'disappeared' bylaws
- bylaws that were repealed and then added or vice versa 

onto this [Notion page](https://www.notion.so/bditto/Update-Speed-Limit-Layer-68aa59b0af294d09a5e470be83dacf8c).

**Comment by jovenc** [comment]
Links to github documentation about speed limit layer [here](https://github.com/CityofToronto/bdit_data-sources/tree/text_to_centreline/gis/bylaw_text_to_centreline)

**Comment by jovenc** [comment]
With `jchew.bylaws_2019` as **Table A** and `jchew.bylaws_2020` as **Table B**, categorized them into 3 different groups: 

1. Group 1: records that was disappeared in table B 
(IDs : 253,588,1607,1962,1963,2133,2613,3337,3471,3741,4262)
```
SELECT a.* FROM jchew.bylaws_2019 a
LEFT JOIN jchew.bylaws_2020 b
USING (id)
WHERE b.id IS NULL
```

2. Records in A that have been changed in B
- 2a. `WHERE deleted = true` and has new record in B that is related —> change speed limit in table `jchew.bylaws_speed_changed` 
(63 pairs of those where the speed limit has changed from table A to table B)
```
--containing all the changes
CREATE TABLE jchew.bylaws_speed_changed AS 
SELECT * FROM jchew.bylaws_2020 
JOIN 
(
SELECT highway, between, count(*) 
	FROM jchew.bylaws_2020
	GROUP BY highway, between
	HAVING COUNT(*) >1
	) a
USING (highway, between) 
ORDER BY highway, between, id

--the actual ones where either one of the paired has id > 6561
--return 126 rows
CREATE TABLE jchew.bylaws_speed_changed_2020 AS
SELECT * FROM jchew.bylaws_2020 
JOIN 
(
SELECT highway, between, count(*) 
	FROM jchew.bylaws_2020
	GROUP BY highway, between
	HAVING COUNT(*) >1 AND MAX(id) > 6561
	) a
USING (highway, between) 
ORDER BY highway, between, id
```

- 2b. `WHERE deleted = true` and does not have new record in B —> set speed limit to 50km/h
(has 908 rows where only 3 rows are from table B)
```
SELECT * FROM jchew.bylaws_2020 
WHERE deleted = true
AND id NOT IN (SELECT id FROM jchew.bylaws_speed_changed)
ORDER BY id
```

3. Completely new records in B, stored in `jchew.bylaws_new`
(352 rows of completely new bylaws)
```
--create a table for those that need to be geocoded
CREATE TABLE jchew.bylaws_new AS
SELECT * FROM jchew.bylaws_2020 
WHERE deleted = false
AND id > 6561
AND id NOT IN (SELECT id FROM jchew.bylaws_speed_changed)
ORDER BY id
```

**Comment by jovenc** [comment]
Funnies to send back to Andrew are:

1. The 11 id's that disappeared in table 2020 
**(id = 253, 588, 1607, 1962, 1963, 2133, 2613, 3337, 3471, 3741, 4262)**
Found using group 1 query as shown above, with results as shown below.
![image](https://user-images.githubusercontent.com/54872846/75699469-8548d900-5c7e-11ea-87da-8fb1c16a97d3.png)

2. The 1 id where `deleted = true` got switched to `deleted = false` in 2020 
**(id=1)**
```
SELECT a.* FROM 
(SELECT * FROM jchew.bylaws_2019
WHERE deleted = true) a
LEFT JOIN
(SELECT * FROM jchew.bylaws_2020
WHERE deleted = true) b
USING (id)
WHERE b.id IS NULL
```

3. The 2 id's where deleted = false but stated as repealed in bylaw 
**(id = 6565 and 6566)**
```
SELECT * FROM jchew.bylaws_2020 
WHERE deleted = false
AND id > 6561
AND id NOT IN (SELECT id FROM jchew.bylaws_speed_changed) 
AND bylaw_no LIKE '%Repealed%'
ORDER BY id
```
![image](https://user-images.githubusercontent.com/54872846/75699742-ee305100-5c7e-11ea-9e9d-2aecbf22526a.png)

**Comment by jovenc** [comment]
Match table A and table B using all columns except `city`, `deleted` and `bylaw_no`. Found 19 rows but 14 of them disappeared in table B and so after excluding those 14 rows, found 8 rows where `highway` and `between` columns have slight differences as shown below.
```
SELECT a.* FROM jchew.bylaws_2019 a
LEFT JOIN
(SELECT * FROM jchew.bylaws_2019 
INNER JOIN
(SELECT * FROM jchew.bylaws_2020
WHERE id <= 6561) b
USING (id, chapter, schedule, schedule_name, highway, between, speed_limit_km_per_h)
) c
USING (id)
WHERE c.id IS NULL

--from the results above
SELECT * FROM jchew.bylaws_2020
WHERE id IN (253,533,588,1093,1430,1607,1962,1963,2133,2459,
			 2613,2835,3337,3471,3741,4262,4747,5878,6053)
--eliminate disappeared ones
AND id NOT IN (253,588,1607,1962,1963,2133,2613,3337,3471,3741,4262)
```
Table A:
![image](https://user-images.githubusercontent.com/54872846/75700067-7e6e9600-5c7f-11ea-857f-783476cc4f56.png)

Table B (with the differences being highlighted):
![image](https://user-images.githubusercontent.com/54872846/75700086-84fd0d80-5c7f-11ea-9739-4bac5a5b1694.png)

Did some manual update to fix the above
```
--Do some manual fix to fix the typo etc
UPDATE jchew.bylaws_2020 SET speed_limit_km_per_h = 40 WHERE id = 533;

UPDATE jchew.bylaws_2020 SET between = 'Millwood Road and Fleming Crescent(north intersection)'
WHERE id = 1093;

UPDATE jchew.bylaws_2019 SET between = 'George Henry Boulevard (south side) and Parkway Forest Drive (south intersection)'
WHERE id = 1430 ;

UPDATE jchew.bylaws_2019 SET highway = 'Marcos Boulevard' WHERE id = 2459 ;

UPDATE jchew.bylaws_2020 SET highway = 'Oxford Street' WHERE id = 2835 ;

--Neither Albermarle nor Albermale is right
UPDATE jchew.bylaws_2019 SET highway = 'Albemarle Avenue' WHERE id = 4747 ;
UPDATE jchew.bylaws_2020 SET highway = 'Albemarle Avenue' WHERE id = 4747 ;

UPDATE jchew.bylaws_2020 SET highway = 'Windsor Street' WHERE id = 5878 ;

UPDATE jchew.bylaws_2019 SET highway = 'Valifor Place' WHERE id = 6053 ;
```

> Technically, 2019 and 2020 sheets are all the same for ID up till 6561 except for the 11 'disappeared' ones. And so I'm just gonna use the 2020 one aka jchew.bylaws_2020

**Comment by jovenc** [comment]
Steps taken to prepare version 1, after #268 is incorporated into the big function.
1. Make a copy of the current table and update the COPY table
```
SELECT * INTO jchew.bylaws_updated FROM crosic.tcl_speed_limit_aug292019
```
2. Results of geocoding and pgrouting using the updated `text_to_centreline()` function for new bylaws
```
--took 5 min, return 338 rows
CREATE TABLE jchew.bylaws_routing1 AS
SELECT bylaws_new.*, results.*
FROM jchew.bylaws_new, 
LATERAL jchew.text_to_centreline_updated(
bylaws_new.highway,
bylaws_new.between,
NULL
) as results

--checking results
SELECT id, highway, between, speed_limit_km_per_h, int1, int2,
con, notice, ST_Union(ST_LineMerge(line_geom)) AS centreline_geom 
	FROM jchew.bylaws_routing1
GROUP BY id, highway, between, speed_limit_km_per_h, int1, int2, con, notice
ORDER BY id
```
3. Dealing with group 3 (completely new bylaws)
```
--UPDATED 2212 rows
UPDATE jchew.bylaws_updated a
SET speed_limit = b.speed_limit_km_per_h, 
confidence = b.con, 
bylaw_id = b.id, 
bylaw_streetname = b.highway, 
bylaw_extents = b.between
FROM jchew.bylaws_routing1 b

WHERE a.objectid = b.objectid
AND a.objectid NOT IN 
(SELECT objectid
FROM jchew.bylaws_updated
GROUP BY objectid
HAVING count (objectid) >1)
```
4. Dealing with group 2b (`deleted = true`)
```
--updated 1447 rows
UPDATE jchew.bylaws_updated a
SET speed_limit = 50,
confidence = NULL,
bylaw_id = NULL,
bylaw_streetname = NULL,
bylaw_extents = NULL
FROM 
(SELECT * FROM jchew.bylaws_2020 
WHERE deleted = true
AND id NOT IN (SELECT id FROM jchew.bylaws_speed_changed)
ORDER BY id) b
WHERE a.bylaw_id = b.id
```
5. Dealing with group 2a (speed limit updated)
```
--updated 142 rows
UPDATE jchew.bylaws_updated a
SET speed_limit = b.new_spd,
bylaw_id = b.new_id
FROM 
(SELECT c.id, c.speed_limit_km_per_h as old_spd, d.id as new_id, d.speed_limit_km_per_h as new_spd 
 FROM (SELECT * FROM jchew.bylaws_speed_changed_2020 WHERE id <= 6561) c 
 INNER JOIN 
 (SELECT * FROM jchew.bylaws_speed_changed_2020 WHERE id > 6561) d 
USING (highway, between)) b
WHERE a.bylaw_id = b.id
```

There are still missing 14 new bylaws as those are the special ones. This issue is currently being tackled at #270 .
