### ISSUE TITLE
Automate refreshing MATERIALIZED VIEWS

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#266]
The airflow process should trigger updating these on the same schedule as OpenData pulls.

- [x] `wys.mobile_api_id`
- [x] `wys.stationary_signs`
- [x] `open_data.wys_stationary_locations`
- [x] run `wys.mobile_summary_for_month(_mon date)`
- [x] run `wys.stationary_summary_for_month(date)`

**Comment by radumas** [comment]
OpenData will be pulling this at 5 A.M. on the 2nd day of each month.

**Comment by candu** [comment]
@radumas not sure whether you're already making use of this, but: if you provide a `UNIQUE` index on your `MATERIALIZED VIEW`, you can `REFRESH MATERIALIZED VIEW CONCURRENTLY` and then people can `SELECT` from the view as it updates 😲

**Comment by radumas** [comment]
I knew this but hadn't thought of it for this application. I will incorporate so that someone accessing a view doesn't lock up the airflow process.

**Comment by radumas** [comment]
Tested and it works!

**Comment by radumas** [comment]
For some reason the schedule isn't working...
