### ISSUE TITLE
Add date when speed limit was last changed to speed limit layer

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#277]
Please add a field, `date_sl_changed`, to describe when that segment last changed its speed limit as per the bylaw.

Example code:
```
SELECT A.*, substring(bylaw_no FROM '[0-9]{4}-[0-9]{2}-[0-9]{2}')::date AS date_sl_changed
FROM jchew.bylaws_updated A
LEFT JOIN (SELECT * FROM jchew.bylaws_2020 WHERE bylaw_no IS NOT NULL AND bylaw_no LIKE '%Added%') B ON A.bylaw_id = B.id
```

**Comment by jovenc** [comment]
Create a table to separate the elements in `bylaw_no` ie 'Added 2019-10-28', 'Repealed 2020-01-15' into `added` and `repealed` columns. A bylaw_id which has more than one elements in the array will have multiple rows. After that, separate the dates from `added` and `repealed` columns and put them into `added_date` and `repealed_date` columns.
```
CREATE TABLE jchew.bylaws_2020_dates_column AS 
WITH ind AS (
SELECT id, deleted, bylaw_no, unnest(regexp_split_to_array(bylaw_no, '(?=\[)')) AS individual,
highway, between, speed_limit_km_per_h
FROM jchew.bylaws_2020
),
sep AS (
SELECT id, deleted, bylaw_no, 
substring(individual FROM 'Added [0-9]{4}-[0-9]{2}-[0-9]{2}') AS added,
substring(individual FROM 'Repealed [0-9]{4}-[0-9]{2}-[0-9]{2}') AS repealed,
highway, between, speed_limit_km_per_h
FROM ind
)
SELECT id, deleted, bylaw_no, 
added, substring(added FROM '[0-9]{4}-[0-9]{2}-[0-9]{2}')::date AS added_date,
repealed, substring(repealed FROM '[0-9]{4}-[0-9]{2}-[0-9]{2}')::date AS repealed_date,
highway, between, speed_limit_km_per_h
FROM sep
```

**Comment by jovenc** [comment]
Added the `date_changed` column to the updated speed limit layer. Now in `jchew.bylaws_updated_with_date` .
```
CREATE TABLE jchew.bylaws_updated_with_date AS
SELECT A.*, B.added_date AS date_changed
FROM jchew.bylaws_updated A
LEFT JOIN (SELECT * FROM jchew.bylaws_2020_dates_column 
		   WHERE deleted = false AND bylaw_no LIKE '%Added%') B 
ON A.bylaw_id = B.id
```

**Comment by jovenc** [comment]
Note the 6 weird bylaws that I found by running the below query WHERE there's a 'Repealed' text in the `bylaw_no` but `deleted` = false? They were repealed but not deleted yet? 

![image](https://user-images.githubusercontent.com/54872846/78368275-639a8480-7591-11ea-8d2c-98ba2f6532f0.png)

**Comment by jovenc** [comment]
Created a table where every bylaw only has a single row with both `added_date` and `repealed_date` 
```sql
--only id=302 repealed twice
CREATE VIEW jchew.bylaws_added_repealed_dates AS
WITH 
added AS ( 
--2907 rows
SELECT id, bylaw_no, substring(bylaw_no FROM 'Added [0-9]{4}-[0-9]{2}-[0-9]{2}') AS added_detail
	FROM jchew.bylaws_2020
	WHERE bylaw_no LIKE '%Added%'	
),
repealed AS (
--1696 rows
SELECT id, bylaw_no, substring(bylaw_no FROM 'Repealed [0-9]{4}-[0-9]{2}-[0-9]{2}') AS repealed_detail
	FROM jchew.bylaws_2020
	WHERE bylaw_no LIKE '%Repealed%'
)
SELECT law.id, law.deleted, law.bylaw_no, 
substring(added.added_detail FROM '[0-9]{4}-[0-9]{2}-[0-9]{2}')::date AS added_date,
substring(repealed.repealed_detail FROM '[0-9]{4}-[0-9]{2}-[0-9]{2}')::date AS repealed_date,
law.highway, law.between, law.speed_limit_km_per_h
FROM jchew.bylaws_2020 law
LEFT JOIN added USING (id)
LEFT JOIN repealed USING (id)
ORDER BY id

```

The result table looks like below. A small thing to note (highlighted below) is that `bylaw_id =302` got repealed twice but my query above only returned the first repealed_date which kinda make more sense too.
![image](https://user-images.githubusercontent.com/54872846/79802636-540b9180-832e-11ea-938e-ef8d19082d8b.png)
