### ISSUE TITLE
Find ten candidate WYS locations for doing ATR counts

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#282]
We want to determine how well the WYS sensors correlate with traffic volumes, so we want to identify locations where we can perform ATR counts in the coming weeks.

Looking at:
- stationary sensors only, 
- which seem to still be active

Determine the top 10 signs where the ratio of hourly 7AM-10PM ~Weekday~ Tuesday-Thursday volumes seem consistent with past ATR counts at that location. `prj_volume.centreline_volumes` seems like a good source of ATR data until further notice, and you can use `wys.stationary_signs` and `wys.speed_counts_agg_5kph` for hourly counts. So something like the top ten locations by `stddev(wys.volume/centreline.volume) GROUP BY sign` https://devdocs.io/postgresql~9.6/functions-aggregate#stddev

**Comment by aharpalaniTO** [comment]
This looks good. `centreline_volumes` is a bit messy for this application but I can create a view that's clean for this application. Does hourly volumes tagged to the centreline work?

**Comment by aharpalaniTO** [comment]
I would also limit the analysis to Tuesday-Thursday since that's consistent with how our past ATR volumes were typically collected.

**Comment by radumas** [comment]
> 
> 
> This looks good. `centreline_volumes` is a bit messy for this application but I can create a view that's clean for this application. Does hourly volumes tagged to the centreline work?

Yeah that should be good. So I guess the thing would then be to find the closest centreline to every stationary `wys.location` and then see if there's an ATR there.

**Comment by aharpalaniTO** [comment]
yup, while ensuring that it's on the same street and tracking the same direction

**Comment by aharpalaniTO** [comment]
Hourly volumes tagged to the centreline located here:  `prj_volume.hourly_atr_counts`


Definition of view is as follows:
```
CREATE MATERIALIZED VIEW prj_volume.hourly_atr_counts AS 

WITH last_dates AS (
	SELECT arterycode, MAX(count_date) AS max_date, MAX(count_date)
	FROM traffic.countinfo
	WHERE EXTRACT(isodow FROM count_date) IN (2,3,4)
	GROUP BY arterycode
),

valid_dates AS (
	SELECT arterycode, count_info_id, count_date
	FROM last_dates
	INNER JOIN traffic.countinfo USING (arterycode)
	WHERE count_date >= (max_date - INTERVAL '6 DAYS') AND EXTRACT(isodow FROM count_date) IN (2,3,4)
	GROUP BY arterycode, count_info_id, count_date
),

hourly_volumes AS (
	SELECT arterycode, count_info_id, count_date, date_trunc('hour',timecount)::time without time zone AS hr_bin, SUM(count) AS volume
	FROM valid_dates
	INNER JOIN traffic.cnt_det USING (count_info_id)
	GROUP BY arterycode, count_info_id, count_date, date_trunc('hour',timecount)::time without time zone
)

SELECT arterycode, centreline_id, direction, location, array_agg(DISTINCT count_date) AS count_dates, hr_bin, AVG(volume) AS hr_volume
FROM hourly_volumes A
INNER JOIN prj_volume.artery_tcl B USING (arterycode)
INNER JOIN traffic.arterydata C USING (arterycode)
GROUP BY arterycode, centreline_id, direction, location, hr_bin
```

**Comment by jovenc** [comment]
Steps to find the top ten locations:

- [ ] Link every api_id from `wys.stationary_signs` to the closest centreline from `gis.centreline_directional`

- [ ] Check and see if there's an ATR at that centreline with ATR from `prj_volume.hourly_atr_counts`

- [ ] Aggregate wys speeds bin from `wys.speed_counts_agg_5kph` to hourly and filter out Tuesday-Thursday as well as 7am-10pm

- [ ] Find the ratio of WYS hr_volume to ATR hr_volume from 7am to 10 pm

- [ ] Using `stddev(hr_volume) GROUP BY arterycode` for the ratio found, determine the top 10 locations

**Comment by jovenc** [comment]
```
CREATE TABLE jchew.wys_signs_nearest_centrelines AS 
SELECT
  wys.*,
  atr.*,
  ST_Distance(ST_Transform(wys.wys_geom,2952), ST_Transform(atr.atr_geom,2952)) AS diff
FROM
(SELECT api_id, sign_id, address, sign_name, dir AS wys_dir, start_date, next_start, prev_start, geom AS wys_geom
FROM wys.stationary_signs
) wys

CROSS JOIN LATERAL

(SELECT centreline_id, linear_name_full, geom AS atr_geom, dir AS atr_dir
FROM gis.centreline_directional
ORDER BY 
ST_Transform(wys.wys_geom,2952) <-> ST_Transform(geom,2952)
LIMIT 1) atr

ORDER BY diff
```
only four locations have the difference in distance > 100 and those are outliers as they are located outside the city of Toronto boundary

**Comment by jovenc** [comment]
```
SELECT b.*, a.api_id, a.sign_id, a. address, a.sign_name, a.wys_dir, a.start_date, a.wys_geom, a.atr_geom, a.diff
FROM jchew.wys_signs_nearest_centrelines a
LEFT JOIN (SELECT DISTINCT centreline_id, direction, location FROM prj_volume.hourly_atr_counts) b
USING (centreline_id)
WHERE a.wys_dir = gis.twochar_direction(b.direction)
```
Found 248 of them which have ATR data (technically 245 rows after taking into consideration those stated below)
**Note: single centreline having two directions for both the WYS and ATR is counted as 2 different rows**

(centreline_id = 7667011 has api_id of 9655 tied to it twice because the sign_id for WYS sign at that location changes)
(centreline_id = 106693 appeared three times because its `location` column which is the name of the street got changed slightly)

**Comment by jovenc** [comment]
From the query below, found (ONLY?) 20 ATR locations that are associated to WYS stationary signs locations.
```
WITH X AS(
SELECT arterycode, centreline_id, location, hr_bin, hr_volume
FROM prj_volume.hourly_atr_counts
WHERE centreline_id IN (SELECT api_id FROM jchew.wys_signs_atr)
AND hr_bin BETWEEN '07:00:00' AND '21:59:59'
ORDER BY arterycode, centreline_id
	)
SELECT arterycode, centreline_id, location, stddev(hr_volume) 
FROM X
GROUP BY arterycode, centreline_id, location
ORDER BY stddev
```
Will aggregate the WYS signs speed_bin that are associated to those 20 centrelines

**Comment by jovenc** [comment]
My apologies, did not take into consideration the ATR and WYS direction. Found 246 locations instead after matching both the centreline_id and direction (and even location)
```
SELECT a.arterycode, a.centreline_id, a.direction, a.location, b.centreline_id, b.direction, b.api_id, b.location
FROM prj_volume.hourly_atr_counts a
JOIN jchew.wys_signs_atr b
USING (centreline_id, direction, location)
GROUP BY a.arterycode, a.centreline_id, a.direction, a.location, b.centreline_id, b.direction, b.api_id, b.location
ORDER BY a.centreline_id
```
Only the highlighted below are the weird ones where the same location with the same centreline_id and direction appear four times.
![image](https://user-images.githubusercontent.com/54872846/76992576-d8c75200-6921-11ea-8ef0-05e52d149304.png)

**Comment by jovenc** [comment]
Aggregated WYS volume based on the api_id found above

**Comment by jovenc** [comment]
Calculated the standard deviation of ratio of ATR volume to WYS volume. Guess we can pick our top ten locations from here if need to? 
```
WITH atr AS (
SELECT arterycode, centreline_id, direction, location, count_dates, hr_bin, hr_volume 
FROM prj_volume.hourly_atr_counts
WHERE arterycode IN (SELECT arterycode FROM jchew.wys_matched_atr)
AND hr_bin BETWEEN '07:00:00' AND '21:59:59'
ORDER BY arterycode
)
, wys AS (
SELECT api_id, time_bin, sum
FROM jchew.wys_hr_bin_volume)
, combined AS (
SELECT lookup.api_id, lookup.arterycode, lookup.centreline_id, lookup.direction, lookup.location, 
count_dates, hr_bin, hr_volume, time_bin, sum, hr_volume/sum AS ratio 
FROM jchew.wys_matched_atr lookup
LEFT JOIN atr USING (arterycode)
LEFT JOIN wys ON lookup.api_id = wys.api_id AND atr.hr_bin = wys.time_bin
WHERE sum IS NOT NULL
ORDER BY api_id)
SELECT api_id, arterycode, centreline_id, direction, location,  stddev(ratio)
FROM combined
GROUP BY api_id, arterycode, centreline_id, direction, location 
ORDER BY stddev
```

**Comment by jovenc** [comment]
Find the top 10 locations within 5km buffer of these 3 points. Coordinates found on google map.
1. 703 Don Mills Road (43.709002, -79.333148)
2. Eastern Yard 
3. Kingston and Main (43.678908, -79.298012)

Steps:

- [ ] Find all `centreline_id` within the 5km buffer of the above 3 points using table `gis.centreline_directional`. Maybe also add a column to specify which point it is close too.

- [ ] Match the `centreline_id` found to table `jchew.wys_atr_full_list` to get the modified version of the top ten signs

**Comment by jovenc** [comment]
Find the top 10 locations within 5km buffer of these 3 points. Coordinates found on google map.
1. 703 Don Mills Road (43.709002, -79.333148)
2. Eastern Yard 
3. Kingston and Main (43.678908, -79.298012)

Steps:

- [ ] Find all `centreline_id` within the 5km buffer of the above 3 points using table `gis.centreline_directional`. Maybe also add a column to specify which point it is close too.

- [ ] Match the `centreline_id` found to table `jchew.wys_atr_full_list` to get the modified version of the top ten signs

**Comment by jovenc** [comment]
Using the query below, found 28 rows/WYS signs from `jchew.wys_atr_full_list` which are within 3km buffer from the 3 locations specified above.
```sql
WITH in_buffer AS 
(
SELECT centreline_id, linear_name_full, address_l, geom,
CASE WHEN ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326)
	, 2952), 3000), 4326)) = True
	THEN '703 Don Mills'
	WHEN ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326)
	, 2952), 3000), 4326)) = True
	THEN 'Eastern Yard'
	WHEN ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.298012, 43.678908), 4326)
	, 2952), 3000), 4326)) = True
	THEN 'Kingston and Main'
	END AS closer_to
FROM gis.centreline_directional
WHERE geom IN 
(SELECT geom
FROM gis.centreline_directional
WHERE (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326)
	, 2952), 3000), 4326)) = True )
OR (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326)
	, 2952), 3000), 4326)) = True )
OR (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.298012, 43.678908), 4326)
	, 2952), 3000), 4326)) = True )
	)
)
SELECT ful.*, in_buffer.closer_to
FROM jchew.wys_atr_full_list ful
LEFT JOIN in_buffer USING (centreline_id)
WHERE centreline_id IN (SELECT centreline_id FROM in_buffer)
ORDER BY stddev
```

**Comment by jovenc** [comment]
For some (unknown) reason, `jchew.wys_signs_nearest_centrelines ` is missing 46 signs? Added the missing ones using the query below.
```
INSERT INTO jchew.wys_signs_nearest_centrelines
SELECT
  wys.*,
  atr.*,
  ST_Distance(ST_Transform(wys.wys_geom,2952), ST_Transform(atr.atr_geom,2952)) AS diff
FROM
(SELECT api_id, sign_id, address, sign_name, dir AS wys_dir, start_date, next_start, prev_start, geom AS wys_geom
FROM wys.stationary_signs
WHERE api_id IN (SELECT api_id FROM wys.stationary_signs
WHERE api_id NOT IN (SELECT api_id FROM jchew.wys_stat_signs_speed_limit ))
) wys

CROSS JOIN LATERAL

(SELECT centreline_id, linear_name_full, geom AS atr_geom, dir AS atr_dir
FROM gis.centreline_directional gis
ORDER BY 
ST_Transform(wys.wys_geom,2952) <-> ST_Transform(gis.geom,2952)
LIMIT 1) atr

ORDER BY diff
```

**Comment by jovenc** [comment]
Find the top 10 locations within 5km buffer of these 3 points. Coordinates found on google map. Third location is changed. Also, the previous results return duplicates and so have to check that as well.

1. 703 Don Mills Road (43.709002, -79.333148)
2. Eastern Yard / 433 Eastern Ave (43.657195, -79.342935)
3. ~Kingston and Main (43.678908, -79.298012)~ 
3. Gerrard and Victoria Park (43.686923, -79.286623)

**Comment by jovenc** [comment]
To find more locations, within 5km buffer of the same 3 points above.
```
WITH in_buffer AS 
(
SELECT centreline_id, linear_name_full, address_l, geom,
CASE WHEN ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326), 2952))
	AND ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.286623, 43.686923), 4326), 2952))
	THEN '703 Don Mills'
	WHEN ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326), 2952))
	AND ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.286623, 43.686923), 4326), 2952))
	THEN 'Eastern Yard'
	WHEN ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.286623, 43.686923), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326), 2952))
	AND ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.286623, 43.686923), 4326), 2952)) < ST_Distance(ST_Transform(geom, 2952), ST_Transform(ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326), 2952))
	THEN 'Gerrard and Victoria Park'
	END AS closer_to
FROM gis.centreline_directional
WHERE geom IN 
(SELECT geom
FROM gis.centreline_directional
WHERE (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.333148, 43.709002), 4326)
	, 2952), 5000), 4326)) = True )
OR (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.342935, 43.657195), 4326)
	, 2952), 5000), 4326)) = True )
OR (ST_Within(geom
, ST_Transform(ST_Buffer(ST_Transform(
	ST_SetSRID(ST_MakePoint(-79.286623, 43.686923), 4326)
	, 2952), 5000), 4326)) = True )
	)
)
SELECT ful.*, in_buffer.closer_to
FROM jchew.wys_atr_full_list ful
LEFT JOIN in_buffer USING (centreline_id)
WHERE centreline_id IN (SELECT centreline_id FROM in_buffer)
ORDER BY stddev
```
Note: query takes about 17 min.

**Comment by jovenc** [comment]
Try to re-match WYS signs to closest centreline but the query has been running for more than 3 hours and is still not done yet. Will leave my query here for now. (Wondering if there's anything wrong with this query)
```
CREATE TABLE jchew.wys_signs_nearest_centrelines_check AS
SELECT
  wys.*,
  atr.*,
  ST_Distance(ST_Transform(wys.wys_geom,2952), ST_Transform(atr.atr_geom,2952)) AS diff
FROM
(SELECT api_id, sign_id, address, 
 sign_name, gis.abbr_street2(regexp_REPLACE(sign_name, ' (NB|SB|WB|EB)', '')) AS cleaned, 
 dir AS wys_dir, start_date, next_start, prev_start, geom AS wys_geom
FROM wys.stationary_signs
) wys
CROSS JOIN LATERAL
(SELECT centreline_id, gis.abbr_street2(linear_name_full), geom AS atr_geom, dir AS atr_dir
FROM gis.centreline_directional
WHERE levenshtein(TRIM(wys.cleaned), 
			TRIM(gis.abbr_street2(linear_name_full)), 1, 1, 1) < 5
ORDER BY 
ST_Transform(wys.wys_geom,2952) <-> ST_Transform(geom,2952),
 levenshtein(TRIM(wys.cleaned), 
			TRIM(gis.abbr_street2(linear_name_full)), 1, 1, 1)
LIMIT 1) atr
ORDER BY diff
```

**Comment by jovenc** [comment]
Many thanks to Raph who added index on the two tables I'm using above. The query took only 3minutes! 
```
CREATE TABLE jchew.wys_signs_nearest_centrelines_leven AS
SELECT
  wys.*,
  atr.*,
  ST_Distance(ST_Transform(wys.wys_geom,2952), ST_Transform(atr.atr_geom,2952)) AS diff
FROM
(SELECT api_id, sign_id, address, 
 sign_name, gis.abbr_street2(regexp_REPLACE(sign_name, ' (NB|SB|WB|EB)', '')) AS cleaned_name, 
 dir AS wys_dir, start_date, next_start, prev_start, geom AS wys_geom
FROM wys.stationary_signs
) wys
CROSS JOIN LATERAL
(SELECT centreline_id, gis.abbr_street2(linear_name_full) AS linear_name_full, 
 geom AS atr_geom, dir AS atr_dir,
 feature_code_desc AS fcode_desc
FROM gis.centreline_directional
WHERE ST_DWithin (ST_Transform(wys.wys_geom,2952), ST_Transform(geom,2952), 500)
AND levenshtein(TRIM(wys.cleaned_name), 
			TRIM(gis.abbr_street2(linear_name_full)), 1, 1, 1) < 5
AND feature_code_desc IN ('Collector','Collector Ramp',
'Local','Major Arterial','Major Arterial Ramp','Minor Arterial',
'Minor Arterial Ramp','Pending')
ORDER BY 
ST_Transform(wys.wys_geom,2952) <-> ST_Transform(geom,2952),
 levenshtein(TRIM(wys.cleaned_name), 
			TRIM(gis.abbr_street2(linear_name_full)), 1, 1, 1)
LIMIT 1) atr
ORDER BY diff
```

From the results, I found that I lost 14 signs in the process (5 of which are out of boundary, 9 of which where the sign name doesn't match with their location). From the results, I also found that those with distance greater than 100m (5 of them) have the sign located rather from the road that it is supposed to "watch the speed". For example, the sign below is supposed to watch the speed of EB traffic on Eglinton Avenue but it is located rather far from that street
![image](https://user-images.githubusercontent.com/54872846/81318748-b23db180-905c-11ea-8346-321ca68ed76e.png)

Will be ignoring the 5 signs that are out of boundary, manually fixing the 9 missing signs as well as the 5 signs where the distance between the signs and centreline is greater than 100m (Should I fix those according to the sign name or its current location?).

1. 5 signs which are out of boundary have `api_id IN (9780, 26319,22776,24999,13959)`
2. 9 missing signs have `api_id IN (5294,7657,9684,9952,10474,13128,13129,13130,22729)`
3. 5 signs where distance is greater than 100m have `api_id IN (9775,9752,9764,7649,9658)`

**Comment by jovenc** [comment]
A little summary of what I found as we dont actually need to bother Jacqui on all the signs mentioned above. @radumas , hope this is helpful.

|api_id|serial_num|status|need to ask|
|------|----------|------|----------|
|||THE 10 MISSING SIGNS||
|5294|17121889|it's inactive, last communicated April 2018?|YES|
|7657|18082242|Couldn't find the location on streetsoncloud|YES|
|9684|18082325|geom on `wys.stationary_signs` is wrong ||
|9952|18122799|The sign has moved according to streetsoncloud|YES|
|10474|18122768|Nth is wrong but it's not included in the result?||
|10497|18122753|The sign has moved according to streetsoncloud|YES|
|13128|19104213|Couldn't find the location on streetsoncloud|YES|
|13129|19074090|Couldn't find the location on streetsoncloud|YES|
|13130|19104227|Couldn't find the location on streetsoncloud|YES|
|22729|19080194|geom on `wys.stationary_signs` is wrong ||
|||DISTANCE GREATER THAN 100M||
|7649|18082225|The sign has moved according to streetsoncloud|YES|
|9658|18102539|no problem, just that the sign is located close to the end of the centreline|YES|
|9752|18112629|sign located 2 streets away for the street on sign name||
|9764|18112606|sign located 2 blocks away for the street on sign name||
|9775|18112642|no problem, just that the sign is located close to the end of the centreline|YES|
