### ISSUE TITLE
RESCU Data - Automatically pull 15-minute data into RDS

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#291]
Write a job that runs on a daily basis in the morning and imports the latest 15-minute volume file (location to be disclosed offline) into our RDS (`rescu.raw_data`).

@radumas will provide support. Test out locally on a sample file, and then enlist support to deploy on server.

**Comment by aharpalaniTO** [comment]
Some additional details:

- the script will be pulling the file from the previous day from a folder that contains multiple files. To ensure this can be used for other applications, it probably makes sense if the user is able specific the date range from which the data should be pulled, but by default it only pulls the previous day's worth of data.

- there is a second part which involves updating a table (`rescu.volumes_15min`). A script already exists for this but should be converted to a trigger based process.

**Comment by aharpalaniTO** [comment]
See https://github.com/CityofToronto/bdit_data-sources/tree/rescu/rescu/

**Comment by radumas** [comment]
https://github.com/CityofToronto/bdit_data-sources/blob/rescu/rescu/populate-table-volumes_15min.sql
