### ISSUE TITLE
Update speed limit layer using updated functions

### ISSUE THREAD

**Issue by jovenc** [CityofToronto/bdit_data-sources#293]
Updating the whole speed limit layer using the latest mega function `jchew.text_to_centreline_updated()` that can now accommodate the 4 major cases stated on [README](https://github.com/CityofToronto/bdit_data-sources/blob/text_to_centreline/gis/bylaw_text_to_centreline/README.md#step-2-separate-into-different-cases). Information about the number of special cases can be found [here](https://github.com/CityofToronto/bdit_data-sources/issues/275#issuecomment-597328404). 

When completed, the mega function results will be in `jchew.bylaws_routing2` and the latest speed limit layer in `jchew.bylaws_updated2`. I will list down the steps taken below as well as some minor issues I encounter along the way.

**Comment by jovenc** [comment]
Note the 4 bylaws (3 technically as 1 is deleted) that could not be cleaned using the function `jchew.clean_bylaws_text2()`. They are ignored for now.

![image](https://user-images.githubusercontent.com/54872846/78369045-97c27500-7592-11ea-9038-83ae7dd3b94a.png)

**Comment by jovenc** [comment]
Note the 6 weird bylaws that I found by running the below query WHERE there's a 'Repealed' text in the `bylaw_no` but `deleted` = false? They were repealed but not deleted yet? They are excluded from the bylaws_to_centreline process too.

![image](https://user-images.githubusercontent.com/54872846/78368275-639a8480-7591-11ea-8d2c-98ba2f6532f0.png)

**Comment by jovenc** [comment]
There are also 15 of them where the `section` column is weird and some geom is unreadable too like #290 . I randomly checked a few of them and found some is due to the geometry of the intersection as shown in the figure below, and some were trimmed less than stated in the bylaws (I checked it with the `oid1_geom_translated`). Not entirely sure what happened. I'm thinking it's a buffer thing?

![image](https://user-images.githubusercontent.com/54872846/78398729-98263480-75c1-11ea-8cba-1c27ada8de5a.png)

Below is an example for bylaw_id = 1342, highway = 'Fairmeadow Avenue' and between = 'Lord Seaton Road and a point 45 metres north of Yorkminster Road', the red crosses are the intersection whereas highlighted is where the centrelines within the buffer should be.
![image](https://user-images.githubusercontent.com/54872846/78399879-bdb43d80-75c3-11ea-9e62-e4dda773c0c3.png)

**Comment by jovenc** [comment]
Note that when the bylaws text is not cleaned nicely (WHERE `direction_btwn1` AND `direction_btwn2` is not one of the 8 stated directions), there is no result from the text_to_centreline process except for bylaw_id = 5244 which is also of a problem stated above.
```
SELECT * FROM jchew.bylaws_2020_cleaned
WHERE TRIM(direction_btwn1) not IN ('north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest')
OR TRIM(direction_btwn2) not IN ('north', 'south', 'east', 'west', 'northeast', 'northwest', 'southeast', 'southwest')
```
![image](https://user-images.githubusercontent.com/54872846/78401091-efc69f00-75c5-11ea-9202-58e380ed5cd8.png)

**Comment by jovenc** [comment]
There are 5163 bylaws in total that are not repealed and have to be routed and my function couldn't process 781 of them?!
```
SELECT * FROM jchew.bylaws_2020 law
WHERE law.deleted = false 
AND (law.bylaw_no NOT LIKE '%Repealed%' OR law.bylaw_no IS NULL) --to exclude those that got repealed but not deleted (6 of them)
AND law.id IN (SELECT bylaw_id FROM jchew.bylaws_2020_cleaned) --to exclude those not cleaned nicely (3 of them)
--to find those that are not routed
AND id NOT IN (SELECT id FROM jchew.bylaws_routing2)
```

**Comment by jovenc** [comment]
In an attempt to debug why 700 bylaws are still missing, I did a quick run on those bylaws to see how many failed at the `get_intersection_id` part and how many failed at the `pgrouting` part etc.

1. After eliminating 89 of them that only have an intersection or are of the entire length case, I'm left with 5074 bylaws that have two intersections for sure. 

2. Using the function `jchew.bylaws_get_id_to_route` which is essentially like the mega function part to find the intersection ids and information and removed everything else that is not applicable and produced a table `jchew.bylaws_found_id`. Out of the 5074 bylaws, I managed to find both intersection id for 4875 bylaws and am only missing 199 bylaws (96 of which does not have both `int1` & `int2` and 103 of which does not have `int2` only). 

3.  Then, I ran the function `jchew.bylaws_route_id` to route those 4875 pairs of intersections found above to produce the table `jchew.bylaws_found_routes`. Out of the 4875 bylaws, I managed to route 4791 bylaws and 84 of them did not return any results.

4. Out of the 4791 bylaws that got routed, I did a check and found that 217 of them fall under special case 2 and so I used `jchew._centreline_case2_combined` to check how many of them fail in this part of the mega function. But I kept seeing this error, 
```
ERROR:  could not open relation with OID 1350136550
SQL state: XX000
```
I find it weird because that function has an exception for that SQL state and also I couldn't find what OID=1350136550 is using `select oid,relname from pg_class where oid=1350136194`

If only the above are the issues happening, I should be missing about ~300 (199+84=283 excluding part4 above for now) bylaws and not 700 of them. A random check on the bylaws where no results were returned from the mega function shows that some bylaws return results if I run the mega function individually and not when I run the function through the bylaws table using the following query.
```
SELECT law.*, results.*
FROM jchew.bylaws_to_update law, 
LATERAL jchew.text_to_centreline_updated(
law.highway,
law.between,
NULL
) as results 
```

**Comment by jovenc** [comment]
Another attempt to run the mega function through the table of bylaws `jchew.bylaws_to_update`.
```
CREATE TABLE jchew.bylaws_to_update AS
SELECT law.*
FROM jchew.bylaws_2020 law
WHERE law.deleted = false 
AND (law.bylaw_no NOT LIKE '%Repealed%' OR law.bylaw_no IS NULL) --to exclude those that got repealed but not deleted (6 of them)
AND law.id IN (SELECT bylaw_id FROM jchew.bylaws_2020_cleaned) --to exclude those not cleaned nicely (3 of them)
```
using the query below
```
SET client_min_messages = warning; 
CREATE TABLE jchew.bylaws_routing3 AS
SELECT law.*, results.*
FROM jchew.bylaws_to_update law,
LATERAL jchew.text_to_centreline_updated(
law.id,
law.highway,
law.between,
NULL
) as results
```
I'm ONLY MISSING 335 bylaws now !!! (199 failed at `get_intersection_id`, 84 failed at `pgrouting` and 52 failed else where that are mostly case2 or maybe other special cases). This can be checked using the query below.
```
WITH no_id AS (
--FOUND 103 rows ONLY int2 NULL WHEREAS 96 rows both int1 & int2 NULL
SELECT * FROM jchew.bylaws_found_id
WHERE int1 IS NULL
OR int2 IS NULL
),
no_routed AS (
--FOUND 84 THAT ARE NOT ROUTED
SELECT * FROM jchew.bylaws_found_id
WHERE int1 IS NOT NULL
AND int2 IS NOT NULL
AND id NOT IN (SELECT bylaw_id FROM jchew.bylaws_found_routes)
	)
--to find how many failed elsewhere
SELECT * FROM jchew.bylaws_to_update
WHERE id NOT IN (SELECT id FROM jchew.bylaws_routing3) 
AND id NOT IN (SELECT id FROM no_id)
AND id NOT IN (SELECT id FROM no_routed)
```

**Comment by jovenc** [comment]
Attempt to run mega function `jchew.text_to_centreline_updated()` through the table `jchew.bylaws_to_update` another time after debugging using the query below.
```
SET client_min_messages = warning;
CREATE TABLE jchew.bylaws_routing3 AS
SELECT law.*, results.*
FROM jchew.bylaws_to_update law,
LATERAL jchew.text_to_centreline_updated(
law.id,
law.highway,
law.between,
NULL
) as results
```
It works this time! The results are in table `jchew.bylaws_routing3 `. **I am only missing 335 bylaws!!!** (199 failed at `get_intersection_id`, 84 failed at `pgrouting` and 52 failed else where such as one of them in entire length but mostly case2 or other minor cases)

**Comment by jovenc** [comment]
A note that Chelsea has put those unmatched bylaws into a csv file [here](https://github.com/CityofToronto/bdit_data-sources/blob/text_to_centreline/gis/posted_speed_limit_update/automated/unmatched.csv) which I copied into `jchew.bylaws_unmatched_2019` .
There are 225 bylaws that did not get matched using Chelsea's process for 2019 bylaws whereas there are 335 bylaws that did not get matched using the latest mega function. There are 183 bylaws that are common in both table.

**Comment by radumas** [comment]
So are there 16 that fail at `get_intersection_id` that didn't fail before?

**Comment by jovenc** [comment]
Soooo, I am trying to combine `gis.centreline` and `jchew.bylaws_routing3` now but I realised that a centreline might be used in more than 1 bylaws and so the following check is done. For now, results where `section` is null or = [0,1] is done but those where `section` != [0,1] is still not done as we have to think of how we can deal with different bylaws using different part of a centreline and try to separate that into different rows with modified geom accordingly. 

I will list out all my steps here.
1. Copy table `gis.centreline`
```
INSERT INTO jchew.bylaws_updated2 (lf_name, objectid, geom, fcode, fcode_desc)
SELECT lf_name, objectid, geom, fcode, fcode_desc
FROM gis.centreline
```
2. Create a view where we can see when the bylaw was added and whether or not it is repealed
```
CREATE OR REPLACE VIEW jchew.bylaws_added_date AS 
WITH added AS (
--to ensure each bylaw_id only has a single row
SELECT * FROM jchew.bylaws_2020_dates_column
WHERE deleted = false
AND repealed IS NULL
)
SELECT rt.id AS bylaw_id, rt.objectid, rt.section, dt.added_date , 
CASE WHEN dt.repealed IS NULL THEN false
ELSE true
END AS repealed, 
rt.speed_limit_km_per_h, 
rt.con, rt.highway, rt.between, rt.lf_name, rt.line_geom
FROM jchew.bylaws_routing3 rt
LEFT JOIN added dt
USING (id)
```
3. Update the centreline table with speed limit information for `section` = NULL or [0,1]
Using CTE
```
WITH no_section_bylaw AS (
	SELECT DISTINCT ON (objectid) objectid, added_date, bylaw_id, speed_limit_km_per_h,
	con, highway, between, lf_name, line_geom, section
	FROM jchew.bylaws_added_date
	WHERE (section IS NULL OR section = '[0,1]')
	ORDER BY objectid, added_date DESC
	)
UPDATE jchew.bylaws_updated2 updated
SET(speed_limit, confidence, bylaw_id, bylaw_streetname, bylaw_extents) = 
(SELECT speed_limit_km_per_h, con, id, highway, between
FROM no_section_bylaw
WHERE updated.objectid = no_section_bylaw.objectid 
);
```
or a FOR LOOP?
```
FOR no_section_bylaw IN
	SELECT DISTINCT ON (objectid) objectid, added_date, bylaw_id, speed_limit_km_per_h,
	con, highway, between, lf_name, line_geom, section
	FROM jchew.bylaws_added_date
	WHERE (section IS NULL OR section = '[0,1]')
	ORDER BY objectid, added_date DESC
LOOP
    UPDATE jchew.bylaws_updated2 updated
    SET (speed_limit, confidence, bylaw_id, bylaw_streetname, bylaw_extents) = 
	(SELECT speed_limit_km_per_h, con, id, highway, between
	FROM no_section_bylaw
	WHERE objectid = no_section_bylaw.objectid);
END LOOP;
```

**Comment by jovenc** [comment]
A quick note here about bylaws that are not being processed. There are 335 in total (199 failed at get_intersection_id, 84 failed at pgrouting and 52 failed elsewhere -> found 1 in entire length but mostly case2) 
```
--CHECKINGGGGG
WITH no_id AS (
--FOUND 103 rows ONLY int2 NULL WHEREAS 96 rows both int1 & int2 NULL
SELECT * FROM jchew.bylaws_found_id
WHERE int1 IS NULL
OR int2 IS NULL
),
no_routed AS (
--FOUND 84 THAT ARE NOT ROUTED
SELECT * FROM jchew.bylaws_found_id
WHERE int1 IS NOT NULL
AND int2 IS NOT NULL
AND id NOT IN (SELECT bylaw_id FROM jchew.bylaws_found_routes)
	)
--to find how many failed elsewhere
SELECT * FROM jchew.bylaws_to_update
WHERE id NOT IN (SELECT id FROM jchew.bylaws_routing3) 
AND id NOT IN (SELECT id FROM no_id)
AND id NOT IN (SELECT id FROM no_routed)
```
