### ISSUE TITLE
Build post-processing process for handling suspected device downtime

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#294]
When data is brought into `miovision_api.volumes_15min` and a specific `intersection_uid`, `datetime_bin`, `leg` and `movement_uid` combination is NULL (where a value is expected), this is scaled using other values in that 15 minute bin. This, however, creates an issue where if all 15 minutes in the bin are 0, it could be due to one of two reasons:

1. Zero volume is an accurate reflection of volume (in which volume = 0 is fine)

2. Zero volume is reflective of the device being down (in which case volume should be updated to NULL)

The replacement of 0s with NULLs for suspected device downtime will ensure that averages taken across multiple (e.g. generating baselines) will not be set falsely lower.

**Comment by aharpalaniTO** [comment]
Running the following query:
```
WITH volumes_15min_zeros AS (
	SELECT 	intersection_uid,  date_trunc('hour',datetime_bin) AS hour_bin, datetime_bin
	FROM	miovision_api.volumes_15min
	GROUP BY intersection_uid, date_trunc('hour', datetime_bin), datetime_bin
	HAVING SUM(volume) = 0
),

volumes_hr AS (
	SELECT intersection_uid, date_trunc('hour',datetime_bin) AS hour_bin, SUM(volume) AS total_volume
	FROM	miovision_api.volumes_15min
	GROUP BY intersection_uid, date_trunc('hour', datetime_bin)
)

SELECT total_volume, COUNT(1) AS num
FROM volumes_15min_zeros A
INNER JOIN volumes_hr B USING (intersection_uid, hour_bin)
GROUP BY total_volume
ORDER BY total_volume
```

results in the lowest non-zero total hourly volume across all modes equal to 6. As a result, we can safely assume that hourly volumes of 0 are incredibly unlikely, and any 15-minute volume that is within an hour that also has 0 volume can safely be set to NULL.

**Comment by aharpalaniTO** [comment]
Some initial conditions for setting volumes in `miovision_api.volumes_15min` to NULL:

1. if the total hourly volume of the hour in which the 15 minute bin is within is equal to zero

OR

2. if the total hourly volume of the hour that either lags or leads the hour in which the 15 minute bin is within is equal to zero

OR 

3. if the total hourly volume of the hour in which the 15 minute bin is within is greater than or equal to 50 (based on some rough visual inspection)

OR

4. if the total hourly volume of either the hour preceding or the hour following the hour bin in which the 15-minute is located is greater than or equal to 200 (maybe we tweak this?)

SQL to identify the one that should remain zero based on this criteria (843 of total 141,914 records where volume = 0 in `miovision_api.volumes_15min`):
```
WITH volumes_15min_zeros AS (
	SELECT 	intersection_uid,  date_trunc('hour',datetime_bin) AS hour_bin, datetime_bin
	FROM	miovision_api.volumes_15min
	GROUP BY intersection_uid, date_trunc('hour', datetime_bin), datetime_bin
	HAVING SUM(volume) = 0
),

volumes_hr AS (
	SELECT intersection_uid, date_trunc('hour',datetime_bin) AS hour_bin, SUM(volume) AS total_volume
	FROM	miovision_api.volumes_15min
	GROUP BY intersection_uid, date_trunc('hour', datetime_bin)
),

volumes_hr_det AS (
	SELECT 	intersection_uid,
			hour_bin,
			total_volume, 
			LAG(total_volume, 1) OVER (ORDER BY intersection_uid, hour_bin) AS total_volume_lag,
			LEAD(total_volume, 1) OVER (ORDER BY intersection_uid, hour_bin) AS total_volume_lead
	FROM volumes_hr
)
SELECT * 
FROM volumes_hr_det 
INNER JOIN volumes_15min_zeros USING (intersection_uid, hour_bin)
WHERE total_volume <@ '[1,50)'::numrange AND
	total_volume_lag <@ '[1,200)'::numrange AND
	total_volume_lead <@ '[1,200)'::numrange
ORDER BY intersection_uid, datetime_bin
```

**Comment by aharpalaniTO** [comment]
@radumas would like a second opinion for my somewhat arbitrary criteria. 

Of the 843 remaining records in which a volume = 0 would be allowed to remain, the hourly distribution of these occurrences is as follows:

|hour of day|occurrences|
| --------- | --------- |
|0|37|
|1|90|
|2|91|
|3|251|
|4|212|
|5|51|
|6|13|
|7|2|
|8|9|
|10|4|
|12|3|
|13|4|
|14|3|
|17|3|
|18|4|
|20|12|
|21|16|
|22|23|
|23|21|

**Comment by aharpalaniTO** [comment]
Not exactly even...

|hour of day|occurrences|pct|
| --------- | --------- | --------- |
|0|5910|4.2%
|1|6030|4.3%
|2|6423|4.5%
|3|6570|4.6%
|4|6660|4.7%
|5|6251|4.4%
|6|5869|4.2%
|7|5732|4.1%
|8|5683|4%
|9|5654|4%
|10|5620|4%
|11|5601|4%
|12|5590|4%
|13|5616|4%
|14|5575|3.9%
|15|5600|4%
|16|5587|4%
|17|5572|3.9%
|18|5541|3.9%
|19|5563|3.9%
|20|5683|4%
|21|5863|4.1%
|22|5960|4.2%
|23|7213|5.1%

**Comment by aharpalaniTO** [comment]
Realized these numbers reflect ATR totals not TMC totals (and therefore are doublecounting vehicles in aggregate counts). Will modify criteria accordingly.

**Comment by aharpalaniTO** [comment]
Started to refine this when I realized two things @radumas:

1. Our truck data doesn't use the same 0-infill process as the other classes. We'd have to account for this as well.

2. Our vendor might have a better way of doing this if device downtime is tracked on their end.

Going to build some crude logic downstream (within the reporting views) and hold off on any changes to the ingestion process.

**Comment by radumas** [comment]
The zero-padding happens at this stage of aggregating to 15-min TMCs and after determining if interpolation is necessary. With it only applying to the 3 main modes we were interested in: lights, bikes, and peds.

https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql#L86-L91
