### ISSUE TITLE
Processed bylaw output format

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#295]
Apologies that this is reversing some previous work but I think this is the better path forward. The output of the bylaw matching function should be stored in a table of a structure:

`bylaw_id, speed_limit, int1, int2, geo_id, con, note, line_geom, section, oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, date_added, date_repealed`

I know [previously](https://github.com/CityofToronto/bdit_data-sources/issues/277) additions and repeals were split into separate rows, but I didn't realize the input was on the same row. For the next step I think having the two dates on the same row makes the most sense.

then we will write a materialized view to generate a speed limit layer for present day:

```sql
WITH recursive sections_to_subtract(geo_id, remaining_section, geom, date_added, step) (
    SELECT DISTINCT ON(geo_id) --Start with only one bylaw per centreline
                geo_id, numrange(0.0,1.0) - section, cl.geom - bylaws.geom, date_added, 0 as step
    FROM bylaws
    INNER JOIN centreline cl USING (geo_id)
    WHERE date_added < today() AND date_repealed > today() --Bylaw is in effect
    AND section is not 0,1 or NULL or whatever
    ORDER BY geo_id, date_added
    UNION
    SELECT geo_id, remaining_section - b.section, b.date_added, step + 1
    FROM sections_to_subtract
    LATERAL INNER JOIN (--Find the next bylaw to apply to each centreline in order of date_added
                                        SELECT geo_id, section, date_added
                                        FROM bylaws
                                        WHERE bylaws.geo_id = sections_to_substract.geo_id
                                                     AND bylaws.date_added > sections_to_substract.date_added 
                                        ORDER BY date_added
                                        LIMIT 1) b ON b.geo_id = sections_to_substract.geo_id
)
SELECT centreline_id, bylaw_id, COALESCE(bylaws.geom centreline.geom), section --, etc.
FROM centreline
LEFT OUTER JOIN bylaws USING (geo_id)
WHERE  date_added IS NULL --no bylaw applied to this centreline
              OR (date_added < today() AND date_repealed > today() ) --Bylaw is in effect
UNION
SELECT centreline_id, 
            NULL as bylaw_id, 
            sections_to_subtract.geom, 
            sections_to_subtract.remaining_section --, etc.
FROM (SELECT DISTINCT  ON (geo_id) * --only select the geo_id on which all the operations have been applied
                     FROM sections_to_subtract 
                     ORDER BY geo_id, step DESC) sections_to_subtract 

```
The above query can also be used in a function to generate a speed limit layer for a particular point in time. 

**Assumptions**: 

- the same bylaw doesn't apply twice to a given centreline
- speed limits don't overlap (`a.section && b.section`)
- speed limits don't bisect a centreline( `NOT (lower(section) >0 AND upper(section) < 1)`)
- any centreline where an active bylaw only applies to a section of it, does not also have a bylaw applying to its entire length.

**Comment by jovenc** [comment]
After fixing the bylaw-date formatting, I combined the table `jchew.bylaws_routing3` (bylaws results) and `jchew.bylaws_added_repealed_dates` (bylaws dates)
```sql
CREATE TABLE jchew.bylaws_routing3_dates AS
SELECT result.*, dates.date_added, dates.date_repealed 
FROM jchew.bylaws_routing3 result
LEFT JOIN jchew.bylaws_added_repealed_dates dates
USING (id)
--20984 rows
```
For centrelines where bylaw is applied to the whole centreline and not just part of it
```sql
SELECT bylaws.id AS bylaw_id, centre.lf_name, bylaws.geo_id, bylaws.speed_limit_km_per_h AS speed_limit, 
bylaws.int1, bylaws.int2, con, note, line_geom AS geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
bylaws.date_added, bylaws.date_repealed
FROM gis.centreline centre
LEFT OUTER JOIN jchew.bylaws_routing3_dates bylaws USING (geo_id)
WHERE (date_added < now()::date AND date_repealed > now()::date) --Bylaw is in effect
OR date_repealed IS NULL --Bylaw not repealed yet
```
The other part (where bylaw applied on certain section of a centreline) is to be added tomorrow. Testing each part of the query first before running them.

**Comment by radumas** [comment]
FYI that last `WHERE` clause should be

```sql
WHERE date_added < now()::date AND (date_repealed > now()::date --Bylaw is in effect
OR date_repealed IS NULL )--Bylaw not repealed yet
```
Are there cases where `date_added` could be null?

**Comment by jovenc** [comment]
Modified the query that Raph wrote and tried to run it but got the error `ERROR:  could not implement recursive UNION`. Is there sth that I have changed or is this UNION too complicated?
```sql
CREATE MATERIALIZED VIEW jchew.bylaws_updated_final AS
WITH recursive sections_to_subtract(geo_id, remaining_section, geom, date_added, step) AS 
(
    SELECT DISTINCT ON(geo_id) --Start with only one bylaw per centreline
                geo_id, numrange(0.0,1.0) - section, 
				ST_Difference(cl.geom, ST_Buffer(bylaws.line_geom, 0.00001)),
				date_added, 0 AS step
    FROM jchew.bylaws_routing3_dates bylaws
    INNER JOIN gis.centreline cl USING (geo_id)
	WHERE (date_added < now()::date OR date_added IS NULL)  --Bylaw is in effect
	AND (date_repealed > now()::date OR date_repealed IS NULL ) --Bylaw not repealed yet
	AND numrange(0.0,1.0) - section IS NOT NULL
	AND numrange(0.0,1.0) - section != 'empty'
    --AND section is not 0,1 or NULL or whatever
	GROUP BY geo_id, section, date_added, cl.geom, bylaws.line_geom
    UNION
    SELECT sections_to_subtract.geo_id, remaining_section - b.section,
	ST_Difference(geom, ST_Buffer(b.line_geom, 0.00001)),
	b.date_added, step + 1
    FROM sections_to_subtract
    INNER JOIN LATERAL (--Find the next bylaw to apply to each centreline in order of date_added
		SELECT geo_id, section, line_geom, date_added
		FROM jchew.bylaws_routing3_dates bylaws
		WHERE bylaws.geo_id = sections_to_subtract.geo_id
					 AND bylaws.date_added > sections_to_subtract.date_added
		ORDER BY date_added
		LIMIT 1) b ON b.geo_id = sections_to_subtract.geo_id
)
SELECT bylaws.id AS bylaw_id, centre.lf_name, bylaws.geo_id, bylaws.speed_limit_km_per_h AS speed_limit, 
bylaws.int1, bylaws.int2, con, note, line_geom AS geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
bylaws.date_added, bylaws.date_repealed
FROM gis.centreline centre
LEFT OUTER JOIN jchew.bylaws_routing3_dates bylaws USING (geo_id)
WHERE (date_added < now()::date OR date_added IS NULL)  --Bylaw is in effect
AND (date_repealed > now()::date OR date_repealed IS NULL ) --Bylaw not repealed yet
UNION
SELECT 
NULL AS bylaw_id, NULL AS lf_name, sections_to_subtract.geo_id, NULL AS speed_limit, 
NULL AS int1, NULL AS int2, NULL AS con, NULL AS note, 
sections_to_subtract.geom, sections_to_subtract.remaining_section, 
NULL AS oid1_geom, NULL AS oid1_geom_translated, NULL AS oid2_geom, NULL AS oid2_geom_translated, 
NULL AS date_added, NULL AS date_repealed
FROM (SELECT DISTINCT  ON (geo_id) * --only select the geo_id on which all the operations have been applied
                     FROM sections_to_subtract 
                     ORDER BY geo_id, step DESC) sections_to_subtract
```

**Comment by radumas** [comment]
uh oh.

Have you tried `UNION ALL`?
https://www.postgresql.org/message-id/25168751.post%40talk.nabble.com

**Comment by jovenc** [comment]
Yes, `UNION ALL` works! Ran a random check on the results table `jchew.bylaws_updated_final` and I think this method addresses the various issues that arise when trying to put them into the right format which are

1. The table must have every single centreline from `gis.centreline` regardless of whether they are used in the bylaws.
2. When more than 1 bylaw (say 3 bylaws) are applied on the same centreline, then 3 rows are shown in the result table with the same centreline information but different bylaw information.
3. If only a part of the centreline is stated in the bylaw (can distinguish from the `section` column), then the result table will show two rows of the same centreline. One row has the geom of the part stated in the bylaw and the other has the geom of the part not stated in the bylaw.
4. If more than 1 bylaw (say 2 bylaws) are applied on different part of the centreline, then there are 2 rows with the same centreline geo_id with an additional row showing the geom of the part of the centreline not included in the bylaw (or the shorter path on the centreline if both section overlap)

The figure below depicts (i), (ii), (iii) above.
![image](https://user-images.githubusercontent.com/54872846/80034749-e5a90980-84bc-11ea-9877-6851f7684243.png)

The figure below depicts (iii), (iv) above.
![image](https://user-images.githubusercontent.com/54872846/80036001-f490bb80-84be-11ea-847f-41f9c689a36b.png)

**Comment by jovenc** [comment]
This I what I came out with according to the output we want. 
> - Every whole centreline should only display one bylaw
> - Any centreline section should only display one bylaw which also means centreline where part of it is involved in a bylaw and part of it not will have two rows with the same centreline geo_id

If more than one bylaw is applied on the same centreline, only the one with the latest `added_date` is included, if `added_date` is NULL for all bylaws then the one with the larger `bylaw_id` (which also mean that it's added later) is chosen. **HOWEVER, `NULL` is 'greater' than any dates.** Since only bylaw_id < 3461 does not have an `added_date`, I proposed to add a date in the empty cell to make sure it is not NULL but not sure what date to add yet. Anyway, if the method below is acceptable or meets expectation then I will try to figure out the date part. Any other suggestion is welcome too.

```
CREATE MATERIALIZED VIEW jchew.bylaws_updated_only_one AS
--gis.centreline has 67769 rows
WITH whole AS(
--68321 rows (68146 rows if only include entire centreline)
SELECT bylaws.id AS bylaw_id, centre.lf_name, bylaws.geo_id, bylaws.speed_limit_km_per_h AS speed_limit, 
bylaws.int1, bylaws.int2, con, note, line_geom AS geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
bylaws.date_added, bylaws.date_repealed
FROM gis.centreline centre
LEFT OUTER JOIN jchew.bylaws_routing3_dates bylaws USING (geo_id)
WHERE (date_added < now()::date OR date_added IS NULL)  --Bylaw is in effect
AND (date_repealed > now()::date OR date_repealed IS NULL ) --Bylaw not repealed yet
--AND (section IS NULL OR section = '[0,1]')
)
, whole_added AS (
--20432 rows
SELECT DISTINCT ON (geo_id) bylaw_id, lf_name, geo_id, speed_limit, 
int1, int2, con, note, geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
date_added, date_repealed
FROM whole
WHERE geo_id IS NOT NULL
ORDER BY geo_id, date_added DESC, bylaw_id DESC
)
, no_bylaw AS (
--47337 rows
SELECT 
NULL::integer AS bylaw_id, lf_name, geo_id, NULL::integer AS speed_limit, 
NULL::integer AS int1, NULL::integer AS int2, NULL::text AS con, NULL::text AS note, 
geom, NULL::numrange AS section, 
NULL::geometry AS oid1_geom, NULL::geometry AS oid1_geom_translated, 
NULL::geometry AS oid2_geom, NULL::geometry AS oid2_geom_translated, 
NULL::date AS date_added, NULL::date AS date_repealed
FROM gis.centreline
WHERE geo_id NOT IN (SELECT geo_id FROM whole_added)
)
, part AS (
--153 rows
SELECT * FROM whole_added
WHERE section IS NOT NULL AND section != '[0,1]'
)
, part_without_bylaw_added AS (
--153 rows
SELECT NULL::integer AS bylaw_id, cl.lf_name, geo_id, NULL::integer AS speed_limit, 
NULL::integer AS int1, NULL::integer AS int2, NULL::text AS con, NULL::text AS note, 
ST_Difference(cl.geom, ST_Buffer(part.geom, 0.00001)) AS geom, (numrange(0.0,1.0) - part.section) AS section, 
NULL::geometry AS oid1_geom, NULL::geometry AS oid1_geom_translated, 
NULL::geometry AS oid2_geom, NULL::geometry AS oid2_geom_translated, 
NULL::date AS date_added, NULL::date AS date_repealed
	FROM part 
    INNER JOIN gis.centreline cl USING (geo_id)
	GROUP BY cl.lf_name, geo_id, section, part.date_added, cl.geom, part.geom
	ORDER BY geo_id
)
SELECT * FROM whole_added
UNION
SELECT * FROM no_bylaw
UNION
SELECT * FROM part_without_bylaw_added
```

**Comment by jovenc** [comment]
Sooo puzzled now, I have only added `NULLS FIRST` in the part shown below and now my `geo_id` is no longer distinct? The results now contain every single `added_date` on the same `geo_id`
```
, whole_added AS (
--20432 rows
SELECT DISTINCT ON (geo_id) bylaw_id, lf_name, geo_id, speed_limit, 
int1, int2, con, note, geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
date_added, date_repealed
FROM whole
WHERE geo_id IS NOT NULL
ORDER BY geo_id, date_added DESC NULLS FIRST, bylaw_id DESC 
)
```
![image](https://user-images.githubusercontent.com/54872846/80263478-bfbb6a80-865e-11ea-83c2-3f2e60d78350.png)

**Comment by radumas** [comment]
For the two examples, this is what I would expect the result to be based on the idea that `bylaw_id` increases chronologically. Since there are bylaws covering the entirety of both centrelines, there shouldn't be any section of those centreline where there is no bylaw.

| bylaw\_id |lf\_name       | geo\_id | speed\_limit | section                     | date\_added  | date\_repealed |
|-------------|------------------|-----------|----------------|-------------------------------|----------------|------------------|
| 4220        | Courcelette Rd | 113268 | 40             | "\[0,0\.85\]"    | "2014\-06\-17" | NULL             |
| 4219        | Courcelette Rd | 113268 | 30             | "\(0\.85,1]"    | "I don't know" | NULL             |
| 6696          | Ameer Ave      | 444295  | 40             | "\[0,1\]"    | NULL           | NULL             |

**Comment by radumas** [comment]
My thoughts on overlapping bylaws for sections of centreline is we want the most recent bylaw to apply and then have sections "below" be dictated by the extents of the most recent bylaw. We could do this sequentially using a LOOP applied in reverse chronological order. We can then create a function that compares the current WIP bylaw section to the next most recent bylaw section. If there is some or no overlap, create a new section of the difference between the WIP bylaw and the next one.

WIP pseudo code

```sql
CREATE FUNCTION get_centreline_bylaw_output(centreline_geom GEOM, [(bylaw_no, date_added, section, geom)])
RETURNS SET OF geom, bylaw_no, date_added, section


--Check the most recent bylaw, if it has section [0,1] then return that

--Otherwise insert it into the output table

--Then loop over the remaining bylaws for this centreline in reverse chronological order, and compare them with what's in the existing output table. If they overlap partially, take the difference and insert that into the output table, if they overlap completely, do nothing.


```

**Comment by jovenc** [comment]
Have fixed the `NULLS` problem. Below is the results from the latest table which is `jchew.bylaws_updated_only_one`. See [here ](https://github.com/CityofToronto/bdit_data-sources/issues/295#issuecomment-618055490) to find out all the relevant bylaws to these particular centrelines. 

| "bylaw\_id" | "lf\_name"       | "geo\_id" | "speed\_limit" | "int1"   | "int2"   | "con"                      | "note"                                                                                                                                       | "geom"                                                                                                                                                                                       | "section"                     | "oid1\_geom"                                         | "oid1\_geom\_translated" | "oid2\_geom"                                         | "oid2\_geom\_translated"                             | "date\_added"  | "date\_repealed" |
|-------------|------------------|-----------|----------------|----------|----------|----------------------------|----------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|------------------------------------------------------|--------------------------|------------------------------------------------------|------------------------------------------------------|----------------|------------------|
| 4220        | "Courcelette Rd" | "113268"  | 40             | 13462347 | 13461885 | "Very High \(100% match\)" | "..." | "sth_geom" | "\[0,0\.854545320037243\]"    | "0101000020E6100000649EFF98C2D153C09D059A026BD64540" | NULL                     | "0101000020E61000005FB8A853D4D153C0DFD8582EC0D64540" | "0101000020E610000014E95EB2D0D153C014F15449AFD64540" | "2014\-06\-17" | NULL             |
| NULL        | "Courcelette Rd" | "113268"  | 50             | NULL     | NULL     | NULL                       | NULL                                                                                                                                         | "sth_geom"                                                                                                 | "\(0\.854545320037243,1\.0\)" | NULL                                                 | NULL                     | NULL                                                 | NULL                                                 | NULL           | NULL             |
| 6696        | "Ameer Ave"      | "444295"  | 40             | 13454414 | 13453964 | "Very High \(100% match\)" | "..."   | "sth_geom"                                                                                                 | "\[0,1\]"                     | "0101000020E610000064A449EF1CDC53C06FEF0BC9B8DC4540" | NULL                     | "0101000020E61000006DCBD1FA33DC53C083E2857C29DD4540" | "0101000020E61000001FFCC4CE35DC53C09B53B2ED31DD4540" | "2019\-06\-25" | NULL             |

I understand this process is not perfect given that it only takes in the latest bylaw and not cases when different bylaw is applied at different section of the centreline. Hence, I have done a little research on cases like that and below is the result I found. There are 8 cases where more than 1 bylaw is applied on the same centreline and `section` is not NULL or '[0,1]', be it at the same section or not. And only 3 centrelines where bylaws are applied at different part of the centreline whereas the rest is applied at about the same section of the centreline. (removed the unnecessary geom part of easier viewing)
| "bylaw\_id" | "lf\_name"       | "geo\_id"  | "speed\_limit" | "int1"   | "int2"   | "con"                             | "note"                                                                                                                                               | "geom"                                                                                                                                                                                                                                                                                       | "section"                  |"date\_added"  | "date\_repealed" |
|-------------|------------------|------------|----------------|----------|----------|-----------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------|----------------|------------------|
| 4220        | "Courcelette Rd" | "113268"   | 40             | 13462347 | 13461885 | "Very High \(100% match\)"        | "..."         | "sth_geom"                                                                                                 | "\[0,0\.854545320037243\]" |"2014\-06\-17" | NULL             |
| 4219        | "Courcelette Rd" | "113268"   | 30             | NULL     | NULL     | "Very High \(100% match\)"        | "..."       | "sth_geom"                                                                                                                                                                 | "\[0\.801110547380398,1\]" |"2014\-06\-17" | NULL             |
| 455         | "Boon Ave"       | "1139898"  | 40             | 13461246 | NULL     | "Very High \(100% match\)"        | "..."         | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.887534200608699\]" || NULL           | NULL             |
| 452         | "Boon Ave"       | "1139898"  | 30             | NULL     | NULL     | "High \(1 character difference\)" | "..."     | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.883746768838358\]" | NULL           | NULL             |
| 1191        | "Earlscourt Ave" | "1139938"  | 40             | 13461290 | NULL     | "Very High \(100% match\)"        | "..."   | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.921832259719223\]" | NULL           | NULL             |
| 1190        | "Earlscourt Ave" | "1139938"  | 30             | NULL     | NULL     | "Very High \(100% match\)"        | "..."      | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.921682088197842\]" | NULL           | NULL             |
| 2514        | "McCormack St"   | "1141121"  | 40             | 13462830 | 13462466 | "Very High \(100% match\)"        | "..."        | "sth_geom"                                                                                                                                                                                                 | "\[1,1\]"                  | NULL           | NULL             |
| 2515        | "McCormack St"   | "1141121"  | 40             | NULL     | NULL     | "Very High \(100% match\)"        | "..."          | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.880770343467845\]" |NULL           | NULL             |
| 3762        | "Traymore Cres"  | "1146129"  | 40             | 13467350 | NULL     | "Very High \(100% match\)"        | "..."        | "sth_geom" | "\[0,0\.872910068779091\]" | NULL           | NULL             |
| 3763        | "Traymore Cres"  | "1146129"  | 40             | 13467350 | 13467108 | "Very High \(100% match\)"        | "..."     | "sth_geom" | "\[0\.372174765194242,1\]" || NULL           | NULL             |
| 1806        | "Harvie Ave"     | "2350209"  | 30             | NULL     | NULL     | "High \(1 character difference\)" | "..."   | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.896704452511841\]" | NULL           | NULL             |
| 1805        | "Harvie Ave"     | "2350209"  | 40             | 13461402 | NULL     | "Very High \(100% match\)"        | "..."       | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.89770788980652\]"  |  NULL           | NULL             |
| 5148        | "Linnsmore Cres" | "8152788"  | 30             | NULL     | NULL     | "Very High \(100% match\)"        | "..." | "sth_geom"                                                                                                                                                                 | "\[0,0\.913145555879642\]" |  "2016\-06\-14" | NULL             |
| 5914        | "Linnsmore Cres" | "8152788"  | 30             | 13460655 | 13460252 | "High \(1 character difference\)" | "..."  | "sth_geom"                                                                                                                                                                 | "\[0\.209507981689479,1\]" |  "2018\-01\-16" | NULL             |
| 6696        | "Ameer Ave"      | "30061212" | 40             | NULL     | NULL     | "Very High \(100% match\)"        | "..."           | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.16226599206116\]"  | "2019\-06\-25" | NULL             |
| 84          | "Ameer Ave"      | "30061212" | 40             | NULL     | NULL     | "Very High \(100% match\)"        | "..."     | "sth_geom"                                                                                                                                                                                                 | "\[0,0\.162208246296917\]" | NULL           | NULL             |

**Comment by jovenc** [comment]
Have created another materialized view `jchew.bylaws_updated_next_part`. This view consists of a few parts. 

1. no_bylaw -> centrelines not involved in bylaws
2. whole_added -> centrelines involved in bylaws, be it fully or partially
3. part_one_without_bylaw -> parts of centrelines not involved in bylaws if there isnt a next applicable bylaw
4. part_two -> for the partial centrelines, include the next bylaw that applies to it if exists
5. part_two_without_bylaw -> for partial centrelines where the next_bylaw has been applied to it, the remaining part of the centreline not involved in the bylaws

```
CREATE MATERIALIZED VIEW jchew.bylaws_updated_next_part AS
--gis.centreline has 67769 rows
WITH whole AS(
--69487 rows (69303 rows if only include entire centreline)
SELECT bylaws.id AS bylaw_id, centre.lf_name, bylaws.geo_id, bylaws.speed_limit_km_per_h AS speed_limit, 
bylaws.int1, bylaws.int2, con, note, line_geom AS geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
bylaws.date_added, bylaws.date_repealed
FROM gis.centreline centre
LEFT OUTER JOIN jchew.bylaws_routing4_dates bylaws USING (geo_id)
WHERE (date_added < now()::date OR date_added IS NULL)  --Bylaw is in effect
AND (date_repealed > now()::date OR date_repealed IS NULL ) --Bylaw not repealed yet
--AND (section IS NULL OR section = '[0,1]')
)

, whole_added AS (
--21205 rows
SELECT DISTINCT ON (geo_id) bylaw_id, lf_name, geo_id, speed_limit, 
int1, int2, con, note, geom, section, 
oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
date_added, date_repealed
FROM whole
WHERE geo_id IS NOT NULL
ORDER BY geo_id, date_added DESC NULLS LAST, bylaw_id DESC
)

, no_bylaw AS (
--46564 rows
SELECT 
NULL::integer AS bylaw_id, lf_name, geo_id, 50 AS speed_limit, 
NULL::integer AS int1, NULL::integer AS int2, NULL::text AS con, NULL::text AS note, 
geom, NULL::numrange AS section, 
NULL::geometry AS oid1_geom, NULL::geometry AS oid1_geom_translated, 
NULL::geometry AS oid2_geom, NULL::geometry AS oid2_geom_translated, 
NULL::date AS date_added, NULL::date AS date_repealed
FROM gis.centreline
WHERE geo_id NOT IN (SELECT geo_id FROM whole_added)
)

, part_one AS (
--151 rows
SELECT * FROM whole_added
WHERE section IS NOT NULL AND section != '[0,1]'
)	

, next_bylaw AS (
SELECT b.id AS bylaw_id, b.lf_name, b.geo_id, b.speed_limit_km_per_h AS speed_limit, b.int1, b.int2, b.con, b.note, 
b.line_geom AS geom, CASE WHEN b.section IS NULL THEN '[0,1]' ELSE b.section END AS section, 
b.oid1_geom, b.oid1_geom_translated, b.oid2_geom, b.oid2_geom_translated, 
b.date_added, b.date_repealed 
FROM part_one one
INNER JOIN LATERAL 
(SELECT id, lf_name, geo_id,
 speed_limit_km_per_h, int1, int2, con, note, line_geom, section,
 oid1_geom, oid1_geom_translated, oid2_geom, oid2_geom_translated, 
 date_added, date_repealed
	FROM jchew.bylaws_routing4_dates bylaws
	WHERE bylaws.geo_id = one.geo_id
	AND (bylaws.date_added < one.date_added
		 OR bylaws.id < one.bylaw_id)
	ORDER BY date_added DESC NULLS LAST, bylaw_id DESC
	LIMIT 1) b 
	ON b.geo_id = one.geo_id
)		

, part_two AS (
--18 rows + 2 empty section ones
SELECT next_bylaw.bylaw_id, next_bylaw.lf_name, next_bylaw.geo_id, 
next_bylaw.speed_limit, next_bylaw.int1, next_bylaw.int2, next_bylaw.con, next_bylaw.note, 
ST_Difference(next_bylaw.geom, ST_Buffer(part_one.geom, 0.00001)) AS geom, 
(next_bylaw.section - part_one.section) AS section, 
next_bylaw.oid1_geom, next_bylaw.oid1_geom_translated, next_bylaw.oid2_geom, next_bylaw.oid2_geom_translated, 
next_bylaw.date_added, next_bylaw.date_repealed
FROM part_one
INNER JOIN next_bylaw
USING (geo_id, lf_name)
WHERE (next_bylaw.section - part_one.section) != 'empty' 
--some next_bylaw applied on the same section as the first_bylaw
)
, part_one_without_bylaw AS (
-- 133 rows
SELECT NULL::integer AS bylaw_id, cl.lf_name, geo_id, 50 AS speed_limit, 
NULL::integer AS int1, NULL::integer AS int2, NULL::text AS con, NULL::text AS note, 
ST_Difference(cl.geom, ST_Buffer(part_one.geom, 0.00001)) AS geom, (numrange(0.0,1.0) - part_one.section) AS section, 
NULL::geometry AS oid1_geom, NULL::geometry AS oid1_geom_translated, 
NULL::geometry AS oid2_geom, NULL::geometry AS oid2_geom_translated, 
NULL::date AS date_added, NULL::date AS date_repealed
	FROM part_one 
    INNER JOIN gis.centreline cl USING (geo_id)
	WHERE geo_id NOT IN (SELECT geo_id FROM part_two)
	GROUP BY cl.lf_name, geo_id, section, part_one.date_added, cl.geom, part_one.geom
	ORDER BY geo_id
)
, part_two_without_bylaw AS (
--only 1 row
SELECT NULL::integer AS bylaw_id, lf_name, geo_id, 50 AS speed_limit, 
NULL::integer AS int1, NULL::integer AS int2, NULL::text AS con, NULL::text AS note, 
ST_Difference (cl.geom, ST_Buffer(ST_Union(part_one.geom, part_two.geom), 0.00001) ) AS geom,
(numrange(0,1) - range_merge(part_one.section, part_two.section))::numrange AS section, 
NULL::geometry AS oid1_geom, NULL::geometry AS oid1_geom_translated, 
NULL::geometry AS oid2_geom, NULL::geometry AS oid2_geom_translated, 
NULL::date AS date_added, NULL::date AS date_repealed
FROM part_one
INNER JOIN part_two USING (geo_id, lf_name)
LEFT JOIN gis.centreline cl USING (geo_id, lf_name)
WHERE part_one.geo_id IN (SELECT geo_id FROM part_two)
AND range_merge(part_one.section, part_two.section) != '[0,1]'
)

SELECT * FROM no_bylaw
UNION
SELECT * FROM whole_added --included partial ones aka part_one
UNION
SELECT * FROM part_one_without_bylaw
UNION
SELECT * FROM part_two --to include next_bylaw for partial ones
UNION
SELECT * FROM part_two_without_bylaw
```
The results will look like this
![image](https://user-images.githubusercontent.com/54872846/80633066-273e3500-8a26-11ea-8455-434d4c01198a.png)
`date_added` is NULL for all bylaws shown in the figure above.

**Comment by jovenc** [comment]
Recording down the steps to update speed limit for highway 
```sql
--to create a table from the m. view to do the update
SELECT *
INTO jchew.bylaws_updated_final_hwy 
FROM jchew.bylaws_updated_final

--gardiner west of humber river (39 rows)
UPDATE jchew.bylaws_updated_final_hwy SET speed_limit = 100 
WHERE geo_id IN (913014,913062,913089,913152,913159,913172,913187,913249,913264,913354,913364,913367
,913403,913493,913503,913520,913534,913625,913633,913670,913677,913714,913720,913728
,913733,913748,913776,913783,913829,913835,913844,913864,913875,20043572,20043579,20043650,20043655,30005878,30005881);

--gardiner east of humber river (128 rows)
UPDATE jchew.bylaws_updated_final_hwy SET speed_limit = 90
WHERE lf_name ILIKE '%F G Gardiner Xy%' 
AND geo_id NOT IN 
(913014,913062,913089,913152,913159,913172,913187,913249,913264,913354,913364,913367
,913403,913493,913503,913520,913534,913625,913633,913670,913677,913714,913720,913728
,913733,913748,913776,913783,913829,913835,913844,913864,913875,20043572,20043579,20043650,20043655,30005878,30005881,
14646841,14646863,14646867); --last 3 are ramps in disguise

--highway 2a & 27 (88 rows)
UPDATE jchew.bylaws_updated_final_hwy SET speed_limit = 80
WHERE lf_name ILIKE '%highway 2%' ;

--highway 400 series (915 rows)
UPDATE jchew.bylaws_updated_final_hwy SET speed_limit = 100
WHERE lf_name ILIKE '%highway 4%' ;
 
--don valley parkway (127 rows)
UPDATE jchew.bylaws_updated_final_hwy SET speed_limit = 90
WHERE lf_name ILIKE '%don valley parkway%' ;

```
