### ISSUE TITLE
RESCU Data - Automate checking yesterday's pull

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#296]
Because of where the script for #291 will be located, we need to automate checking whether the script ran correctly (and things seem ok with the data) separately in airflow.

In a dag write a function that counts the number of rows of data for the previous day. If this seems low (or 0), trigger a slack message

**Comment by jovenc** [comment]
Created the dag to do the above but it appears to be broken now as the conn_id `rescu_bot` isn't defined. We need a postgres user for this checking purposes. I tried using `PostgresHook("jchew")` but that didn't seem to work too. Feel like there's sth that has to be done on pgAdmin first.
