### ISSUE TITLE
WYS-Bylaw output speed limit comparison 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#299]
@jovenc created a lookup table of WYS signs and speed limits `jchew.wys_stat_signs_speed_limit`. There are about 64 signs with different speed limits than from the processed bylaw. 

Can we spot check some of these differences, possibly by looking at the speed reductions layers, before handing over the list of signs to the WYSS team for further investigation?

Also a summary of the differences in speed limits between the two layers like

|speed limit bylaw | speed limit sign | count
|--------------------|------------------|------:|
|30                          |                  40    |  10    |
|30                          |                    50  |   7   |

Ultimately we want a list with:
- sign serial number
- bylaw speed limit
- sign speed limit
- median speed? mode of the speed bin?

**Comment by KatiRG** [comment]
Summary of differences:

![image](https://user-images.githubusercontent.com/1254764/81016896-4d514400-8e2f-11ea-85f9-06e6e5886cc2.png)

see notebook: https://github.com/CityofToronto/bdit_data_analysis/blob/wys_covid/wys/notebooks/wys_speed_limit_checks_issue299.ipynb

**Comment by KatiRG** [comment]
There are **28 signs** where the wyss limit > bylaw limit:

![image](https://user-images.githubusercontent.com/1254764/81066636-6566a900-8eab-11ea-8eb3-3bc20151698b.png)

There are **40 signs** where the wyss limit < bylaw limit:

![image](https://user-images.githubusercontent.com/1254764/81066841-bc6c7e00-8eab-11ea-9223-921a04dc55a7.png)
![image](https://user-images.githubusercontent.com/1254764/81066878-cc845d80-8eab-11ea-8c51-085909e751b6.png)

**Comment by KatiRG** [comment]
Spot checks on a few signs with Google Street View and [Open Data Portal](https://open.toronto.ca/dataset/traffic-and-parking-by-law-schedules/ ) (see Sch 35 Speed limit on public highways xml file).

![image](https://user-images.githubusercontent.com/1254764/81072665-78ca4200-8eb4-11ea-9aee-0dc9a717633e.png)

**Comment by radumas** [comment]
Sent an update to Jacqui including the above tables and 4 new signs

```sql
SELECT api_id, address, sign_name, wys_dir, start_date, wyss.speed_limit as sign_speed, bylaw.speed_limit as bylaw_speed, bylaW_id, date_added
	FROM jchew.wys_stat_signs_speed_limit bylaw
	INNER JOIN wys.sign_schedules_list USING (api_id)
	INNER JOIN wys.sign_schedules_clean wyss USING(schedule_name)
	WHERE start_date > '2020-04-04'  AND wyss.speed_limit != bylaw.speed_limit
```

We could automate checking this into our airflow process if they're interested. Waiting to get feedback from Jacqui on the locations we sent her.

I did note that a lot of the locations where the sign speed was lower than the speed limit don't have bylaws, so we are either:

- missing more up to date reductions
- failing to match bylaws at those locations
