### ISSUE TITLE
Revisit Miovision gap-filling process

### ISSUE THREAD

**Issue by jovenc** [CityofToronto/bdit_data-sources#310]
Revisiting the gap filling process since the current one seems to populate too many 15-minute bins with zeros.

Note:
- @aharpalaniTO had developed a process for this → can we transfer over?
- but wasn't Miovision developing something for downtime? Should follow up

**Comment by aharpalaniTO** [comment]
Hi @jovenc - I had done an investigation here: https://github.com/CityofToronto/bdit_data-sources/issues/294

Essentially, it comes down to the following:

a) Decide if the camera was up during that 15-minute period. If it was, populate all the relevant valid turning movements and classes with 0 if no record is present in the raw data

b) If the camera is down during that 15-minute period -> determine whether enough data exists from which you can interpolate (the current function does this). If it's completely missing, or doesn't meet some pre-determine criteria, ensure that all records for that 15-minute bin are dropped for that intersection (across all classes and movements)

This should be done at the TMC level, after which the ATRs will automatically be fixed.

This gets complicated so I'd propose creating a rough plan and then get feedback.

**Comment by jovenc** [comment]
Since we currently have a function to check if the machine is broken, I'm thinking about doing the following.
1. Create a new function similar to `miovision_api.determine_working_machine()` but return the relevant rows to get the time_min/gap_start and time_max/gap_end of the gap as well as the intersection_uid (the `gap_size` magic number might need to be modified). 
2. Modify the function `miovision_api.aggregate_15_min_tmc_test()`  and check if the 15min bin is within that gap by doing this. datetime_bin > gap_start and datetime_bin < gap_end (but this might be a little confusing when gap_end = '15:05' and the datetime_bin of '15:00' will be included too) . Which is why im thinking about generating 15min bin based on the gap_start and gap_end within the determine_working_machine function but not too sure what to do when the gap starts at '15:38'. We want that time_bin to be '15:38' to '15:45' and the next one will be '15:45' - '16:00' and not the usual 15min from that gap_start time. Is there a way around that?
3. If that 15min bin is not within the gap, then do the usual thg in the existing aggregate function.
4. If that 15min bin is entirely within the gap/partially within the gap, check if we can interpolate which is to check if there are at least 5 distinct time_bin within that 15min. If we cant, then delete all 15min bin for that intersection(across all classes and movements)? Or do we just want to delete those 15min that are within the gap?

**Questions:**
a. I feel like our definition of a camera not working is different, can we chat about that? Also, I'm unsure about which magic number to use.
b. Any suggestion on approaching the gap's time_bin that do not start at quarters of each hour?
c. Clarification on what to delete if the 15min bin is within the gap.

**Comment by radumas** [comment]
**WIP**

Per [Aakash's comment](https://github.com/CityofToronto/bdit_data-sources/issues/294#issuecomment-609548428), we should shift the interpolation focus to having decent data within an hour, rather than focusing on the 15-minute bins. I think the simple logic fix here would be:
If the hour bin overlaps with a camera outage, verify the [criteria outline by Aakash](https://github.com/CityofToronto/bdit_data-sources/issues/294#issuecomment-609548428), if yes, then set the 15-min bins within to NULL.

**Comment by jovenc** [comment]
Once #311 is done, the new gap filling process will not include any interpolation and the magic number/ gap_size will be obtained from the results of that issue as well.

The new process will be as followed:

- [ ] Check if the timebin is within the gap, no matter if it's fully or partial, remove everything. I.e. If gaps are from 7:15 to 8:30, drop everything between 7:00 and 9:00. 
(By removing I mean setting the volume to NULL instead of 0)

- [ ] **AND** put those data into another table in case we want to circle back.
The columns for the new table `intersection_outages` would be  `intersection_uid`, `intersection_uid`, `time range not included data` and maybe also a foreign key?

But before doing that,
first look into the past 3/4 months of data, look at them by the time of the day and check what percentage of data are getting dropped.

**Comment by jovenc** [comment]
Steps: (only done up to step 4 for now)
1. A function to find all gaps > minute  - `miovision_api.determine_gapsize_test()`
2. A mat view (to be refreshed daily) containing the hourly bin where the gap_size is unacceptable  - `miovision_api.gaps_unacceptable`
(might need to modify this function slightly to deal with gaps > 1 hour??? Will that be necessary?)
3. A table to keep all those "dumped" data - `miovision_api.intersection_outages`
(just realised I don't really need a foreign key since volume_uid is unique, right?)
4. A query to find those raw data within the hour found from step 2 and insert them into the table in step 3 - shown below

```SQL
INSERT INTO miovision_api.intersection_outages
WITH un AS 
(
SELECT DISTINCT ON (hourly_bin) intersection_uid, gap_start, gap_end, gap_minute, gap_size AS allowed_gap
FROM miovision_api.gaps_unacceptable
)
SELECT volume_uid , vol.intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume
FROM un 
LEFT JOIN miovision_api.volumes vol
ON un.intersection_uid = vol.intersection_uid
AND DATE_TRUNC('day', un.gap_start)::date = DATE_TRUNC('day', vol.datetime_bin)::date 
AND EXTRACT(hour FROM un.gap_start) = EXTRACT(hour FROM vol.datetime_bin) 
WHERE vol.datetime_bin >= '2020-07-15 00:00:00' --CHANGE WHEN READY, ONLY TIMESTAMP IS INDEXED NOT DATE O
AND vol.datetime_bin < '2020-07-16 00:00:00'
ORDER BY volume_uid, vol.intersection_uid
```

5. Modify `miovision_api.aggregate_15_min_tmc()` to exclude data in `miovision_api.intersection_outages` and interpolate the rest.

Question:
a) Am thinking about combining steps 1 - 4 into one big function? Would that be ideal?
b) Am kinda stuck on step 5, the current process is pretty complicated and I don't know where to start / how to approach

**Comment by jovenc** [comment]
Soooo, I combined steps  1 - 4 above into a big function named `miovision_api.remove_gaps()` which find gaps exceeded allowable gap_size and inter those bins into a new table named `miovision_api.intersection_outages`. 
(Might add RAISE NOTICE in that function later on).

I also use some errr not so pretty/organised way to include that process into the current aggregating function. (trying to minimise changes to the current function)
1. Exclude those 1min bin when aggregating and interpolating 
2. Current function: Generate series with 15min interval with volume = 0 (zero-padding) , aggregate insert into the tmc table. 
3. After that, set those 15min bin within the hour to volume = NULL (where the CTE is `set_null_vol`) before inserting zeroes into the zeroes table
You can find that in `miovision_api.aggregate_15_min_tmc_test_gap()`

Feel like there might be a better/cleaner way to do this?
Any advice?

**Comment by jovenc** [comment]
Oh ya, forgot to also include how much of the data is going to be removed for the new gap-filling process. So, using this query
```sql
WITH raw AS (
SELECT datetime_bin::date,  COUNT(*) AS raw_data_count, SUM(VOLUME) AS raw_sum_vol
FROM miovision_api.volumes
WHERE (datetime_bin >= '2020-07-05'::timestamp without time zone
AND datetime_bin < '2020-07-06'::timestamp without time zone)
OR (datetime_bin >= '2020-07-15'::timestamp without time zone
AND datetime_bin < '2020-07-16'::timestamp without time zone)
OR (datetime_bin >= '2020-06-22'::timestamp without time zone
AND datetime_bin < '2020-06-23'::timestamp without time zone)
OR (datetime_bin >= '2020-06-05'::timestamp without time zone
AND datetime_bin < '2020-06-06'::timestamp without time zone)
GROUP BY datetime_bin::date
)
, outage AS (
SELECT DISTINCT(datetime_bin::date) , COUNT(*) AS removed_data_count, SUM(VOLUME) AS removed_sum_vol
FROM miovision_api.intersection_outages
GROUP BY datetime_bin::date
)
SELECT datetime_bin, EXTRACT(isodow FROM datetime_bin) AS dow,
raw_data_count, raw_sum_vol, removed_data_count, removed_sum_vol
FROM raw
INNER JOIN outage USING (datetime_bin)
```

I found that the number of rows and total volume that will be removed from the new gap filling process varies greatly. But, on average, there are 3-4 hours of unreliable data that are being removed for each day. I have only tested it out on 4 days so far (picked randomly).

![image](https://user-images.githubusercontent.com/54872846/88184634-f1fa4b00-cc00-11ea-99da-f318e5948bdc.png)

**Comment by jovenc** [comment]
Sooo, in order to find out if the outages are somewhat uniformly distributed throughout the day, I ran the function `miovision_api.find_gaps()` to find every single unacceptable gaps from May 1st onwards (note that the acceptable gap size is based on past 60 days data for all of them aka the gap size is based on data from mid May to mid July) and below is the results I found. I separated them into two tables because 8 of them got decommissioned on June 15th, 2020. So the top table is for those old intersection that is not decommissioned and the bottom table is for those old intersection that got decommissioned on June 15th.

Total occurrences of unacceptable gaps for these 26 intersection = 392
![image](https://user-images.githubusercontent.com/54872846/88432783-db9feb00-cdca-11ea-874a-5826483d572d.png)

Total occurrences of unacceptable gaps for these 8 intersection = 37 
(Note that we dont have gaps at every hour of the day, missing 0400, 0500, 1000, 1100, 1800)
![image](https://user-images.githubusercontent.com/54872846/88433008-4a7d4400-cdcb-11ea-921e-aa07acff7746.png)


**OR if we want to look at all intersections together**
Total occurrences of unacceptable gaps for these 32 intersection = 429
![image](https://user-images.githubusercontent.com/54872846/88433225-a9db5400-cdcb-11ea-85b9-5d9181aefc45.png)


The query used is 
```sql
SELECT EXTRACT(hour FROM gap_start) AS hour_of_day, count(*) AS occurrences, 
ROUND(count(*)::numeric / 429 * 100, 2) AS pct 
FROM miovision_api.unacceptable_gaps
--WHERE intersection_uid IN (9,11,13,14,16,19,30,32)
GROUP BY EXTRACT(hour FROM gap_start)
ORDER BY EXTRACT(hour FROM gap_start)
```

**THOUGHTS:** It is not that uniformly distributed but are about 4% at each ohour with some outliers here and there especially at 1700, 2000. I checked those hours and nothing seems weird to me? 

If you are curious as to which intersection has the most gaps, below is the answer. Note that intersection_uid =14 (King/Simcoe) does not have any data/is weird and so is excluded.
![image](https://user-images.githubusercontent.com/54872846/88433816-ccba3800-cdcc-11ea-98cd-eb244f15d756.png)

**Comment by radumas** [comment]
So the lack of uniformity by time of day is a little concerning. Would it be possible to include... the type of gap ( I guess by the 3 volume bins) in these time of day distributions? It would also be nice to get an overall number for what proportion of hours of data we're throwing out.

**Comment by jovenc** [comment]
In order to show the type of gap in the time of day distribution, I aggregated the data (all intersections) as followed. (Is this actually easy for the eyes? Is this enough to show that?)
(0000 - 1159)
![image](https://user-images.githubusercontent.com/54872846/88595990-20798b00-d032-11ea-847c-c483603129e0.png)
(1200 - 2359)
![image](https://user-images.githubusercontent.com/54872846/88596056-4010b380-d032-11ea-8e98-9e96cfb4e60b.png)


In order to look at the proportion of hours of data we are throwing out, I have created a table `miovision_api.gaps_investigation` using the query

```sql
CREATE TABLE miovision_api.gaps_investigation AS
WITH dayy AS (
SELECT intersection_uid, DATE_TRUNC('day', datetime_bin) AS daily,  
	COUNT(*) AS daily_data_count, SUM(VOLUME) AS daily_sum_vol
FROM miovision_api.volumes
WHERE datetime_bin >= '2020-05-01'::timestamp without time zone
AND datetime_bin < '2020-07-01'::timestamp without time zone
GROUP BY intersection_uid, DATE_TRUNC('day', datetime_bin)
)
, hr AS (
SELECT intersection_uid, DATE_TRUNC('hour', datetime_bin) AS hourly,  
	COUNT(*) AS hr_data_count, SUM(VOLUME) AS hr_sum_vol
FROM miovision_api.volumes
WHERE datetime_bin >= '2020-05-01'::timestamp without time zone
AND datetime_bin < '2020-07-01'::timestamp without time zone
GROUP BY intersection_uid, DATE_TRUNC('hour', datetime_bin)
)
, outage AS (
SELECT intersection_uid, DATE_TRUNC('hour', gap_start) AS hourly
FROM miovision_api.unacceptable_gaps
)
SELECT outage.intersection_uid, hourly, hr_data_count, hr_sum_vol,
daily_data_count, daily_sum_vol,
ROUND(hr_data_count::numeric / daily_data_count::numeric * 100,3) AS count_pct,
ROUND(hr_sum_vol::numeric / daily_sum_vol::numeric * 100,3) AS vol_pct
FROM hr
INNER JOIN outage USING (intersection_uid, hourly)
INNER JOIN dayy ON dayy.intersection_uid = outage.intersection_uid AND dayy.daily = outage.hourly::date
```

_Note that the following is only looking at 2 months worth of data (May & June 2020)_
There are 352 gaps in total in these two months.

**Comment by jovenc** [comment]
So, Raph mentioned that the amount of data we are throwing away because of the gaps are a little too much? We are throwing away a full hour of data when there is a gap >= 2 minutes for intersection with high volume. (I personally find that the 2 minutes is a little too smol?)

Therefore, I am trying to find out the results if the allowed gap size is modified. According to the results on this [volume vs gap notebook](https://github.com/CityofToronto/bdit_data-sources/blob/miovision_api_bugfix/volumes/miovision/volume_vs_gaps.ipynb), I found the point/gap size where `cumu_pct_desc` is about 0.02. That means that for each volume category, we are only removing about 0.02% of the data. 

A little before and after "picture" here for better comparison.
# Before
|avg_vol|allowed gap size|
|----|----|
volume [0,99)| 20 mins
volume [100,499)| 10 mins
volume [500,1499)| 5 mins
volume [1500,∞)| 2 mins

Based on the volumes data from May 1st - June 30th, we found that there are 352 gaps in total with the following details.
|allowed gap|count|
|---|---|
2|131
5|133
10|80
20|8

Time of day distribution
![image](https://user-images.githubusercontent.com/54872846/88719025-a0fec100-d0f0-11ea-81a4-e5c7eb5970fc.png)

Proportion of data being removed (I calculated the total volume and count of data in that hour as well as that of that day and find the percentage). I am only showing the average here for each intersection but you can find out more at `miovision_api.gaps_investigation`. 
*OOOPS, forgot to rename my column but the 2nd column is `avg_count_pct` and the last column is `avg_vol_pct`*
![image](https://user-images.githubusercontent.com/54872846/88720220-8299c500-d0f2-11ea-9efc-28a55bd78141.png)

# After
|avg_vol|allowed gap size|
|----|----|
volume [0,99)| 20 mins
volume [100,499)| 17 mins
volume [500,1499)| 14 mins
volume [1500,∞)| 8 mins

Based on the volumes data from May 1st - June 30th, we found that there are 81 gaps in total with the following details.
|allowed gap|count|
|---|---|
8|50
14|7
17|16
20|8

Time of day distribution
![image](https://user-images.githubusercontent.com/54872846/88719065-af4cdd00-d0f0-11ea-87d7-bf0dc49b6b76.png)

Proportion of data being removed (I calculated the total volume and count of data in that hour as well as that of that day and find the percentage). I am only showing the average here for each intersection but you can find out more at `miovision_api.gaps_investigation_modified`.  
**NOTE that not all intersections have gaps. Intersections without unacceptable gaps are 1,3,10,11,13,16,17,19,21,23,32
![image](https://user-images.githubusercontent.com/54872846/88720781-6e09fc80-d0f3-11ea-9432-99094344a48e.png)

### Conclusion
It doesn't seem to have a fix distribution? I am wondering what are the other things that we have to consider to draw a conclusion on the gap size to use.
