### ISSUE TITLE
Updating Bluetooth Segments: process should use routing now

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#317]
After matching intersections to Bluetooth detector locations, should be using routing in the centreline network rather than drawing a straight line between the two points as outlined [here](https://github.com/CityofToronto/bdit_data-sources/blob/master/bluetooth/update/README.md#explanation-of-query).

- [x] Identify routes which are missing segments.
- [ ] Update process for drawing in segments using routing on centreline
- [ ] Update documentation on how to use
- [ ] Draw segments for the new ~Bloor~ Routes

**Comment by radumas** [comment]
Natalie has explained how to use routing https://github.com/CityofToronto/bdit_data-sources/issues/234 should just update the documentation to use that process.

**Comment by radumas** [comment]
I think the only segment that needs to be drawn will be the new Bloor routes. 

- [ ] Check that all the "missing segments" in `mohan.missing_segments` are actually drawn in `natalie.bluetooth_routed` see #234

**Comment by webgisgeek** [comment]
> I think the only segment that needs to be drawn will be the new Bloor routes.
> 
> * [x]  Check that all the "missing segments" in `mohan.missing_segments` are actually drawn in `natalie.bluetooth_routed` see #234

All the mohan.missing_segments are actually drawn in natalie.bluetooth_routed.

**Comment by radumas** [comment]
Thanks for checking! 

I just updated the first comment text to clarify we want to draw all newly created segments. 

Plopping the image of those here too

![image](https://user-images.githubusercontent.com/10623872/98127874-3397c480-1e85-11eb-894c-b370c20ae592.png)

**Comment by chmnata** [comment]
It is now using routing!
