### ISSUE TITLE
Duplicate Key roadblocks when pulling data for a same day

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#324]
- `miovision_api.volumes`
- `miovision_api.unacceptable_gaps`
probably
- `miovision_api.volumes_15min_tmc`
- `miovision_api.volumes_15min`

I think bypassing the unique key for `volumes` is ok, aggregation might not work well

**Comment by radumas** [comment]
You could add `ON CONFLICT DO NOTHING` to the `INSERT` statements in this trigger

https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/sql/trigger-volumes_insert_trigger.sql

**Comment by cczhu** [comment]
Managed to screw this up and added duplicates using `python intersection_tmc.py run-api` using settings `--start_date 2019-07-10 --end_date 2019-07-12 --intersection 2`. Will delete duplicates.

**Comment by cczhu** [comment]
Also managed to screw up the fix by putting `ON CONFLICT` in the `INSERT` command in Python rather than in the trigger. Fixed with [567ea9](https://github.com/CityofToronto/bdit_data-sources/commit/567ea906c3b98cd58a0520618bb348d5346f60bf).

**Comment by radumas** [comment]
After what happened I think that the `UNIQUE` constraint on the child tables don't prevent the bulk insert from failing, which might be why we added the exception detection in the TRIGGER and add logic in the script to fail loudly when duplicate data is inserted (which unfortunately doesn't prevent the insert from succeeding)

https://github.com/CityofToronto/bdit_data-sources/blob/a22e407b09534dc01da99e15893725c2917f0248/volumes/miovision/sql/trigger-volumes_insert_trigger.sql#L23-L26
