### ISSUE TITLE
Update Miovision API script to deal with classification "MotorizedVehicle"

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#329]
This is not being dealt with in the current Python script and results in `classification_uid = 0`.

https://github.com/CityofToronto/bdit_data-sources/blob/a22e407b09534dc01da99e15893725c2917f0248/volumes/miovision/api/intersection_tmc.py#L121-L136

- [x] So a new classification needs to be created in the script and in the `classification` table

- [x] All records after 2019-11-07 with `classification_uid = 0` should get updated to the new number

- [x] Honestly the script should fail if the classification is unknown 

- [ ] New `intersection_movements` need to be created for the new classification, this could be done similarly to point 2 under [Adding Intersections](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/miovision#adding-intersections)

**Comment by cczhu** [comment]
Should we raise `ValueError` rather than `return '0'` in `get_classification` to solve that third point?

**Comment by radumas** [comment]
Ya that seems like an elegant solution

**Comment by radumas** [comment]
Added created new `intersection_movements` to task list

**Comment by cczhu** [comment]
> Added created new `intersection_movements` to task list

The link currently goes to the TPS challenge 😹

**Comment by radumas** [comment]
lol I need to actually copy the URL from the address bar, not just click on the 🔗 button

**Comment by cczhu** [comment]
Cool, sounds like I can do

```sql
INSERT INTO miovision_api.intersection_movements
      ( intersection_uid, classification_uid, leg, movement_uid )
SELECT intersection_uid,
       '9'::integer AS classification_uid,
       leg,
	   movement_uid
FROM miovision_api.intersection_movements 
WHERE classification_uid = 1
```

to update the valid movements. Is it an issue that `miovision_api.intersection_movements` will no longer be sorted?
