### ISSUE TITLE
Have the script attept to re-pull queries that return HTTP 500 errors

### ISSUE THREAD

**Issue by cczhu** [CityofToronto/bdit_data-sources#335]
Recently discovered that querying Bay / King on 2020-09-24 from 12:00 to 18:00 by using

```python
import psycopg2
import pytz
import requests
import json

postgres_settings = POSTGRES_CREDS
miov_token = MIOVISION_KEY

local_tz = pytz.timezone('US/Eastern')

url = 'https://api.miovision.com/intersections/' 
tmc_endpoint = '/tmc'

headers = {'Content-Type':'application/json', 'Authorization': miov_token}

# Generator for cycling through 6-hour time blocks.
def timerange(start_time, end_time, dt):
    for i in range(math.ceil((end_time - start_time) / dt)):
        c_start = start_time + i * dt
        c_end = min(c_start + dt, end_time)
        yield (c_start, c_end)

def get_raw_api_call(start_time, end_time, dt, intersection_id):
    tmc_all = []

    for (c_start_t, c_end_t) in timerange(start_time, end_time, dt):
        params = {'endTime': c_end_t, 'startTime' : c_start_t} 
        response=requests.get(url + intersection_id + tmc_endpoint,
                              params=params, headers=headers)
        tmc = json.loads(response.content.decode('utf-8'))
        tmc_all += tmc
    return tmc_all

start_time = local_tz.localize(datetime.datetime(2020, 9, 24, 12, 0, 0))
end_time = local_tz.localize(datetime.datetime(2020, 9, 25, 18, 1, 0))
dt = datetime.timedelta(hours=6)
intersection_id = "218ca562-44fc-41d3-80ac-213db6672c9e"
# I'm using my generic `get_raw_api_call` from `02 - Test New Data Insertion.ipynb`, but this
# will only cycle through that function's for loop once.
raw_tmc = get_raw_api_call(start_time, end_time, dt, intersection_id)

print(raw_tmc[-5:])
```

```
[{'timestamp': '2020-09-25T05:59:00.000-04:00', 'class': 'Light', 'entrance': 'S', 'exit': 'N', 'qty': 2}, {'timestamp': '2020-09-25T05:59:00.000-04:00', 'class': 'Light', 'entrance': 'W', 'exit': 'E', 'qty': 2}, 'error', 'error', 'error']
```

results in `'error'` being returned for the last three elements of the `raw_tmc` list. Currently in `intersection_tmc.py` the raw output of the JSON dump is fed through the loop

https://github.com/CityofToronto/bdit_data-sources/blob/89941363a54d9a272394d380eed9cb04f8edaaf1/volumes/miovision/api/intersection_tmc.py#L151-L157

which will return an error when attempting to unpack `item['class']`. This isn't picked up by any of our error handling, so we'll need to write an additional control block to handle these.

**Comment by cczhu** [comment]
We should also check whether there currently are lots of 6-hour gaps in the raw data. If there are, we'll need to update the data again.

**Comment by cczhu** [comment]
Straightforward check - find all days in the last two months where the number of distinct timestamps for light autos is less than around 80% of complete (complete being 1440 per day):

```sql
SELECT intersection_uid, datetime_bin::date, COUNT(DISTINCT datetime_bin) n_unique_timestamps
FROM miovision_api.volumes
WHERE datetime_bin BETWEEN '2020-08-01 00:00:00' AND '2020-09-24 23:59:59' AND classification_uid = 1
GROUP BY intersection_uid, datetime_bin::date
HAVING COUNT(DISTINCT datetime_bin) < 1200
ORDER BY 1, 2
```

This returns

**intersection_uid**|**datetime_bin**|**n_unique_timestamps**
:-----:|:-----:|:-----:
5 |2020-09-24|1172
6 |2020-09-23|1074
8 |2020-08-02|1181
15|2020-08-02|1140
15|2020-09-24|1040
17|2020-09-24|1018
18|2020-09-24|666
20|2020-09-24|1024
21|2020-09-24|846
23|2020-09-24|1077
25|2020-08-02|1153
25|2020-08-03|1197
26|2020-09-24|1024
28|2020-09-24|1050
29|2020-08-02|1143
29|2020-09-24|1061
31|2020-09-24|1041
33|2020-09-24|1068
40|2020-09-24|1056

So we're only encountering this issue as of today, with no such problems throughout August and early September.

**Comment by cczhu** [comment]
Revised `intersection_tmc.py` to handle cases where a list of data is successfully retrieved but some list elements aren't dicts. Test-ran the script with:

```
python intersection_tmc.py run-api --path /etc/airflow/data_scripts/volumes/miovision/api/config.cfg --start_date 2020-09-22 --end_date 2020-09-25 --pull &> log_refresh_sept2324.txt
```

but of course now all the `'error'` entries coming from the API have disappeared! Tried

```sql
SELECT intersection_uid, datetime_bin::date, COUNT(DISTINCT datetime_bin) n_unique_timestamps
FROM miovision_api.volumes
WHERE datetime_bin BETWEEN '2020-08-01 00:00:00' AND '2020-09-28 23:59:59' AND classification_uid = 1
GROUP BY intersection_uid, datetime_bin::date
HAVING COUNT(DISTINCT datetime_bin) < 1200
ORDER BY 1, 2
```

again and found issues only from 2020-09-25 onward (though those issues exist for multiple intersections). Of note,

```sql
SELECT *
FROM miovision_api.volumes
WHERE intersection_uid = 17 AND datetime_bin BETWEEN '2020-09-26 00:00:00' AND '2020-09-27 00:00:00' AND classification_uid = 1
```

returns only 3205 rows, and appears to be missing any data from 06:00 - 12:00. If I run the Python script [above](https://github.com/CityofToronto/bdit_data-sources/issues/335#issue-709035708) using 

```python
start_time = local_tz.localize(datetime.datetime(2020, 9, 26, 0, 0, 0))
end_time = local_tz.localize(datetime.datetime(2020, 9, 27, 0, 1, 0))
dt = datetime.timedelta(hours=6)
intersection_id = "218ca562-44fc-41d3-80ac-213db6672c9e"
```

I get 1406 unique timestamps and 4111 rows where `classification_uid=1`. Plotting volumes of light vehicles from the two data sources, we clearly see a 6-hour gap in data *which is now completely accessible by the API*.

![image](https://user-images.githubusercontent.com/442891/94375454-b9d02680-00e1-11eb-8673-e40979df2bca.png)

This is therefore an issue that seems to affect early-morning pulls which is subsequently fixed in the API! We'll need to confirm tomorrow at ~8:00 to ensure this is the case. If it is, we'll still need to implement the fix to the API script.

**Comment by cczhu** [comment]
Annoyingly it no longer seems possible to reproduce the `error` list entries bug discovered a few days prior, but the Miovision API retrieval failures persist. I hacked `intersection_tmc.py` to reproduce the `response.status_code` value and got:

```
Unknown status code 500 pulling tmcs for intersection 151ee827-dd49-4ad4-af21-dde5d7032c21
```

among a number of other 500 errors during the most recent Miovision pull (8:00 on 2020-09-29). Attempting a manual pull in Python (9:30 same day):

```python
import psycopg2
import pytz
import requests
import json

postgres_settings = POSTGRES_CREDS
miov_token = MIOVISION_KEY

local_tz = pytz.timezone('US/Eastern')

url = 'https://api.miovision.com/intersections/' 
tmc_endpoint = '/tmc'

headers = {'Content-Type':'application/json', 'Authorization': miov_token}

# Generator for cycling through 6-hour time blocks.
def timerange(start_time, end_time, dt):
    for i in range(math.ceil((end_time - start_time) / dt)):
        c_start = start_time + i * dt
        c_end = min(c_start + dt, end_time)
        yield (c_start, c_end)

def get_raw_api_call(start_time, end_time, dt, intersection_id):
    tmc_all = []

    for (c_start_t, c_end_t) in timerange(start_time, end_time, dt):
        params = {'endTime': c_end_t, 'startTime' : c_start_t} 
        response=requests.get(url + intersection_id + tmc_endpoint,
                              params=params, headers=headers)
        tmc = json.loads(response.content.decode('utf-8'))
        tmc_all += tmc
    return tmc_all

start_time = local_tz.localize(datetime.datetime(2020, 9, 28, 0, 0, 0))
end_time = local_tz.localize(datetime.datetime(2020, 9, 29, 0, 1, 0))
dt = datetime.timedelta(hours=6)
intersection_id = "151ee827-dd49-4ad4-af21-dde5d7032c21"
# I'm using my generic `get_raw_api_call` from `02 - Test New Data Insertion.ipynb`, but this
# will only cycle through that function's for loop once.
raw_tmc = get_raw_api_call(start_time, end_time, dt, intersection_id)

print(raw_tmc[-5:])
```

successfully returns (with status code 200):

```
[{'timestamp': '2020-09-28T23:59:00.000-04:00', 'class': 'Light', 'entrance': 'N', 'exit': 'W', 'qty': 1}, {'timestamp': '2020-09-28T23:59:00.000-04:00', 'class': 'Light', 'entrance': 'S', 'exit': 'N', 'qty': 2}, {'timestamp': '2020-09-29T00:00:00.000-04:00', 'class': 'Bus', 'entrance': 'E', 'exit': 'W', 'qty': 1}, {'timestamp': '2020-09-29T00:00:00.000-04:00', 'class': 'Light', 'entrance': 'N', 'exit': 'S', 'qty': 1}, {'timestamp': '2020-09-29T00:00:00.000-04:00', 'class': 'Light', 'entrance': 'S', 'exit': 'N', 'qty': 4}]
```

rather than a code 500.

Meanwhile

```
SELECT DISTINCT datetime_bin
FROM miovision_api.volumes
WHERE intersection_uid = 12 AND datetime_bin BETWEEN '2020-09-28 00:00:00' AND '2020-09-29 00:00:00'
```

shows no data between 0:00 - 6:00.

**Comment by radumas** [comment]
There's already error handling for a variety of other errors the API throws for the `get_tmc()` and `get_pedestrian()` calls to the API.

https://github.com/CityofToronto/bdit_data-sources/blob/89941363a54d9a272394d380eed9cb04f8edaaf1/volumes/miovision/api/intersection_tmc.py#L319-L340

This is what decoding the response for those calls to the API looks like. The 500 error is not explicitly getting caught so the function returns a `MiovisionAPIException` which means the script stops attempting to pull data for that intersection and time. 

https://github.com/CityofToronto/bdit_data-sources/blob/89941363a54d9a272394d380eed9cb04f8edaaf1/volumes/miovision/api/intersection_tmc.py#L183-L209

Instead, a 500 error should trigger a similar wait and try again protocol.

**Comment by cczhu** [comment]
Irritatingly the issue in my Jupyter notebooks discussed [above](https://github.com/CityofToronto/bdit_data-sources/issues/335#issue-709035708) can't be reproduced. Meanwhile, we've found that the 6-hour blocks of missing data correspond with HTTP 500 errors. Currently testing the fix discussed in [this comment](https://github.com/CityofToronto/bdit_data-sources/issues/335#issuecomment-700785331) and will consider the issue resolved if that succeeds.

**Comment by radumas** [comment]
As mentioned yesterday, there's a big flaw with this error handling structure, the data returned is being appended to the `table` variable before those two statements complete successfully without exceptions. So if `get_pedestrian()` throws an error, then `table` will contain the results of `get_intersection_tmc()` twice.

https://github.com/CityofToronto/bdit_data-sources/blob/9243c53cb576833a099c23a6142a6ec08c192189/volumes/miovision/api/intersection_tmc.py#L327-L331

the solution would be to do `table.extend()`  after the `except` blocks.

**Comment by cczhu** [comment]
Finished pulling 2020 data. To QC the results, ran

```
SELECT intersection_uid, datetime_bin::date, COUNT(DISTINCT FLOOR(EXTRACT(HOUR from datetime_bin) / 6)) n_sixhourbins
FROM miovision_api.volumes
WHERE datetime_bin BETWEEN '2020-01-01 00:00:00' AND '2020-09-28 23:59:59' AND classification_uid = 1
GROUP BY intersection_uid, datetime_bin::date
HAVING COUNT(DISTINCT FLOOR(EXTRACT(HOUR from datetime_bin) / 6)) < 4
ORDER BY 1, 2
```

which returned 31 rows. Following up on a subsection of these, no intersection-date combinations examined show the telltale sign of missing exactly a six-hour block.

Interestingly, Richmond / Spadina in late February had its camera turned off from 8 AM - 5 PM every day for 5 days.

```
SELECT DISTINCT datetime_bin::date, EXTRACT(HOUR from datetime_bin)
FROM miovision_api.volumes
WHERE intersection_uid = 27 AND datetime_bin BETWEEN '2020-02-20 00:00:00' AND '2020-02-27 23:59:59'
ORDER BY 1, 2
```

Also, looking at the logs generated after pulling 1 year's worth of data from the Miovision API reveals something interesting. Back when we refreshed 2020 data on 2020-09-23, there was only a single instance of `Error500`, but when we pulled 2019 data on 2020-09-26, there were 2700. In the 2020 data re-pull from yesterday there were 350 `Error500`. I'm wondering if this is a recent trend with the API?
