### ISSUE TITLE
Bug in Miovision gap finding process for setting data to `NULL`

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#338]
`BETWEEN` is an inclusive operator.

`a BETWEEN x AND y`

is equivalent to

`a >= x AND a <= y`

https://github.com/CityofToronto/bdit_data-sources/blob/263464d1ffdeff12bb57a4aae1f6bfb044332402/volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql#L37-L38

**Comment by cczhu** [comment]
Resolved by #344.
