### ISSUE TITLE
New Miovision API crashes our pipeline

### ISSUE THREAD

**Issue by cczhu** [CityofToronto/bdit_data-sources#374]
Today we discovered that the API has been breaking for the last several days because the crosswalkTMC feed is now reporting bicycles as well as pedestrians crossing at crosswalks. For example, using the Miovision API, for `intersectionID = cc869625-3a14-447f-9156-38283845c47b` from `startTime = 2021-01-03T18:30` to `endTime = 2021-01-03T18:40`, we're getting:

```
...
  {
    "timestamp": "2021-01-03T18:35:00.000-05:00",
    "class": "Bicycle",
    "direction": "CCW",
    "crosswalkSide": "E",
    "qty": 1
  },
  {
    "timestamp": "2021-01-03T18:35:00.000-05:00",
    "class": "Pedestrian",
    "direction": "CCW",
    "crosswalkSide": "E",
    "qty": 1
  },
...
```

We discovered this issue because Raph recently changed the way the volume insert triggers to `miovision_api.volumes_2020` and `miovision_api.volumes_2021` handle duplicates, so it's likely this has been an issue whenever bikes in crosswalks started being included in the streaming data. Before, `intersection_tmc.py` would [incorrectly relabel](https://github.com/CityofToronto/bdit_data-sources/blob/18e300aba8aa270a66f198b7fba02dd1a16219b1/volumes/miovision/api/intersection_tmc.py#L207) any volume at a crosswalk as a pedestrian volume, meaning there is incorrect/excessive ped volumes in the API tables. It's also possible (since the CSV processes mirror the API ones) that the same error exists in the CSV tables.

Things that need to be fixed:
- `intersection_tmc.py` needs to be modified to treat bikes in crosswalk as a Class 7.
- The aggregation process for both API and CSV needs to be updated to handle class 7 movements. This includes appending valid movements in `miovision_api.intersection_movements`.
- We'll need to drop and reaggregate all pedestrian data from the day when bikes in crosswalks came online.

As a stopgap measure, we can hack the `intersection_tmc.py` script to drop any volumes that aren't peds.

**Comment by cczhu** [comment]
I should have noticed this earlier (because why would they only include bike in crosswalk volumes and not also the bike approach volumes) - Miovision is now also including bike approach and departure volumes, which the API is not equipped to handle. For example, for `intersectionId = 2cd73fbd-a5c2-4083-80f4-c487c114f48b` from `startTime = 2021-01-01T12:40:00` to `endTime = 2021-01-01T12:45:00`

```sql
...
  {
    "timestamp": "2021-01-01T12:43:00.000-05:00",
    "class": "Bicycle",
    "entrance": "UNDEFINED",
    "exit": "S",
    "qty": 1
  },
  {
    "timestamp": "2021-01-01T12:43:00.000-05:00",
    "class": "Bicycle",
    "entrance": "UNDEFINED",
    "exit": "W",
    "qty": 1
  },
...
```

 What had thrown me in for a loop was that I had expected the API to fail loudly when faced with approach volumes. Instead,  [get_movement defaults to '4' as its output](https://github.com/CityofToronto/bdit_data-sources/blob/0b7807986125a9cd7b7a4ee8cb2c1343ddd2fa34/volumes/miovision/api/intersection_tmc.py#L129) if faced with unknown inputs.

**Comment by cczhu** [comment]
@aharpalaniTO found a fun fact - since the new bike approach volumes default to `'4'`, we should see a large spike of u-turning bikes in our data whenever Miovision turned on the new API:

```sql
SELECT datetime_bin, SUM(volume)
FROM miovision_api.volumes_15min_tmc
WHERE classification_uid = 2 AND movement_uid = 4 AND datetime_bin >= '2020-12-10'
GROUP BY datetime_bin
ORDER BY 1
```

and behold:


datetime_bin | sum
-- | --
2020-12-10 | 46
2020-12-11 | 59
2020-12-12 | 71
2020-12-13 | 31
2020-12-14 | 2605
2020-12-15 | 5492
2020-12-16 | 3693
2020-12-17 | 7241
2020-12-18 | 11213
2020-12-19 | 7631
2020-12-20 | 6253
2020-12-21 | 10021

**Comment by cczhu** [comment]
We've decided to drop all the improperly imported API data from 2020-12-14 to 2020-12-31 and re-run the interim API puller for those dates. Meanwhile Aakash has asked for a CSV dump of those dates as well, and we'll consider how to handle bike approaches and bicycles in crosswalks at a future date.

Deleted all data from `miovision_api` volumes and record tables from December 14th to 31st inclusive. Backfilled data using `airflow backfill pull_miovision_testcwbikes -m -s 2020-12-14 -e 2020-12-31T23:59:00`. This, it turns out, generates the tasks but doesn't run them. For reasons I'm still not sure I understand, I needed to re-run each using `airflow test pull_miovision_testcwbikes pull_miovision_testcwbikes {date}` rather than clearing the task in the GUI.

**Comment by cczhu** [comment]
Found a very odd issue - If I run the crosswalkTmc API using intersectionID = 7876a959-a1ab-48fe-ada6-0411c174643f, endTime = 2020-12-22T18:00 and startTime = 2020-12-22T17:00, I get a final entry at 18:00:

```
  {
    "timestamp": "2020-12-22T18:00:00.000-05:00",
    "class": "Pedestrian",
    "direction": "CW",
    "crosswalkSide": "N",
    "qty": 1
  }
```

If the end time is not 18:00, *this entry disappears*.

I'm pretty sure this is a bug.

**Comment by cczhu** [comment]
Found another one - if I run the tmc API using intersection = 13711f91-de04-4fe7-9301-a12b2c2b68d3, endTime = 2021-01-05T18:00, startTime = 2021-01-05T17:59, I obtain an extra row at 18:00:

```
  {
    "timestamp": "2021-01-05T18:00:00.000-05:00",
    "class": "Light",
    "entrance": "N",
    "exit": "S",
    "qty": 1
  }
```

If I switch endTime to 2021-01-05T18:01, this row is no longer returned.

**Comment by cczhu** [comment]
Data has been backfilled, and

```sql
SELECT datetime_bin::date, SUM(volume)
FROM miovision_api.volumes_15min_tmc
WHERE datetime_bin >= '2020-12-10' AND classification_uid = 2 AND movement_uid = 4
GROUP BY datetime_bin::date
ORDER BY 1
```

returns

datetime_bin | sum
-- | --
2020-12-10 | 46
2020-12-11 | 59
2020-12-12 | 71
2020-12-13 | 31
2020-12-14 | 103
2020-12-15 | 142
2020-12-16 | 108
2020-12-17 | 289
2020-12-18 | 443
2020-12-19 | 286
2020-12-20 | 254

which is much more sensible, though still a bit unusual in the number of u-turns by bikes.

**Comment by aharpalaniTO** [comment]
Hi Charles - ran some quick checks against `miovision_api.volumes_15min` for December 2020 and January 2021 (until yesterday) and generally looks fine. Noticed the following:

- All data missing for `intersection_uid` = 43 from January 4th onward
- not sure if intentional, but classification_uid = 7 is currently not in `miovision_api.classifications`
- cyclist volumes seem abnormally high on December 18th (especially given weather wasn't any warmer). looks fine on the surface however.
- As you mentioned, there is definitely still an increase in u-turning bikes from December 17th onwards, although not as obvious as before. There is some pretty weird stuff at the intersection level if you run the following query for the pct of bike volume that are u-turns:
```
SELECT datetime_bin::date, intersection_uid, intersection_name, ROUND(SUM(CASE WHEN movement_uid = 4 THEN volume ELSE 0 END) / SUM(volume+0.001),4) as pct_uturn
FROM miovision_api.volumes_15min_tmc
INNER JOIN miovision_api.intersections USING (intersection_uid)
WHERE datetime_bin >= '2020-12-01' AND classification_uid = 2
GROUP BY datetime_bin::date, intersection_uid, intersection_name
ORDER BY intersection_uid, datetime_bin::date
```
Obvious one is Ellesmere and Morningside, where for the first ~10 days in December u-turns make up a significant (~20-25% of all bike volume), but then is 0 after that. I'd just like to confirm this is present in the API itself (or we can just get the CSV dump and compare that - probably easier), and then ask Miovision what is going on.


The base query I used was
```
SELECT datetime_bin::date, intersection_uid, classification_uid, classification, count(1) as records, SUM(volume) as total_volume
FROM miovision_api.volumes_15min
INNER JOIN miovision_api.classifications USING (classification_uid)
WHERE datetime_bin >= '2020-12-01'
GROUP BY classification_uid, intersection_uid, datetime_bin::date, classification
ORDER BY classification_uid, intersection_uid, datetime_bin::date
```

**Comment by cczhu** [comment]
Thanks @aharpalaniTO!

- I've checked that Danforth / Logan is missing data starting on 2021-01-04 in the Miovision API itself, and contacted Brent about it.
- This is intentional. Supporting that data requires that we include it in `miovision_api.intersection_movements` and I still have concerns about that table I think should be resolved alongside revamping the entire API to support bike approach volumes.
- Yeah I have no idea why that's happening, and am worried there may be some strange double-counting going on there. 
- From the query above it looks like only Ellesmere & Morningside actually suffers from an extreme number (>5%) of cyclist U-turns per day. If you set the `datetime_bin` further back this seems to be an issue with data *before* the API change, going back to when the station first came online. It also exists in `miovision_csv` and, as I just checked, in the raw Miovision API. I'll ask Brent.

**Comment by cczhu** [comment]
Follow up from [this](https://github.com/CityofToronto/bdit_data-sources/issues/374#issuecomment-755303374) comment earlier - according to Brent (e-mail 2020-01-07) this is expected behaviour because individual detections (with timestamps with millisecond precision) are stored in their data lake, and aggregated up to the minute when the API is called. The `startTime` and `endTime` variables in the API are *inclusive* for this aggregation. Since there are so few detections that occur within 1 ms of `endTime`, having an extra bin with `datetime_bin = endTime` is rare, but will still occur every once in a while.

The solution, which I already implemented in [74a239](https://github.com/CityofToronto/bdit_data-sources/commit/74a2392491bb8098c12bc779d63ea10277d4505c), is to offset the endTime of a query by 1 ms. This ensures our time intervals are exclusive of `endTime`.

**Comment by cczhu** [comment]
Update about Ellesmere & Morningside. From Brent (e-mail 2021-01-11):

> Looking at the configuration from Ellesmere and Morningside - this appears to be how the U-turn was originally configured. Its movement was drawn in a way that was capturing false positives but was corrected when we pushed the upgraded configurations out on Dec 8th. 

So yes, it's anomalous. Based on previous comments, Miovision doesn't store high-res camera footage for long enough to re-process months-old counts.
