### ISSUE TITLE
WYS API includes NULL rows

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#388]
Since March 31st the API has been returning some rows with no speed or count. All API values are encoded as string, so they are implicitly converted to timestamps and numeric types, but empty strings fail that implicit conversion.

```python
[2021-04-06 18:59:17,606] {logging_mixin.py:112} INFO - [2021-04-06 18:59:17,606] {wys_api.py:297} CRITICAL - invalid input syntax for integer: ""
LINE 3: ...,'59','1'),(9632,'2021-03-31T03:19:00'::timestamp,'',''),(96...
```

We should ask the vendor what's up with these values, but we can also prevent the script from failing by ensuring that empty strings are treated as null. In the below assignment, this could be explicit with `int(i) if i else None` ([source](https://www.geeksforgeeks.org/python-empty-string-to-none-conversion/) [and](https://www.pythonpool.com/python-inline-if/)). 

https://github.com/CityofToronto/bdit_data-sources/blob/f64364c59307353a2f280fa573fdd6df62717e89/wys/api/python/wys_api.py#L153

**Comment by KatiRG** [comment]
It this what you had in mind?

```
for item in counter:
    this_speed=int(item['speed']) if item['speed'] else None
    this_count=int(item['count']) if item['count'] else None
    speed_row=[api_id, datetime_bin, this_speed, this_count]
```

**Comment by radumas** [comment]
yup ☺️
