### ISSUE TITLE
WYS Analyze Null Data

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#393]
Since #388 there have been NULL data in the API. Investigate for which signs this is happening and how much.

**Comment by KatiRG** [comment]
```
select * from wys.raw_data
where speed IS NULL
or count IS NULL;
```
=> 858001 rows affected.

**Comment by KatiRG** [comment]
I have made a temporary view `wys.qc_raw_data_nulls` that counts the number of `NULL` entries per hour per date per sign.

E.g. for sign `1750` on `2021-03-30` and `2021-03-31`, here are the number of times in each hour (`num_null`) that `speed` or `count` was `NULL` 

| api_id |	dt |	hour |	num_null |
|--|--|--|--|
| 1750 |	2021-03-30 |	0 |	6 |
| 1750 |	2021-03-30 |	1 |	7 |
| 1750 |	2021-03-30 |	2 |	10 |
| 1750 |	2021-03-30 |	3 |	9 |
| 1750 |	2021-03-30 |	4 |	9 |
| 1750 |	2021-03-30 |	5 |	2 |
| 1750 |	2021-03-30 |	6 |	1 |
| 1750 |	2021-03-30 |	20 |	1 |
| 1750 |	2021-03-30 |	22 |	1 |
| 1750 |	2021-03-30 |	23 |	7 |
| 1750 |	2021-03-31 |	0 |	7 |
| 1750 |	2021-03-31 |	1 |	8 |
| 1750 |	2021-03-31 |	2 |	10 |
| 1750 |	2021-03-31 |	3 |	10 |
| 1750 |	2021-03-31 |	4 |	7 |
| 1750 |	2021-03-31 |	5 |	6 |
| 1750 |	2021-03-31 |	6 |	1 |
| 1750 |	2021-03-31 |	16 |	1 |
| 1750 |	2021-03-31 |	21 |	1 |
| 1750 |	2021-03-31 |	22 |	2 |
|1750	|2021-03-31 |	23 |	7 |

**Comment by KatiRG** [comment]
What I have found so far:
-    there are currently 872 rows in `wys.raw_data`
```
    SELECT DISTINCT (api_id)
    FROM wys.raw_data;
```

 -   727 of these contain rows with NULL speed and count columns
```
    SELECT DISTINCT (api_id)
    FROM wys.qc_raw_data_nulls;
```

 -   only 395 rows have matching geoms in `wys.wys_stat_signs_speed_limit`

**Comment by KatiRG** [comment]
![image](https://user-images.githubusercontent.com/1254764/115724163-b555ae80-a34e-11eb-8d5c-128285a65fb8.png)
Fig 1: Total number of NULL rows summed by hour across all signs, considering only hours with more than cutoff=5 NULL rows.

**Comment by KatiRG** [comment]
I have also made a kind of "Gantt" chart showing the dates for each sign that contain NULL rows. This plot is best viewed in the notebook as separate figures instead of this condensed version that is hard to read.

![image](https://user-images.githubusercontent.com/1254764/115724268-cacad880-a34e-11eb-8faa-41ddb49f3db2.png)
**Fig 2c: Condenses Fig 2a, b into two subplots showing dates for signs where at least one hour in each day had more than `cutoff=5` NULL rows for first `303` out of `607` signs (left) and last `304` out of `607` signs (right).**

**Comment by radumas** [comment]
So the conclusion I'm drawing here is that this is basically affecting all the signs. Did you count the number of signs that were operating since 2021-03-30? Kind of seems like the implication is that now we will get at least 1 row/5 min bin&sign

**Comment by KatiRG** [comment]
- `739` signs have been operating since > `2021-03-31`:
```
select distinct (api_id)
from wys.raw_data
where datetime_bin::date > '2021-03-30';
```  


- of the `739` signs have operating since > `2021-03-31`, `734` have NULL speed or count columns:  
```
select distinct (api_id)
from wys.raw_data
where datetime_bin::date > '2021-03-30'
and (speed IS NULL OR count IS NULL);
```

**Comment by radumas** [comment]
You can prepare a PR to close this. It would be nice to reference the notebook in the WYS readme and the main takeaways there as well.
