### ISSUE TITLE
Big list of `miovision.intersection_movement` inconsistencies and bugs

### ISSUE THREAD

**Issue by cczhu** [CityofToronto/bdit_data-sources#406]
Here's a list of `intersection_movement` inconsistencies I've discovered while scanning through it. "U-turn inconsistent" means that u-turns are included for some legs, or some classes of vehicles, but not otherse, in an arbitrary manner (eg. articulated trucks can u-turn but not single trucks). This is possibly due to the count-based valid intersection scheme we used to use.

- Intersection 1 has E leg movements for classes 1, 3, 4, 5, 7, 9 despite being a one-way eastbound road.
- Intersection 1 has left turns for S leg and right turns for N leg, despite being a t-intersection.
- Intersection 2 class 1 W leg allows u-turns on a one-way street
- Intersection 2 class 3 S leg has u-turns but not N leg
- Intersection 2 class 5 N, S legs have no u-turns even though other vehicle classes do
- Intersection 3 has E leg movements for classes 1, 2, 3, 4, 5, 7, 9 despite being a one-way eastbound road.
- Intersection 3 doesn't allow bike u-turns
- Intersection 3 doesn't allow class 3, 4, 5 u-turns (except class 4 N-leg and class 5 S-leg)
- Intersection 3 class 4 W leg allows u-turns on a one-way street
- Intersection 4 class 1 W leg allows u-turns on a one-way street
- Intersection 4 class 2, 3, 5 doesn't allow u-turns (except class 5 N leg)
- Intersection 4 class 8 allows u-turns on one way street
- Intersection 5 class 2 doesn't allow u-turns on W leg only
- Intersection 5 class 1 allows S leg left turns and N leg right turns on a T-intersection with only the E leg. Not quite sure what's going on.
- Intersection 5 class 3 doesn't allow E leg movement 1 (which should be impossible, but class 1 does have it)
- Intersection 5 class 3 doesn't allow u-turns
- Intersection 5 class 4 doesn't allow S leg u-turns but does N leg
- Intersection 5 class 5 doesn't allow S leg left turns but allows N leg right turns
- **Intersection 6 - 40 class 2, 3, 5 u-turns inconsistent**
- Intersection 33 - 39 class 1, 8, 9 no u-turns represented (despite there definitely being u-turns at that location).
- Intersection 33 - 57 no class 7 representation at all, but we're still getting class 7 volumes
- Intersection 35 class 1 has S leg movements, despite Shaw being a one-way southbound street
- Intersection 43 - Open class 2 up to all possible movements? Bikes movements aren't necessarily limited on one-way streets.

Most of these issues aren't as serious as #405, but we should address them at some point.

**Comment by cczhu** [comment]
Another one:

Intersection 37 S leg class 2 has hundreds of `movement_uid = 1`. 37 is Danforth and Jones t-intersection, and S leg movement 1 would be to the north sidewalk of Danforth:

![image](https://user-images.githubusercontent.com/442891/120654753-fb268c00-c44f-11eb-9c7e-574bce4ae8df.png)

Entirely possible that cyclists are doing this, but not sure if we want to record it as an intersection movement.

**Comment by aharpalaniTO** [comment]
Interesting. This movement (S leg throughs) is isolated to cyclists only? Are we talking a lot of volume here? Either way, it's entirely a possible movement (and one I've made myself) so it should be recorded as valid (for cyclists only)

**Comment by aharpalaniTO** [comment]
> Another one:
> 
> Intersection 37 S leg class 2 has hundreds of `movement_uid = 1`. 37 is Danforth and Jones t-intersection, and S leg movement 1 would be to the north sidewalk of Danforth:
> 
> ![image](https://user-images.githubusercontent.com/442891/120654753-fb268c00-c44f-11eb-9c7e-574bce4ae8df.png)
> 
> Because there's no street on the north side, it's not a valid movement stored in `miovision_api.intersection_movements`, but it's entirely possible that cyclists are doing this. Not sure if we want to record it as an intersection movement.

Interesting. This movement (S leg throughs) is isolated to cyclists only? Are we talking a lot of volume here? Either way, it's entirely a possible movement (and one I've made myself) so it should be recorded as valid (for cyclists only)

**Comment by cczhu** [comment]
@aharpalaniTO yes it's only for cyclists, and over the course of 6 days we had 381 such movements.

I can spin off a new issue similar to #405, and then make a fix to `miovision_api.intersection_movements` so that we start including this movement immediately. We'll then need to backfill this location from mid-2020 onward.

**Comment by radumas** [comment]
Yeah agree with Aakash that cyclists do weird stuff that we wouldn't expect vehicles to do

**Comment by cczhu** [comment]
Spinning [this observation](https://github.com/CityofToronto/bdit_data-sources/issues/406#issuecomment-853879516) into its own issue, #408.

**Comment by gabrielwol** [comment]
Issue is superseded by https://github.com/CityofToronto/bdit_data-sources/issues/855 which will monitor for common movements excluded from `intersection_movements` table.
