### ISSUE TITLE
WYS: Can't pull historical data more than 2 days old using Airflow dag

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#424]
Occasionally the DAG fails, when we try to rerun it then we get a bunch of 504 Errors.

This is what the vendor has told us about what is happening.

>Could you tell what route are you trying to run was it with parameters from/to https://api.streetsoncloud.com/sv2/signs/statistics/location/lcoation_id/date/<date>/from/<from>/to/<to> 
>
> Or was it  just a date https://api.streetsoncloud.com/sv2/signs/statistics/location/location_id/date/<date> 
> 
> If you are trying to fetch data from June 28th  it means the data  is stored in the archived storage already, all data older than 2 days old moved  into archive. Retrieving data from archived storage for a whole day usually takes more than 29 sec the  which means most likely you will receive error 504.
> 
> So our suggestion for all statistics requests  for more than 2 days old data to use the api route with parameters FROM/TO with smaller intervals, ideally by hours, for example https://api.streetsoncloud.com/sv2/signs/statistics/location/<location_id>/date/2021-06-28/from/08:00/to/09:00 
 
Someone needs to test this for the two days we are missing: May 31st and June 28th, 2020

**Comment by radumas** [comment]
Deleted the following days of data with the below query. Not sure why there's a foreign key column between raw data and aggregate data but there's no explicit foreign key relationship.

```sql
WITH agg_delete as (
	DELETE FROM wys.speed_counts_agg_5kph
	WHERE 
	(datetime_bin >= '2021-07-26' AND datetime_bin < '2021-07-26'::DATE + INterval '1 day' ) OR
	(datetime_bin >= '2021-07-28' AND datetime_bin < '2021-07-28'::DATE + INterval '1 day' ) OR
	(datetime_bin >= '2021-07-29' AND datetime_bin < '2021-07-29'::DATE + INterval '1 day' ) OR
	(datetime_bin >= '2021-08-04' AND datetime_bin < '2021-08-04'::DATE + INterval '1 day' ) 
	RETURNING speed_counts_agg_5kph_id)
DELETE FROM wys.raw_data_2021 raw_data
USING agg_delete
WHERE raw_data.speed_count_uid = agg_delete.speed_counts_agg_5kph_id
```

This should get written into the README for wys, or alternatively there could be a "replace data" command written into the script that would use the call written above and also delete data for the days to be re-pulled.

**Comment by scann0n** [comment]
This also happened on 2021-12-03 - the start_date was 2021-12-01 (two days prior).
