### ISSUE TITLE
VZ Map - Investigate why Google Sheets API is failing

### ISSUE THREAD

**Issue by KatiRG** [CityofToronto/bdit_data-sources#427]
![image](https://user-images.githubusercontent.com/1254764/130457568-a0cedc22-3ad9-438f-a77d-5b2d70cf8962.png)

![image](https://user-images.githubusercontent.com/1254764/130457419-72c60ff0-f17e-45a3-9169-f9cb80e4665c.png)

**Comment by radumas** [comment]
Those tasks did succeed the two following days so I don't think there's anything to investigate further at the moment
