### ISSUE TITLE
Automate updating of the collision data within the RDS

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#441]
The MOVE replicator is now kindly sending us collision data to `collisions_replicator.ACC`. However this is `DROP`ped every refresh so we can't have `MATERIALIZED VIEW`s depending on it. Peter has suggested we validate the data before transferring it to a safe copy table currently `collisions_replicator.acc_safe_copy`

https://github.com/CityofToronto/bdit_move_etl/blob/master/scripts/airflow/dags/taskflow_dag.py
the task group is `replicator_update_schema`
the files: https://github.com/CityofToronto/bdit_move_etl/tree/master/scripts/airflow/tasks/replicator_update_schema

Also the old details on transferring data need to be deleted and the documentation updated.

**Comment by scann0n** [comment]
The last feasible (aka not in the future) date for which a collision was recorded in the collisions_replicator database is Jan 21 2022. Suggested next steps: set up an airflow dag (or piggy back on an existing one) to update the collisions_replicator.acc table with a drop cascade, then rebuild the collision_no, events and involved mat views when the acc table is updated.

Does that make sense?
 
Still need to discuss: 
1. The "home" schema - will it still be collisions_replicator? If so, there's no conflict with a VZ mat view (vz_analysis.hin_ksis_network)...
2. What existing dag to build this into (the dag referenced above does not refer to collisions_replicator and the existing .py file used to pull acc data into collisions looks old (and it doesn't use Airflow, so...)
