### ISSUE TITLE
Update query for inserting new locations in the API 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#449]
The query here is not ideal. The `UNION` section is hard to read and could lead to errors and the first CTE is not quite correct.

https://github.com/CityofToronto/bdit_data-sources/blob/b4cc5dbf4930d5957a87eb2745e16c363412198f/wys/api/python/wys_api.py#L363-L400

- [ ] The first CTE should be something like

```sql
-- appropriate version for most_recent_locations CTE
-- Gets the row in the locations table for each api_id with the most recent start_date
With  AS (
		SELECT DISTINCT ON(api_id) api_id, address, sign_name, dir, loc, start_date
    FROM wys.locations
		ORDER BY api_id, start_date DESC					
)
```
- [ ] The direction should be checked as well to see if it changes.
- [ ] Geometries should be created on insertion
- [ ] Perform an analysis of locations that have changed geometries over time to determine a distance threshold for updating the location
- [ ] distance between geometries should also be checked

**Comment by tahaislam** [comment]
Need to add the geometry to the existing signs in the locations table. Maybe something like this:
```
ALTER TABLE wys.locations
ADD COLUMN geom geometry;

UPDATE wys.locations
SET geom = st_setsrid(st_makepoint(split_part(regexp_replace(locations.loc, '[()]'::text, ''::text, 'g'::text), ','::text, 2)::double precision, split_part(regexp_replace(locations.loc, '[()]'::text, ''::text, 'g'::text), ','::text, 1)::double precision), 4326);
```

**Comment by tahaislam** [comment]
Based on analyzing the previous changes in stationary signs locations, there are 32 location changes: 
* 3 moved to new locations less than 100 meters away from their old locations
* 29 moved to new locations more than 2000 meters away from their old locations

Hence, the latest commit used a threshold of 100 meters to differentiate actual location changes
```
SELECT * FROM (
SELECT loc.api_id,
       loc.geom,
       ST_Distance_Sphere(geom, lead(loc.geom) OVER w) AS dist_to_next
FROM wys.stationary_signs loc
WINDOW w AS (PARTITION BY loc.api_id ORDER BY loc.start_date)) a
WHERE a.dist_to_next > 0
ORDER BY a.dist_to_next;
```
