### ISSUE TITLE
Fix bug in Red Light Camera 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#460]
We were pulling Red Light Camera data from Open Data but there's a bug https://github.com/CityofToronto/bdit_data-sources/pull/226#pullrequestreview-890488103

Some more info about the process but it's a little convoluted https://github.com/CityofToronto/bdit_data-sources/tree/b8071dac154d72580aeef848c9aa87d18827512f/assets/rlc 

Also in my strongly held opinion, the truncation should happen within the Python task, or this should be set up to do an UPSERT + delete (this is a stretch goal).

**Comment by radumas** [comment]
URL should be `https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/9fcff3e1-3737-43cf-b410-05acd615e27b/resource/7e4ac806-4e7a-49d3-81e1-7a14375c9025/download/Red%20Light%20Cameras%20Data.geojson` based on looking at the [Open Data page](https://open.toronto.ca/dataset/red-light-cameras/)

**Comment by tahaislam** [comment]
The data retrieved from the updated url look different from the old one. The keys in the new dataset don't match the column names of the table `vz_safety_programs_staging.rlc`. We should:
- [ ] create a new table for the newly retrieved data
- [ ] update [rlc.py](https://github.com/CityofToronto/bdit_data-sources/blob/b8071dac154d72580aeef848c9aa87d18827512f/dags/rlc.py) to retrieve the `properties` of each `Feature`
