### ISSUE TITLE
Pull signal asset layers from OpenData instead of internal Oracle

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#461]
We assemble datasets from various internal sources to publish to the https://www.toronto.ca/services-payments/streets-parking-transportation/road-safety/vision-zero/vision-zero-dashboard/

Despite what the [documentation](https://github.com/Toronto-Big-Data-Innovation-Team/bdit_vz_programs/#8-dashboard-indicators) reads, the layers from SignalView are not, in fact automated, and now the dashboard is pretty out of date.

I think we should pull the datasets from Open Data, though they will look slightly different
https://open.toronto.ca/dataset/traffic-signals-tabular/ for Pedestrian Head Start Signals, Accessible Pedestrian Signals, and LED Blank-out Signs
https://open.toronto.ca/dataset/traffic-control-devices/ for Pedestrian Crossovers (PXO)

I think the code to pull these layers could be similar to that for the Red Light Camera layer.

Note that the traffic signals dataset currently used in the dashboard that came from the internal Oracle database is stored in `vz_safety_programs_staging.signals_cart`  and I think came in as one singular dataset before being used by a bunch of Views. So I think there needs to be a process to combine the necessary info about PXOs and the other traffic signal info into those eventual view structures.

**Comment by radumas** [comment]
Unfortunately some further data analysis is required since PXOs can be found both in the Traffic Signals and the Traffic Control Devices endpoints on OpenData. Traffic Signals appears to have more data and be more recent based on a quick filter in excel (for TCD I had to filter by NAME contains "PXO"

**Comment by qu-xiang** [comment]
I have two questions regarding the PXO data source. [https://open.toronto.ca/dataset/traffic-control-devices/](url)
1. They have two types of PXO: "Recently Activated Pedestrian Crossover (PXO)" and "Upcoming Pedestrian Crossover (PXO)". Do I include the upcoming PXOs as well or leave them out?
2. The number of PXOs in the new source are much fewer than that in `signals_cart` database. Is this a normal phenomenon?
Thanks

**Comment by radumas** [comment]
Per our conversation and investigation today: Pedestrian Head Start Signals/LPIs are the type of data which currently have an activation date. So focus on extracting those from the Traffic Signals Tabular OpenData feed.

For the activation date, given there are 4 directions in the feed, use the most recent one.

For now, do not update the signals_cart tables since that would remove the dates that are currently populated and which are feeding into the Vision Zero Map.

**Comment by radumas** [comment]
I will follow up with Open Data about the sources of the datasets but we have two REST endpoints for data:

* traffic signals: https://secure.toronto.ca/opendata/cart/traffic_signals/v3?format=json
* PXOs: https://secure.toronto.ca/opendata/cart/pedestrian_crossovers/v2?format=csv

This new traffic signals file has activation date for LPI and APS. Then we would be missing activation dates for UPS and LED Blankouts, will follow up with Vision Zero about those.

**Comment by tahaislam** [comment]
Testing the new code, here's the difference between old and new number of records:

| Asset Type | Old Count | New Count |
| ---              | ---             | ---               |
|"Leading Pedestrian Intervals"|260|984
|"Pedestrian Crossovers"|485|488
|"Audible Pedestrian Signals"|1075|1172
