### ISSUE TITLE
Automate transfer of count data from `"TRAFFIC_NEW"` to the `traffic` schema

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#462]
Now that the `replicator_bot` is refreshing data in `"TRAFFIC_NEW"` on a nightly basis, we need to automate putting the data into our `traffic` schema.

This process can be automated by performing some comparison of the number of rows in the `"TRAFFIC_NEW"` tables compared to `traffic` and then copying over the data, like with the collisions pipeline

**Comment by scann0n** [comment]
Getting started questions...

1. Does `"TRAFFIC_NEW"` = `traffic_new`?
2. I can haz access to `traffic_new`?
3. Is the general idea to update `traffic.arc_link` with `traffic_new."ARC_LINK"`?

**Comment by radumas** [comment]
`traffic_new` no longer exists, I think that resolves most of your questions :)

**Comment by scann0n** [comment]
Why yes indeed - 
Silly me...
"TRAFFIC_NEW"
Isn't next to "u"...
It's all the way
Ahead of "a"
And question 2
I must redo...
I can haz access to "TRAFFIC_NEW"?

**Comment by scann0n** [comment]
Are all collisions_admins also bdit_humans?
