### ISSUE TITLE
Add retry to the HERE pipeline

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#465]
The HERE pipeline occasionally fails due to a timeout (https://github.com/CityofToronto/bdit_data-sources/issues/204) or the data not being available yet. The typical fix is to retry after waiting an hour or so. We should add that to the DAG.

**Comment by chmnata** [comment]
Was trying to see if there is a call_back or parameter to send a message if the retry was successful, but nah. The [callbacks ](https://airflow.apache.org/docs/apache-airflow/2.2.1/logging-monitoring/callbacks.html#callback-types) they have:
Name | Description
-- | --
on_success_callback | Invoked when the task succeeds
on_failure_callback | Invoked when the task fails
sla_miss_callback | Invoked when a task misses its defined SLA
on_retry_callback | Invoked when the task is up for retry

I don't think the on_retry_callback will be necessary as it will just send a msg everytime the dag is retying.

I think it might be possible by using [task instances ](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/taskinstance/index.html#airflow.models.taskinstance.TaskInstanceKey) cause there is a `try_number` and `with_try_number` param which looks useful. I'm gonna leave this till next time cause seems like there's no available callback to quickly implement it.

**Comment by chmnata** [comment]
![image](https://user-images.githubusercontent.com/46324452/172488933-28301171-85d2-4fc1-9c39-99fcdbd5f899.png)
uhhhhhhhhhhhhh it didn't work. When a tasks fail it should have a status `up_for_retry` instead of just `fail`.
