### ISSUE TITLE
Update travel time documentation

### ISSUE THREAD

**Issue by scann0n** [CityofToronto/bdit_data-sources#481]
Our HERE documentation is a wee bit out of date  / not geared for noobs.  Also there should be documentation for Bluetooth...

**Comment by radumas** [comment]
We haven't reorganized the travel time datasets under one folder, there is loads of Bluetooth documentation under [`bluetooth`](../tree/master/bluetooth/)

**Comment by scann0n** [comment]
Oh that Bluetooth intel is sooo good to know!

Do you think we should reorganize bdit_data-sources before we update the documentation?

**Comment by radumas** [comment]
I don't think it should make that much difference, whoever does the moving will have to edit some documentation anyways about where things are located.
