### ISSUE TITLE
Traffic signal puller failed due to duplicate records

### ISSUE THREAD

**Issue by qu-xiang** [CityofToronto/bdit_data-sources#522]
There is a duplicate record of px = 1484 which violated `gis.traffic_signal` 's PK constraint, causing the `traffic_signals_dag` to fail.

Both are at Eglinton & Centennial Park but one has an activation date of 1988-07-01 and the other's is 2022-11-10. 

Might need to change our traffic signal end point, doesn't seem to be pointed to by OpenData anymore. Link to OpenData: https://open.toronto.ca/dataset/traffic-signals-tabular/

Link the DAG currently pulls from: https://secure.toronto.ca/opendata/cart/traffic_signals/v3?format=json

**Comment by tahaislam** [comment]
Boris Guenkine located duplicated record and deleted it (kept the older activation date).
