### ISSUE TITLE
`wys` `locations.api_id` is not a unique identifier

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#535]
Four times in `wys/api/README.md` `api_id` is referred to as a unique identifier for the `locations` table, though this doesn't seem to actually be the case. 

> ID used for the API, and unique identifier for the `locations` table

There are many instances of multiple `locations` records sharing the same `api_id`, seemingly notwithstanding issue #533. It's unclear how to, for example, see what data we have in `wys.raw_data` corresponding to a specified location.

**Comment by tahaislam** [comment]
I'll update the README to fix this. `api_id` isn't unique, `wys.locations.id` is the primary key to that table. 
I believe that each sign has a unique `api_id`, but they sometimes got recycled/relocated somewhere else. Hence, some `api_id`s appear multiple times at different locations
