### ISSUE TITLE
`/collisions/Readme.md` needs updating

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#538]
At the least, it refers extensively to a `collisions` schema that no longer exists. We now have:
* `collision_factors`
* `collisions_DO_NOT_USE`
* `collisions_replicator`

though given this difference, there are likely other changes that should be documented as well.

**Comment by radumas** [comment]
The last line from the description paragraph is out of date.

>The table is copied to a file in the [MOVE data platform](https://github.com/CityofToronto/bdit_flashcrow)'s AWS fileserver on a weekly basis. pull_acc_script.py, described below, copies this file onto our Postgres database.

Thanks to @scann0n and Peter, this data is now being pushed from MOVE's replicator nightly. [collisions_replicator_transfer.py] runs after this to move data from `"ACC"` to `acc_safe_copy` (https://github.com/CityofToronto/bdit_data-sources/blob/master/dags/collisions_replicator_transfer.py) [func_upd_acc_sc.sql](https://github.com/CityofToronto/bdit_data-sources/blob/074d23c7cba0d1bab6285828a97eeadc8c962af0/collisions/func_upd_acc_sc.sql)
