### ISSUE TITLE
Refactor get_layer() in gcc_puller_functions

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#543]
I don't feel like this code needs to get repeated after the outer `else`.
The only thing in the outer `else` could be  
```python
else:
    return_json = get_data(mapserver, layer_id, max_number = max_number, record_max = record_max)
#and then 
if is_audited:
    #etc
```

_Originally posted by @radumas in https://github.com/CityofToronto/bdit_data-sources/pull/506#discussion_r1125060472_

**Comment by gabrielwol** [comment]
Replaced by https://github.com/CityofToronto/bdit_data-sources/issues/561
