### ISSUE TITLE
Bluetooth: Bluetooth Backfilling 20230315 to 20230320 is incomplete

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_data-sources#548]
Backfilled  20230315 to 20230320 but some days were not complete. A full day should be 288 5 min bins. 
```
select datetime_bin::date, count(distinct datetime_bin) from bluetooth.aggr_5min
where datetime_bin >= '2023-03-15' and datetime_bin <'2023-03-21'
group by datetime_bin::date
order by datetime_bin::date
```

date | distinct 5 min bins
-- | --
03/15/2023 | 288
03/16/2023 | 288
03/17/2023 | 14
03/18/2023 | 178
03/19/2023 | 111
03/20/2023 | 288

Today's pull also only pulled 23 , 5 min bins
```
select datetime_bin::date, count(distinct datetime_bin) from bluetooth.aggr_5min
where datetime_bin >= '2023-03-21' and datetime_bin <'2023-03-21'
group by datetime_bin::date
order by datetime_bin::date
```

2023-03-21 distinct 5 min bins
--
03/21/2023 0:00
03/21/2023 0:05
03/21/2023 0:10
03/21/2023 0:15
03/21/2023 0:20
03/21/2023 0:25
03/21/2023 0:30
03/21/2023 0:35
03/21/2023 0:40
03/21/2023 0:45
03/21/2023 0:50
03/21/2023 0:55
03/21/2023 1:00
03/21/2023 1:05
03/21/2023 1:10
03/21/2023 1:15
03/21/2023 1:20
03/21/2023 1:25
03/21/2023 1:30
03/21/2023 1:35
03/21/2023 1:40
03/21/2023 1:45
03/21/2023 1:50

</body>

</html>

**Comment by chmnata** [comment]
Today's task (2023-03-23) successful ran but there were no data to insert

**Comment by radumas** [comment]
I think there may have been data filled in Friday the 24th

**Comment by chmnata** [comment]
So 2023-03-22 successfully re-pulled but the other days are still missing data:
"2023-03-17"	14
"2023-03-18"	178
"2023-03-19"	111
"2023-03-21"	89

**Comment by radumas** [comment]
I don't think we're going to get more data
