### ISSUE TITLE
Root README Update

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#550]
- [x] Remove the "Notes" sections
- [x] Remove the data definitions
- [ ] identify actively used datasets
- [ ] add brief description, if missing

**Comment by Nate-Wessel** [comment]
@radumas do you know if the ["RoDARS" dataset mentioned in the readme](https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge#road-disruption-activity-rodars) is documented anywhere else? Should this section be kept or removed? It seems this is different from [`SpecialEvents/`](https://github.com/CityofToronto/bdit_data-sources/tree/master/SpecialEvents)

**Comment by radumas** [comment]
That now exists as OpenData https://open.toronto.ca/dataset/road-restrictions/. It is functionally useless for (most of) our purposes because the restrictions only list permitted activities, and don't get updated to to specify when lanes are actually occupied.

**Comment by Nate-Wessel** [comment]
Thanks @radumas ; I've removed it. How about "[Vision Zero - Google Sheets API](https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge#vision-zero---google-sheets-api)"? And "[Vehicle Detector Station](https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge#vehicle-detector-station-vds)"?

**Comment by radumas** [comment]
> Thanks @radumas ; I've removed it. How about "[Vision Zero - Google Sheets API](https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge#vision-zero---google-sheets-api)"? 

That work can be found here https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge/gis/school_safety_zones

> And "[Vehicle Detector Station](https://github.com/CityofToronto/bdit_data-sources/tree/readme-purge#vehicle-detector-station-vds)"?

This is what we commonly (incorrectly) refer to as RESCU data, even though our documentation has a confusing tendency to link to information about the cameras, which are only used manually for incident detection and management, not data collection.
