### ISSUE TITLE
Identify long gaps in Miovision data

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#570]
Per https://github.com/CityofToronto/bdit_data-sources/issues/419 and also because occasionally there are installation issues which can lead to long periods of low (but not no) data.

Prepare a table first based on visual inspection for each intersection for long outages.

Proposed schema 

- intersection
- classification_uid ??????? (maybe not initially)
- datetime range (`[)`)
- reason (e.g road closure, camera shifted)
- resolution: month, week, day
- tag to determine progress (`SUS` :the volumes looks wrong,  `Malfunction` : all 0s, `Known Outlier`)
- spike or dip? (types of discrepancy)

**Comment by chmnata** [comment]
Can we also add a description in the readme for this table + in the [re-pulling data section](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/miovision#4-repulling-data) add a reminder to delete or note if a previously identified gap has been "filled" with the new pull.

**Comment by Nate-Wessel** [comment]
I believe this should be closed by https://github.com/CityofToronto/bdit_data-sources/pull/589
