### ISSUE TITLE
Revisit structure of `bluetooth` schema

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#58]

**Comment by aharpalaniTO** [comment]
Given need for quicker turnarounds, and current sub-optimal naming of tables/fields, should re-organize/re-name tables, as well as create triggers to populate aggregated tables upon changes to `bluetooth.observations`

**Comment by radumas** [comment]
- [ ] robust error detection for missing data
- [ ] automate sensor-failure detection
