### ISSUE TITLE
Distinction between meaning of `leg` in various miovision tables is unclear

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#590]
This incorrectly shows substantial wrong-way car travel on Richmond at Bay. 
```sql
SELECT 
    SUM(volume),
    COUNT(*)
FROM miovision_api.volumes_15min
WHERE 
    classification_uid = 1 -- cars
    AND intersection_uid = 28 -- Richmond and Bay
    AND leg = 'W' -- approaching from the west
```
If the approach leg is 'W', then travel is Eastbound (right?), but Richmond only goes westbound. It's more than a couple random deviants. 

The raw `volumes` table correctly has no such data. 

I'm not sure if there are other instances of this problem. i.e. other intersections, directions.

**Comment by Nate-Wessel** [comment]
It is also a problem with Adelaide & Richmond @ Spadina & Bay. Again, no such data in `volumes`, so I'm defaulting to the raw table for now.

**Comment by chmnata** [comment]
It's not even in the `miovision_api.volumes_15min_mvt` which is weird. 
```
-- returned 0 rows
SELECT  *
FROM miovision_api.volumes_15min_mvt
WHERE 
    classification_uid = 1 -- cars
    AND intersection_uid = 28 -- Richmond and Bay
    AND leg = 'W' -- approaching from the west (so heading east)

	limit 100
```

**Comment by radumas** [comment]
Please review the diagram in the README for how TMC data is converted to ATR

**Comment by chmnata** [comment]
Sorry, it depends on the leg + direction, so there is no EB + leg = W which is correct.

**Comment by chmnata** [comment]
So when you filter for `leg = 'W'` and `dir = 'EB'`, it returns 0 rows. 

The summed volume in the above sql only includes `leg = 'W'` and `dir = 'WB'`. 

The readme section below shows how `miovision_api.volumes_15min_mvt` converts to `miovision_api.volumes`
https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/README.md#volumes_15min
```
-- returns zero
SELECT *
FROM miovision_api.volumes_15min
WHERE 
    classification_uid = 1 -- cars
    AND intersection_uid = 28 -- Richmond and Bay
    AND leg = 'W' -- approaching from the west (so heading east)
	and dir = 'EB'
```

**Comment by Nate-Wessel** [comment]
Per the discussion yesterday, I'm going to say this is still a bug, but the bug is actually in the _documentation_, not the data. I'll see if I can clear it up a little.
