### ISSUE TITLE
Update the RESCU VDS pipeline to pull from a database

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#603]
the RESCU pipeline currently operates on the Terminal Server and pulls from a data exhaust created in uploading data to ATM's Oracle database. If the loading process fails, backfills do not create this exhaust.

We should instead be pulling from the source, which should make the pipeline more robust, if previous loading steps fail, we should be able to pull backfilled data.

**Comment by radumas** [comment]
Regarding the data slowly trickling in. Could we come up with a threshold based on the detector inventory or some expectation of number of actively working detectors?

**Comment by gabrielwol** [comment]
I don't know what the future holds, but when I identified the issue last week there was only a small delta, so I don't think a threshold would work. 
<html><body>


date_trunc | RDS Count | ITSC Count | Dif
-- | -- | -- | --
06/28/2023 0:00 | 56285 | 57149 | 864
06/29/2023 0:00 | 53754 | 53826 | 72
06/30/2023 0:00 | 55417 | 56713 | 1296
07/01/2023 0:00 | 52893 | 56349 | 3456
07/02/2023 0:00 | 53727 | 54339 | 612
07/03/2023 0:00 | 54090 | 54090 | 0
07/04/2023 0:00 | 53958 | 53958 | 0
07/05/2023 0:00 | 53506 | 53506 | 0
07/06/2023 0:00 | 53286 | 53286 | 0


</body>
</html>
