### ISSUE TITLE
Fuse Artery Code Network with Pavement Assets

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#606]
I think the sql to do this could go under `volumes/short_term_counting_program/sql`

And then document the location of the resulting transform in the README here https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/short_term_counting_program#5-useful-views

Do the work under your own schema, but when the sql is ready for a PR change the schema to `traffic` and note that those assets will need to be migrated to that schema upon merge.

**Comment by A-DUYVESTYN** [comment]
current sub-issue: `traffic.arterydata` `geo_id` column is null in 70% of rows. `geo_id` was used to join `traffic.arterydata` to `gis_shared_streets.centreline_pavement_180430` and, in turn, `vz_analysis.gcc_pavement_asset`

**Comment by A-DUYVESTYN** [comment]
Created branch artery_assets_objectid and pushed the sql and changes to README.

**Comment by A-DUYVESTYN** [comment]
table `counts.arteries_centreline` in FLASHCROW database was copied to user schema `aduyves.arteries_centreline` for working (I do not have access to flashcrow db). Not clear how should this be handled/migrated?
