### ISSUE TITLE
Updating some old WYS code

### ISSUE THREAD

**Issue by tahaislam** [CityofToronto/bdit_data-sources#614]
While applying the changes of #602, I noticed some issues that should be resolved:
- The files  [`wys/api/sql/open_data/view-mobile_detailed.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/4e340a2711dd6b143a0e410f0092f499922569ca/wys/api/sql/open_data/view-mobile_detailed.sql) and [`wys/api/sql/open_data/view-stationary_detailed.sql`](https://github.com/CityofToronto/bdit_data-sources/blob/4e340a2711dd6b143a0e410f0092f499922569ca/wys/api/sql/open_data/view-stationary_detailed.sql) are outdated. `speed_bins` should be replaced with `speed_bins_old`.

- We also need to update https://github.com/CityofToronto/bdit_data-sources/blob/4e340a2711dd6b143a0e410f0092f499922569ca/wys/api/sql/create-view-mobile_api_id.sql#L1 to be `DROP MATERIALIZED VIEW wys.mobile_api_id`

- Another note (that might apply to other projects):
The `CASCADE` in https://github.com/CityofToronto/bdit_data-sources/blob/4e340a2711dd6b143a0e410f0092f499922569ca/wys/api/sql/create-view-mobile_api_id.sql#L1 should be deleted. Dropping mat views should be done carefully after backing up any dependent objects to be able to restore them after modifying the mat view. We can follow [Natalie's instructions](https://www.notion.so/bditto/Save-and-drop-dependencies-function-in-PostgreSQL-26e4faa3816946c080994ac35b6655b8?pvs=4) on how to use `public.deps_save_and_drop_dependencies` and `public.deps_restore_dependencies` to automate the modification of mat views

**Comment by radumas** [comment]
Should we rename my eternal shame `speed_bins_old` to `speed_bins_5kph`?
