### ISSUE TITLE
Identify RESCU VDS locations in need of repair

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#617]
We have a once annual opportunity to repair detectors on the Gardiner and DVP.

To ensure redundancy and quality data collection, see if there are 2 sets of stations for each direction for

- Gardiner
  - West of Humber
  - East of Humber
  - East of Downtown
- Don Valley Parkway
  - South of Don Mills
  - Near the 401

You can have a peep at https://github.com/CityofToronto/bdit_data-sources/pull/605 for inspiration

I think we want to make sure that each station has been producing the right volumes reliably over the last month.

If there's a way to automate this identification then we would be golden for future years.

**Comment by gabrielwol** [comment]
I know you said high priority but is there a specific deadline?

**Comment by gabrielwol** [comment]
@radumas I added an sql folder and a readme for my additions. I included some sample sql to join the outage tables to volumes.
