### ISSUE TITLE
Create new shapefile for BT open data

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_data-sources#62]
1. Ensure all relevant BT segments are included (incl. King Pilot)
2. Create new shapefile with following fields:
- segment_name (e.g. A_B)
- street (e.g. King St.)
- direction (e.g. Eastbound)
- cross_street_start (e.g. Bathurst)
- cross_street_end (e.g. Spadina)
- length_km (e.g. 1.45)
- bt (e.g. TRUE) <- TRUE for all routes
- wifi (e.g. FALSE) <- TRUE for all expressways (incl. Lakeshore), FALSE for all arterials

**Raph update**:

- [ ] Adelaide Duncan-Sherbourne is either mis-drawn or mis-labeled. Route ends at Simcoe not Duncan.
- [ ] #102

**Comment by radumas** [comment]
Cross streets for the previous routes can be found in `bluetooth.ref_segments`, I'm not sure how this table was created though. The same information is probably available from the `route_points` json in `bluetooth.all_analyses`

**Comment by radumas** [comment]
@aharpalaniTO I'm seeing a number of East-West segments with 3 routes, 2 with wifi in either direction, and only one EB without WiFi
![image](https://user-images.githubusercontent.com/10623872/34123632-2fc4863c-e3fe-11e7-8957-a5b3006af3ce.png)

**Comment by radumas** [comment]
And a bunch of the downtown grid is missing 2 directions per segment

**Comment by ReedRodgers** [comment]
It looks like the segments appeared in Ron's table and in the bluetooth.ref_segments. 
The CO_UN_CO_PA is Ron's segment id, AC4_AC3 is from bluetooth.ref_segments

**Comment by radumas** [comment]
So it seems an update to the table has fixed the issues with missing segments.
The street routes that use WiFi should be axed, *but*, we have to make sure that the new routes have an identifier that matches up with the public API

**Comment by aharpalaniTO** [comment]
Things to do:
- [ ] Change all segment names to match format [S1_C1_S2_C2] (e.g. AD_JA_AD_PA)
- [ ] Identify "duplicate" segments - create a field called 'duplicate' and set to TRUE for older segments
- [ ] General QC on whole file

**Comment by radumas** [comment]
It'll be useful to know which are the old duplicates, to remove from the public routes as well.

**Comment by radumas** [comment]
# Reconciling the public API, the segments table and what we're currently pulling

The public API, the routes we're currently pulling data for, and the `segments` table which contain geometries all have different numbers of rows.

|Table| Number of routes|
|------|------------------:|
|Public API| 176|
|`bluetooth.segments`| 195|
|`all_analyses WHERE pull_data` | 327 |

Three things to consider:

1. When route's `analysis_id` changed but the geometry did not
2. When route's `analysis_id` changed and the geometry did
3. Something else

- [ ] For 1 there should be a lookup table for deprecated `analysis_id`s linking to the new `segment_name`. This should silently span those report changes for the historical Open Data release.
- [ ] For 2 there should be a table identifying when routes came on and off-line.

## Public API but not in `segments`

result_id
|--------|
A_B
B_A
C_D
D_C
D_E
E_D
E_F
F_E
F_G
G_F
G_H
H_G
H_I
I_H
I_J
J_I
J_K
K_J
B1_B
B1_C
B_B1
B_Z1
B_Z2
C_B1
E_LY
LY_D
Z1_B
LE_LY
LY_Z2
LY_Z3
Z1_Z2
Z2_LB
Z2_Z1
Z2_Z3
Z3_LB
Z3_Z2
AD_BA_AD_SP
KN_BA_KN_ST
KN_DF_KN_ST
KN_DF_QU_RO
KN_PA_QU_BV
KN_SP_KN_BA
KN_ST_KN_BA
KN_ST_KN_DF
QU_BA_QU_ST
QU_BV_KN_PA
QU_DF_QU_ST
QU_RO_KN_DF
QU_ST_QU_BA
QU_ST_QU_DF
RM_SP_RM_BA

## In `segments` but not in Public API 

```sql
SELECT segment_name, analysis_id, street, report_name, direction, start_crossstreet, 
       end_crossstreet, length, bluetooth, wifi, duplicate
  FROM bluetooth.segments
  INNER JOIN bluetooth.all_analyses USING (analysis_id)
WHERE segment_name NOT IN ('DU_YO_QU_YO','D_C','QU_ST_KN_ST','D_E','FR_SP_FB_SP','H_G','H_I','FB_YK_FR_UN','KN_JA_KN_PA','FR_UN_FB_YK','AD_YO_AD_JA','DU_PA_QU_PA','FR_SP_FR_UN','DU_BA_CO_BA','RM_JA_RM_YO','QU_YO_KN_YO','KN_SP_QU_SP','FR_UN_KN_UN','QU_UN_QU_SP','RM_PA_RM_JA','KN_PA_QU_PA','EA_BV_QU_BV','B_Z2','B_Z1','B1_B','KN_ST_KN_BA','B1_C','FR_UN_FR_YO','LY_D','Z1_B','CO_UN_CO_PA','FR_JA_WE_YO','FR_YO_KN_YO','FR_PA_KN_PA','DU_UN_DU_YO','QU_SP_DU_SP','QU_SP_QU_UN','QU_SP_QU_BA','DU_SP_DU_BA','QU_DF_DU_DF','C_D','Z1_Z2','G_F','CO_BA_DU_BA','Z3_LB','DU_JA_DU_PA','G_H','LY_Z2','DU_YO_DU_UN','FR_JA_FR_PA','B_B1','LY_Z3','QU_DF_QU_RO','QU_JA_KN_JA','RM_UN_RM_SP','KN_ST_QU_ST','K_J','LE_LY','WE_UN_WE_BJ','CO_PA_CO_UN','QU_BA_KN_BA','QU_PA_KN_PA','KN_PA_FR_PA','KN_YO_FR_YO','QU_SP_KN_SP','KN_ST_KN_DF','DU_DF_QU_DF','QU_UN_QU_YO','FR_YO_FR_UN','KN_JA_KN_YO','QU_BA_QU_SP','AD_JA_AD_PA','AD_PA_EA_BV','QU_BV_EA_BV','DU_UN_CO_UN','DU_UN_QU_UN','QU_BA_QU_ST','KN_SP_FR_SP','DU_JA_DU_YO','CO_UN_DU_UN','FB_SP_FB_BA','B_A','DU_PA_CO_PA','KN_BA_FR_BA','KN_SP_KN_BA','QU_UN_DU_UN','F_E','KN_JA_QU_JA','QU_PA_QU_BV','F_G','KN_PA_QU_BV','RM_SP_RM_BA','Z2_Z1','KN_BA_QU_BA','J_I','FB_BA_FB_SP','KN_YO_KN_UN','J_K','KN_DF_QU_DF','DU_PA_DU_JA','AD_UN_AD_YO','FB_SP_FR_SP','FR_SP_KN_SP','KN_UN_QU_UN','QU_RO_KN_DF','FR_PA_FR_JA','Z2_Z3','QU_YO_DU_YO','QU_JA_QU_YO','QU_PA_QU_JA','KN_JA_FR_JA','QU_ST_QU_DF','KN_BA_KN_ST','C_B1','DU_BA_DU_SP','QU_BV_KN_PA','QU_PA_DU_PA','QU_RO_DU_RO','QU_YO_QU_JA','FR_BA_FB_BA','QU_DF_QU_ST','KN_UN_KN_YO','CO_PA_DU_PA','QU_RO_QU_DF','KN_BA_KN_SP','QU_BV_QU_PA','QU_BA_DU_BA','A_B','FR_SP_FR_BA','FB_BA_FR_BA','DU_RO_QU_RO','E_D','E_F','DU_DF_DU_BA','KN_YO_QU_YO','DU_SP_QU_SP','FB_SP_FB_YK','AD_SP_AD_UN','DU_BA_DU_DF','DU_DF_DU_RO','FR_YO_FR_JA','I_H','KN_DF_QU_RO','I_J','DU_JA_QU_JA','EA_BV_RM_PA','QU_YO_QU_UN','QU_DF_KN_DF','FR_BA_FR_SP','WE_YO_WE_UN','FB_YK_FB_SP','KN_PA_KN_JA','AD_BA_AD_SP','DU_UN_DU_SP','CO_BA_CO_UN','FR_UN_FR_SP','E_LY','DU_RO_DU_DF','DU_BA_QU_BA','QU_JA_DU_JA','DU_SP_DU_UN','RM_YO_RM_UN','KN_UN_FR_UN','KN_DF_KN_ST','Z2_LB','Z3_Z2','KN_SP_KN_UN','DU_YO_DU_JA','QU_JA_QU_PA','FR_BA_KN_BA','CO_UN_CO_BA','QU_UN_KN_UN','KN_YO_KN_JA','FR_JA_KN_JA','QU_ST_QU_BA','KN_UN_KN_SP')
ORDER BY street, direction, start_crossstreet
```

street|direction|start_crossstreet|end_crossstreet|length|bluetooth|wifi
|------|--------|-----------------|---------------|------|---------|----|
Adelaide|EB|Sherbourne|Parliament|440|t|t
Adelaide|EB|Bathurst|Simcoe|1392|t|t
Adelaide|EB|Duncan|Sherbourne|1511|t|t
Bathurst|NB|Queen|College|1072|t|t
Bathurst|SB|College|Queen|1072|t|t
College|EB|Dovercourt|Bathurst|1559|t|t
College|WB|Bathurst|Dovercourt|1559|t|t
Dovercourt|NB|Dundas|College|480|t|t
Dovercourt|SB|College|Dundas|480|t|t
Dundas|EB|Dovercourt|Spadina|2216|t|t
Dundas|EB|Roncesvalles|Sterling|776|t|t
Dundas|EB|Sterling|Dovercourt|1495|t|t
Dundas|WB|Sterling|Roncesvalles|776|t|t
Dundas|WB|Dovercourt|Sterling|1495|t|t
Dundas|WB|Spadina|Dovercourt|2216|t|t
DVP|NB|Wynford|Lawrence|1407|t|t
DVP|NB|Bayview Ramp|Don Mills|3693|t|t
DVP|NB|Dundas|Bayview Ramp|2405|t|t
DVP|NB|Lawrence|York Mills|2069|t|t
DVP|NB|Don Mills|Wynford|2974|t|t
DVP|SB|York Mills|Lawrence|2065|t|t
DVP|SB|Wynford|Don Mills|2942|t|t
DVP|SB|Lawrence|Wynford|1409|t|t
DVP|SB|Bayview Ramp|Dundas|2412|t|t
DVP|SB|Don Mills|Bayview Ramp|3696|t|t
DVP/Gardiner|SB/WB|Dundas|Parliament|2310|t|t
Gardiner|EB|Dufferin|Spadina|2537|t|t
Gardiner|EB|Spadina|Parliament|2898|t|t
Gardiner|EB|Grand|Roncesvalles|4556|t|t
Gardiner|EB|Wickman|Grand|3181|t|t
Gardiner|EB|Roncesvalles|Dufferin|1848|t|t
Gardiner|WB|Grand|Wickman|3179|t|t
Gardiner|WB|Parliament|Spadina|2894|t|t
Gardiner|WB|Roncesvalles|Grand|4565|t|t
Gardiner|WB|Spadina|Dufferin|2541|t|t
Gardiner|WB|Dufferin|Roncesvalles|1833|t|t
Gardiner/DVP|EB/NB|Parliament|Dundas|2359|t|t
Gardiner/Lakeshore|EB|Grand|Dufferin|5995|t|t
Gardiner/Lakeshore|EB|Grand|Ellis|2976|t|t
Gardiner/Lakeshore|WB|Parliament|Yonge|1676|t|t
King|EB|Dufferin|Strachan|1309|t|f
King|EB|Parliament|Broadview|1302|t|f
King|EB|Roncesvalles|Dufferin|1652|t|f
King|EB|Strachan|Bathurst|740|t|f
King|WB|Dufferin|Roncesvalles|1653|t|f
King|WB|Spadina|Bathurst|643|t|f
King|WB|Bathurst|Strachan|740|t|f
King|WB|Broadview|Parliament|1291|t|f
King|WB|Strachan|Dufferin|1309|t|f
Lakeshore|EB|Strachan|Bay|2976|t|t
Lakeshore|EB|Ellis|Dufferin|3258|t|t
Lakeshore|EB|Dufferin|Strachan|1433|t|t
Lakeshore|EB|Dufferin|Bay|4397|t|t
Lakeshore|WB|Yonge|Strachan|3494|t|t
Lakeshore|WB|Parliament|Yonge|1749|t|t
Lakeshore|WB|Strachan|Dufferin|1433|t|t
Lakeshore|WB|Dufferin|Ellis|3238|t|t
Lakeshore|WB|Yonge|Dufferin|4929|t|t
Lakeshore/Gardiner|WB|Yonge|Spadina|1780|t|t
Lakeshore/Gardiner|WB|Ellis|Grand|2778|t|t
Queen|EB|Dufferin|Bathurst|2061|t|t
Queen|EB|Dufferin|Strachan|1307|t|f
Queen|EB|Strachan|Bathurst|752|t|f
Queen|WB|Bathurst|Strachan|752|t|f
Queen|WB|Bathurst|Dufferin|2061|t|t
Queen|WB|Strachan|Dufferin|1307|t|f
Richmond|WB|Parliament|Sherbourne|434|t|t
Richmond|WB|Spadina|Bathurst|629|t|f
Richmond|WB|Sherbourne|Duncan|1687|t|t
Richmond|WB|Duncan|Bathurst|1229|t|t

**Comment by radumas** [comment]
#100 dealt with the mismatch with the API and `segments` table. There is one route that is in the API but not the table: Adelaide Bathurst to Spadina.

**Comment by radumas** [comment]
Made sure line direction matches street direction with the below query.
```sql
SELECT segment_name, analysis_id, street, direction, start_crossstreet, 
       end_crossstreet, length, bluetooth, wifi, 
       CASE WHEN gis.twochar_direction(gis.direction_from_line(st_linemerge)) = direction THEN st_linemerge
	    ELSE st_reverse(st_linemerge) END AS geom , 
       duplicate,
       gis.twochar_direction(gis.direction_from_line(st_linemerge)) = direction as reversed
  INTO bluetooth.segments_dir_corrected
  FROM bluetooth.segments
  ;
  COMMENT ON TABLE bluetooth.segments_dir_corrected IS 'Correcting the line directions from bluetooth.segments';
```

**Comment by radumas** [comment]
The below query identifies the analyses for which we've stopped receiving data and when. 

```sql
SELECT a.analysis_id, a.report_name, segment_name,
       start_date, end_date
  FROM bluetooth.all_analyses a
LEFT OUTER JOIN bluetooth.segments seg USING(analysis_id )
JOIN bluetooth.report_active_dates USING(analysis_id)
  WHERE pull_data
  ORDER BY end_date, report_name, start_date
```

analysis_id|report_name|segment_name|start_date|end_date
|----------|---------------|-----------------|-----------|----------|
130557|Gardiner-C to Gardiner-D|GD_DF_GD_SP|2014-02-27|2014-04-06
165725|Lakeshore-LY to Gardiner-D|LS_YO_GD_SP|2014-07-22|2014-09-16
165718|Gardiner-E to Lakeshore-LY|GD_PA_LS_YO|2014-07-22|2014-09-17
1419415|GTA - Lawrence AL1-AL2 EB||2016-04-09|2017-04-19
1419433|GTA - Lawrence AL2-AL1 WB||2016-04-09|2017-04-19
1419444|GTA - Sheppard AS1-AS2 EB||2016-04-09|2017-07-05
1419450|GTA - Sheppard AS2-AS1 WB||2016-04-09|2017-07-06
1428103|Shep Heron Hill to Pharmacy||2017-04-19|2017-07-06
1428150|Shep Pharmacy to 401||2017-04-19|2017-07-06
1428139|Shep Pharmacy to Clydesdale||2017-04-19|2017-07-06
1428120|Shep Pharmacy to Heron Hill||2017-04-19|2017-07-06
1427570|VP 401 to Pharmacy||2017-04-19|2017-07-06
1428092|VP Clydesdale to Pharmacy||2017-04-19|2017-07-06
1432987|DTB - Adelaide to Richmond at Duncan and Simcoe||2017-04-19|2017-07-21
1432982|DTB - Richmond -BR2-BR3|RM_SB_RM_DN|2016-10-01|2017-07-21
1432978|DTB - Richmond -BR3-BR4|RM_DC_RM_BA|2016-10-01|2017-07-21
1432992|DTB - Richmond to Adelaide at Duncan and Simcoe||2017-04-19|2017-07-21
1453239|DT-0005. Dundas-EB_Roncesvalles-to-Dufferin|DU_RO_DU_DF|2017-10-05|2017-12-17
1453507|DT-0018. Dundas-WB_Dufferin-to-Roncesvalles|DU_DF_DU_RO|2017-10-05|2017-12-17
1454832|DT-0083. Roncesvalles-SB_Dundas-to-Queen|DU_RO_QU_RO|2017-09-21|2017-12-17
1454853|DT-0084. Roncesvalles-NB_Queen-to-Dundas|QU_RO_DU_RO|2017-09-21|2017-12-17
1412641|DT- Dundas - AD1 to AD2|DU_RO_DU_SL|2015-12-03|2017-12-17
1412684|DT- Dundas - AD2 to AD1|DU_SL_DU_RO|2015-12-03|2017-12-17
1448452|Miln Milner to 401Morn||2017-08-16|2017-12-27
1448469|Morn 401Morn to McLevin||2017-08-15|2017-12-27
1448474|Morn 401Morn to Meadowvale||2017-08-15|2017-12-27
1448479|Morn 401Morn to Milner||2017-08-16|2017-12-27
1448484|Morn 401Morn to Morningside||2017-08-15|2017-12-27
1448489|Morn 401Morn to Neilson||2017-08-15|2017-12-27
1448494|Morn 401Morn to Sheppard||2017-08-15|2017-12-27
1448499|Morn McLevin to 401Morn||2017-08-15|2017-12-27
1448531|Morn Morningside to 401Morn||2017-08-15|2017-12-27
1448567|Morn Sheppard to 401Morn||2017-10-30|2017-12-27
1448665|SE Meadowvale to 401Morn||2017-08-16|2017-12-27
1448715|SE Neilson to 401Morn||2017-08-16|2017-12-27
1453667|DT-0027. Queen-EB_Parliament-to-Broadview|QU_PA_QU_BV|2017-10-02|2018-02-15
1453680|DT-0028. Queen-WB_Broadview-to-Parliament|QU_BV_QU_PA|2017-10-02|2018-02-15
1454293|DT-0057. King-EB_Parliament-to-Broadview|KN_PA_KN_BV|2017-10-02|2018-02-15
1454311|DT-0058. King-WB_Broadview-to-Parliament|KN_BV_KN_PA|2017-10-02|2018-02-15
1455710|DT-0139. Broadview-SB_Queen-to-Eastern|QU_BV_EA_BV|2017-10-02|2018-02-15
1455724|DT-0140. Broadview-NB_Eastern-to-Queen|EA_BV_QU_BV|2017-10-02|2018-02-15

**Comment by radumas** [comment]
Made a backup of the `segments` table in `bluetooth.segments_20181211` .

Added an `end_street` column:
```sql
ALTER TABLE bluetooth.segments ADD COLUMN end_street text;
```

And then updated that column with the start street if it wasn't a compound with a `/`. Else treated the latter half of that `'start_street/end_street'` string as the `end_street`

```sql
	UPDATE bluetooth.segments
	SET street = split_part(street, '/', 1), end_street = split_part(street, '/', 2)
	WHERE street LIKE '%/%'
	
	UPDATE bluetooth.segments 
	SET end_street = street 
	WHERE end_street IS NULL;
```

**Comment by radumas** [comment]
Added #102 segments to the table.
