### ISSUE TITLE
Miovision, two new cameras haven't been configured

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#622]
68 is working fine but nobody added it to intersection_movements so the data isn't being aggregated for it.
```sql
SELECT intersection_uid, classification_uid, leg, movement_uid
	FROM miovision_api.intersection_movements
	WHERE intersection_uid IN (67,68)
```
There's no data for 67

```sql
SELECT volume_uid, intersection_uid, datetime_bin, classification_uid, leg, movement_uid, volume, volume_15min_mvt_uid
	FROM miovision_api.volumes
	WHERE intersection_uid IN (67) LIMIT 100
```

The procedure for adding new intersections is currently in the Archive but there's an outstanding issue https://github.com/CityofToronto/bdit_data-sources/issues/593 to bring it back into main IIRC

https://github.com/CityofToronto/bdit_data-sources/blob/6e4c958e5092e4e6999710fefdc26f1623628bba/volumes/miovision/Archive.md?plain=1#L43

**Comment by radumas** [comment]
Also Keele & Sheppard has been fixed

**Comment by gabrielwol** [comment]
Data is in `volumes` for both these intersections but never got added to `intersection_movements`. Will add today and aggregate.

**Comment by gabrielwol** [comment]
Completed aggregating intersection 68 for 2023-01-23 00:00:00 to 2023-06-29 00:00:00.
Still to do: 67, 68 from 2023-06-29 onwards. Test with new faster functions.

**Comment by gabrielwol** [comment]
Finished aggregating these 2 intersections! One of them was already more than a year old 🥲
