### ISSUE TITLE
Detect Unusual Miovision Volume Counts Automagically 

### ISSUE THREAD

**Issue by scann0n** [CityofToronto/bdit_data-sources#630]
Through issue #570, weekly volume counts for all Miovision cameras were graphed and weeks with unusual volumes were visually identified (the ranges of bad dates per camera are stored in `miovision_api.bad_data_ranges`).

Is there a way to identify these bad data ranges without the time consuming visual inspection piece? Let's find out!

**Comment by gabrielwol** [comment]
I've opened #777 which would start to address this issue by automatically including zero count periods in `miovision_api.anomalous_ranges`. Further work will be required for periods with non-zero low/high volumes.

**Comment by Nate-Wessel** [comment]
I'd like a chance to review this before anything gets added automatically to `anomalous_ranges`. I'm off for the next couple of days though. 

I'm a little anxious about automation letting this table quickly get very big, beyond our abilities to manually check... though it's definitely the right place to flag these issues.

**Comment by gabrielwol** [comment]
No rush. Idea: we could keep manual and automated gap ID in separate tables and combine with a view if you prefer.

**Comment by Nate-Wessel** [comment]
> No rush. Idea: we could keep manual and automated gap ID in separate tables and combine with a view if you prefer.

There's actually already a way to mark ranges not yet checked by a human. See `miovision_api.anomaly_investigation_levels`'s `auto-flagged` value.
