### ISSUE TITLE
Determine when algorithm changed for streetcar classification

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#634]
#611 includes a warning about the evolution of how streetcars are classified over time.

- [x] Specify when the algorithm changed
- [x] Determine how the "mapping" works, if one classification is wholly encompassed in a different one (and if this changes)
- [x] Does this change what classifications get the higher order label "Vehicles" to avoid double counting
- [x] This issue is referenced in the README, so that should be updated when it is closed https://github.com/CityofToronto/bdit_data-sources/blob/d18b1a15ec702d1e802eb77107e3e3945d06489e/volumes/miovision/README.md?plain=1#L66

**Comment by radumas** [comment]
Tempted to include that other classifications changing over time should be documented. Primarily when did bicycle approach counts start.

**Comment by Nate-Wessel** [comment]
> Tempted to include that other classifications changing over time should be documented. Primarily when did bicycle approach counts start.

Bicycle approach counts seem to have started for real on 2021-07-11, though there are ~a few~ _three_ weird records before then for at least some cameras:
* 2021-01-26: zero
* 2021-01-27: a low value... maybe just the season and the holiday though?
* 2021-07-10: zero
(These dates are consistent for several cameras I checked.)

Then the counts seem to start in a stable pattern on 2021-07-11.

**Comment by Nate-Wessel** [comment]
As for streetcars, that algorithm appears to have changed on 2019-08-22 or 2019-08-23.

I'm basing that on a big shift in total counts observable at
* Spadina & King
* Spadina & Queen
* Bathurst & King

I'm assuming these are the places the change would be most visible. 

```sql
SELECT 
    intersection_uid,
    datetime_bin::date AS date,
    SUM(volume) FILTER (WHERE classification_uid = 3) AS count3,
    SUM(volume) FILTER (WHERE classification_uid = 9) AS count9
FROM miovision_api.volumes_15min_mvt
WHERE
    classification_uid IN (3, 9)
    AND intersection_uid = 23 -- 12 for King, 23 for Spadina
    AND datetime_bin BETWEEN '2019-07-22' AND '2019-09-22'
GROUP BY
    intersection_uid,
    datetime_bin::date
ORDER BY date
```

**Comment by Nate-Wessel** [comment]
> This issue is referenced in the README, so that should be updated when it is closed

This reference seems to have been removed. It's not in `master`.

**Comment by Nate-Wessel** [comment]
> Determine how the "mapping" works, if one classification is wholly encompassed in a different one (and if this changes)

I don't think it's the case that one category would fit within another. "Bus" would presumably still have actual buses, and "MotorizedVehicle" would still have other non-streetcar vehicles. Streetcars were never in a category by themselves. 

> Does this change what classifications get the higher order label "Vehicles" to avoid double counting

I would consider buses and streetcars to be vehicles. Is there an argument against that? It seems like a pretty clear omission to me. 

![Capture](https://github.com/CityofToronto/bdit_data-sources/assets/7830465/e2bb86c3-ff1d-4242-beac-f1c735c18726)

**Comment by radumas** [comment]
> > Determine how the "mapping" works, if one classification is wholly encompassed in a different one (and if this changes)
> 
> I don't think it's the case that one category would fit within another. "Bus" would presumably still have actual buses, and "MotorizedVehicle" would still have other non-streetcar vehicles. Streetcars were never in a category by themselves.

Per an email from Miovision August 27 2019

>The reason you might see two 'Bus' Classes is this: 'Motorized Vehicles' happens to be what we label Streetcars. We have found in Toronto that it seems like the only thing our Motorized Vehicle class is catching are Streetcars. Per an earlier conversation we had, I think it was your preference that we label streetcars as buses, so we have introduced this mapping,
Motorized Vehicle -> Bus
Bus is also a separate class type.
>
>So we generate two items in the API if in the same bin, at least one bus and one street car make the same movement.


> > Does this change what classifications get the higher order label "Vehicles" to avoid double counting
> 
> I would consider buses and streetcars to be vehicles. Is there an argument against that? It seems like a pretty clear omission to me.
> 
> ![Capture](https://user-images.githubusercontent.com/7830465/260770455-e2bb86c3-ff1d-4242-beac-f1c735c18726.PNG)

This should be better documented, we are excluding them as "Vehicles" because transit vehicle volumes are irrelevant to most of our analyses, so these volumes shouldn't be used in most analyses.
