### ISSUE TITLE
Missing mobile summary data since April 

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#639]
Nothing is appearing on OpenData.

```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, datetime_bin, speed_bin, volume
	FROM open_data.wys_mobile_detailed
	WHERE datetime_bin >= '2023-04-01' AND datetime_bin < '2023-06-01'
	LIMIT 100
```
0

```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, schedule, min_speed, pct_05, pct_10, pct_15, pct_20, pct_25, pct_30, pct_35, pct_40, pct_45, pct_50, pct_55, pct_60, pct_65, pct_70, pct_75, pct_80, pct_85, pct_90, pct_95, spd_00, spd_05, spd_10, spd_15, spd_20, spd_25, spd_30, spd_35, spd_40, spd_45, spd_50, spd_55, spd_60, spd_65, spd_70, spd_75, spd_80, spd_85, spd_90, spd_95, spd_100_and_above, volume
	FROM open_data.wys_mobile_summary
	WHERE installation_date >= '2023-04-01' AND installation_date < '2023-06-01'
	LIMIT 100
```

0

**Comment by radumas** [comment]
We only publish mobile data after the signs have been removed.

The detailed data `open_data` view is tied to the `summary` one using `location_id`. But the `wys.mobile_summary` table is also missing data (which is filled by a function). The airflow process for it ran successfully. 

```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, schedule, min_speed, pct_05, pct_10, pct_15, pct_20, pct_25, pct_30, pct_35, pct_40, pct_45, pct_50, pct_55, pct_60, pct_65, pct_70, pct_75, pct_80, pct_85, pct_90, pct_95, spd_00, spd_05, spd_10, spd_15, spd_20, spd_25, spd_30, spd_35, spd_40, spd_45, spd_50, spd_55, spd_60, spd_65, spd_70, spd_75, spd_80, spd_85, spd_90, spd_95, spd_100_and_above, volume
	FROM wys.mobile_summary
		WHERE installation_date >= '2023-04-01' AND installation_date < '2023-06-01'
```

**The airflow process doesn't check how many rows get inserted, which it maybe should and error if the number is 0**

Now we reach a possible inflection point. `wys.mobile_sign_installations` has no new installations since 2023-03-30, but is only populated when signs get removed. 

```sql
SELECT ward_no, location, from_street, to_street, direction, installation_date, removal_date, new_sign_number, comments, id
	FROM wys.mobile_sign_installations
	ORDER BY installation_date DESC
```

Ordering by `removal_date` instead we see a month gap in removals between 2023-03-30 and 2023-05-03. This was the period between the two signage contracts.

Given that signs are typically installed for 3 weeks, but maybe there's a bit of a backlog... possibly new installs since 2023-05-03 haven't been removed yet. 

That aside.... are signs removed after April 1st appearing in Open Data?

The dependency is 

1. `wys.mobile_sign_installations`
2. `wys.mobile_api_id`
3. `wys.mobile_summary`
4. `open_data.wys_mobile_summary`
5. `open_data.wys_mobile_detailed`

 The `wys.mobile_api_id` materialized view doesn't have anything with removal date after April 1st.

```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, comments, combined, api_id
	FROM wys.mobile_api_id
			WHERE removal_date >= '2023-04-01' 
```

Running the query inside the materialized view with `WHERE removal_date >= '2023-04-01'` produces 129 rows. Same as 

```sql
FROM wys.mobile_sign_installations
	WHERE removal_date >= '2023-04-01'```

So the problem isn't with the Mat View, but that it doesn't appear to have been refreshed.

Yet in Airflow the function refreshing the view ran successfully... (the second time)

```
[2023-06-02, 10:00:34 EDT] {dbapi.py:225} INFO - Running statement: SELECT wys.refresh_mat_view_mobile_api_id(), parameters: None
[2023-06-02, 10:00:36 EDT] {dbapi.py:233} INFO - Rows affected: 1
```

Give removals started May 3rd, the May run of this wouldn't have done anything.

**Comment by radumas** [comment]
Running the function called by Airflow
```sql
SELECT wys.refresh_mat_view_mobile_api_id();
SELECT location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, comments, combined, api_id
	FROM wys.mobile_api_id
			WHERE removal_date >= '2023-04-01'
-- 129 rows
```

So clearing the `wys_mobile_summary` task for the past two months. Note the May task didn't do anything since it aggregates the signs removed in the month of April (there were none).

**Comment by radumas** [comment]
Data is updated, should update to Open Data soon. 

Will check when the opendata tasks run next month that everything is smooth and then close this issue.

**Comment by radumas** [comment]
```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, datetime_bin, speed_bin, volume
	FROM open_data.wys_mobile_detailed
	WHERE datetime_bin >= '2023-06-01'
	LIMIT 100
```
0. Uh oh. Granted detailed data will only appear for signs removed **after** June 1st
```sql
SELECT location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, schedule, min_speed, volume
	FROM open_data.wys_mobile_summary
	WHERE removal_date >= '2023-06-01'
	LIMIT 100
```
12

The 8 signs removed after June 1st all have summary data, but could they be missing data in June?
```sql
SELECT location_id, sm.from_street, sm.to_street, sm.direction, installation_date, removal_date,
datetime_bin::DATE dt, COUNT(*) as cnt
	FROM open_data.wys_mobile_summary sm
	INNER JOIN open_data.wys_mobile_detailed USING(location_id)
	WHERE removal_date > '2023-06-01'
GROUP BY location_id, dt, sm.from_street, sm.to_street, sm.direction, installation_date, removal_date
ORDER BY location_id, dt
```
Some notes on this result:
* `location_id = 9016137` is missing installation details
* `location_id = 9006345` is a long installation on St. Clair, but data stops at 2022-12-27
* None of the signs have data after 2023-03-31

**Comment by gabrielwol** [comment]
See also #687
