### ISSUE TITLE
Replication processes should check there's data in the replicated drop zone

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#645]
Because these replication processes operate by `TRUNCATE` & `INSERT`, we should check that the replicator actually finished inserting data before we run our own `TRUNCATE` & `INSERT` to our schemas.

Alternatively return the count of inserted rows in the function and have the task fail if that's 0.

**Comment by gabrielwol** [comment]
The replication process has changed since this issue was created, but I think this is still relevant to the new process. We can check that the destination table has non-zero row count.

**Comment by radumas** [comment]
source table for copying data with `trans-bdit` no?

**Comment by gabrielwol** [comment]
Will check the source table before copying and the destination table after copying.
