### ISSUE TITLE
miovision_api.find_gaps improvements

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#673]
Looking at the pull_miovision airflow logs, this step alone takes 40 minutes to run. 

- Explain shows it includes multiple seq scans over `miovision_api.volumes` table
- 10+ CTEs
- long and not well commented
- use of `ful` table probably not necessary.
- needs fluffing for readability 
- Fails silently for intersections with no data at all
- For gaps overlapping multiple hours, only the start of the hour is used to determine the allowed_gap threshold.
- Holidays not considered when determining weekdays/weekends
- gap sizes are exaggerated by 1 minute, since both gap_start and gap_end are exclusive. 

@scann0n's gap and islands approach for rescu can be used for inspiration (runs in just a few seconds for whole year of rescu data): https://github.com/CityofToronto/bdit_data-sources/blob/d85291a5b76b65cc6348f5d30949a1887b35e236/volumes/rescu/date_evaluation/x2_rescu_gaps.sql

**Comment by radumas** [comment]
Also relevant:
https://github.com/CityofToronto/bdit_data-sources/issues/3700
https://github.com/CityofToronto/bdit_data-sources/issues/419

**Comment by gabrielwol** [comment]
@radumas Another issue with this function is it accepts `start_date` and `end_date` to be run for multiple days, however it uses a 60 day lookback to identify an acceptable threshold based only on end_date. In other words it may not produce the same results backfilling over a period as it would when run daily. 
Alternatives: 
1) Change to only accept start_date and run for a single date. I think we could still run multiple days at a time with a LATERAL command. 
2) Set new thresholds at the `intersections` table level which are not calculated based on end_date. Perhaps 1 single threshold across all sensors (15 minutes?). This is the current threshold case statement, where `avg(mio.vol)` is the avg volume for that hour over the previous 60 days.  
```
CASE
    WHEN avg(mio.vol) < 100::numeric THEN 20
    WHEN avg(mio.vol) >= 100::numeric AND avg(mio.vol) < 500::numeric THEN 15
    WHEN avg(mio.vol) >= 500::numeric AND avg(mio.vol) < 1500::numeric THEN 10
    WHEN avg(mio.vol) > 1500::numeric THEN 5
    ELSE NULL::integer
END AS gap_tolerance 
```

**Comment by gabrielwol** [comment]
> @radumas Another issue with this function is it accepts `start_date` and `end_date` to be run for multiple days, however it uses a 60 day lookback to identify an acceptable threshold based only on end_date. In other words it may not produce the same results backfilling over a period as it would when run daily. Alternatives:
> 
>     1. Change to only accept start_date and run for a single date. I think we could still run multiple days at a time with a LATERAL command.
> 
>     2. Set new thresholds at the `intersections` table level which are not calculated based on end_date. Perhaps 1 single threshold across all sensors (15 minutes?). This is the current threshold case statement, where `avg(mio.vol)` is the avg volume for that hour over the previous 60 days.
> 
> 
> ```
> CASE
>     WHEN avg(mio.vol) < 100::numeric THEN 20
>     WHEN avg(mio.vol) >= 100::numeric AND avg(mio.vol) < 500::numeric THEN 15
>     WHEN avg(mio.vol) >= 500::numeric AND avg(mio.vol) < 1500::numeric THEN 10
>     WHEN avg(mio.vol) > 1500::numeric THEN 5
>     ELSE NULL::integer
> END AS gap_tolerance 
> ```

After discussion with Raph I chose to use a standard 15 minute allowable gap size instead of a dynamically calculated one based on lookback, which avoids issues described above, and that of using bad data to choose a threshold.

**Comment by gabrielwol** [comment]
Note for future: current method curiously doesn't capture 15 minute gaps that overlap an hour boundary. I think this might be OK, since we use this data to decide which hours to throw out.
