### ISSUE TITLE
`traffic.cnt_det` is occasionally empty

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#675]
From earlier discussion on Slack, I believe there is a bug somewhere in the process that updates this table. Possibly a timing issue?

From @radumas 
> There's data in `"TRAFFIC_NEW"."CNT_DET"` so there must've been a timing issue with our synchronizing function...

This is the second time I've noticed the problem. The table has no records at the moment where before  they were plentiful.

**Comment by gabrielwol** [comment]
New replication process since #748 - don't think this is an issue anymore.
