### ISSUE TITLE
pull_wys.read_google_sheets is failing silently inserting into ward_NO tables.

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#677]
`pull_wys.read_google_sheets` is failing silently when trying to insert signs with duplicate constrained values. Related to PRIMARY KEY (installation_date, new_sign_number).   

[One example:](https://10.160.2.198/airflow/log?dag_id=pull_wys&task_id=read_google_sheets&execution_date=2023-08-16T19%3A00%3A00%2B00%3A00)
```
[2023-08-17, 15:00:28 EDT] {wys_google_sheet.py:144} ERROR - There was an error inserting into ward_16
[2023-08-17, 15:00:28 EDT] {wys_google_sheet.py:145} ERROR - ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

**Comment by radumas** [comment]
@tahaislam was working on porting this over to be using the work order.
