### ISSUE TITLE
Make all DAGs Time Zone Aware

### ISSUE THREAD

**Issue by tahaislam** [CityofToronto/bdit_data-sources#685]
We should make our DAGs time zone aware by explicitly specifying the time zone of each DAG's `start_date`. Here's an example of the proposed change:

`start_date = datetime(2020, 4, 1)`
should be
`start_date = pendulum.datetime(2020, 4, 1, tz="America/Toronto")`

**Comment by radumas** [comment]
Just linking to the documentation for future reference on this
https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timezone.html#time-zone-aware-dags
