### ISSUE TITLE
Port over `check_rescu` functionality to `vds`

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#702]
Port over functionality from `check_rescu` DAG to new `vds` schema.

- Change to rolling lookback rather than fixed value. 
- Implement on `raw_vdsdata` and `raw_vdsvehicledata`

**Comment by radumas** [comment]
Noting some occasional performance issues with this (e.g. yesterday). Possibly related to when `VACUUM`ing happens, related to https://github.com/CityofToronto/bdit_data-sources/issues/469 ?

**Comment by gabrielwol** [comment]
> Noting some occasional performance issues with this (e.g. yesterday). Possibly related to when `VACUUM`ing happens, related to #469 ?

Note that there was no auto-vacuum on the queried tables in the intervening time between the slow attempts and the next day's normal speed.

**Comment by gabrielwol** [comment]
Was closed by #705
