### ISSUE TITLE
Pull path only data for HERE 

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_data-sources#704]
Transition from pulling probe_path to probe only data for HERE.

- [x] Create the same table structure for probe data in `here` schema.

- [x] Edit here_api.py to pull for `path`

- [x] Modify DAG to pull monthly instead of daily (for backfilling purposes)

**Comment by Nate-Wessel** [comment]
`path` only is what we're looking for. `probe` is weighted by individual GPS points, not the number of vehicles. `probe-path` was a bizarre combination of those two approaches.
