### ISSUE TITLE
WYS `get_schedules` failing with `TypeError`

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#713]
Failing with following [error message](https://10.162.65.124/airflow/dags/pull_wys/grid?root=&dag_run_id=scheduled__2023-09-27T19%3A00%3A00%2B00%3A00&task_id=pull_wys&tab=logs): 
```
[2023-09-28, 23:55:06 EDT] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/data/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/data/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/data/airflow/dev_scripts/wys/api/python/wys_api.py", line 380, in api_main
    get_schedules(conn, api_key)
  File "/data/airflow/dev_scripts/wys/api/python/wys_api.py", line 475, in get_schedules
    rows = [(schedule['name'], api_id) for schedule in schedule_list if schedule['assigned_on_locations']
  File "/data/airflow/dev_scripts/wys/api/python/wys_api.py", line 475, in <listcomp>
    rows = [(schedule['name'], api_id) for schedule in schedule_list if schedule['assigned_on_locations']
TypeError: string indices must be integers
```
Seems to be related to a change in API response value. 
Related to #629, this small, standalone function is called is at the end of `pull_wys` task (1 hour run time), causing that task to fail. As part of this bug fix we should consider separating it into it's own Airflow task.

**Comment by gabrielwol** [comment]
Response at endpoint `https://api.streetsoncloud.com/sv2/signs/schedules` is: 
Status: 200
`{'result': {'error': {'error-exception': 'An error occurred during execution; please try again later.'}}}`

**Comment by radumas** [comment]
>As part of this bug fix we should consider separating it into it's own Airflow task.
Yes definitely .

https://github.com/CityofToronto/bdit_data-sources/blob/2d76634bf55e498226ecdcb1bb93289298741b90/wys/api/python/wys_api.py#L477-L483

This section isn't performing any checking on the response before looping over the elements of the resulting json. 

Should be using a `raise_for_status()` like this example. Though the error block should also print the response, which I think can be gotten from the requests.exceptions.HTTPError with `exc.response`  https://requests.readthedocs.io/en/latest/_modules/requests/exceptions/#RequestException

https://github.com/CityofToronto/bdit_data-sources/blob/2d76634bf55e498226ecdcb1bb93289298741b90/bluetooth/api/blip_space_log.py#L33-L40
