### ISSUE TITLE
`wys.aggregate_speed_counts_one_hour_5kph` failing with duplicate key error

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#720]
See [airflow logs](https://trans-bdit.intra.prod-toronto.ca/airflow/log?dag_id=pull_wys&task_id=pull_wys&execution_date=2023-08-25T23%3A46%3A01.602352%2B00%3A00). I suspect this occurred because on one of the (many) retries for this date, new data was pulled for a `api_id` /  `datetime_bin` combo which had previously been aggregated. The aggregate table is not cleared before inserting, so new data (`speed_count_uid IS NULL`) matching an existing combination will result in this duplicate key error. Due to #719, the new data could overlap only on `api_id` /  `datetime_bin` and not `speed_id`.

**Comment by gabrielwol** [comment]
@radumas a temporary fix would be to clear this date: 
```sql
DELETE FROM wys.speed_counts_agg_5kph
WHERE datetime_bin >= '2023-08-25 00:00:00'::timestamp
AND datetime_bin < '2023-08-25 00:00:00'::timestamp + interval '1 day';
DELETE FROM wys.raw_data_2023
WHERE datetime_bin >= '2023-08-25 00:00:00'::timestamp
AND datetime_bin < '2023-08-25 00:00:00'::timestamp + interval '1 day';
```
And re-run via [airflow UI](https://trans-bdit.intra.prod-toronto.ca/airflow/dags/pull_wys/grid?base_date=2023-08-26T23%3A59%3A59.999Z&dag_run_id=scheduled__2023-08-25T19%3A00%3A00%2B00%3A00&task_id=pull_wys&tab=logs).

**Comment by radumas** [comment]
Deleted and task cleared. Thanks Gabe!
