### ISSUE TITLE
Add a new collision replicator DAG

### ISSUE THREAD

**Issue by tahaislam** [CityofToronto/bdit_data-sources#734]
Add a new collision replicator DAG to save `ACC` and other MOVE's materialized views in the newly created `collisions` schema. This DAG should truncate and insert records of `ACC`, `events`, `involved`, and `events_centrelines` tables from the `collisions_staging` into `collisions` schema every day after the MOVE replicator DAG finishes its daily run.

**Comment by gabrielwol** [comment]
Closed by https://github.com/CityofToronto/bdit_data-sources/pull/748.
