### ISSUE TITLE
Backfill miovision intersection_uid = 65 

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#754]
Data accidentally deleted under #735 due to new primary key which prevents null `classification_uid`. 
The pedestrian in roadway are now bicycle volumes. 
See details of the extents here: https://github.com/CityofToronto/bdit_data-sources/pull/735#issuecomment-1794882070
Notes by @radumas here: https://github.com/CityofToronto/bdit_data-sources/pull/735#issuecomment-1793091109

**Comment by radumas** [comment]
@gabrielwol should create an anomalous range for intersection_uid 65, movement_uid 7, classification 10 and highlight that volumes *might* be low because of an algorithm issue at this location.

And then not worry about backfilling, this issue can be closed after the range is created.

**Comment by gabrielwol** [comment]
Added to intersection movements and re-ran all the aggregations for this intersection for all dates to include bike approaches.
