### ISSUE TITLE
Failed to check traffic signals geometry

### ISSUE THREAD

**Issue by tahaislam** [CityofToronto/bdit_data-sources#768]
One of the records in `gis.traffic_signal`, which is being updated daily by the DAG `traffic_signals_dag`, has invalid geometry (latitude) as shown below. We need to check each record's coordinates before inserting it into the database.

From the source
![image](https://github.com/CityofToronto/bdit_data-sources/assets/97190976/136b871a-1e39-40d9-b687-df0bcfcaf0b4)

In our database
![image](https://github.com/CityofToronto/bdit_data-sources/assets/97190976/a2d93885-71c3-4c86-9e51-e8e4b5a89df2)

**Comment by gabrielwol** [comment]
This geometry has since been fixed.
