### ISSUE TITLE
Create a daily Miovision table for Data Collection

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#780]
- Data Collection team is seeking daily volumes, so do not filter out entire hours because small gaps (5 minutes) are missing! This is the status quo in the current `volumes` -> `volumes_15min_mvt` -> `volumes_daily aggregation`.
- This should be fast to query, so it should be a table (not a mat view since it is updated daily). 
- Make it obvious that a day has unacceptable gaps, but do not exclude. Let end user come up with thresholds. 
- Exclude `anomalous_ranges`.

**Comment by ZahraGhayen** [comment]
@gabrielwol  Thanks for the great work!!
As we discussed, two columns need to be added to this table; 
1.  `gap_estimated_total_volume`, which represent volume from `historical_hourly_volume` data at the time of the gaps we are detecting in each count.  
2. `historical_total_daily_volume` of each location.

This way we can decide if the gaps are affecting total volumes in a significant way or not.

**Comment by Nate-Wessel** [comment]
> This should be fast to query, so it should be a table (not a mat view since it is updated daily).

Isn't a mat view just as fast to query? You can put the same indices on it and update it concurrently.

**Comment by gabrielwol** [comment]
@Nate-Wessel The trade-off I meant was that each day we can either:
(1) insert one new record into this (table)
or (2) refresh the entire thing (mat view).
