### ISSUE TITLE
Change WYS inheretence -> declarative partitioning

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#781]
Update `wys.mobile_sign_installations` and `wys.raw_data` to declarative partitioning. 
- `wys.raw_data`:
  - yearly tables are approaching 30GB+30GB indices. Further partition into monthly tables. 
  - Add new functions for partition creates + new airflow task check_partitions (similar to recent Miovision addition)
- `wys.mobile_sign_installations`:
  - 25 ward tables is very cluttered! Change to declarative partitioning. No other changes required. 
  - Intersections_tmc requires minor update - change inserts to target parent table.

**Comment by gabrielwol** [comment]
There are 21M records with null speed/count in 2021/2022:
```sql
-- sum, count, min, max, distinct
-- null, 20996831, "2021-03-30 00:00:00", "2022-10-03 23:59:00", 866
SELECT SUM(count), COUNT(*), MIN(datetime_bin), MAX(datetime_bin), COUNT(DISTINCT api_id)
FROM wys.raw_data WHERE datetime_bin >= '2020-01-01'::date AND datetime_bin < '2023-01-01'::date AND speed IS NULL;
```
@radumas Do we want to preserve these when re-partitioning?
Note they are not included in any of our current summarizations due to inner joins with `speed_bins_old`.

**Comment by radumas** [comment]
I would say keep them in. I didn't realize they had stopped being recorded in that way.

I think when we raised this it was explained/interpreted as being a way to identify the sign worked but didn't record any data. Can dig in quick

**Comment by gabrielwol** [comment]
A history lesson! thanks.

**Comment by gabrielwol** [comment]
A bit of a hiccup: among those `speed IS NULL` records, there are duplicates - because nulls are not considered distinct values they got past the unique constraint. 
```sql
--278864 records that are at least duplicated (or worse)
SELECT api_id, datetime_bin, COUNT(*)
FROM wys.raw_data 
WHERE
    datetime_bin >= '2020-01-01'::date
    AND datetime_bin < '2023-01-01'::date
    AND speed IS NULL
GROUP BY 1, 2
HAVING COUNT(*) > 1
```

Example (not exactly sure how `speed_count_uid` ended up as null): 
```sql
SELECT * FROM wys.raw_data
WHERE api_id = 1750	AND datetime_bin = '2022-04-16 23:59:00'::timestamp
```
| "api_id" | "datetime_bin"        | "speed" | "count" | "speed_count_uid" |
|----------|-----------------------|---------|---------|-------------------|
| 1750     | "2022-04-16 23:59:00" |         |         |                   |
| 1750     | "2022-04-16 23:59:00" |         |         |                   |
| 1750     | "2022-04-16 23:59:00" |         |         | 157481330         |

Going to solve this with a `NULLS NOT DISTINCT` to the unique constraint and summarizing these records.
