### ISSUE TITLE
Low Miovision Volumes [Oct 2, Oct 5], [Nov 9]

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#799]
There was an issue with [pedestrians in the roadway](https://bditto.slack.com/archives/C021YMH9BK5/p1696317089457899) and the pull_miovision DAG [failed](https://trans-bdit.intra.prod-toronto.ca/airflow/dags/pull_miovision/grid?base_date=2023-10-06T23%3A59%3A59.999Z&dag_run_id=scheduled__2023-10-05T07%3A00%3A00%2B00%3A00) for those 4 days. We may have re-run from the command line, but the volumes are very low: 

![image](https://github.com/CityofToronto/bdit_data-sources/assets/80077912/5fd30b31-6ece-49c8-b0e9-f9d2a502efeb)

We'll need to clear the existing values before re-running.
- [x] Oct 2
- [x] Oct 3
- [x] Oct 4
- [x] Oct 5
- [x] Nov 9

**Comment by chmnata** [comment]
There is no data at all for Oct 04?

**Comment by gabrielwol** [comment]
Actually, there is some data for Oct 4, but it didn't get aggregated at all. 
Also the volume for that date is only total 136844, when it should be about 10x that.

**Comment by chmnata** [comment]
Ran 
```
DELETE FROM miovision_api.unacceptable_gaps
WHERE gap_start >= '2023-10-02 00:00:00'::timestamp
AND gap_start < '2023-10-06 00:00:00'::timestamp;

SELECT miovision_api.clear_api_log('2023-10-02', '2023-10-06');
SELECT miovision_api.clear_volumes('2023-10-02', '2023-10-06');
SELECT miovision_api.clear_volumes_15min('2023-10-02', '2023-10-06');
SELECT miovision_api.clear_15_min_mvt('2023-10-02', '2023-10-06');
```
Now re-running airflow dag

**Comment by chmnata** [comment]
ran into peds error issue, will have to

- [ ] run a version of the code that pulls and ignores the error
- [ ] Reinsert those peds volumes as bike
- [ ] run aggregate function

**Comment by chmnata** [comment]
So an issue im encountering, there are cases where there are already a bike detected at the same datetime_bin + same volume + same movement. I not sure if I should delete the duplicated one or add them??
(classification_uid = 10 is bike from api classification, classification_uid = 999 is peds but I renamed to 999 to bypass null constraint error)
![image](https://github.com/CityofToronto/bdit_data-sources/assets/46324452/e62dd1b2-ae21-4737-a9cc-fbb8347cc63c)

**Comment by chmnata** [comment]
Number of duplicated rows: 
- 2023-10-02: 12 rows, total volume 13
- 2023-10-03: 16 rows, total volume 16
- 2023-10-04: 19 rows, total volume 20
- 2023-10-05: 9 rows, total volume 9

Kinda confused why I am not aware of this issue before :confused:, I think I might have just inserted duplicated data and not knowing about it before 😢

**Comment by chmnata** [comment]
Repulling completed for all days, we summed the volumes up where wrong peds and bike (classification 10) was recorded at the same time, we will check to see if the bike volumes are weird.

**Comment by radumas** [comment]
>it doesn't get aggregated to volume_15 or volume_15_mvt.

@gabrielwol can you investigate why 10 isn't getting aggregated for intersection 65?

**Comment by chmnata** [comment]
Thats cause it wasn't a movement in `miovision_api.intersection_movements`

**Comment by gabrielwol** [comment]
Added to intersection movements and re-ran all the aggregations for this intersection for all dates to include bike approaches.
Also added comment to anomalous_ranges (uid 896) about bikes in crosswalks for 10-02 to 10-05 at Bayview/River.
