### ISSUE TITLE
Generalized MOVE Summary Stats Transform-nation

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#810]
We did a request that required:
- peak hour counts from TMCs and speed volumes
- mean, 15th, 50th, 85th and 95th percentile speeds
- Daily traffic volumes (from speed volumes)

Now can we generalize this to make future requests (and work) easier?

I was thinking a `VIEW`, but it might be more appropriate to be calculating summary stats on a function basis, which should maybe go into the MOVE count loading and then get replicated over to us. 

cc: @peter-lyons @mkewins

**Comment by mkewins** [comment]
Yes please! This would be fantastic. We've had fairly extensive conversations with David and Jesse about Peak Hour calculations in the past.

A couple notes:
- Here is our [Peak Hour calculation for the TMC Summary Report](https://github.com/CityofToronto/bdit_flashcrow/blob/d6012c0e580a771afc531846d01a18088fa44fff/lib/reports/ReportCountSummaryTurningMovement.js#L196), or see the [human-readable description](https://www.notion.so/bditto/Frequently-Asked-Questions-9d6526e8d84d4abc90d43d4cdaba14e2?pvs=4#c2b0c8075efa42279e710b56a8c84fa1); is it different from what you defined?
- There's been some discussion with Data Collection around changing the definitions of Peak Hours to accommodate continuous data, not just the legacy 8-hour Routine vs Ped hours; did you consider this?

**Comment by scann0n** [comment]
I defined peak hours based on that code! And I got a match with MOVE.

**Comment by radumas** [comment]
The percentile calculations in MOVE are documented [here ](https://www.notion.so/bditto/Percentile-Speed-Calculations-6abf2f545f2f4781936726e4d54b3713?pvs=4)
