### ISSUE TITLE
Basic/Introductory documentation needed for Miovision data

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#858]
Someone asked me for some basic information on our Miovision data, and there really doesn't seem to be anything to show them that doesn't get way too technical way too fast. 
https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/README.md

I'd like to create an introductory readme that just contains the basics.
* what are these cameras?
* what do they count?
* when?
* how?
* where are they?
* we are adding more!
* etc

The technical stuff then can be buried a little deeper, and I think would be better in linked readme's, not the main one. Basically, we need better information hierarchy here - general to specific.

**Comment by gabrielwol** [comment]
@Nate-Wessel good recommendations. I blew up the main Miovision readme and moved anything that wasn't introductory to existing sub readmes. You can review proposed changes here: https://github.com/CityofToronto/bdit_data-sources/blob/832-miovision-readme-updates/volumes/miovision/README.md

**Comment by Nate-Wessel** [comment]
That introductory readme is excellent!! Exactly the sort of thing I had in mind!
