### ISSUE TITLE
Trip Filtering

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#87]
Filter out
- [x] Trips linked to vehicles that spend less than 1 km or more than 4 km in the pilot area (Bathurst to Jarvis).
- [x] Trips linked to vehicles that spend more than 100 minutes in the pilot 
- [x] Trips with run numbers between 60 and 89.

**Comment by DorothyZou** [comment]
For the third requirement, there is not trip of route 514 in 2017 having the run number between 60 and 89.

Not result output after running this query:
```sql
SELECT * FROM ttc.cis_20171004
WHERE route = 514 AND (run BETWEEN 60 AND 89)
```

**Comment by DorothyZou** [comment]
The run numbers of route 514 on 10/04/2017 are from 50 to 59.

```sql
SELECT DISTINCT run FROM ttc.cis_20171004
WHERE route = 514
ORDER BY run
```

|run|
|---|
|50|
|50|
|50|
|50|
|50|
|50|
