### ISSUE TITLE
Miovision: action items on anomalous_ranges and discontinuities

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#874]
Transferring over action items from [meeting notes on anomalous_ranges](https://www.notion.so/bditto/2024-02-08-AR-and-DISCO-bad5d29cf07645148c87d2a0da2e9b21) to github for more visibility.

**Ranges to add:** 
- [x]  Add schema comments as ARs: Modes are considered reliable enough to use as of... “June 2019 for pedestrians”, "September 2019 for bikes"
- [ ]  rethink zero-padding of classifications in backfilled data before those classifications came online
  - is this an AR to add?
 
**Rethink investigation_level x problem_level.** Nate already did some work on consolidating.  
- [x]  Nate to have a think about the investigation_level x problem_level combos  
- [ ]  Cross constraint in anomalous ranges on investigation levels and problem levels
- [x]  remove `investigating` investigation_level, replacing with `suspect`

**Create discontinuity table**: https://github.com/CityofToronto/bdit_data-sources/pull/877
- [x] @Nate-Wessel evaluate all the null `intersection_uid` entries and evaluate if they belong in AR or Disco table (or both). Action item moved to https://github.com/CityofToronto/bdit_data-sources/pull/877. 
- [x] Add issues from here: https://github.com/CityofToronto/bdit_data-sources/issues/846#issuecomment-1947241738

**Updates to anomalous_ranges structure:** 
- [x] add `leg` to anomalous_ranges (nulls allowed): https://github.com/CityofToronto/bdit_data-sources/tree/874-anomalous_ranges-and-discontinuities-updates
- [x] ~~`intersection_uid` column of anomalous_ranges should not be NULL (after disco table is created).~~ Item axed after [discussion](https://github.com/CityofToronto/bdit_data-sources/issues/874#issuecomment-1944105613). 
- [x] Any changes to anomalous_ranges will require updates to `identify_zero_counts`

**features to add**
- [x] A weekly reminder to investigate open issues with volumes. Added in https://github.com/CityofToronto/bdit_data-sources/pulls/854

**Documentation**
- [ ]  Prepare example cases/documentation on creating anomalous ranges

**Comment by Nate-Wessel** [comment]
>  remove `investigating` investigation_level, replacing with `suspect`

This is partly done. Someone more powerful than I just needs to run 

```sql
DELETE
FROM miovision_api.anomaly_investigation_levels
WHERE uid = 'investigating'
```

**Comment by chmnata** [comment]
> > remove `investigating` investigation_level, replacing with `suspect`
> 
> This is partly done. Someone more powerful than I just needs to run
> 
> ```sql
> DELETE
> FROM miovision_api.anomaly_investigation_levels
> WHERE uid = 'investigating'
> ```

deleted!

**Comment by Nate-Wessel** [comment]
>  `intersection_uid` column of `anomalous_ranges` should not be NULL (after disco table is created).

I don't recall discussing this and would be opposed to it. There are still a lot of valid cases where things worth noting here could effect all intersections. These could be algorithm rollouts, power outages, freak weather events, or emergency measures related to pandemics... (no, we're not all going to just remember the exact date of the first lockdown ten years from now).

If we add a not-null constraint here I think we're likely to just end up with a ton of duplicate records all trying to say the same thing.
