### ISSUE TITLE
Where did all the `WorkVan`s go?

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#875]
There is no data for `classification_uid = 8` in any of the Miovision volumes tables. 

```sql
SELECT *
FROM miovision_api.volumes
WHERE classification_uid = 8
```

Did we have this before? Has it always been missing and I'm just now noticing?

**Comment by gabrielwol** [comment]
A quick investigation: 
- I spot checked the API results for a few intersections and I didn't see any `WorkVan`s. Even querying a few dates/intersections 2019 I didn't see any.
- The [API docs](https://docs.api.miovision.com/) for `tmc` endpoint do still mention `WorkVan`: 
> Returns the number of vehicles that SmartSense detected in the configured zones, where they came from, the direction of travel (N,S,E,W,NE,SE,SW,NW,UNDEFINED), and their class (Pedestrian, Bicycle, Light, WorkVan, SingleUnitTruck, ArticulatedTruck, Bus). Results are aggregated into 1 minute bins.

- As noted by Raph, we were getting WorkVan data in 2019 through the API: https://github.com/CityofToronto/bdit_data-sources/issues/233#issuecomment-556048902  

It is mysterious that they would not be present in `volumes` table, at least for 2019 😕 One theory is that they were merged with another mode, possibly back in 2019, and we repulled data, overwriting the older API results which did include `Workvan`.

**Comment by gabrielwol** [comment]
I added an entry to anomalous_range table, so when we send the list of open issues to Miovision, we will include a question about WorkVans.

**Comment by radumas** [comment]
Good catch Nate!


They are now folded into `Light`, so we should edit the documentation and remove them from the code and database.

**Comment by Nate-Wessel** [comment]
Is there any work that would have used these in the past? We might want to retain mention of this rather than fully purge it from the collective memory.

**Comment by radumas** [comment]
Looks like just data requests and all last year, so there probably wouldn't have been volume returned.
