### ISSUE TITLE
Match Stops

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#88]
Buffer: 200m upstream and 10m downstream respectively (with no interpolation).
 - [x] Arrival time: earliest point within buffer
 - [x] Departure time: latest point within buffer

**Comment by radumas** [comment]
1. [ST_LineLocatePoint](http://postgis.net/docs/manual-2.1/ST_Line_Locate_Point.html) to get the GPS point on the appropriate `shapes_geom`.
2. Compare distance along line with matched stop to see if GPS record is before or after stop. 
3. Get arrival time and departure time within 200m upstream, 10m downstream as per above :point_up:

**Comment by DorothyZou** [comment]
1. Using [ST_ClosestPoint](http://postgis.net/docs/manual-1.5/ST_ClosestPoint.html) instead of ST_LineLocatePoint
