### ISSUE TITLE
Determine direction

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#89]
- [x] Generate lookup table of gtfs stops and azimuths between the preceding stop and the current one.
 - [x] Determine compass azimuth between current point and next point using [`ST_Azimuth()`](https://postgis.net/docs/ST_Azimuth.html). _Include previous point as well? If three points create an acute angle, point is probably at a terminal..._
 - [x] Match CIS data to nearest stop `AND cis.azimuth BETWEEN stop.azimuth - 45 AND stop.azimuth + 45`. 
 - [x] Investigate non-matches.

**Comment by radumas** [comment]
@DorothyZou See also 
https://github.com/CityofToronto/bdit_team_wiki/blob/master/ttc_data_plan.md#2-snap-stops
And @jwrcoleman updated that document after our phonecall

**Comment by DorothyZou** [comment]
To investigate the non-matches,
there are 23708 records of CIS data of route 514 on Oct.04, 2017, and 15581 of them are non-matches **(about 65.7%)**.

Most of the non-matches have the distance between 10 to 100 metres with their nearest GTFS stops. 

```sql 
WITH group_non_match AS (
SELECT
CASE WHEN st_distance BETWEEN 0 AND 10
THEN 'less than 10 metres'
WHEN st_distance BETWEEN 10 AND 100
THEN '10-100 metres'
WHEN st_distance BETWEEN 100 AND 500
THEN '100-500 metres'
WHEN st_distance BETWEEN 500 AND 1000
THEN '500-1000 metres'
WHEN st_distance > 1000
THEN 'more than 1000 metres'
ELSE 'negaitive'
END AS interval_st_distance
FROM dzou2.test6_non_match)

SELECT interval_st_distance, count(*) AS total_num
FROM group_non_match
GROUP BY interval_st_distance
```

The result is 

| interval_st_distance | total_num|
| --- | --- |
| less than 10 metres | 2582 |
| 10-100 metres | 9068 |
| 100-500 metres | 1355 |
| 500-1000 metres | 198 |
| more than 1000 metres | 2378 |

The limitation of `AND cis.azimuth BETWEEN stop.azimuth - 45 AND stop.azimuth + 45` is the reason why the non-matches are filtered out.

```sql
WITH group_non_match AS (
SELECT
CASE WHEN cis_angle_pre < stop_angle_pre - 45
THEN 'the angle with previous point(CIS) < the angle with previous point(GTFS)-45 '
WHEN cis_angle_pre > stop_angle_pre + 45
THEN 'the angle with previous point(CIS) > the angle with previous point(GTFS)+45'
WHEN cis_angle_next < stop_angle_next - 45
THEN 'the angle with next point (CIS) < the angle with next point(GTFS)-45'
WHEN cis_angle_next > stop_angle_next + 45
THEN 'the angle with next point (CIS) > the angle with next point(GTFS)+45'
ELSE 'negaitive'
END AS angle_differences
FROM dzou2.test6_non_match)

SELECT angle_differences, count(*) AS total_num
FROM group_non_match
GROUP BY angle_differences
```

Result output:

| angle_differences | total_num|
| --- | --- |
| the angle with previous point(CIS) < the angle with previous point(GTFS)-45  | 9881 |
| the angle with previous point(CIS) > the angle with previous point(GTFS)+45 | 2976 |
| the angle with next point (CIS) < the angle with next point(GTFS)-45 | 2325 |
| the angle with next point (CIS) > the angle with next point(GTFS)+45 | 399 |

**Comment by radumas** [comment]
For the comparison, it would be helpful to compare to what scheduled service was that day. We should be getting a number of matched stops close to the scheduled stop times for that day, for example in the view `gtfs_raph.stop_times_20171004_504_514`.
