### ISSUE TITLE
Airflow Replicator: Add daily status message for collision and count replicator DAGs

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_data-sources#894]
### Feature Request
Please add a daily notification with a status (success or failure) message from `collisions_replicator` and `counts_replicator` DAGs.

### Background
These tasks failed, and there was no notification. In order to track these, I'd like a notification so I can be aware of success or failure on a daily basis. This will help with debugging data status issues.

**Comment by chmnata** [comment]
There is a failed slack notification in the _dev channel. Currently it only alerts Islam, I will change it to Gabe + me + you for those two dags.

**Comment by chmnata** [comment]
I have added your username to the alert message for those two dags, is there any other DAG you would like to be notified of?

**Comment by gabrielwol** [comment]
Made some progress on adding a success message and consolidating the failure messages for different tables into one. Will test upon return.

**Comment by mkewins** [comment]
@chmnata I think those two replicator tasks are good for now.
