### ISSUE TITLE
Miovision Bathurst & King

### ISSUE THREAD

**Issue by jwrcoleman** [CityofToronto/bdit_data-sources#929]
While working on the King St Transit dashboard with the Data Science team, we noticed some weird car flows at King & Bathurst, a flipping of which approach had the highest volumes from the West approach to the East approach, and some low pedestrian totals. Not sure if its a construction issue, or what has been happening at that location but just flagging for a quick review. Seemed to happen over the timeline of early 2024, looked from fall 2023 to present.

**Comment by gabrielwol** [comment]
Suspicions confirmed: it looks like after a brief outage between 2024-01-04 and 2024-01-16, the legs were switched (E<->W, N<->S). A similar but less pronounced pattern for ped volumes also occurs. There was no record of an alert around then. Will do a bit more investigation after standup. 
![image](https://github.com/CityofToronto/bdit_data-sources/assets/80077912/fd66468b-3c58-4832-8898-88068d605943)

```sql
SELECT datetime_bin::date AS dt,
    SUM(volume) FILTER (WHERE leg = 'E') AS vol_E,
    SUM(volume) FILTER (WHERE leg = 'W') AS vol_W,
    SUM(volume) FILTER (WHERE leg = 'N') AS vol_N,
    SUM(volume) FILTER (WHERE leg = 'S') AS vol_S
FROM miovision_api.volumes
WHERE
    intersection_uid = 10 AND datetime_bin >= '2023-10-01'::date AND classification_uid = 1
GROUP BY 1
ORDER BY 1
```

**Comment by gabrielwol** [comment]
@jwrcoleman I confirmed in Miovision One that this camera was reconfigured on Jan 18th by Miovision with a 2nd camera being added on that date. Will add to the shared spreadsheet for communication with Miovision and add some anomalous_ranges. Once the issue is resolved we could edit the historical data to reverse these directions.

**Comment by gabrielwol** [comment]
Followed up to the vendor with more questions. There is even further confusion starting on 2024-04-09 where the S and W volumes seem to double overnight and pedestrian volumes disappear 🤦‍♂️
