### ISSUE TITLE
Nine different day numbers in `traffic.countinfomics.day_no`? 

### ISSUE THREAD

**Issue by Nate-Wessel** [CityofToronto/bdit_data-sources#952]
This [isn't super-well documented](https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/short_term_counting_program#countinfomics), but I'd expect this field to have 7 distinct values. It has 9

```sql
SELECT DISTINCT day_no 
FROM traffic.countinfomics
ORDER BY day_no
```

Is this `DOW`? `ISODOW`? Both and more?

**Comment by mkewins** [comment]
For posterity...

- It appears this is likely an off-by-1 error introduced by MOVE. @peter-lyons is looking into this with respect to new data.
- We'll need to investigate/cleanup old data (can loop this into MOVE task, since this is study-related, coming upstream from MOVE ETL pipelines).
- and, we should likely drop the column `day_no` in bigdata views if it shouldn't be used. cc: @radumas

**Comment by gabrielwol** [comment]
Will need to do some heavy lifting to edit all these views which depend on day_no columns:

`traffic.countinfo`:
view aduyves.investigate_cp_geo_id_coverage depends on column day_no of table traffic.countinfo
materialized view traffic.speed_counts_cl depends on column day_no of table traffic.countinfo
materialized view traffic.speed_counts depends on column day_no of table traffic.countinfo
materialized view traffic.speed_vol_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed1_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed3_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed4_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed_all_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed_study_groups depends on column day_no of table traffic.countinfo
materialized view dmcelroy.speed_vol_study_groups depends on column day_no of table traffic.countinfo
materialized view vz_challenge.speed_counts depends on column day_no of table traffic.countinfo
view data_requests.i0529_ase_speed_volumes depends on column day_no of table traffic.countinfo

`traffic.countinfomics`:
view bqu.countinfomics_2017 depends on column day_no of table traffic.countinfomics
materialized view data_requests.i0419_curb_radii_tmcs depends on column day_no of table traffic.countinfomics
materialized view scannon.i0419_curb_radii_tmcs depends on column day_no of table traffic.countinfomics

**Comment by gabrielwol** [comment]
I edited the dependencies and dropped the `day_no` columns from `traffic.countinfo` and `traffic.countinfomics` ✅ 
PR open to edit the replicator to copy only destination table columns from move_staging.
