### ISSUE TITLE
VDS notification failure

### ISSUE THREAD

**Issue by gabrielwol** [CityofToronto/bdit_data-sources#975]
- [`vds_pull.check_rows_vdsdata_div2`](https://morbius.corp.toronto.ca:8080/airflow/dags/vds_pull_vdsdata/grid?base_date=2024-06-02T23%3A59%3A59.999Z&dag_run_id=scheduled__2024-05-30T08%3A00%3A00%2B00%3A00&task_id=data_checks.check_rows_vdsdata_div2&tab=logs) slack notification didn't work because of a None value returned from the SQLCheckOperatorWithReturnValue: 
> File "/data/home/gwolofs/bdit_data-sources/dags/dag_functions.py", line 103, in task_fail_slack_alert
    extra_msg_str = '\n> '.join(
TypeError: sequence item 3: expected str instance, NoneType found
- The slack alert shouldn't fail when a None is returned from SQLCheckOperatorWithReturnValue.
- The None was from the weather summary function `weather.airport_weather_summary(date)`, because the weather pipeline runs at 10:30AM and the VDS pipeline runs earlier. We should move up this pipeline so all the volume pipelines can reference it.

**Comment by radumas** [comment]
There might be a reason the weather pipeline was scheduled for 10:30 AM

**Comment by gabrielwol** [comment]
There might be, but it's not mentioned in the docs and there is no readme page for scraping weather.gc.ca. The [package](https://pypi.org/project/env-canada/) we use for predictions also doesn't mention anything. We can check results tomorrow.
Likely it was just to make testing easier.
