### ISSUE TITLE
Update Miovision processing so it can be automated

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_data-sources#99]
Current procedure requires dangerous amount of permissions for whoever is running scripts.
- [x] Delete all `populate-table-*.sql` files.
- [x] Make sure functions to call match [what's in the README](https://github.com/CityofToronto/bdit_data-sources/tree/7acfca21cbb454da93faf93175c5dc55fe121d38/volumes/miovision#d-populate-report_dates)
- [x] @radumas to check permissions in the `miovision` schema to lock things down against accidents.
- [x] Write-up Foreign Key structure into README
- [x] Add indexes to relevant tables.

**Comment by radumas** [comment]
Updated task list

**Comment by rickl4** [comment]
To insert to `rliu.raw data` and populate `rliu.volumes`:
Using trigger functions for May data (505,296 rows): 157 Seconds
Adding a foreign key relationship with the volumn `volume_uid` and using partial May data (only 9424 rows): Over 25 minutes

Using the full May data causes the `INSERT INTO rliu.raw_data` to hang for a long time.

Adding the keys/indexes is probably the issue. And there is probably 10-15x more data than `volumes_15min_tmc` which explains the longer run time.

**Comment by radumas** [comment]
>Adding a foreign key relationship with the volumn volume_uid and using partial May data (only 9424 rows): Over 25 minutes
What was your implementation for this? I'm wondering if we could change the trigger so `BEFORE INSERT`, it instead inserts into `volumes`, with `RETURNING` the `volume_id` and then inserts into `raw_data`. That might save the long run-time of running an `UPDATE` on `raw_data` for each row?

Separate thing I just thought of related to the `FOREIGN KEY`s for our discussion today: not all data in `volumes` gets aggregated to the `15min_tmc` and so on if the data is missing or whatever. This means that a small minority of `volume_15min_tmc_uid` are `NULL` in `volumes` and wouldn't (necessarily) have a CASCADED DELETE, depending on how deleting gets implemented.

**Comment by rickl4** [comment]
`volumes` had a primary key on `volume_uid` and `raw_data` had a foreign key on `volume_uid` and an index on `volume_uid`. It inserted the data to `volumes` after it was inserted to `raw_data`.

**Comment by radumas** [comment]
Superseded by #145 
Also basically done with all the other referenced issues.
